### ISSUE TITLE
got a NotImplementedError with tutorial

### ISSUE THREAD

**Issue by astwyg** [scrapy/scrapy#1025]
i am following Scrapy Documentation, Release 0.24.0
on a window7(x32) 
all required packages are installed using pip

i meet a NotImplementedError error during step:
`run scrapy crawl dmoz`

my console looks like:
```
E:\DOCs\46Scrapy\tutorial>scrapy crawl dmoz
2015-01-27 10:58:32+0800 [scrapy] INFO: Scrapy 0.24.4 started (bot: tutorial)
2015-01-27 10:58:32+0800 [scrapy] INFO: Optional features available: ssl, http11
, django
2015-01-27 10:58:32+0800 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE'
: 'tutorial.spiders', 'SPIDER_MODULES': ['tutorial.spiders'], 'BOT_NAME': 'tutor
ial'}
2015-01-27 10:58:33+0800 [scrapy] INFO: Enabled extensions: LogStats, TelnetCons
ole, CloseSpider, WebService, CoreStats, SpiderState
2015-01-27 10:58:35+0800 [scrapy] INFO: Enabled downloader middlewares: HttpAuth
Middleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, Def
aultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, Redirec
tMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2015-01-27 10:58:35+0800 [scrapy] INFO: Enabled spider middlewares: HttpErrorMid
dleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddlew
are
2015-01-27 10:58:35+0800 [scrapy] INFO: Enabled item pipelines:
2015-01-27 10:58:35+0800 [dmoz] INFO: Spider opened
2015-01-27 10:58:35+0800 [dmoz] INFO: Crawled 0 pages (at 0 pages/min), scraped
0 items (at 0 items/min)
2015-01-27 10:58:35+0800 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6
023
2015-01-27 10:58:35+0800 [scrapy] DEBUG: Web service listening on 127.0.0.1:6080

2015-01-27 10:58:36+0800 [dmoz] DEBUG: Crawled (200) <GET http://www.dmoz.org/Co
mputers/Programming/Languages/Python/Resources/> (referer: None)
2015-01-27 10:58:36+0800 [dmoz] ERROR: Spider error processing <GET http://www.d
moz.org/Computers/Programming/Languages/Python/Resources/>
        Traceback (most recent call last):
          File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 12
01, in mainLoop
            self.runUntilCurrent()
          File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 82
4, in runUntilCurrent
            call.func(*call.args, **call.kw)
          File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 3
82, in callback
            self._startRunCallbacks(result)
          File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 4
90, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 5
77, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "C:\Python27\lib\site-packages\scrapy\spider.py", line 56, in par
se
            raise NotImplementedError
        exceptions.NotImplementedError:

2015-01-27 10:58:36+0800 [dmoz] DEBUG: Crawled (200) <GET http://www.dmoz.org/Co
mputers/Programming/Languages/Python/Books/> (referer: None)
2015-01-27 10:58:36+0800 [dmoz] ERROR: Spider error processing <GET http://www.d
moz.org/Computers/Programming/Languages/Python/Books/>
        Traceback (most recent call last):
          File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 12
01, in mainLoop
            self.runUntilCurrent()
          File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 82
4, in runUntilCurrent
            call.func(*call.args, **call.kw)
          File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 3
82, in callback
            self._startRunCallbacks(result)
          File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 4
90, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 5
77, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "C:\Python27\lib\site-packages\scrapy\spider.py", line 56, in par
se
            raise NotImplementedError
        exceptions.NotImplementedError:

2015-01-27 10:58:36+0800 [dmoz] INFO: Closing spider (finished)
2015-01-27 10:58:36+0800 [dmoz] INFO: Dumping Scrapy stats:
        {'downloader/request_bytes': 516,
         'downloader/request_count': 2,
         'downloader/request_method_count/GET': 2,
         'downloader/response_bytes': 16342,
         'downloader/response_count': 2,
         'downloader/response_status_count/200': 2,
         'finish_reason': 'finished',
         'finish_time': datetime.datetime(2015, 1, 27, 2, 58, 36, 731000),
         'log_count/DEBUG': 4,
         'log_count/ERROR': 2,
         'log_count/INFO': 7,
         'response_received_count': 2,
         'scheduler/dequeued': 2,
         'scheduler/dequeued/memory': 2,
         'scheduler/enqueued': 2,
         'scheduler/enqueued/memory': 2,
         'spider_exceptions/NotImplementedError': 2,
         'start_time': datetime.datetime(2015, 1, 27, 2, 58, 35, 186000)}
2015-01-27 10:58:36+0800 [dmoz] INFO: Spider closed (finished)

```

it seems something wrong with `twisted`,i change the version of twisted to 13.2.0 , but the error still there.
i searched google got no answer about this question.
So, anyone with idea please help me.

**Comment by astwyg** [comment]
well..i solved the problem...

in `dmoz_spider.py`
function `parse(self, response)` is part of class`DmozSpider(scrapy.Spider)`

`Scrapy Documentation, Release 0.24.0` page turning in this part..so i misread them.

i am blue to git . cloud anyone please tell me how to close the issue , thanks!
