### ISSUE TITLE
Issue with twisted==15.0.0

### ISSUE THREAD

**Issue by mou55** [scrapy/scrapy#1040]
It seems that there's an issue with **twisted==15.0.0**, Scrapy used to work fine with the 14.2.0 version.
So I think 15.0.0 should be removed from https://github.com/scrapy/scrapy/blob/master/requirements.txt#L1.

The stack trace:
>
	Traceback (most recent call last):
	  File "/home/moussa/Work/python/pb-env/local/lib/python2.7/site-packages/scrapy/core/downloader/middleware.py", line 38, in process_request
	    return download_func(request=request, spider=spider)
	  File "/home/moussa/Work/python/pb-env/local/lib/python2.7/site-packages/scrapy/core/downloader/__init__.py", line 123, in _enqueue_request
	    self._process_queue(spider, slot)
	  File "/home/moussa/Work/python/pb-env/local/lib/python2.7/site-packages/scrapy/core/downloader/__init__.py", line 143, in _process_queue
	    dfd = self._download(slot, request, spider)
	  File "/home/moussa/Work/python/pb-env/local/lib/python2.7/site-packages/scrapy/core/downloader/__init__.py", line 154, in _download
	    dfd = mustbe_deferred(self.handlers.download_request, request, spider)
	--- <exception caught here> ---
	  File "/home/moussa/Work/python/pb-env/local/lib/python2.7/site-packages/scrapy/utils/defer.py", line 39, in mustbe_deferred
	    result = f(*args, **kw)
	  File "/home/moussa/Work/python/pb-env/local/lib/python2.7/site-packages/scrapy/core/downloader/handlers/__init__.py", line 40, in download_request
	    return handler(request, spider)
	  File "/home/moussa/Work/python/pb-env/local/lib/python2.7/site-packages/scrapy/core/downloader/handlers/http11.py", line 36, in download_request
	    return agent.download_request(request)
	  File "/home/moussa/Work/python/pb-env/local/lib/python2.7/site-packages/scrapy/core/downloader/handlers/http11.py", line 174, in download_request
	    d = agent.request(method, url, headers, bodyproducer)
	  File "/home/moussa/Work/python/pb-env/local/lib/python2.7/site-packages/twisted/web/client.py", line 1560, in request
	    endpoint = self._getEndpoint(parsedURI)
	exceptions.TypeError: _getEndpoint() takes exactly 4 arguments (2 given)
>

**Comment by mou55** [comment]
#1034
