### ISSUE TITLE
scrapy fail to load in both python 2.7 and 3.4

### ISSUE THREAD

**Issue by gozes** [scrapy/scrapy#1061]
I just installed scrapy from pypi, when I try to run any command I get the following traceback

Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 9, in <module>
    load_entry_point('Scrapy==0.24.5', 'console_scripts', 'scrapy')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/scrapy/__init__.py", line 28, in <module>
    import _monkeypatches
ImportError: No module named '_monkeypatches'

the same traceback is display for 2.7

**Comment by kmike** [comment]
Scrapy doesn't support Python 3.x yet.

Could you please paste a traceback for Python 2.7? If traceback is the *same* it means `/usr/local/bin/scrapy` tries to run Scrapy using Python 3.x, not with 2.7.

**Comment by gozes** [comment]
I did, it is the same output. just change were ii says python3 to python2.7

**Comment by kmike** [comment]
Could you try installing Scrapy in virtualenv?

**Comment by gozes** [comment]
got it to work by reinstalling scrapy.
