### ISSUE TITLE
ImportError: cannot import name LinkExtractor

### ISSUE THREAD

**Issue by pkpp1233** [scrapy/scrapy#1174]
I'm getting the following error in scrapy v 0.24.5

ImportError: cannot import name LinkExtractor
This happens when I do:

from scrapy.contrib.linkextractors import LinkExtractor
Any ideas?

**Comment by kmike** [comment]
Could you please paste the full exception?

**Comment by psravyareddy** [comment]
getting the same error :

below is the stack trace 
anaconda3\lib\site-packages\scrapy\spiderloader.py:55: RuntimeWarning: 
Traceback (most recent call last):
  File "anaconda3\lib\site-packages\scrapy\spiderloader.py", line 51, in _load_all_spiders
    for module in walk_modules(name):
  File "anaconda3\lib\site-packages\scrapy\utils\misc.py", line 89, in walk_modules
    submod = import_module(fullpath)
  File "\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)  
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "*****.py", line 3, in <module>
    from scrapy.linkextractors import LinkExtractors
ImportError: cannot import name 'LinkExtractors' from 'scrapy.linkextractors' (*****__init__.py)
Could not load spiders from module 'articlescraper.spiders'. See 
d (bot: articlescraper)
2021-03-27 14:06:15 [scrapy.utils.log] INFO: Versions: lxml 4.6.1.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0d (bot: articlescrap, Twisted 21.2.0, Python 3.8.5 (default, Sep  3 2020, 21:29:08) 1.0, libxml2 2.9.10,
[MSC v.1916 64 bit (AMD64)], pyOpenSSL 19.1.0 (OpenSSL 1.1.1h  2t, Sep  3 2020, 21:22 Sep 2020), cryptography 3.1.1, Platform Windows-10-10.0.19041- cryptography 3.1.1,SP0
2021-03-27 14:06:15 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.selectsted.internet.selectreactor.SelectReactor
Usage
=====
  scrapy runspider [options] <spider_file>

runspider: error: Unable to load '***.py': cannot import name 'LinkExtractors'ame 'LinkExtractors' from 'scrapy.linkextractors' (__inita\anaconda3\lib\site-packages\scrapy\linkextractors\__init__.py)

PS: tried upgrading Scrapy to the latest version and python-scrapy is not installed

Any solution to fix this issue?
Thanks in advance!
