### ISSUE TITLE
Scrapy doesnt check if response is html and fail with exception 'Response' object has no attribute 'body_as_unicode'

### ISSUE THREAD

**Issue by aldarund** [scrapy/scrapy#1204]
If scrapy found  a link that outputs not an html but pdf or something else it  fails with exception. 
Here is stracktrace:
```
2015-05-03 18:16:28+0000 [external_link_spider] ERROR: Spider error processing <GET http://www.chanel.com/en_AS/Watches/print?popup=1&ref=H0451>
        Traceback (most recent call last):
          File "/opt/webapps/link_crawler/local/lib/python2.7/site-packages/twisted/internet/base.py", line 824, in runUntilCurrent
            call.func(*call.args, **call.kw)
          File "/opt/webapps/link_crawler/local/lib/python2.7/site-packages/twisted/internet/task.py", line 638, in _tick
            taskObj._oneWorkUnit()
          File "/opt/webapps/link_crawler/local/lib/python2.7/site-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
            result = next(self._iterator)
          File "/opt/webapps/link_crawler/local/lib/python2.7/site-packages/scrapy/utils/defer.py", line 57, in <genexpr>
            work = (callable(elem, *args, **named) for elem in iterable)
        --- <exception caught here> ---
          File "/opt/webapps/link_crawler/local/lib/python2.7/site-packages/scrapy/utils/defer.py", line 96, in iter_errback
            yield next(it)
          File "/opt/webapps/link_crawler/local/lib/python2.7/site-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
            for x in result:
          File "/opt/webapps/link_crawler/local/lib/python2.7/site-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
            return (_set_referer(r) for r in result or ())
          File "/opt/webapps/link_crawler/local/lib/python2.7/site-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
            for x in result:
          File "/opt/webapps/link_crawler/local/lib/python2.7/site-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
            return (r for r in result or () if _filter(r))
          File "/opt/webapps/link_crawler/local/lib/python2.7/site-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
            return (r for r in result or () if _filter(r))
          File "/opt/webapps/link_crawler/local/lib/python2.7/site-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
            for requests_or_item in iterate_spider_output(cb_res):
          File "build/bdist.linux-x86_64/egg/ex_link_crawl/spiders/external_link_spider.py", line 28, in parse_obj

          File "/opt/webapps/link_crawler/local/lib/python2.7/site-packages/scrapy/contrib/linkextractors/lxmlhtml.py", line 96, in extract_links
            html = Selector(response)
          File "/opt/webapps/link_crawler/local/lib/python2.7/site-packages/scrapy/selector/unified.py", line 80, in __init__
            _root = LxmlDocument(response, self._parser)
          File "/opt/webapps/link_crawler/local/lib/python2.7/site-packages/scrapy/selector/lxmldocument.py", line 27, in __new__
            cache[parser] = _factory(response, parser)
          File "/opt/webapps/link_crawler/local/lib/python2.7/site-packages/scrapy/selector/lxmldocument.py", line 13, in _factory
            body = response.body_as_unicode().strip().encode('utf8') or '<html/>'
        exceptions.AttributeError: 'Response' object has no attribute 'body_as_unicode'
```

**Comment by nramirezuy** [comment]
Then why are you passing a `.pdf` to `Selector`?  This isn't a bug; if you have questions please make them on the [`scrapy-users`](https://groups.google.com/forum/#!forum/scrapy-users) forums.

**Comment by aldarund** [comment]
Im not passing pdf to selector.Its behaviour of standard CrawlSpider. And if you take look at the log - it doesnt have a pdf extension. http://www.chanel.com/en_AS/Watches/print?popup=1&ref=H0451
 It just output pdf content.
Still considering this as not a bug when standard crawlspider produce an unhandled exception?

**Comment by nramirezuy** [comment]
Still not a bug. `.pdf` extension or not scrapy isn't detecting the response as `html` (demonstrated below); "standard `CrawlSpider`" just extract links from [`html` responses](https://github.com/scrapy/scrapy/blob/master/scrapy/spiders/crawl.py#L48).

```python
>>> response
<200 http://www.chanel.com/en_AS/Watches/print?popup=1&ref=H0451>
>>> response.__class__
<class 'scrapy.http.response.Response'>
```

If you still think it is a bug you will need to demonstrate it, by giving us a way to reproduce it; because I can't see it from the on the traceback.

**Comment by aldarund** [comment]
The problem is that i have generic spider that crawl all urls from domain. There is no way i can know that its pdf or not just looking at the link, because its generic spider that just crawl pages from any site.
And the log is just become polluted with exceptions when it  site with non html content type link appears.

**Comment by nramirezuy** [comment]
@aldarund  Join IRC: #scrapy
