### ISSUE TITLE
'NoneType' object has no attribute '_app_data' because of misuse ClientTLSOptions 

### ISSUE THREAD

**Issue by aldarund** [scrapy/scrapy#1227]
See this answer for reference:
http://stackoverflow.com/a/30203408/239354
full exception stacktrace:

````
 Traceback (most recent call last):
      File "/opt/webapps/link_crawler/lib/python2.7/site-packages/twisted/protocols/tls.py", line 415, in dataReceived
        self._write(bytes)
      File "/opt/webapps/link_crawler/lib/python2.7/site-packages/twisted/protocols/tls.py", line 554, in _write
        sent = self._tlsConnection.send(toSend)
      File "/opt/webapps/link_crawler/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1270, in send
        result = _lib.SSL_write(self._ssl, buf, len(buf))
      File "/opt/webapps/link_crawler/lib/python2.7/site-packages/OpenSSL/SSL.py", line 926, in wrapper
        callback(Connection._reverse_mapping[ssl], where, return_code)
    --- <exception caught here> ---
      File "/opt/webapps/link_crawler/lib/python2.7/site-packages/twisted/internet/_sslverify.py", line 1055, in infoCallback
        return wrapped(connection, where, ret)
      File "/opt/webapps/link_crawler/lib/python2.7/site-packages/twisted/internet/_sslverify.py", line 1157, in _identityVerifyingInfoCallback
        transport = connection.get_app_data()
      File "/opt/webapps/link_crawler/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1589, in get_app_data
        return self._app_data
      File "/opt/webapps/link_crawler/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1148, in __getattr__
        return getattr(self._socket, name)
    exceptions.AttributeError: 'NoneType' object has no attribute '_app_data'
```

**Comment by dangra** [comment]
@nyov aaeb837db409442579d260f703e2f2ca705020ca is firing back.

**Comment by nyov** [comment]
Ouch. I suppose this means reviewing #1103 and doing a more elaborate dance with SSL connections here.

**Comment by fluential** [comment]
Any progress on that?

**Comment by nautilus28** [comment]
any solution to workaround on that?

**Comment by nyov** [comment]
I can think of these:
- revert the change and dont visit SNI-dependent sites
- use #1103 and report issues if it doesn't work for you
- don't visit sites with invalid SSL certificates

I'm not aware of any work regarding this, it seems #1103 is missing tests. But I'm unable to provide these, not knowing all the twisted internals here (was bad enough I signed off on this patch without seeing all the angles ;).

**Comment by lisandro52** [comment]
I found a workaround or kindof:
`pip uninstall service_identity`
`pip install service_identity`

For some reason, this module was causing some troubles but reinstalling it made the error disappear.

**Comment by somghosh** [comment]
+1

**Comment by nautilus28** [comment]
@lisandro52 it does not work for me :(

**Comment by abliu** [comment]
+1 @lisandro52

**Comment by kslazarev** [comment]
+1

**Comment by redapple** [comment]
Scrapy 1.1 handles SNI properly with https://github.com/scrapy/scrapy/pull/1794 and https://github.com/scrapy/scrapy/pull/1933
