### ISSUE TITLE
Scrapy and twisted Unhandled Error

### ISSUE THREAD

**Issue by Free16t** [scrapy/scrapy#1277]
Hi,
I'm trying to use [Hyphe](https://github.com/medialab/hyphe). Hyphe is using Scrapy but I failed to connect scrapy.

Here is my log file from `scrapyd.log`

>2015-06-02 14:29:22+0200 [-] "127.0.0.1" - - [02/Jun/2015:12:29:22 +0000] "POST /schedule.json HTTP/1.0" 200 50 "-" "Twisted PageGetter"
2015-06-02 14:29:23+0200 [-] "127.0.0.1" - - [02/Jun/2015:12:29:22 +0000] "GET /jobs HTTP/1.0" 200 434 "-" "Twisted PageGetter"
2015-06-02 14:29:23+0200 [HTTPChannel,43147,127.0.0.1] Unhandled Error
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 1755, in allContentReceived
req.requestReceived(command, path, version)
File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 823, in requestReceived
self.process()
File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 189, in process
self.render(resrc)
File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 238, in render
body = resrc.render(self)
--- ---
File "/usr/lib/pymodules/python2.7/scrapyd/webservice.py", line 18, in render
return JsonResource.render(self, txrequest)
File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/txweb.py", line 10, in render
r = resource.Resource.render(self, txrequest)
File "/usr/local/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
return m(request)
File "/usr/lib/pymodules/python2.7/scrapyd/webservice.py", line 37, in render_POST
self.root.scheduler.schedule(project, spider, **args)
File "/usr/lib/pymodules/python2.7/scrapyd/scheduler.py", line 15, in schedule
q = self.queues[project]
exceptions.KeyError: 'hyphe.xxx'

Sincerely

**Comment by dangra** [comment]
You will have better luck by reporting the problem to Hyphe developers, you may try scrapy-users forums too. Github issue tracker is for Scrapy bug reports.

thanks.
