### ISSUE TITLE
exceptions.IOError: Not a gzipped file

### ISSUE THREAD

**Issue by tonal** [scrapy/scrapy#1288]
```
$ scrapy fetch 'http://www.airs.ru/index.php?q=catalog/heating/burner/producer-cib-unigas/page-0/order-title-asc'
2015-06-08 10:50:15+0600 [scrapy] INFO: Scrapy 0.25.0-454-gfa1039f started (bot: scrapybot)
2015-06-08 10:50:15+0600 [scrapy] INFO: Optional features available: ssl, http11, boto
2015-06-08 10:50:15+0600 [scrapy] INFO: Overridden settings: {}
2015-06-08 10:50:15+0600 [scrapy] INFO: Enabled extensions: LogStats, TelnetConsole, CloseSpider, CoreStats, SpiderState
2015-06-08 10:50:16+0600 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2015-06-08 10:50:16+0600 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2015-06-08 10:50:16+0600 [scrapy] INFO: Enabled item pipelines: 
2015-06-08 10:50:16+0600 [default] INFO: Spider opened
2015-06-08 10:50:16+0600 [default] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2015-06-08 10:50:16+0600 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6023
2015-06-08 10:50:16+0600 [default] ERROR: Error downloading <GET http://www.airs.ru/index.php?q=catalog/heating/burner/producer-cib-unigas/page-0/order-title-asc>
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
            self._runCallbacks()
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
            self._startRunCallbacks(result)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/lib/pymodules/python2.7/scrapy/core/downloader/middleware.py", line 46, in process_response
            response = method(request=request, response=response, spider=spider)
          File "/usr/lib/pymodules/python2.7/scrapy/contrib/downloadermiddleware/httpcompression.py", line 27, in process_response
            decoded_body = self._decode(response.body, encoding.lower())
          File "/usr/lib/pymodules/python2.7/scrapy/contrib/downloadermiddleware/httpcompression.py", line 43, in _decode
            body = gunzip(body)
          File "/usr/lib/pymodules/python2.7/scrapy/utils/gz.py", line 20, in gunzip
            chunk = f.read(8196)
          File "/usr/lib/python2.7/gzip.py", line 261, in read
            self._read(readsize)
          File "/usr/lib/python2.7/gzip.py", line 296, in _read
            self._read_gzip_header()
          File "/usr/lib/python2.7/gzip.py", line 190, in _read_gzip_header
            raise IOError, 'Not a gzipped file'
        exceptions.IOError: Not a gzipped file
```
In scrapy `scrapy fetch --headers ...` also IOError
Headers for curl:
```
$ curl -v -H 'Accept-Encoding: gzip, deflate, compress' http://www.airs.ru/index.php?q=catalog/heating/burner/producer-cib-unigas/page-0/order-title-asc > /dev/null
* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 62.76.190.156...
* Connected to www.airs.ru (62.76.190.156) port 80 (#0)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0> GET /index.php?q=catalog/heating/burner/producer-cib-unigas/page-0/order-title-asc HTTP/1.1
> User-Agent: curl/7.35.0
> Host: www.airs.ru
> Accept: */*
> Accept-Encoding: gzip, deflate, compress
> 
< HTTP/1.1 404 Not Found
* Server nginx is not blacklisted
< Server: nginx
< Date: Mon, 08 Jun 2015 05:08:59 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: PHP/5.2.17
< Set-Cookie: SESS8a5a439f1c15790e74709e9d7d429ba3=v477l94mq6fnfu55ceh18a2rg1; expires=Wed, 01-Jul-2015 08:42:19 GMT; path=/; domain=.airs.ru
< Last-Modified: Thu, 04 Jun 2015 20:02:00 GMT
< ETag: "223c8deda8bd618407cdf708254bd689"
< Expires: Sun, 19 Nov 1978 05:00:00 GMT
< Cache-Control: max-age=172800, private, must-revalidate
< Content-Encoding: gzip
< Transfer-Encoding: chunked
```

**Comment by tonal** [comment]
Site airs.ru forget header `Transfer-Encoding: chunked` for 404 ansver ...
I write download middelvare for recovery header.
