### ISSUE TITLE
when scrapy run to (scrapy\downloadermiddlewares\)retry.py  appear " UnicodeDecodeError"

### ISSUE THREAD

**Issue by movingheart** [scrapy/scrapy#1330]
Some error message as:
2015-07-01 16:03:46+0800 [Launcher,7500/stderr] Traceback (most recent call last
):
          File "D:\Python27\lib\logging__init__.py", line 882, in emit
            stream.write(fs % msg.encode("UTF-8"))
        UnicodeDecodeError: 'utf8' codec can't decode byte 0xd3 in position 267:
 invalid continuation byte
        Logged from file retry.py, line 73
        Traceback (most recent call last):
          File "D:\Python27\lib\logging__init__.py", line 882, in emit
            stream.write(fs % msg.encode("UTF-8"))
        UnicodeDecodeError: 'utf8' codec can't decode byte 0xd3 in position 267:
 invalid continuation byte
        Logged from file retry.py, line 73
        Traceback (most recent call last):
          File "D:\Python27\lib\logging__init__.py", line 882, in emit
            stream.write(fs % msg.encode("UTF-8"))

**Comment by movingheart** [comment]
Tracing this error,I find that 'msg' is:
'2015-07-01 17:17:31 [scrapy] DEBUG: Retrying <GET http://search.10jqka.com.cn/s
tockpick/search?id=stockpick&w=%E5%AE%9E%E9%99%85%E6%8E%A7%E5%88%B6%E4%BA%BA+601
666&offset=3&limit=0&source=data&callback=conceptSearch> (failed 1 times): TCP c
onnection timed out: 10060: \xd3\xc9\xd3\xda\xc1\xac\xbd\xd3\xb7\xbd\xd4\xda\xd2
\xbb\xb6\xce\xca\xb1\xbc\xe4\xba\xf3\xc3\xbb\xd3\xd0\xd5\xfd\xc8\xb7\xb4\xf0\xb8
\xb4\xbb\xf2\xc1\xac\xbd\xd3\xb5\xc4\xd6\xf7\xbb\xfa\xc3\xbb\xd3\xd0\xb7\xb4\xd3
\xa6\xa3\xac\xc1\xac\xbd\xd3\xb3\xa2\xca\xd4\xca\xa7\xb0\xdc\xa1\xa3.'

**Comment by kmike** [comment]
Do you have an idea what could 
```
\xd3\xc9\xd3\xda\xc1\xac\xbd\xd3\xb7\xbd\xd4\xda\xd2
\xbb\xb6\xce\xca\xb1\xbc\xe4\xba\xf3\xc3\xbb\xd3\xd0\xd5\xfd\xc8\xb7\xb4\xf0\xb8
\xb4\xbb\xf2\xc1\xac\xbd\xd3\xb5\xc4\xd6\xf7\xbb\xfa\xc3\xbb\xd3\xd0\xb7\xb4\xd3
\xa6\xa3\xac\xc1\xac\xbd\xd3\xb3\xa2\xca\xd4\xca\xa7\xb0\xdc\xa1\xa3.
```
mean? 

Could you please also paste the output of the following script:

```
import sys, locale
print(sys.getdefaultencoding(), sys.stdout.encoding, locale.getpreferredencoding())
```

I wonder why are there these weird characters in exception description. We can solve it by making exception messages ascii-only, but it is better to figure out what happened here before doing it.

**Comment by movingheart** [comment]
\xd3\xc9\xd3\xda\xc1\xac\xbd\xd3\xb7\xbd\xd4\xda\xd2
\xbb\xb6\xce\xca\xb1\xbc\xe4\xba\xf3\xc3\xbb\xd3\xd0\xd5\xfd\xc8\xb7\xb4\xf0\xb8
\xb4\xbb\xf2\xc1\xac\xbd\xd3\xb5\xc4\xd6\xf7\xbb\xfa\xc3\xbb\xd3\xd0\xb7\xb4\xd3
\xa6\xa3\xac\xc1\xac\xbd\xd3\xb3\xa2\xca\xd4\xca\xa7\xb0\xdc\xa1\xa3.

when I print this in python IDLE , show:
由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.

>>> import sys, locale
>>> print(sys.getdefaultencoding(), sys.stdout.encoding, locale.getpreferredencoding())
('ascii', 'cp936', 'cp936')

when I run it in scripts, output:
('ascii', None, 'cp936')

**Comment by movingheart** [comment]
I guess that the error appear because "msg" contain chinese characters , perhaps other place in scrapy remain this conditions.

**Comment by kmike** [comment]
Could you try setting [LOG_ENCODING](http://doc.scrapy.org/en/master/topics/settings.html#log-encoding) to cp936? This is far from ideal, but it could help. 

Printing these non-ascii messages looks useful; #1331 will make then unreadable, at least in Python 2.x.

**Comment by curita** [comment]
I've been trying to reproduce this issue in a newly installed windows 7 (that specific message error is windows related) to no avail :/ The environment is a little too specific so I could be missing something.

### System

SO: Windows 7 SP1 64 bit.

I'm using the Chinese (Simplified, PRC) system locale to get that encoding, along with the Chinese (Simplified) language package to get the error message in that language.

**Python**==2.7.10 (Can be checked with `python --version`)
**pywin32**==219 (Can be checked either with `pip show pywin32` or `pip freeze` in older versions of pip)
**Scrapy**==1.0.1 (Can be checked with `scrapy --version` or pip)

### Locales
```python
In [1]: import sys, locale

In [2]: print(sys.getdefaultencoding(), sys.stdout.encoding, locale.getpreferredencoding())
('ascii', 'cp936', 'cp936')
```

### Test
```bash
PS C:\Users\julia> scrapy fetch http://google.com:81
...
2015-07-03 05:00:32 [scrapy] DEBUG: Retrying <GET http://google.com:81> (failed 1 times): TCP connection timed out: 1006
0: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
```

So, I'm not sure at all what's throwing the unicode error on this issue, all seems to work fine with default settings.

@movingheart, could you run `scrapy fetch http://google.com:81` and see if it throws the same issue? That way we can discard your spider's code from the equation. If the same issue is raised I think we should inspect your system configuration to try to find the culprit.

**Comment by kmike** [comment]
@curita I think the reason it doesn't work for @movingheart is 

> when I run it in scripts, output:
('ascii', None, 'cp936')

**Comment by movingheart** [comment]
I am moved by your(@kmike,@curita) help.I will list detailed environment:
system os: Windows 旗舰版(Ultimate) 32bit
python version: 2.7.9
scrapy: 1.0.1

My tries:
1.Change retry.py source code according your(@kmike) commit can't resolve this question.
2.Setting LOG_ENCODING to cp936 still can't resolve
3.@curita Running (scrapy fetch http://google.com:81) in cmd ,show same info with you.But it can not explain this question.Can you check the code with my follows (you will receive my code) ?

When I run my code by command(scrapy crawl stockuc -a ctime=20150703) in cmd,all shows as follows:

F:\BaiduYunDownload\STOCK_UC>scrapy crawl stockuc -a ctime=20150703
now use ip: 122.224.169.90:8081
now use ip: 163.177.79.5:81
now use ip: 122.224.169.90:8081
now use ip: 163.177.79.5:81
Traceback (most recent call last):
  File "D:\Python27\lib\logging\__init__.py", line 882, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd3 in position 279: invalid
 continuation byte
Logged from file retry.py, line 73
now use ip: 163.177.79.5:81
Traceback (most recent call last):
  File "D:\Python27\lib\logging\__init__.py", line 882, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd3 in position 279: invalid
 continuation byte
Logged from file retry.py, line 73
now use ip: 122.224.169.90:8081
Traceback (most recent call last):
  File "D:\Python27\lib\logging\__init__.py", line 882, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd3 in position 279: invalid
 continuation byte
Logged from file retry.py, line 73
now use ip: 122.224.169.90:8081

Finally,I will send my source code to you(@kmike,@curita). And please keep a secret and delete it after resolved this question.

**Comment by curita** [comment]
Thanks for sending us your project! Don't worry, I just deleted it, I can reproduce the issue now without it but it certainly helped to figure up what was going on.

To reproduce the issue, you have to log the output to a file:
```bash
$ scrapy fetch http://google.com:81 --logfile log.txt
```

Or, discarding all the env setup, log something with non-ascii chars in an encoding not compatible with utf-8.

Problem here is that the log messages are mixing encodings, changing LOG_ENCODING to either utf-8 or cp936 won't help because both are present.

@movingheart an immediate solution would be to set LOG_ENCODING to `None` in your settings.py file. That way log messages will be written as bytes (unicode seems to be encoded as utf-8 by default) without any prior decoding process. Some symbols may be unreadable because of the mixed encodings, but the content of the file would be the same as appending `2>log.txt` to the command.

@kmike a solution from our side could be to decode the exception message to unicode using the system locale but I'm not sure this is the correct approach, there could be a lot of cases we're missing and users could log things with different encodings in other places. For example, running something like `scrapy fetch http://google.ch --logfile log.txt -s LOG_STDOUT=1` breaks too in a similar manner.

I think something we could do is to set up LOG_ENCODING to `None` by default, I think twisted logging never really used it seeing how it mixes encodings in these test cases :/

**Comment by movingheart** [comment]
Excellently, when I set LOG_ENCODING to None, it work well.Thanks for you help.

**Comment by kmike** [comment]
@curita I think exception messages should be ascii-only in Python 2.x; unicode is not really supported for exception messages in Python 2.x. If an error message is not ascii we can't know which encoding does it use. So https://github.com/scrapy/scrapy/pull/1331 starts to look good to me.

**Comment by curita** [comment]
It makes sense to avoid non-ascii characters in exception messages, +1 to address that. I wonder though if on top of that we should change LOG_ENCODING default to None for backward compatibility in other cases.

**Comment by Gallaecio** [comment]
Should we close this now that Python 2 support has been dropped?
