### ISSUE TITLE
It seems that something is going wrong.

### ISSUE THREAD

**Issue by d555** [scrapy/scrapy#1341]
After install scrapy from pip on isolated  environment, I could not run the example with success from the website so this is the log at the end:
First:
```python
$ scrapy runspider myscrapy.py                                                                                                                      [9:51:40]
2015-07-06 09:52:28 [scrapy] INFO: Scrapy 1.0.1 started (bot: scrapybot)
2015-07-06 09:52:28 [scrapy] INFO: Optional features available: ssl, http11
2015-07-06 09:52:28 [scrapy] INFO: Overridden settings: {}
2015-07-06 09:52:28 [py.warnings] WARNING: :0: UserWarning: You do not have a working installation of the service_identity module: 'No module named service_identity'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module and a recent enough pyOpenSSL to support it, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.

2015-07-06 09:52:28 [scrapy] INFO: Enabled extensions: CloseSpider, TelnetConsole, LogStats, CoreStats, SpiderState
2015-07-06 09:52:28 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2015-07-06 09:52:28 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2015-07-06 09:52:28 [scrapy] INFO: Enabled item pipelines:
2015-07-06 09:52:28 [scrapy] INFO: Spider opened
2015-07-06 09:52:28 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2015-07-06 09:52:28 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6023
2015-07-06 09:52:29 [scrapy] DEBUG: Crawled (200) <GET http://blog.scrapinghub.com> (referer: None)
2015-07-06 09:52:29 [scrapy] ERROR: Spider error processing <GET http://blog.scrapinghub.com> (referer: None)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/usr/local/lib/python2.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 28, in process_spider_output
    for x in result:
  File "/usr/local/lib/python2.7/site-packages/scrapy/spidermiddlewares/referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/usr/local/lib/python2.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python2.7/site-packages/scrapy/spidermiddlewares/depth.py", line 54, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/Users/usuario/Desktop/web/myscrapy.py", line 9, in parse
    yield scrapy.Request(response.urljoin(url), self.parse_titles)
NameError: global name 'scrapy' is not defined
2015-07-06 09:52:29 [scrapy] INFO: Closing spider (finished)
2015-07-06 09:52:29 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 218,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 26371,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2015, 7, 6, 14, 52, 29, 221816),
 'log_count/DEBUG': 2,
 'log_count/ERROR': 1,
 'log_count/INFO': 7,
 'log_count/WARNING': 1,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'spider_exceptions/NameError': 1,
 'start_time': datetime.datetime(2015, 7, 6, 14, 52, 28, 827605)}
2015-07-06 09:52:29 [scrapy] INFO: Spider closed (finished)
```

What about `NameError: global name 'scrapy' is not defined`?
`pip` has installed the package successful.

**Comment by curita** [comment]
Could it be you're missing an `import scrapy` line? Can we see the code of your spider otherwise?

**Comment by mazh91** [comment]
I'm getting the exact same error. Here's is my source code copied from the site tutorial:
```
import scrapy

class BlogSpider(scrapy.Spider):
    name = 'blogspider'
    start_urls = ['https://blog.scrapinghub.com']

    def parse(self, response):
        for title in response.css('h2.entry-title'):
            yield {'title': title.css('a ::text').extract_first()}

        for next_page in response.css('div.prev-post > a'):
            yield response.follow(next_page, self.parse)
```
