### ISSUE TITLE
LogCounterHandler should only handle messages from self.crawler

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#1362]
LogCounterHandler increases crawler log_count stats for each record, but it should only increase them for logs from the crawler it is created by. This is an issue if you're running several Crawlers in the same process.

**Comment by mikekutzma** [comment]
Is this issue still open?

**Comment by kmike** [comment]
@mikekutzma yes.

**Comment by GeorgeA92** [comment]
Log entries from scrapy modules(not everywhere) have `extra` param like on:
https://github.com/scrapy/scrapy/blob/41e15e93e7459673e93ff2591462b47b7ae01566/scrapy/core/engine.py#L202-L206
or
https://github.com/scrapy/scrapy/blob/41e15e93e7459673e93ff2591462b47b7ae01566/scrapy/extensions/memusage.py#L98-L102
This can be used to.. make LogCounterHandler to count log entries independently for each crawler

<details><summary>script.py</summary>

```python
import scrapy
from scrapy.crawler import CrawlerProcess
from scrapy.utils.log import LogCounterHandler
from scrapy import Spider
import logging
from typing import Any, Dict, Optional
StatsT = Dict[str, Any]

class PerSpiderLogCounterHandler(LogCounterHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def emit(self, record):
        if hasattr(record, 'crawler'):
            sname = f"{str(record.crawler.spider)}/log_count/{record.levelname}"
            record.crawler.stats.inc_value(sname)
        if hasattr(record, 'spider'):
            sname = f"{str(record.spider)}/log_count/{record.levelname}"
            record.spider.crawler.stats.inc_value(sname)

from scrapy.statscollectors import StatsCollector

class PerSpiderStatsCollector(StatsCollector):
    def get_value(
        self, key: str, default: Any = None, spider: Optional[Spider] = None
    ) -> Any:
        return self._stats.get(f"{str(spider)}/{key}", default)

    def set_value(self, key: str, value: Any, spider: Optional[Spider] = None) -> None:
        self._stats[f"{str(spider)}/{key}"] = value

    def inc_value(
        self, key: str, count: int = 1, start: int = 0, spider: Optional[Spider] = None
    ) -> None:
        d = self._stats
        d[key] = d.setdefault(key, start) + count


class BooksToScrapeSpider(scrapy.Spider):
    name = "books"; custom_settings = {"DOWNLOAD_DELAY": 1, 'DEPTH_LIMIT':10}

    def start_requests(self):
        yield scrapy.Request(url='http://books.toscrape.com/catalogue/page-1.html', callback=self.parse)

    def parse(self, response):
        for book in response.css("h3 a::attr(href)").getall():
            yield {'url':book}
        if next_page := response.css("li.next a::attr(href)").get():
            yield scrapy.Request(url=response.urljoin(next_page), callback=self.parse)


class QuotesToScrapeSpider(scrapy.Spider):
    name = "quotes"; custom_settings = {"DOWNLOAD_DELAY": 1}

    def start_requests(self):
        yield scrapy.Request(url='http://quotes.toscrape.com/', callback=self.parse)

    def parse(self, response):
        for quote in response.css("div.quote"):
            yield {
                "quote": quote.css("span.text::text").getall(),
                "author": quote.css("small.author::text").getall(),
                "tags": quote.css("a.tag::text").getall()
            }
        result = 1/0

if __name__ == "__main__":
    p = CrawlerProcess()
    p.settings.set("LOG_LEVEL", logging.INFO, 50)
    p.crawl(BooksToScrapeSpider)
    p.crawl(QuotesToScrapeSpider)
    handler = PerSpiderLogCounterHandler(p.settings.get("LOG_LEVEL"))
    logging.root.addHandler(handler)
    p.start()

```
</details>


<details><summary>log output</summary>

```
2024-06-26 20:45:09 [scrapy.utils.log] INFO: Scrapy 2.11.0 started (bot: scrapybot)
2024-06-26 20:45:09 [scrapy.utils.log] INFO: Versions: lxml 4.9.1.0, libxml2 2.9.14, cssselect 1.2.0, parsel 1.6.0, w3lib 1.21.0, Twisted 22.10.0, Python 3.10.8 | packaged by conda-forge | (main, Nov 24 2022, 14:07:00) [MSC v.1916 64 bit (AMD64)], pyOpenSSL 23.0.0 (OpenSSL 1.1.1w  11 Sep 2023), cryptography 39.0.1, Platform Windows-10-10.0.22631-SP0
2024-06-26 20:45:09 [scrapy.addons] INFO: Enabled addons:
[]
2024-06-26 20:45:09 [scrapy.extensions.telnet] INFO: Telnet Password: 572c5f4caca240fa
2024-06-26 20:45:09 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2024-06-26 20:45:09 [scrapy.crawler] INFO: Overridden settings:
{'DEPTH_LIMIT': 10, 'DOWNLOAD_DELAY': 1, 'LOG_LEVEL': 20}
2024-06-26 20:45:10 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2024-06-26 20:45:10 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2024-06-26 20:45:10 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2024-06-26 20:45:10 [scrapy.core.engine] INFO: Spider opened
2024-06-26 20:45:10 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2024-06-26 20:45:10 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2024-06-26 20:45:10 [scrapy.addons] INFO: Enabled addons:
[]
2024-06-26 20:45:10 [scrapy.extensions.telnet] INFO: Telnet Password: 99d675e7426f85dd
2024-06-26 20:45:10 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2024-06-26 20:45:10 [scrapy.crawler] INFO: Overridden settings:
{'DOWNLOAD_DELAY': 1, 'LOG_LEVEL': 20}
2024-06-26 20:45:10 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2024-06-26 20:45:10 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2024-06-26 20:45:10 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2024-06-26 20:45:10 [scrapy.core.engine] INFO: Spider opened
2024-06-26 20:45:10 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2024-06-26 20:45:10 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6024
2024-06-26 20:45:10 [scrapy.core.scraper] ERROR: Spider error processing <GET http://quotes.toscrape.com/> (referer: None)
Traceback (most recent call last):
  File "C:\Users\georg\PycharmProjects\scrapy\scrapy\utils\defer.py", line 279, in iter_errback
    yield next(it)
  File "C:\Users\georg\PycharmProjects\scrapy\scrapy\utils\python.py", line 349, in __next__
    return next(self.data)
  File "C:\Users\georg\PycharmProjects\scrapy\scrapy\utils\python.py", line 349, in __next__
    return next(self.data)
  File "C:\Users\georg\PycharmProjects\scrapy\scrapy\core\spidermw.py", line 106, in process_sync
    yield from iterable
  File "C:\Users\georg\PycharmProjects\scrapy\scrapy\spidermiddlewares\offsite.py", line 41, in <genexpr>
    return (r for r in result if self._filter(r, spider))
  File "C:\Users\georg\PycharmProjects\scrapy\scrapy\core\spidermw.py", line 106, in process_sync
    yield from iterable
  File "C:\Users\georg\PycharmProjects\scrapy\scrapy\spidermiddlewares\referer.py", line 385, in <genexpr>
    return (self._set_referer(r, response) for r in result)
  File "C:\Users\georg\PycharmProjects\scrapy\scrapy\core\spidermw.py", line 106, in process_sync
    yield from iterable
  File "C:\Users\georg\PycharmProjects\scrapy\scrapy\spidermiddlewares\urllength.py", line 38, in <genexpr>
    return (r for r in result if self._filter(r, spider))
  File "C:\Users\georg\PycharmProjects\scrapy\scrapy\core\spidermw.py", line 106, in process_sync
    yield from iterable
  File "C:\Users\georg\PycharmProjects\scrapy\scrapy\spidermiddlewares\depth.py", line 50, in <genexpr>
    return (r for r in result if self._filter(r, response, spider))
  File "C:\Users\georg\PycharmProjects\scrapy\scrapy\core\spidermw.py", line 106, in process_sync
    yield from iterable
  File "C:/Users/georg/PycharmProjects/scrapy/t1/issues/1362_logcounter.py", line 65, in parse
    result = 1/0
ZeroDivisionError: division by zero
2024-06-26 20:45:10 [scrapy.core.engine] INFO: Closing spider (finished)
2024-06-26 20:45:10 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{"<QuotesToScrapeSpider 'quotes' at 0x282aa51b190>/log_count/DEBUG": 11,
 "<QuotesToScrapeSpider 'quotes' at 0x282aa51b190>/log_count/ERROR": 1,
 "<QuotesToScrapeSpider 'quotes' at 0x282aa51b190>/log_count/INFO": 1,
 'downloader/request_bytes': 224,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 2090,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 0.694528,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2024, 6, 26, 18, 45, 10, 905370, tzinfo=datetime.timezone.utc),
 'httpcompression/response_bytes': 11054,
 'httpcompression/response_count': 1,
 'item_scraped_count': 10,
 'log_count/ERROR': 1,
 'log_count/INFO': 10,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'spider_exceptions/ZeroDivisionError': 1,
 'start_time': datetime.datetime(2024, 6, 26, 18, 45, 10, 210842, tzinfo=datetime.timezone.utc)}
2024-06-26 20:45:10 [scrapy.core.engine] INFO: Spider closed (finished)
2024-06-26 20:45:22 [scrapy.core.engine] INFO: Closing spider (finished)
2024-06-26 20:45:22 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{"<BooksToScrapeSpider 'books' at 0x282a8f58880>/log_count/DEBUG": 232,
 "<BooksToScrapeSpider 'books' at 0x282a8f58880>/log_count/INFO": 1,
 'downloader/request_bytes': 3267,
 'downloader/request_count': 11,
 'downloader/request_method_count/GET': 11,
 'downloader/response_bytes': 61382,
 'downloader/response_count': 11,
 'downloader/response_status_count/200': 11,
 'elapsed_time_seconds': 12.526996,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2024, 6, 26, 18, 45, 22, 719236, tzinfo=datetime.timezone.utc),
 'httpcompression/response_bytes': 563470,
 'httpcompression/response_count': 11,
 'item_scraped_count': 220,
 'log_count/ERROR': 1,
 'log_count/INFO': 23,
 'request_depth_max': 10,
 'response_received_count': 11,
 'scheduler/dequeued': 11,
 'scheduler/dequeued/memory': 11,
 'scheduler/enqueued': 11,
 'scheduler/enqueued/memory': 11,
 'start_time': datetime.datetime(2024, 6, 26, 18, 45, 10, 192240, tzinfo=datetime.timezone.utc)}
2024-06-26 20:45:22 [scrapy.core.engine] INFO: Spider closed (finished)

```
</details>
