### ISSUE TITLE
Exceptions occuring in the logger do not invoke the debugger.

### ISSUE THREAD

**Issue by Digenis** [scrapy/scrapy#1551]
When the logger is misused and throws and exception
the `--pdb` flag doesn't make it drop into a pdb shell.

E.g. if I put this in the init of some spider:

``` python
def __init__(self, **kwargs):
    self.logger.info('%s %s', 1)  # fails because it needs another positional arg.
```

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 850, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 723, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Logged from file so_and_so_spider.py, line 18
```

I think errors there deserve a debugger shell
because some can be caused by conditions in runtime.
Here's an example:
An xls file is downloaded and parsed
so far the spider was expecting an integer on cell A1
but a structural update made cell A1 a string.
`self.logger.info('%d', cell.value())` will fail
without a chance to inspect.

**Comment by Digenis** [comment]
This is the simplest solution I came up with.
Suck hacky patching is also done by twisted in `failure.startDebugMode()`

```diff
diff --git a/scrapy/commands/__init__.py b/scrapy/commands/__init__.py
index 9ac0130..f9145bf 100644
--- a/scrapy/commands/__init__.py
+++ b/scrapy/commands/__init__.py
@@ -99,6 +99,12 @@ class ScrapyCommand(object):

         if opts.pdb:
             failure.startDebugMode()
+            import pdb, logging
+            _handleError = logging.Handler.handleError
+            def handleError(self, record):
+                pdb.post_mortem()
+                return _handleError(self, record)
+            logging.Handler.handleError = handleError

     def run(self, args, opts):
         """
```

Is there any interest in fixing this?

**Comment by lookfwd** [comment]
Tried this fix and as far as I can tell it didn't work

**Comment by Digenis** [comment]
@lookfwd, do you mean the patch?

**Comment by lookfwd** [comment]
Yes, I tried it with 1.0.3 yesterday - and as far as I can tell it didn't open the old good debugger :/

**Comment by Digenis** [comment]
I forgot to say it needs the `--pdb` parameter
as seen by the enclosing if: `if opts.pdb:`

**Comment by lookfwd** [comment]
I certainly used `--pdb` but no worries - it might be just me... What I mean is that I might have a bit older version of Twisted etc. I didn't check with the very latest... if it works for you, that's fine!

**Comment by Digenis** [comment]
Twisted shouldn't matter, this monkeypatches only the logging module.
How did you try to reproduce it?
`logger.info('%d', 'a')` suffice.

**Comment by AdrianAtZyte** [comment]
> `--pdb` already does this for the common case: [`_PdbHandler`](https://github.com/scrapy/scrapy/blob/506555bf9d79501c07c21e86760d8293b49c22b1/scrapy/commands/__init__.py#L35-L43) drops into `pdb.post_mortem` on any error-level record logged with `exc_info`, which covers spider callback exceptions.
>
> What is left here is narrower: an exception raised while formatting the log record itself (bad `%` args). Fixing that would mean monkeypatching `logging.Handler.handleError` globally, affecting every handler in the process, not just Scrapy’s, for what is really a bad-format-string bug that a linter catches at write time.

Shall we close this?
