### ISSUE TITLE
Scrapy taking 30+ minutes to execute any spiders or scrapy bench

### ISSUE THREAD

**Issue by bnussey** [scrapy/scrapy#1599]
I have a project using `Scrapy 1.0.3`. Everything was running fine, and after no considerable changes, spiders are taking at least 30 minutes to execute. Here are some logs from the prod environment:

    0:	2015-11-13 12:00:50	INFO	Log opened.
    1:	2015-11-13 12:00:50	INFO	[scrapy.log] Scrapy 1.0.3.post6+g2d688cd started
    2:	2015-11-13 12:39:26	INFO	[scrapy.utils.log] Scrapy 1.0.3.post6+g2d688cd started (bot: fancy)
    3:	2015-11-13 12:39:26	INFO	[scrapy.utils.log] Optional features available: ssl, http11, boto

As you can see from the logs, it took ~40 minutes to even start.

From my console if I run `scrapy bench`, `scrapy list` or `scrapy check` I get the same problem.

Does anyone have any ideas?

I've checked this on our dev and prod environment and having the same issue.

I thought it could be code related, but if it's effecting just basic scrapy commands, I am a bit confused as to what this could be.

Normal python scripts execute without issue.

Thanks

**Comment by kmike** [comment]
Hey @bnussey,

My only guess is an issue with boto library. Did you update it recently? Maybe there is some change in boto (e.g. increased default timeouts). If it is a boto issue, and you don't use Scrapy to download s3:// files it can be worked around by setting
```
DOWNLOAD_HANDLERS = {'s3': None}
```
Alternatively, update to scrapy master which shouldn't have this issue.

**Comment by bnussey** [comment]
Hey @kmike no changes at all to the boto library.. I might try a reinstall and if that doesn't work, update to the master branch

**Comment by kmike** [comment]
@bnussey is `DOWNLOAD_HANDLERS = {'s3': None}` workaround working?

**Comment by bnussey** [comment]
Hey @kmike sorry yeah no effect at all. Tried a reinstall but still the same issue..

**Comment by bnussey** [comment]
Hey @kmike I just noticed scrapy bench works fine in the root directory but soon as I got into the project's directory, thats where I have issues.. So going to mess with the settings and see what I can do

**Comment by kmike** [comment]
Can you try pressing Ctrl-C while Scrapy is waiting? It may show a traceback and point you to the code which is hanging.

**Comment by bnussey** [comment]
Of cousre mate, great idea, sorry should of included that, really appreciate your help. Please find it below:

^CTraceback (most recent call last):
      File "/home/nitrous/code/trendomine/bin/scrapy", line 11, in <module>
        sys.exit(execute())
      File "/home/nitrous/code/trendomine/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 142, in execute
        cmd.crawler_process = CrawlerProcess(settings)
      File "/home/nitrous/code/trendomine/local/lib/python2.7/site-packages/scrapy/crawler.py", line 209, in __init__
        super(CrawlerProcess, self).__init__(settings)
      File "/home/nitrous/code/trendomine/local/lib/python2.7/site-packages/scrapy/crawler.py", line 115, in __init__
        self.spider_loader = _get_spider_loader(settings)
      
    File "/home/nitrous/code/trendomine/local/lib/python2.7/site-packages/scrapy/crawler.py", line 296, in _get_spider_loader
        return loader_cls.from_settings(settings.frozencopy())
      File "/home/nitrous/code/trendomine/local/lib/python2.7/site-packages/scrapy/spiderloader.py", line 30, in from_settings
        return cls(settings)
      File "/home/nitrous/code/trendomine/local/lib/python2.7/site-packages/scrapy/spiderloader.py", line 21, in __init__
        for module in walk_modules(name):
      File "/home/nitrous/code/trendomine/local/lib/python2.7/site-packages/scrapy/utils/misc.py", line 71, in walk_modules
        submod = import_module(fullpath)
      File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/home/nitrous/code/trendomine/fancy/fancy/spiders/fancy_update_spider.py", line 11, in <module>
        class FancyUpdateSpider(scrapy.Spider):
      File "/home/nitrous/code/trendomine/fancy/fancy/spiders/fancy_update_spider.py", line 28, in FancyUpdateSpider
        pg_r = requests.get(url, headers=headers)
      File "/home/nitrous/code/trendomine/local/lib/python2.7/site-packages/requests/api.py", line 69, in get
        return request('get', url, params=params, **kwargs)
      File "/home/nitrous/code/trendomine/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
        response = session.request(method=method, url=url, **kwargs)
      File "/home/nitrous/code/trendomine/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/nitrous/code/trendomine/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
        r = adapter.send(request, **kwargs)
      File "/home/nitrous/code/trendomine/local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
        timeout=timeout
      File "/home/nitrous/code/trendomine/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
        body=body, headers=headers)
      File "/home/nitrous/code/trendomine/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 376, in _make_request
        httplib_response = conn.getresponse(buffering=True)
      File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
        response.begin()
      File "/usr/lib/python2.7/httplib.py", line 415, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
        line = self.fp.readline(_MAXLINE + 1)
      File "/usr/lib/python2.7/socket.py", line 476, in readline
        data = self._sock.recv(self._rbufsize)
      File "/home/nitrous/code/trendomine/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 179, in recv
        data = self.connection.recv(*args, **kwargs)
      File "/home/nitrous/code/trendomine/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1319, in recv
        result = _lib.SSL_read(self._ssl, buf, bufsiz)
    KeyboardInterrupt

Thanks

**Comment by kmike** [comment]
Aha, so it looks like you have FancyUpdateSpider which sends a request using requests library, and this requests takes a lot of time.

**Comment by kmike** [comment]
It doesn't looks like a Scrapy issue, so I'm closing it.

**Comment by bnussey** [comment]
Hey @kmike got it, thanks for your help. I know this is out of scope, but I am new to Scrapy, so if you could assist, I would be hugely appreciative: In terms of the structure of scrapy scripts, is there anyway to wrap this up in a function so the request is not executed every time I do anything else in my project?

```
import scrapy
from urlparse import urljoin
import re
import json
import requests
import math
from scrapy.conf import settings

from fancy.items import FancyItem

def roundup(x):
  return int(math.ceil(x / 10.0)) * 10

class FancyUpdateSpider(scrapy.Spider):

  name = 'fancy_update'
  allowed_domains = ['foo.com']

def get_urls():
    # Get URLS
    url = 'https://www.foo.co/api/v1/product_urls?q%5Bcompany_in%5D%5B%5D=bar'
    headers = {'X-Api-Key': settings['API_KEY'], 'Content-Type': 'application/json'}
    r = requests.get(url, headers=headers)
    # Get initial data
    start_urls_data = json.loads(r.content)
    # Grab the total number of products and round up to nearest 10
    count = roundup(int(r.headers['count']))
    pages = (count / 10) + 1

    for i in range (2, pages):
      pg_url = 'https://www.foo.co/api/v1/product_urls?q%5Bcompany_in%5D%5B%5D=bar&page={0}'.format(i)
      pg_r = requests.get(pg_url, headers=headers)
      # Add remaining data to the JSON
      additional_start_urls_data = json.loads(pg_r.content)
      start_urls_data.extend(additional_start_urls_data)

  get_urls()
  start_urls = [x["link"] for x in start_urls_data]

  def parse(self, response):
    item = FancyItem()
    item['link'] = response.url
    new_body = re.sub(r'<a href="#" class="fancyd_list "/>', '<a href="#" class="fancyd_list ">', response.body)
    response = response.replace(body=new_body)
    likes = response.xpath("//div[@class='frm']/div[@class='figure-button']/a[contains(@class, 'fancyd_list')]/text()").extract_first()
    # Check if likes exist and then strip if so. If no likes, then set to 0
    if likes:
      item['interest'] = likes.strip().replace(",", "")
    else:
      item['interest'] = 0
    return item
```

**Comment by bnussey** [comment]
Think I resolved it with `def start_requests(self):` Thanks mate!
