### ISSUE TITLE
ImportError: Error loading object 'scrapy.contrib.memusage.MemoryUsage': No module named uu

### ISSUE THREAD

**Issue by praveshjain** [scrapy/scrapy#1604]
I've been using scrapy on Mac for over 6 months now when today, out of nowhere I start getting this issue.

I ran it like I normally do using "scrapy crawl <spider>". I also tried checking my twisted installation, which is working fine.

Here is the complete stacktrace of the issue:

2015-11-16 17:07:00+0530 [scrapy] INFO: Scrapy 0.24.6 started (bot: scrapybot)
2015-11-16 17:07:00+0530 [scrapy] INFO: Optional features available: ssl, http11
2015-11-16 17:07:00+0530 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'Crawler.spiders', 'SPIDER_MODULES': ['Crawler.spiders', 'Crawler.availability_spiders'], 'COOKIES_ENABLED': False, 'USER_AGENT': 'Mozilla/5.0 (Windows NT 6.3; rv:36.0) Gecko/20100101 Firefox/36.0'}
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/Library/Python/2.7/site-packages/scrapy/cmdline.py", line 143, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/Library/Python/2.7/site-packages/scrapy/cmdline.py", line 89, in _run_print_help
    func(*a, **kw)
  File "/Library/Python/2.7/site-packages/scrapy/cmdline.py", line 150, in _run_command
    cmd.run(args, opts)
  File "/Library/Python/2.7/site-packages/scrapy/commands/crawl.py", line 60, in run
    self.crawler_process.start()
  File "/Library/Python/2.7/site-packages/scrapy/crawler.py", line 92, in start
    if self.start_crawling():
  File "/Library/Python/2.7/site-packages/scrapy/crawler.py", line 124, in start_crawling
    return self._start_crawler() is not None
  File "/Library/Python/2.7/site-packages/scrapy/crawler.py", line 139, in _start_crawler
    crawler.configure()
  File "/Library/Python/2.7/site-packages/scrapy/crawler.py", line 46, in configure
    self.extensions = ExtensionManager.from_crawler(self)
  File "/Library/Python/2.7/site-packages/scrapy/middleware.py", line 50, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/Library/Python/2.7/site-packages/scrapy/middleware.py", line 29, in from_settings
    mwcls = load_object(clspath)
  File "/Library/Python/2.7/site-packages/scrapy/utils/misc.py", line 42, in load_object
    raise ImportError("Error loading object '%s': %s" % (path, e))
ImportError: Error loading object 'scrapy.contrib.memusage.MemoryUsage': No module named uu

Please provide guidelines on why this is happening.

**Comment by nramirezuy** [comment]
@praveshjain Well the trace is pretty explanatory. So either you are overriding scrapy modules on your PYTHONPATH or the actual files are overridden the files.


So, these issues are meant for bugs about Scrapy.
Please use the community channels to ask for help about how to use Scrapy (mailing list: http://groups.google.com/group/scrapy-users Stackoverflow scrapy tag: http://stackoverflow.com/questions/tagged/scrapy)

**Comment by praveshjain** [comment]
@nramirezuy I'm sorry I didn't realise that. Thanks a lot for directing me!
