### ISSUE TITLE
TypeError: 'ItemLoader' object does not support item assignment

### ISSUE THREAD

**Issue by haoflynet** [scrapy/scrapy#1608]
There is my code:
    def parse(self, response):
        item = ItemLoader(item=MyItem(), response = response)
        item.default_output_processor = TakeFirst()

        item.add_value('name', 'value')

        yield scrapy.Request(Myurl, meta={'myitem': item}, callback=self.parse_next)

    def parse_next(self, response):
        item = response.meta['myitem']

        newitem = ItemLoader(item=item, response=response)

        newitem.add_value('name1', 'value1')
        newitem.add_xpath('name2', '//div')

        # type(response.meta['myitem']), it output "<class 'scrapy.loader.ItemLoader'>"
        # type(newitem), it also output "<class 'scrapy.loader.ItemLoader'>"

        yield newitem.load_item()

I want to transfer one item to another parse function, but I encounter one exception at last.

    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 102, in iter_errback
        yield next(it)
      File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/offsite.py", line 28, in process_spider_output
        for x in result:
      File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/referer.py", line 22, in <genexpr>
        return (_set_referer(r) for r in result or ())
      File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
        return (r for r in result or () if _filter(r))
      File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/depth.py", line 54, in <genexpr>
        return (r for r in result or () if _filter(r))
      File "/media/sf_workspace/yiche/yiche/spiders/CarstyleSpider.py", line 117, in parse_car
        yield carstyle.load_item()
      File "/usr/local/lib/python2.7/dist-packages/scrapy/loader/__init__.py", line 86, in load_item
        item[field_name] = value
    TypeError: 'ItemLoader' object does not support item assignment
    2015-11-19 20:03:07 [scrapy] INFO: Closing spider (finished)

**Comment by nramirezuy** [comment]
@haoflynet [read the docs](http://doc.scrapy.org/en/master/topics/loaders.html#scrapy.loader.ItemLoader.load_item), you are moving an `ItemLoader` instance.

So, these issues are meant for bugs about Scrapy.
Please use the community channels to ask for help about how to use Scrapy (mailing list: http://groups.google.com/group/scrapy-users Stackoverflow scrapy tag: http://stackoverflow.com/questions/tagged/scrapy).
