### ISSUE TITLE
Tracebacks are wrongfully written to stderr

### ISSUE THREAD

**Issue by brunsgaard** [scrapy/scrapy#1609]
Hay folks,

Sometimes i see this error while crawling, and that is fine and dandy.  

```
2015-11-20 17:11:36 [scrapy] ERROR: Error downloading <GET http://reservations.hotline.com/templates/52591/>
```

But is it expected behavior that the Traceback end up in the terminal, or is that a bug that have to be addressed?

```
2015-11-20 17:11:36 [scrapy] ERROR: Error downloading <GET http://reservations.hotline.com/templates/52591/>
Traceback (most recent call last):
  File "/Users/brunsgaard/clerk/crawlers/venv2/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/brunsgaard/clerk/crawlers/venv2/lib/python2.7/site-packages/scrapy/core/downloader/handlers/http11.py", line 226, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
TimeoutError: User timeout caused connection failure: Getting http://reservations.hotline.com/templates/52591/ took longer than 6.0 seconds..
```

It seems that
https://github.com/scrapy/scrapy/blob/master/scrapy/core/downloader/handlers/http11.py#L226
raises the error, but shouldn't the error be caught somewhere?

**Comment by Digenis** [comment]
This bug appeared after switching from twisted to python logging.
It is not the only case where tracebacks are dumped to stderr.

**Comment by nyov** [comment]
So anyone knows [what is wrong with it](https://github.com/scrapy/scrapy/blob/3735eb8e5f62a52c5630ede765b443cb1313ff96/scrapy/core/downloader/handlers/http11.py#L301)? Why does it bubble up, where to catch it?

**Comment by westwind027** [comment]
@Digenis   You mean if we use self.logger  and  use  errcallback there will not  have those  traceback print again?

@nyov  I think you can refer http://doc.scrapy.org/en/latest/topics/request-response.html#using-errbacks-to-catch-exceptions-in-request-processing

**Comment by Digenis** [comment]
No. I think a proper solution would be what I describe here.
https://github.com/scrapy/scrapy/issues/1964#issuecomment-216814406
Unfortunately I'm very busy these weeks and I can't work on it.

**Comment by westwind027** [comment]
OK, I understand what you want to do

**Comment by AdrianAtZyte** [comment]
This seems to be the behavior if no downloader middleware or errback catches the exception, and to me that sounds as designed. Not sure there is anything to be done here.

**Comment by wRAR** [comment]
Yes, it's by design AFAIK.
