### ISSUE TITLE
Test for startproject command fails in OS X

### ISSUE THREAD

**Issue by rolando** [scrapy/scrapy#1635]
Apparently, `os.mknod` is a privileged call in OS X:

```
$ python -c 'import os; os.mknod("/tmp/test")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 1] Operation not permitted

```

Output of the test failure:

```
$ nosetests tests/test_commands.py
...................E..
======================================================================
ERROR: test_startproject_template_override
----------------------------------------------------------------------
Traceback (most recent call last):
  File "lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "lib/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "scrapy/tests/test_commands.py", line 86, in test_startproject_template_override
    os.mknod(join(self.tmpl_proj, 'root_template'))
OSError: [Errno 1] Operation not permitted
```

**Comment by eLRuLL** [comment]
related PR: https://github.com/scrapy/scrapy/pull/1575

**Comment by palego** [comment]
Could you please check that PR #1657 solves this issue?

**Comment by rolando** [comment]
@palego I get this failure:

```
scrapy git:(pr/1657) ✗ nosetests tests/test_commands.py
...................F..
======================================================================
FAIL: test_startproject_template_override
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rolando/miniconda/envs/orchardmile-spiders/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/Users/rolando/miniconda/envs/orchardmile-spiders/lib/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/Users/rolando/miniconda/envs/orchardmile-spiders/lib/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/Users/rolando/Projects/gh/scrapy/tests/test_commands.py", line 94, in test_startproject_template_override
    (self.project_name, join(self.tmpl, 'project')), out)
  File "/Users/rolando/miniconda/envs/orchardmile-spiders/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 497, in assertIn
    % (containee, container))
FailTest: "New Scrapy project 'testproject', using template directory '/var/folders/55/nbg15c6j4k3cg06tjfhqypd40000gn/T/tmpl2NVJx/templates/project', created in:" not in "New Scrapy project 'testproject' created in:\n    /private/var/folders/55/nbg15c6j4k3cg06tjfhqypd40000gn/T/tmpl2NVJx/testproject\n\nYou can start your first spider with:\n    cd testproject\n    scrapy genspider example example.com\n"

----------------------------------------------------------------------
Ran 22 tests in 28.886s

FAILED (failures=1)
```

**Comment by rolando** [comment]
The test fails because `/var` is a link to `/private/var`. So the output contains the path with the unexpected `/private` prefix.

**Comment by palego** [comment]
I have just pushed a new commit to PR #1657 to work around the path mangling.

Additionally, the last line of your latest traceback indicates that PR #1575 is not applied:
> "New Scrapy project 'testproject', using template directory..." not in
> "New Scrapy project 'testproject' created in..."

The tests depend on the changes brought by #1575 and will fail in their absence.

**Comment by redapple** [comment]
@rolando , are you ok with closing the issue now that https://github.com/scrapy/scrapy/pull/1657 is merged?

**Comment by rolando** [comment]
@redapple yes! This issue is fixed.

**Comment by redapple** [comment]
Thanks for checking @rolando
