### ISSUE TITLE
ipython 4.0.1 / python 2.7.11 "scrapy shell" breaks with "ValueError: fallback required, but not specified"

### ISSUE THREAD

**Issue by jschilling1** [scrapy/scrapy#1646]
scrapy shell "url" breaks with the following traceback:

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/master2/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/home/user/.pyenv/versions/2.7.11/envs/master2/lib/python2.7/site-packages/scrapy/cmdline.py", line 143, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/home/user/.pyenv/versions/2.7.11/envs/master2/lib/python2.7/site-packages/scrapy/cmdline.py", line 89, in _run_print_help
    func(_a, *_kw)
  File "/home/user/.pyenv/versions/2.7.11/envs/master2/lib/python2.7/site-packages/scrapy/cmdline.py", line 150, in _run_command
    cmd.run(args, opts)
  File "/home/user/.pyenv/versions/2.7.11/envs/master2/lib/python2.7/site-packages/scrapy/commands/shell.py", line 63, in run
    shell.start(url=url)
  File "/home/user/.pyenv/versions/2.7.11/envs/master2/lib/python2.7/site-packages/scrapy/shell.py", line 55, in start
    start_python_console(self.vars)
  File "/home/user/.pyenv/versions/2.7.11/envs/master2/lib/python2.7/site-packages/scrapy/utils/console.py", line 24, in start_python_console
    banner1=banner, user_ns=namespace, config=config)
  File "/home/user/.pyenv/versions/2.7.11/envs/master2/lib/python2.7/site-packages/IPython/terminal/embed.py", line 68, in __init__
    super(InteractiveShellEmbed,self).**init**(**kw)
  File "/home/user/.pyenv/versions/2.7.11/envs/master2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 547, in **init**
    self.init_io()
  File "/home/user/.pyenv/versions/2.7.11/envs/master2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 718, in init_io
    io.stdout = io.IOStream(sys.stdout)
  File "/home/user/.pyenv/versions/2.7.11/envs/master2/lib/python2.7/site-packages/IPython/utils/io.py", line 28, in **init**
    raise ValueError("fallback required, but not specified")
ValueError: fallback required, but not specified

**Comment by Digenis** [comment]
To reproduce this bug, set `LOG_STDOUT=True`
eg `scrapy shell -s LOG_STDOUT=1`
 :wink:

**Comment by Digenis** [comment]
I suggest this issue is renamed to `"LOG_STDOUT = True" breaks scrapy commands.`
This is a bug.

Maybe LOG_STDOUT should cause stdout to be replicated in the log instead of redirected.
An alternative would be to override LOG_STDOUT in various scrapy commands.

**Comment by wRAR** [comment]
Unable to reproduce.
