### ISSUE TITLE
KeyError in robotstxt middleware

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#1733]
I'm getting these errors in robots.txt middleware:

```
2016-01-27 16:18:21 [scrapy.core.scraper] ERROR: Error downloading <GET http://yellowpages.co.th>
Traceback (most recent call last):
  File "/Users/kmike/envs/scraping/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/Users/kmike/svn/scrapy/scrapy/downloadermiddlewares/robotstxt.py", line 65, in robot_parser
    if isinstance(self._parsers[netloc], Deferred):
KeyError: 'yellowpages.co.th'
```

It looks like https://github.com/scrapy/scrapy/pull/1473 caused it (I can't get this issue in Scrapy 1.0.4, but it present in Scrapy master). It happens when page failed to download and HTTP cache is enabled. I haven't debugged it further.

**Comment by kmike** [comment]
Marking it for 1.1 because it is regression since 1.0.x.
