### ISSUE TITLE
Python 3.4+ still not supported in 1.1.0rc1

### ISSUE THREAD

**Issue by jschilling1** [scrapy/scrapy#1759]
Looks like you guys might have only tested 3.3 for now, i can't even run that one because of a Django 1.9 dependency, running 3.4.4 and 3.5.1 results in the following:

```
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.4.4/lib/python3.4/site-packages/scrapy/commands/crawl.py", line 57, in run
    self.crawler_process.crawl(spname, **opts.spargs)
  File "/home/user/.pyenv/versions/3.4.4/lib/python3.4/site-packages/scrapy/crawler.py", line 152, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "/home/user/.pyenv/versions/3.4.4/lib/python3.4/site-packages/scrapy/crawler.py", line 156, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.4.4/lib/python3.4/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/home/user/.pyenv/versions/3.4.4/lib/python3.4/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/user/.pyenv/versions/3.4.4/lib/python3.4/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/user/.pyenv/versions/3.4.4/lib/python3.4/site-packages/scrapy/crawler.py", line 80, in crawl
    yield exc
builtins.SyntaxError: invalid syntax (context_managers.py, line 535)
2016-02-04 11:45:07 [twisted] CRITICAL: 
```

**Comment by kmike** [comment]
hey @jschilling1,

I'm running Scrapy in Python 3.5.

The traceback shows 'builtins.SyntaxError: invalid syntax (context_managers.py, line 535)'  error - what is `context_managers.py` file? Scrapy doesn't have it. It looks like a problem with some code outside Scrapy. Are you using any third-party components, or is there a `context_managers.py` file in your project?

**Comment by jschilling1** [comment]
An unused import for Fabric was causing that error. 
Does Scrapy need to show more traceback info or this a python 3 "feature" due to its improved error reporting? I basically had to Google context_managers.py to figure this one out. 

I'm now getting an item loader related error:
```
  File "/home/user/Code/projects/flowershop/crawlers/spiders/spiders.py", line 487, in parse_items
    l.add_xpath('url', ".//a[@title='Details']/@href")
  File "/home/user/.pyenv/versions/master3/lib/python3.5/site-packages/scrapy/loader/__init__.py", line 167, in add_xpath
    self.add_value(field_name, values, *processors, **kw)
  File "/home/user/.pyenv/versions/master3/lib/python3.5/site-packages/scrapy/loader/__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "/home/user/.pyenv/versions/master3/lib/python3.5/site-packages/scrapy/loader/__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "/home/user/.pyenv/versions/master3/lib/python3.5/site-packages/scrapy/loader/__init__.py", line 148, in _process_input_value
    proc = self.get_input_processor(field_name)
  File "/home/user/.pyenv/versions/master3/lib/python3.5/site-packages/scrapy/loader/__init__.py", line 137, in get_input_processor
    self.default_input_processor)
  File "/home/user/.pyenv/versions/master3/lib/python3.5/site-packages/scrapy/loader/__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'url'
```

**Comment by kmike** [comment]
@jschilling1 better error reporting will certainly help, but it is not clear how to do it; I think now we just rely on Twisted to show errors. Suggestions are welcome! Errors in Python 3 should be more detailed than in Python 2.x because it stores full exception chains, not only the last exception. But I'm not sure how well Twisted Deferreds support this.

**Comment by kmike** [comment]
Could you please provide an example to reproduce the second issue?

**Comment by kmike** [comment]
by the way, where was this import?

**Comment by jschilling1** [comment]
i'm trying to get more info on the loader issue.
it was "import my_class" which had "from fabfile import fab, reindex" which are fabric task functions

**Comment by kmike** [comment]
did you have `import my_class` import in spider code, or in settings, or in some component (extesion/middleware/pipeline), or did it happen at runtime (e.g. in start_requests)?

**Comment by jschilling1** [comment]
it was at the top of a pipeline

**Comment by jschilling1** [comment]
The loader issue has to do with the DjangoItem, i replaced it with a normal Item and the spider works. It looks like DjangoIitem need a few Python3 tweaks.  This one fixed my immediate error:

```
class DjangoItem(Item, metaclass=DjangoItemMeta):

    # __metaclass__ = DjangoItemMeta 
```

**Comment by kmike** [comment]
:+1: thanks for checking it! Yeah, it looks like [scrapy-djangoitem](https://github.com/scrapy-plugins/scrapy-djangoitem) is not ported yet.

**Comment by kmike** [comment]
I've opened https://github.com/scrapy-plugins/scrapy-djangoitem/issues/10 and #1760 for the problems you reported.
