### ISSUE TITLE
Unable to run scrapy on Python3.5.1

### ISSUE THREAD

**Issue by adeelehsan** [scrapy/scrapy#1773]
I have python3.5.1 on my system and i have also creates the virtual enviorment with python 3.5.1. I have installed scrapy 1.0.5 and when i tried to run the command "Scrapy version"  or scrapy startproject , I am getting following error:
Traceback (most recent call last):
  File "/home/adeel/Intermix_py3.5/venv/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/home/adeel/Intermix_py3.5/venv/lib/python3.5/site-packages/scrapy/cmdline.py", line 122, in execute
    cmds = _get_commands_dict(settings, inproject)
  File "/home/adeel/Intermix_py3.5/venv/lib/python3.5/site-packages/scrapy/cmdline.py", line 46, in _get_commands_dict
    cmds = _get_commands_from_module('scrapy.commands', inproject)
  File "/home/adeel/Intermix_py3.5/venv/lib/python3.5/site-packages/scrapy/cmdline.py", line 29, in _get_commands_from_module
    for cmd in _iter_command_classes(module):
  File "/home/adeel/Intermix_py3.5/venv/lib/python3.5/site-packages/scrapy/cmdline.py", line 21, in _iter_command_classes
    for obj in vars(module).itervalues():
AttributeError: 'dict' object has no attribute 'itervalues'

**Comment by redapple** [comment]
This `.itervalues()` call for the command line tool has been [changed here](https://github.com/scrapy/scrapy/commit/3e6d6c43ac0763adf2cd92efdb4a1dc2ba165440)

@adeelehsan , what version of scrapy have you installed?
Scrapy 1.0.x is not Python 3 compatible.
Either use the current master branch or install 1.1.0rc1
`$ pip install scrapy==1.1.0rc1`

**Comment by micmalti** [comment]
@redapple I've tried both of your suggestions but didn't work.

```
File "/home/micmalti/Downloads/pypy3-v5.8.0-linux64/site-packages/scrapy/http/request/form.py", line 11, in <module>
    import lxml.html
  File "/home/micmalti/Downloads/pypy3-v5.8.0-linux64/site-packages/lxml/html/__init__.py", line 54, in <module>
    from .. import etree
  File "src/lxml/xmlschema.pxi", line 22, in init lxml.etree (src/lxml/lxml.etree.c:231895)
  File "src/lxml/xpath.pxi", line 420, in lxml.etree.XPath.__init__ (src/lxml/lxml.etree.c:173999)
  File "src/lxml/xpath.pxi", line 150, in lxml.etree._XPathEvaluatorBase.set_context (src/lxml/lxml.etree.c:170398)
  File "src/lxml/xpath.pxi", line 66, in lxml.etree._XPathContext.set_context (src/lxml/lxml.etree.c:169176)
  File "src/lxml/extensions.pxi", line 255, in lxml.etree._BaseContext.registerLocalFunctions (src/lxml/lxml.etree.c:160400)
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by redapple** [comment]
@micmalti , are you using PyPy3 on purpose? I don't think we test Scrapy for PyPy3 yet (nor do I know if lxml supports it)

**Comment by micmalti** [comment]
Yes, to test whether there will be any improvement in performance.  I am currently running the script in scrapy 1.4.0 as part of python 3.6.1

**Comment by kmike** [comment]
@micmalti error message points to lxml; what is your lxml version? They improved pypy compatibility recently. Anyways, it looks very different from the original issue.

**Comment by lopuhin** [comment]
@micmalti I was getting the same error message with lxml + pypy3, it was fixed (https://bitbucket.org/pypy/pypy/issues/2497/installing-lxml-fails-on-pypy-35-static) but then broke again I think. Best report it to pypy issue tracker, especially if you can also check master lxml + master cython.

**Comment by lopuhin** [comment]
sorry, this is the right issue https://bitbucket.org/pypy/pypy/issues/2498/cython-on-pypy-3-dict-object-has-no

**Comment by micmalti** [comment]
@kmike I'm using lxml 3.8.0

**Comment by micmalti** [comment]
@lopuhin I've seen that discussion.  However, I didn't understand how am I going to solve the issue and have lxml running properly. Transitioning to pypy3 should lower the execution time of my script, hopefully.

**Comment by lopuhin** [comment]
@micmalti I tried to install it some time ago and also couldn't do it. I think the best way to solve this is to try lxml master + cython master, and if this still does not work, open an issue in pypy bugtracker. Also be aware that scrapy is not tested on pypy3 at all, so there might be other issues hiding. There is some speed improvement for pypy2 + scrapy (if your spider is CPU bound).

**Comment by micmalti** [comment]
Thanks @lopuhin

**Comment by micmalti** [comment]
@lopuhin Due to incompatibility issues with the cryptography module, scrapy doesn't run on pypy2.

**Comment by lopuhin** [comment]
@micmalti scrapy is tested with pypy on travis: https://travis-ci.org/scrapy/scrapy but installing cryptography can be tricky indeed, depending on your system and libraries, but it should be possible.

**Comment by micmalti** [comment]
@lopuhin I'll give it a try and will keep you posted.

**Comment by micmalti** [comment]
Update:
Downloaded pypy2-v5.6.0 from: https://bitbucket.org/pypy/pypy/downloads/  I found that cryptography is compatible with this version.  Then installed pip and all the necessary modules through: 
```
wget https://bootstrap.pypa.io/get-pip.py
sudo pypy get-pip.py
sudo -H pypy -m pip install cython lxml BeautifulSoup4 requests cryptography
sudo -H pypy -m pip install scrapy
```
However, I'm now getting this error:
```

2017-09-06 22:10:06 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method CoreStats.spider_opened of <scrapy.extensions.corestats.CoreStats object at 0x000000000370bd70>>
Traceback (most recent call last):
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
TypeError: spider_opened() got 2 unexpected keyword arguments

2017-09-06 22:10:06 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method instance.start_listening of <scrapy.extensions.telnet.TelnetConsole instance at 0x0000000002b3ace0>>
Traceback (most recent call last):
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
TypeError: start_listening() got 2 unexpected keyword arguments

2017-09-06 22:10:06 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method MemoryUsage.engine_started of <scrapy.extensions.memusage.MemoryUsage object at 0x0000000003af8838>>
Traceback (most recent call last):
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
TypeError: engine_started() got 2 unexpected keyword arguments

2017-09-06 22:10:06 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method RefererMiddleware.request_scheduled of <scrapy.spidermiddlewares.referer.RefererMiddleware object at 0x00000000037f4988>>
Traceback (most recent call last):
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/scrapy/utils/signal.py", line 30, in send_catch_log
    *arguments, **named)
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
TypeError: request_scheduled() got 2 unexpected keyword arguments

2017-09-06 22:10:10 [scrapy.core.engine] DEBUG: Crawled (200) <GET  _requested url_> (referer: None)
2017-09-06 22:10:10 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method CoreStats.response_received of <scrapy.extensions.corestats.CoreStats object at 0x000000000370bd70>>
Traceback (most recent call last):
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/scrapy/utils/signal.py", line 30, in send_catch_log
    *arguments, **named)
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
TypeError: response_received() got 4 unexpected keyword arguments

2017-09-06 22:10:10 [scrapy.core.scraper] ERROR: Spider error processing <GET _requested url_> (referer: None)
Traceback (most recent call last):
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/scrapy/spidermiddlewares/offsite.py", line 31, in process_spider_output
    if x.dont_filter or self.should_follow(x, spider):
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/scrapy/spidermiddlewares/offsite.py", line 45, in should_follow
    regex = self.host_regex
AttributeError: 'OffsiteMiddleware' object has no attribute 'host_regex'

2017-09-06 22:10:11 [scrapy.core.engine] DEBUG: Crawled (200) <GET _requested url_> (referer: None)
2017-09-06 22:10:11 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method CoreStats.response_received of <scrapy.extensions.corestats.CoreStats object at 0x000000000370bd70>>
Traceback (most recent call last):
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/scrapy/utils/signal.py", line 30, in send_catch_log
    *arguments, **named)
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
TypeError: response_received() got 4 unexpected keyword arguments

2017-09-06 22:10:12 [scrapy.core.scraper] ERROR: Spider error processing <GET _requested url_> (referer: None)
Traceback (most recent call last):
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/scrapy/spidermiddlewares/offsite.py", line 31, in process_spider_output
    if x.dont_filter or self.should_follow(x, spider):
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/scrapy/spidermiddlewares/offsite.py", line 45, in should_follow
    regex = self.host_regex
AttributeError: 'OffsiteMiddleware' object has no attribute 'host_regex'

2017-09-06 22:10:12 [scrapy.core.engine] INFO: Closing spider (finished)
2017-09-06 22:10:12 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method CoreStats.spider_closed of <scrapy.extensions.corestats.CoreStats object at 0x000000000370bd70>>
Traceback (most recent call last):
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
TypeError: spider_closed() got 2 unexpected keyword arguments

2017-09-06 22:10:12 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method LogStats.spider_closed of <scrapy.extensions.logstats.LogStats object at 0x0000000003b3c058>>
Traceback (most recent call last):
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
TypeError: spider_closed() got 2 unexpected keyword arguments

2017-09-06 22:10:12 [scrapy.utils.signal] ERROR: Error caught on signal handler: <function close at 0x0000000002477880>
Traceback (most recent call last):
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
TypeError: close() got 2 unexpected keyword arguments

2017-09-06 22:10:12 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 577,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 3849716,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 2,
 'log_count/DEBUG': 2,
 'log_count/ERROR': 17,
 'log_count/INFO': 6,
 'request_depth_max': 1,
 'scheduler/dequeued': 2,
 'scheduler/dequeued/memory': 2,
 'scheduler/enqueued': 2,
 'scheduler/enqueued/memory': 2,
 'spider_exceptions/AttributeError': 2}
2017-09-06 22:10:12 [scrapy.core.engine] INFO: Spider closed (finished)

2017-09-06 22:10:12 [scrapy.utils.signal] ERROR: Error caught on signal handler: <function <lambda> at 0x00000000024e4ae8>
Traceback (most recent call last):
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
TypeError: <lambda>() takes no arguments (2 given)

2017-09-06 22:10:12 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method instance.stop_listening of <scrapy.extensions.telnet.TelnetConsole instance at 0x0000000002b3ace0>>
Traceback (most recent call last):
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
TypeError: stop_listening() got 2 unexpected keyword arguments
2017-09-06 22:10:12 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method MemoryUsage.engine_stopped of <scrapy.extensions.memusage.MemoryUsage object at 0x0000000003af8838>>
Traceback (most recent call last):
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/micmalti/pypy2-v5.6.0-linux64/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
TypeError: engine_stopped() got 2 unexpected keyword arguments

```

**Comment by lopuhin** [comment]
@micmalti this is an issue that is fixed in a pypy-compatible pydispatcher, which should have been installed when you did ``pip install scrapy``. Do you happen to have the log of how you installed scrapy?
Running ``pip install PyPyDispatcher>=2.1.0`` should fix this issue.

**Comment by micmalti** [comment]
@lopuhin Yes, it worked.  However, it didn't come with the performance boost which I was expecting.

**Comment by lopuhin** [comment]
@micmalti glad you solved the problem, and sorry to hear that you didn't get the speedup you were expecting. There can be several reasons:
- pypy takes some time to "warm up" the JIT, more than 10 seconds for scrapy
- maybe pypy is unable to speedup the kind of code that is most critical in your case (e.g. frequent small lxml operations)
- maybe the spider was not CPU bound?

We're yet to put up a proper benchmark with PyPy, but on simple CPU bound spiders I observed about 1.5x-2x speedup.
