### ISSUE TITLE
Spider has no attribute 'update_settings'

### ISSUE THREAD

**Issue by DeckerCHAN** [scrapy/scrapy#1849]
"D:\Program Files\Python\Python35-32\python.exe" G:/Python/ParkingSearch/entry_point.py
2016-03-06 12:43:40 [scrapy] INFO: Scrapy 1.0.5 started (bot: scrapybot)
2016-03-06 12:43:40 [scrapy] INFO: Optional features available: http11, ssl
2016-03-06 12:43:40 [scrapy] INFO: Overridden settings: {}
Traceback (most recent call last):
  File "G:/Python/ParkingSearch/entry_point.py", line 16, in <module>
    main()
  File "G:/Python/ParkingSearch/entry_point.py", line 11, in main
    process.crawl(go_and_see_aus_spider)
  File "D:\Program Files\Python\Python35-32\lib\site-packages\scrapy\crawler.py", line 150, in crawl
    crawler = self._create_crawler(crawler_or_spidercls)
  File "D:\Program Files\Python\Python35-32\lib\site-packages\scrapy\crawler.py", line 166, in _create_crawler
    return Crawler(spidercls, self.settings)
  File "D:\Program Files\Python\Python35-32\lib\site-packages\scrapy\crawler.py", line 32, in __init__
    self.spidercls.update_settings(self.settings)
AttributeError: module 'crawler.spiders.test_spider' has no attribute 'update_settings'

**Comment by kmike** [comment]
@DeckerCHAN could you please provide an example code which fails with this error?

**Comment by DeckerCHAN** [comment]
[This](https://github.com/DeckerCHAN/parkingSearcherPython) is my repo. You may explore this code.

**Comment by kmike** [comment]
@DeckerCHAN you're passing a module to process.crawl, while it accepts either a Spider instance or a spider name. See http://doc.scrapy.org/en/latest/topics/api.html#scrapy.crawler.CrawlerProcess.crawl

**Comment by DeckerCHAN** [comment]
BTW, I've encountered problem when using "scrapy" command in CMD.
System Infos: Win10 Py35(32bit)
![image](https://cloud.githubusercontent.com/assets/1845937/13601982/db05a6d8-e587-11e5-8fb5-fa040800d8ba.png)

**Comment by kmike** [comment]
@DeckerCHAN it looks like https://github.com/pypa/pip/issues/2783; before Python 3.5 default install dir was without spaces, but 3.5 is installed in Program Files. Could you try

1. upgrading pip;
2. upgrading Scrapy using new pip?

I don't think it can be fixed in Scrapy.

**Comment by DeckerCHAN** [comment]
After re-install python at root of driver D and update pip with easy_install, everything works good! Thank you for your assistance! Helps a lot!
