### ISSUE TITLE
ImportError: No module named spiders

### ISSUE THREAD

**Issue by kallesoderlund** [scrapy/scrapy#1859]
I've been working on a scrapy project, and although I'm fairly new to scrapy I've been able to get it to run properly. However, after I tried to get Scrapyd to work, I can't get Scrapy to work either. 
I get the ImportError, and can't figure out what to do. 

I did a pip uninstall scrapy and reinstalled it, but still the same problem. I can't even start a new scrapy project, I get the same ImportError message. I run Scrapy 1.04. Please help

**Comment by kallesoderlund** [comment]
This is my traceback btw.

C:\Users\A503482\afevent>scrapy startproject testa
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\scrapy.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\scrapy\cmdline.py", line 142, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "c:\python27\lib\site-packages\scrapy\crawler.py", line 209, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "c:\python27\lib\site-packages\scrapy\crawler.py", line 115, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "c:\python27\lib\site-packages\scrapy\crawler.py", line 296, in _get_spid
er_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "c:\python27\lib\site-packages\scrapy\spiderloader.py", line 30, in from_
settings
    return cls(settings)
  File "c:\python27\lib\site-packages\scrapy\spiderloader.py", line 21, in __ini
t__
    for module in walk_modules(name):
  File "c:\python27\lib\site-packages\scrapy\utils\misc.py", line 63, in walk_mo
dules
    mod = import_module(path)
  File "c:\python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named spiders

**Comment by shafaq** [comment]
In your code did you do something like 
`from scrapy.spiders import Spider`??

**Comment by kallesoderlund** [comment]
@shafaq Yes, in one spider I have
 `from scrapy.spiders import Spider` 
and in another spider I have
`from scrapy.spiders import CrawlSpider`

But none of them are working. I'm running out of ideas, and it's extra frustrating because it has been working fine recently.

**Comment by kallesoderlund** [comment]
Okay, for some reason it's resolved, although I'm not sure why it worked. Copied the entire project folder and deleted the old one. Then I created a new scrapy project with the same name and pasted all my work into the new folder. 

Thanks though for the help.

**Comment by redapple** [comment]
@kallesoderlund , glad you worked it out!
