### ISSUE TITLE
ImportError: No module named '${project_name}'

### ISSUE THREAD

**Issue by djkuddel** [scrapy/scrapy#1863]
Hello,

I try the tutorial and I got the following error. Can anyone help?

Best Regards,
Andy

Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 9, in <module>
    load_entry_point('Scrapy==1.0.5', 'console_scripts', 'scrapy')()
  File "/usr/local/lib/python3.4/dist-packages/scrapy/cmdline.py", line 109, in execute
    settings = get_project_settings()
  File "/usr/local/lib/python3.4/dist-packages/scrapy/utils/project.py", line 60, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/usr/local/lib/python3.4/dist-packages/scrapy/settings/__init__.py", line 108, in setmodule
    module = import_module(module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named '${project_name}'

**Comment by redapple** [comment]
what step of the tutorial as you getting this error?

**Comment by djkuddel** [comment]
when I try this

 scrapy crawl dmoz

**Comment by redapple** [comment]
Note that Scrapy 1.0.5 does not work with Python3.
Please use either Python 2.7, or install scrapy 1.1 RC3 (`pip install scrapy==1.1.0rc3`)

With Python3.4 and scrapy 1.0.5 (which is not expected to work) I can't even pass the startproject step:

```
$ scrapy startproject tutorial
Traceback (most recent call last):
  File "/home/paul/.virtualenvs/scrapy105.py34/bin/scrapy", line 9, in <module>
    load_entry_point('Scrapy==1.0.5', 'console_scripts', 'scrapy')()
  File "/home/paul/.virtualenvs/scrapy105.py34/lib/python3.4/site-packages/scrapy/cmdline.py", line 122, in execute
    cmds = _get_commands_dict(settings, inproject)
  File "/home/paul/.virtualenvs/scrapy105.py34/lib/python3.4/site-packages/scrapy/cmdline.py", line 46, in _get_commands_dict
    cmds = _get_commands_from_module('scrapy.commands', inproject)
  File "/home/paul/.virtualenvs/scrapy105.py34/lib/python3.4/site-packages/scrapy/cmdline.py", line 29, in _get_commands_from_module
    for cmd in _iter_command_classes(module):
  File "/home/paul/.virtualenvs/scrapy105.py34/lib/python3.4/site-packages/scrapy/cmdline.py", line 21, in _iter_command_classes
    for obj in vars(module).itervalues():
AttributeError: 'dict' object has no attribute 'itervalues'
```

**Comment by djkuddel** [comment]
I install it now and i got this error now

Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python3.4/dist-packages/scrapy/cmdline.py", line 108, in execute
    settings = get_project_settings()
  File "/usr/local/lib/python3.4/dist-packages/scrapy/utils/project.py", line 60, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/usr/local/lib/python3.4/dist-packages/scrapy/settings/__init__.py", line 282, in setmodule
    module = import_module(module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named '${project_name}'

**Comment by djkuddel** [comment]
I got it. I must create the project new first.

**Comment by Digenis** [comment]
When trying project commands outside of a project
the output is not what you pasted.
