### ISSUE TITLE
Error on scrapy startproject tutorial

### ISSUE THREAD

**Issue by maelfosso** [scrapy/scrapy#1865]
Hi

I'm on Ubuntu 14.04 and it's my first time to use Scrapy. 
I have this error when I try to create a Scrapy project

```
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: service-identity
```

How to solve it please

**Comment by redapple** [comment]
@maelfosso , a few questions for us to help you best
- how did you install scrapy?
- what version of scrapy did you install?
- did it come with your Ubuntu?

**Comment by shafayeatsumit** [comment]
you do not have service identity installed try this.

`sudo pip install service-identity`

**Comment by redapple** [comment]
@maelfosso , I'm closing this as https://github.com/scrapy/scrapy/issues/1865#issuecomment-198526947 should fix it.
