### ISSUE TITLE
ImageException "uncaught"

### ISSUE THREAD

**Issue by djunzu** [scrapy/scrapy#1884]
My log have some exceptions like this one:

    2016-03-25 20:33:35 [XYZ_SpiderName] WARNING: File (error): Error processing file from <GET http://url_path/xyz_img.jpg> referred in <None>: Image too small (279x560 < 300x300)
    Traceback (most recent call last):
      File "/home/me/.local/lib64/python2.7/site-packages/Scrapy-1.0.5-py2.7.egg/scrapy/pipelines/files.py", line 268, in media_downloaded
        checksum = self.file_downloaded(response, request, info)
      File "/home/me/.local/lib64/python2.7/site-packages/Scrapy-1.0.5-py2.7.egg/scrapy/pipelines/images.py", line 60, in file_downloaded
        return self.image_downloaded(response, request, info)
      File "/home/me/.local/lib64/python2.7/site-packages/Scrapy-1.0.5-py2.7.egg/scrapy/pipelines/images.py", line 64, in image_downloaded
        for path, image, buf in self.get_images(response, request, info):
      File "/home/me/.local/lib64/python2.7/site-packages/Scrapy-1.0.5-py2.7.egg/scrapy/pipelines/images.py", line 82, in get_images
        (width, height, self.MIN_WIDTH, self.MIN_HEIGHT))
    ImageException: Image too small (279x560 < 300x300)

1. The exception is [raised](https://github.com/scrapy/scrapy/blob/master/scrapy/pipelines/images.py#L82) because the downloaded image is too small. OK!
2. The exception is [caught](https://github.com/scrapy/scrapy/blob/master/scrapy/pipelines/files.py#L337) and the event is logged. OK!
3. The exception is then reraised. -> Is this right?

I do not expect to see this kind of exception when running a spider. I think the expected behavior is to have the event logged, but not propagated as a uncaught exception.

**Comment by djunzu** [comment]
Note: the only exception that is propagated and shows up in my log is the "Image too small". Others events are just logged and the exception is not propagated (as expected!):

    2016-03-25 20:33:40 [XYZ_SpiderName] WARNING: File (empty-content): Empty file from <GET http://www.xzy_domain/imagens/07112014044422/07112014044422_1.jpg> referred in <None>: no-content
    2016-03-25 20:33:40 [ABC_SpiderName] DEBUG: Crawled (200) <GET http://www.abc_domain.com/abc> (referer: http://www.abc_domain.com/type.php?id=1)

**Comment by djunzu** [comment]
Further investigation shows that traceback shows up due to `exc_info=True`. So, it is correctly caught.

If the traceback should be in the log is another issue....
