### ISSUE TITLE
scrapper is getting erros

### ISSUE THREAD

**Issue by flik** [scrapy/scrapy#1935]
```
 scrapy runspider a.py -o top-stackoverflow-questions.json

Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 7, in <module>
    from scrapy.cmdline import execute
  File "/usr/local/lib/python2.7/dist-packages/scrapy/__init__.py", line 48, in <module>
    from scrapy.spiders import Spider
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spiders/__init__.py", line 10, in <module>
    from scrapy.http import Request
  File "/usr/local/lib/python2.7/dist-packages/scrapy/http/__init__.py", line 8, in <module>
    from scrapy.http.headers import Headers
  File "/usr/local/lib/python2.7/dist-packages/scrapy/http/headers.py", line 2, in <module>
    from w3lib.http import headers_dict_to_raw
ImportError: No module named w3lib.http
```

**Comment by redapple** [comment]
@flik , how did you install scrapy?
can you check if you have w3lib installed properly? (or try doing `[sudo] pip install --upgrade w3lib`)

**Comment by korsunowk** [comment]
use  easy_install w3lib worked for me

**Comment by redapple** [comment]
@flik , I'm cleaning up past issues.
Have you managed to solved this?
Are you ok with me closing this issue?

**Comment by cucombrehombre** [comment]
I get this issue too after I install scrapy (with errors) and attempt to start a project with 'scrapy startproject' . I tried easy install and upgrade w3lib
 the error is below:
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
