### ISSUE TITLE
Incorrect traceback in downloader middleware with @inlineCallbacks

### ISSUE THREAD

**Issue by lopuhin** [scrapy/scrapy#1948]
Here is a silly example (put it into `bad_traceback.py` and run with `python3.4 bad_traceback.py`):

``` python
import scrapy
from twisted.internet.defer import inlineCallbacks
from scrapy.crawler import CrawlerProcess

class BuggyMiddleware(object):
    @inlineCallbacks
    def process_request(self, request, spider):
        undefined  # this is the bug for which I expect to see the traceback
        yield scrapy.Request('http://yandex.ru')

class Spider(scrapy.Spider):
    name = 'spider'
    start_urls = ['http://google.com']
    def parse(self, response):
        print(response)

process = CrawlerProcess({
    'DOWNLOADER_MIDDLEWARES': {'bad_traceback.BuggyMiddleware': 584}
    })
process.crawl(Spider)
process.start()
```

The output is duplicate for some reason (it's not the case when running it in a normal scrapy project), the traceback I get is:

```
2016-04-21 16:02:05 [scrapy] ERROR: Error downloading <GET http://google.com>
Traceback (most recent call last):
  File "/Users/kostia/shub/memex/undercrawler/venv/lib/python3.4/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/Users/kostia/shub/memex/undercrawler/venv/lib/python3.4/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/Users/kostia/shub/memex/undercrawler/venv/lib/python3.4/site-packages/scrapy/core/downloader/middleware.py", line 37, in process_request
    response = yield method(request=request, spider=spider)
NameError: name 'undefined' is not defined
```

Here I expected to see `BuggyMiddleware.process_request`. I used CPython 3.4.1 with a recent scrapy (288f8c09f8bac4c92f49332c8a5f5a21a182cc15), using Twisted 15.5.0 and 16.1.1 (output is the same in both cases).

**Comment by Gallaecio** [comment]
I wonder if this still applies, and if so, if it can be avoided by using [coroutine syntax](https://docs.scrapy.org/en/latest/topics/coroutines.html).

**Comment by wRAR** [comment]
It doesn't happen anymore, probably as a side effect of something, but still.

```
2025-01-08 14:21:38 [scrapy.core.scraper] ERROR: Error downloading <GET http://google.com>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 2013, in _inlineCallbacks
    result = context.run(
             ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 467, in throwExceptionIntoGenerator
    return g.throw(self.value.with_traceback(self.tb))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/scrapy/core/downloader/middleware.py", line 56, in process_request
    response = yield deferred_from_coro(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 2017, in _inlineCallbacks
    result = context.run(gen.send, result)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wrar/tmp/1/sp.py", line 8, in process_request
    undefined  # this is the bug for which I expect to see the traceback
    ^^^^^^^^^
NameError: name 'undefined' is not defined
```

OTOH `inlineCallbacks` are known to sometimes break the traceback for some reason and I doubt we can do much about that in general, and yeah I think `async def` functions should behave better in this regard.
