### ISSUE TITLE
ImportError: cannot import name walk_modules

### ISSUE THREAD

**Issue by fanpei91** [scrapy/scrapy#1955]
When I execute `scrapy` command, here is the error message:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/scrapy", line 7, in <module>
    from scrapy.cmdline import execute
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapy/__init__.py", line 48, in <module>
    from scrapy.spiders import Spider
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapy/spiders/__init__.py", line 115, in <module>
    from scrapy.spiders.crawl import CrawlSpider, Rule
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapy/spiders/crawl.py", line 11, in <module>
    from scrapy.utils.spider import iterate_spider_output
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapy/utils/spider.py", line 7, in <module>
    from scrapy.utils.misc import  arg_to_iter
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapy/utils/misc.py", line 4, in <module>
    from importlib import import_module
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 5, in <module>
    import scrapy.spiderloader
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapy/spiderloader.py", line 7, in <module>
    from scrapy.utils.misc import walk_modules
ImportError: cannot import name walk_modules
```

**Comment by redapple** [comment]
how did you install scrapy? what OS are you running on?

**Comment by Fuck-You-GFW** [comment]
Installation way: `pip2 install scrapy`
OS: Mac OS X EI Capitan Version 10.11.13

**Comment by redapple** [comment]
are you able to test in a virtualenv?

**Comment by korsunowk** [comment]
Try to update or uninstall and install scrapy

**Comment by redapple** [comment]
@Fuck-You-GFW , have you solved this issue?

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.
