### ISSUE TITLE
ImportError: No module named spiders

### ISSUE THREAD

**Issue by Zjw-ML** [scrapy/scrapy#1959]
I'm sure my script is ok because it can run on my old computer ，but on my new computer it get this error

```
E:\python\python27\python.exe E:/pycharm/PycharmProjects/spider/test/novelspider/main.py
Traceback (most recent call last):
  File "E:/pycharm/PycharmProjects/spider/test/novelspider/main.py", line 3, in <module>
    cmdline.execute("scrapy crawl novspider".split())
  File "E:\python\python27\lib\site-packages\scrapy\cmdline.py", line 142, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "E:\python\python27\lib\site-packages\scrapy\crawler.py", line 209, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "E:\python\python27\lib\site-packages\scrapy\crawler.py", line 115, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "E:\python\python27\lib\site-packages\scrapy\crawler.py", line 296, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "E:\python\python27\lib\site-packages\scrapy\spiderloader.py", line 30, in from_settings
    return cls(settings)
  File "E:\python\python27\lib\site-packages\scrapy\spiderloader.py", line 21, in __init__
    for module in walk_modules(name):
  File "E:\python\python27\lib\site-packages\scrapy\utils\misc.py", line 63, in walk_modules
    mod = import_module(path)
  File "E:\python\python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named spiders
```

I do not know where the problem is , please help me !

**Comment by redapple** [comment]
@Zjw-ML ,
what version of scrapy are you using?
is it different from the version on your old compter? (use `scrapy version -v` to check)

**Comment by mmccullar** [comment]
@Zjw-ML ,

Have you solved the issue?

If it worked on your old computer but not your new one, is it possible you haven't installed the necessary libraries?

- Matt

**Comment by korsunowk** [comment]
try rename package with scrapy project and try again. I have the same error with import my_scrapy_project.items. I rename project to other name and all worked. I hope its help for you.

**Comment by redapple** [comment]
@Zjw-ML , are you still having this issue?
If not, can I close this one?
