### ISSUE TITLE
Scrapy websockets downloader

### ISSUE THREAD

**Issue by pawelmhm** [scrapy/scrapy#2007]
Seems like now there is no way to crawl website using websockets with Scrapy. Can we support something like this? There are websocket implementations based on Twisted: http://autobahn.ws/python/ so probably it could be possible to add some downloader for websockets? I know that HTTP is main protocol most spiders use, but we do support FTP so we could just as well support websockets.

**Comment by yssoe** [comment]
Hi, I have it working successfully by using the following: 

from websocket import create_connection

then create a connection using: 

ws = create connection('wss://ws.site.com')

ws.send(all things that needs to be send, logins, subscriptions etc)

you can grab the data with

ws.recv() and put them into your item fields. 

Hope that helped you a bit, you basically use the Python Websocket, write python code to login/subscribe to the websocket and then grab the data and populate your fields. 

Cheers

**Comment by pawelmhm** [comment]
thanks @yssoe this sounds like good workaround and probably the only way to do things now, but I thought more about handling websockets protocol inside Scrapy itself. 

This way websockets code will be async and properly integrated with all other components. In your approach we'll be mixing blocking code from other networking library with Scrapy. It would be better to simply add support for websockets to Scrapy, so that for example users could do following thing:

```python

class TestProductsSpider(Spider):
    name = "test_sockets_spider"

    def start_requests(self):
        body = json.dumps({"msg": "hello world from Scrapy"})
        yield Message("ws://localhost:9000/", body=body, callback=self.callback)

   def callback(self, websocket_response):
        # websocket connection here and you can do e.g.
        message = yield websocket_response.sendMessage("hello again")
```

I tried writing some test implementation, but I stumbled on following problems.

1) Downloader middleware is designed to deal with HTTP requests. Nothing that matters in middleware matters for websocket messages (headers, status codes, cookies etc this is all irrelevant for message sent via websockets). So websocket messages need some way to bypass downloader middleware

More important problem is dealing with server push. 

2) Many core components (engine, scraper etc) assume that download_request will return Twisted Deferrred. But handler.download_request() for websockets cannot return deferred for every message sent. This is because websockets allow for server push. So if user sends message he can get multiple responses for it. This means that Deferred would fire multiple times. Firing deferred multiple times raises Twisted exceptions. 

I could go forward and try to design some solution for this (if possible). I wonder though if we agree this is actually needed in Scrapy? What do you think @kmike @redapple @eliasdorneles ? Do you think it's good to have websockets support?

**Comment by redapple** [comment]
@pawelmhm , thanks for opening the discussion.
I'm really not familiar with websockets so what I say below is surely missing a lot of important stuff.
I believe the notion of callbacks and errbacks does fit websockets well, including server push. whether it'd still be `Response` or something else that are passes to spider methods needs careful design obviously.
WebSockets being low-level, I'm not sure there's a need for a downloader middleware pass, so bypassing them altogether seems reasonable.

As for the need, I do think scrapy will have to support HTTP/2 at some point, and HTTP/2 has server push option too, so it makes total sense to work on a design (API and/or Twisted-compatible implementation) that accomodates both HTTP/2 and web sockets.

**Comment by yssoe** [comment]
@pawelmhm @redapple Thank you for your work. Successfully subscribing to a websocket server and getting data pushed from it is a much better way to scrape data than getting the whole page every time, for us, scrapers, and for the site owners because of the selective variable data that's been send via the websocket without the whole html/static shebang. What really would be cool, and what the whole goal is about websockets, is to keep the connection alive (sendalives are used in websockets and needed since most proxy servers disconnect after 65 seconds idle (default with nginx)) with the websocket server so updated data gets pushed and eventually populated into the item fields of scrapy, every time there's an updated data field, the websocket server will push the update to your subscription. Think about how cool this would be :-)

**Comment by PSJMcNeill** [comment]
Was there any progress on this? Would be a very useful feature

**Comment by Cally99** [comment]
Bumping this. To be honest in the web world important data with value doesn't want to be scraped. Precious data will be delivered over web sockets. I've spent three days gathering xpaths for a site I'm scraping for a client and the last and least element which is the most precious is delivered over websocket.  All the brute work is done and now I'm stuck on the most important element on the page to capture and I don't know how do get it. I even re wrote the code from requests-html to scrapy/splash and lua. Still can't get the most important element.  The web scraping community needs to get their shit together because the webs moving in one direction and the scraping community is still fucking around with plain html

**Comment by elacuesta** [comment]
As mentioned by @pawelmhm above, supporting websockets "natively" within Scrapy is not trivial. However, since Scrapy 2.0, it is possible to use the following workaround, which is not blocking:

```python
import logging

import websockets
from scrapy import Spider


logging.getLogger("websockets").setLevel(logging.INFO)


class WebsocketsSpider(Spider):
    name = "websockets"
    start_urls = ["data:,"]  # avoid making an actual upstream request

    async def parse(self, response):
        async with websockets.connect("wss://echo.websocket.org") as ws:
            await ws.send("Hello!")
            received = await ws.recv()
        yield {"received": received}
```
```
2020-05-13 15:24:16 [scrapy.core.engine] INFO: Spider opened
2020-05-13 15:24:16 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2020-05-13 15:24:16 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-05-13 15:24:16 [scrapy.core.engine] DEBUG: Crawled (200) <GET data:,> (referer: None)
2020-05-13 15:24:17 [scrapy.core.scraper] DEBUG: Scraped from <200 data:,>
{'received': 'Hello!'}
2020-05-13 15:24:17 [scrapy.core.engine] INFO: Closing spider (finished)
```

Keep in mind that this needs [the `asyncio` reactor](https://docs.scrapy.org/en/latest/topics/asyncio.html#installing-the-asyncio-reactor) in order to work. You could add `TWISTED_REACTOR = "twisted.internet.asyncioreactor.AsyncioSelectorReactor"` to the project's settings file or run the spider with `-s TWISTED_REACTOR=twisted.internet.asyncioreactor.AsyncioSelectorReactor`

PS: The [`websockets`](https://websockets.readthedocs.io) package works in Python >= 3.6

**Comment by alfredsasko** [comment]
Hi @elacuesta I tried your code using scrapy 2.3.0 and got NotImplemented error when I modified the settings using:
`TWISTED_REACTOR = "twisted.internet.asyncioreactor.AsyncioSelectorReactor"`
 
This is my spider:
`import logging

import websockets
from scrapy import Spider


logging.getLogger('websockets').setLevel(logging.INFO)


class CoinWebSocket(Spider):
    name = 'coin_websocket'
    start_urls = ['data:,']
    socket_urls = ['wss://www.livecoin.net/socket/socket.io/?EIO=3&transport=websocket']

    async def parse(self, response):
        async with websockets.connect(self.socket_urls[0]) as ws:
            await ws.send(["subscribe",{"channel":"dailyPrices"}])
            recieved = await ws.recv()
        yield {'recieved': recieved}
`

And this is the error:
`$ scrapy crawl coin_websocket
Traceback (most recent call last):
  File "C:\Users\Fredo\.conda\envs\SGS\Scripts\scrapy-script.py", line 10, in <module>
    sys.exit(execute())
  File "C:\Users\Fredo\.conda\envs\SGS\lib\site-packages\scrapy\cmdline.py", line 144, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "C:\Users\Fredo\.conda\envs\SGS\lib\site-packages\scrapy\crawler.py", line 280, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "C:\Users\Fredo\.conda\envs\SGS\lib\site-packages\scrapy\crawler.py", line 156, in __init__
    self._handle_twisted_reactor()
  File "C:\Users\Fredo\.conda\envs\SGS\lib\site-packages\scrapy\crawler.py", line 343, in _handle_twisted_reactor
    install_reactor(self.settings["TWISTED_REACTOR"])
  File "C:\Users\Fredo\.conda\envs\SGS\lib\site-packages\scrapy\utils\reactor.py", line 59, in install_reactor
    asyncioreactor.install(asyncio.get_event_loop())
  File "C:\Users\Fredo\.conda\envs\SGS\lib\site-packages\twisted\internet\asyncioreactor.py", line 320, in install
    reactor = AsyncioSelectorReactor(eventloop)
  File "C:\Users\Fredo\.conda\envs\SGS\lib\site-packages\twisted\internet\asyncioreactor.py", line 69, in __init__
    super().__init__()
  File "C:\Users\Fredo\.conda\envs\SGS\lib\site-packages\twisted\internet\base.py", line 571, in __init__
    self.installWaker()
  File "C:\Users\Fredo\.conda\envs\SGS\lib\site-packages\twisted\internet\posixbase.py", line 286, in installWaker
    self.addReader(self.waker)
  File "C:\Users\Fredo\.conda\envs\SGS\lib\site-packages\twisted\internet\asyncioreactor.py", line 151, in addReader
    self._asyncioEventloop.add_reader(fd, callWithLogger, reader,
  File "C:\Users\Fredo\.conda\envs\SGS\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
`

**Comment by Gallaecio** [comment]
@alfredsasko Is this [using Python 3.8 and Windows](https://bugs.python.org/issue37373)?
