### ISSUE TITLE
The setting ITEM_PIPELINE can't be overridden from terminal

### ISSUE THREAD

**Issue by liusangel** [scrapy/scrapy#2018]
In my settings.py I have:

```
ITEM_PIPELINES = {
    'turing.pipelines.InitFieldsNotInitializedPipeline': 299,
    'turing.pipelines.SetNoneIfFieldEmptyPipeline': 300,
    'turing.pipelines.CheckCategoryPipeline': 301,
    'turing.pipelines.CheckContactPipeline': 302,
}
```

And it works great. But sometime I want run the spider without ANY pipelines.
When I run

```
scrapy crawl -s FEED_URI=stdout: -s FEED_FORMAT=json -s ITEM_PIPELINES=[] -a test_extract_url=http://example.com/ example_spider
```

I get this error:
    return d.iteritems(**kw)
exceptions.AttributeError: 'str' object has no attribute 'iteritems'

How can I run the spider without the pipelines?

So far I tried:
- scrapy crawl -s FEED_URI=stdout: -s FEED_FORMAT=json -s ITEM_PIPELINES=[] -a test_extract_url=http://example.com/ example_spider
- scrapy crawl -s FEED_URI=stdout: -s FEED_FORMAT=json -s ITEM_PIPELINES={} -a test_extract_url=http://example.com/ example_spider
- scrapy crawl -s FEED_URI=stdout: -s FEED_FORMAT=json -s "ITEM_PIPELINES=[]" -a test_extract_url=http://example.com/ example_spider
- scrapy crawl -s FEED_URI=stdout: -s FEED_FORMAT=json -s "ITEM_PIPELINES={}" -a test_extract_url=http://example.com/ example_spider
- scrapy crawl -s FEED_URI=stdout: -s FEED_FORMAT=json -s ITEM_PIPELINES=['turing.pipelines.InitFieldsNotInitializedPipeline': 299,] -a test_extract_url=http://example.com/ example_spider
- scrapy crawl -s FEED_URI=stdout: -s FEED_FORMAT=json -s ITEM_PIPELINES={'turing.pipelines.InitFieldsNotInitializedPipeline': 299,} -a test_extract_url=http://example.com/ example_spider
- Others combinations
- Look in the docs http://doc.scrapy.org/en/latest/topics/settings.html

Hopefully you can help me. Thanks.

**Comment by kmike** [comment]
Hey @liusangel,

I'm not sure how to disable the pipeline directly from command line. There is a couple of unfinished tickets / pull requests to make it easier: https://github.com/scrapy/scrapy/pull/1048, https://github.com/scrapy/scrapy/pull/1591. Help with #1048 is welcome :)

Currently the common practice is to have an option which disables an extension/middleware/pipeline. See e.g. an implementation of AUTOTHROTTLE_ENABLED: https://github.com/scrapy/scrapy/blob/d3ced85ec350e8c195760a8ce975a18ca42f29a0/scrapy/extensions/throttle.py#L14

**Comment by kmike** [comment]
Hm, maybe it is supported after all - could you please try your examples with single quotes instead of double quotes? I.e. `-s 'ITEM_PIPELINES={}'`

**Comment by liusangel** [comment]
I tried but the problem persists. Same problem:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapy/cmdline.py", line 150, in _run_command
    cmd.run(args, opts)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapy/commands/crawl.py", line 57, in run
    self.crawler_process.crawl(spname, **opts.spargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapy/crawler.py", line 153, in crawl
    d = crawler.crawl(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapy/crawler.py", line 71, in crawl
    self.engine = self._create_engine()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapy/crawler.py", line 83, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapy/core/engine.py", line 69, in __init__
    self.scraper = Scraper(crawler)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapy/core/scraper.py", line 70, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapy/middleware.py", line 56, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapy/middleware.py", line 28, in from_settings
    mwlist = cls._get_mwlist_from_settings(settings)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapy/pipelines/__init__.py", line 24, in _get_mwlist_from_settings
    return build_component_list(settings['ITEM_PIPELINES_BASE'], item_pipelines)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapy/utils/conf.py", line 31, in build_component_list
    compdict.update(_map_keys(custom))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scrapy/utils/conf.py", line 28, in _map_keys
    return {convert(k): v for k, v in six.iteritems(compdict)}
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/six.py", line 599, in iteritems
    return d.iteritems(**kw)
exceptions.AttributeError: 'str' object has no attribute 'iteritems'
2016-05-27 18:31:27 [twisted] CRITICAL: 
```

When I run: 
```
scrapy crawl -s FEED_URI=stdout: -s FEED_FORMAT=json -s 'ITEM_PIPELINES={}' -a test_extract_url=http://example.com/ -L ERROR c_example
```

And after see the page I don't understand where can I disable the pipelines.
Any other ideas?? Thanks.

**Comment by pawelmhm** [comment]
hey @liusangel can you check if this branch works ok for you? https://github.com/scrapy/scrapy/pull/1989

**Comment by undernewmanagement** [comment]
I was able to get it to work by escaping the `{}` like so: `\{\}'

`scrapy crawl -s FEED_URI=stdout: -s FEED_FORMAT=json -s ITEM_PIPELINES=\{\} -a test_extract_url=http://example.com/ -L ERROR c_example`

**Comment by Digenis** [comment]
When was this introduced?
I don't see it in the changelog.

**Comment by redapple** [comment]
`.getdict()` for JSON string settings is quite old (https://github.com/scrapy/scrapy/pull/269, v0.18)
but the use of [it was not in v1.0](https://github.com/scrapy/scrapy/blob/1.0/scrapy/pipelines/__init__.py#L16) for `ITEM_PIPELINES` for example: 
> item_pipelines = settings['ITEM_PIPELINES']

Then v1.1 changed how settings are read quite a bit (see https://github.com/scrapy/scrapy/pull/1586)

**Comment by Gallaecio** [comment]
Closing as per https://github.com/scrapy/scrapy/issues/2018#issuecomment-228464421
