### ISSUE TITLE
pip to install scrapy

### ISSUE THREAD

**Issue by chengxxxxwang** [scrapy/scrapy#2019]
I am new to using command line and apologize in advance for any confusion. I am trying to install scrapy but I get an Errno 13 Permission denied as response.

Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.0-py2.7.egg/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.0-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.0-py2.7.egg/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-8.1.0-py2.7.egg/pip/req/req_install.py", line 835, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-8.1.0-py2.7.egg/pip/req/req_install.py", line 1030, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-8.1.0-py2.7.egg/pip/wheel.py", line 344, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-8.1.0-py2.7.egg/pip/wheel.py", line 315, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-8.1.0-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/pyasn1'

**Comment by chengxxxxwang** [comment]
Should I need to *sudo* this? how?

**Comment by chengxxxxwang** [comment]
I use ``sudo chown -R $USER /Library/Python/2.7`` to install  scrapy  and  there is anther error

OSError: [Errno 1] Operation not permitted: '/var/folders/gw/231t4vw562sgqxjn0t715cjm0000gn/T/pip-y3cvT4-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

**Comment by chengxxxxwang** [comment]
I have fixed this problem . The reason is that I use OS EI Capitan system on my Mac.So I have to install
python/six-1.4.1 to do this I use ``sudo -H pip install --ignore-installed six`` and it worked
