### ISSUE TITLE
Some of the errors occurred in the Chinese web crawling

### ISSUE THREAD

**Issue by buzai** [scrapy/scrapy#2055]
The html source is :

```
<dd>
<a href="5367496.html" =style="" style="">书友群</a>
</dd>
<dd>
<a href="5367497.html" =style="" style="">十月份打赏清单。</a>
</dd>
<dt>《修真聊天群》九洲一号群</dt>
<dd>
<a class="firefinder-match" href="5367498.html" =style="" style="">第一章 黄山真君和九洲一号群</a>
</dd>
<dd>
<a class="firefinder-match" href="5367499.html" =style="" style="">第二章 且待本尊算上一卦</a>
</dd>
```

my spider is :

```
    def parse(self, response):
    	# a = '第'.encode('Unicode')\"h1title\"
    	arr = response.xpath("//dd//a[contains(.,\"第\")]").extract()
    	print arr[0]
```

I just want the a tag with the word "第" in the beginning.
but it not work , but in the fixfox firexpath i can find right.

some error is :

```
2016-06-14 20:14:11 [scrapy] ERROR: Spider error processing <GET http://www.23us.cc/html/101/101573/> (referer: None)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.2.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/chenhao/Desktop/ssss/sinaweibo/sinaweibo/spiders/xiao.py", line 18, in parse
    arr = response.xpath("//dd//a[contains(.,\"第\")]").extract()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/http/response/text.py", line 115, in xpath
    return self.selector.xpath(query)
  File "/usr/local/lib/python2.7/dist-packages/parsel/selector.py", line 179, in xpath
    smart_strings=self._lxml_smart_strings)
  File "lxml.etree.pyx", line 1507, in lxml.etree._Element.xpath (src/lxml/lxml.etree.c:52198)
  File "xpath.pxi", line 295, in lxml.etree.XPathElementEvaluator.__call__ (src/lxml/lxml.etree.c:151999)
  File "apihelpers.pxi", line 1393, in lxml.etree._utf8 (src/lxml/lxml.etree.c:27125)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```

**Comment by redapple** [comment]
Can you try with a `u` prefix on the XPath selector? i.e.
```
response.xpath(u"//dd//a[contains(.,\"第\")]").extract()
```

**Comment by redapple** [comment]
```
>>> import scrapy
>>> selector = scrapy.Selector(text=u"""<dd>
... <a href="5367496.html" =style="" style="">书友群</a>
... </dd>
... <dd>
... <a href="5367497.html" =style="" style="">十月份打赏清单。</a>
... </dd>
... <dt>《修真聊天群》九洲一号群</dt>
... <dd>
... <a class="firefinder-match" href="5367498.html" =style="" style="">第一章 黄山真君和九洲一号群</a>
... </dd>
... <dd>
... <a class="firefinder-match" href="5367499.html" =style="" style="">第二章 且待本尊算上一卦</a>
... </dd>""", type="html")
>>> selector.xpath("//dd//a[contains(.,\"第\")]").extract()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/paul/.virtualenvs/scrapy11.py2/local/lib/python2.7/site-packages/parsel/selector.py", line 179, in xpath
    smart_strings=self._lxml_smart_strings)
  File "src/lxml/lxml.etree.pyx", line 1587, in lxml.etree._Element.xpath (src/lxml/lxml.etree.c:57884)
  File "src/lxml/xpath.pxi", line 295, in lxml.etree.XPathElementEvaluator.__call__ (src/lxml/lxml.etree.c:166780)
  File "src/lxml/apihelpers.pxi", line 1439, in lxml.etree._utf8 (src/lxml/lxml.etree.c:30219)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
>>> selector.xpath(u"//dd//a[contains(.,\"第\")]").extract()
[u'<a class="firefinder-match" href="5367498.html" style="">\u7b2c\u4e00\u7ae0 \u9ec4\u5c71\u771f\u541b\u548c\u4e5d\u6d32\u4e00\u53f7\u7fa4</a>', u'<a class="firefinder-match" href="5367499.html" style="">\u7b2c\u4e8c\u7ae0 \u4e14\u5f85\u672c\u5c0a\u7b97\u4e0a\u4e00\u5366</a>']
>>> selector.xpath(u'//dd//a[contains(.,"\u7b2c")]').extract()
[u'<a class="firefinder-match" href="5367498.html" style="">\u7b2c\u4e00\u7ae0 \u9ec4\u5c71\u771f\u541b\u548c\u4e5d\u6d32\u4e00\u53f7\u7fa4</a>', u'<a class="firefinder-match" href="5367499.html" style="">\u7b2c\u4e8c\u7ae0 \u4e14\u5f85\u672c\u5c0a\u7b97\u4e0a\u4e00\u5366</a>']
>>> 
```

**Comment by buzai** [comment]
Oh, my God, it's been a long time for me to find the mistake. Thank you so much.
