### ISSUE TITLE
Unhandled error caused by HTTP non-compliant headers

### ISSUE THREAD

**Issue by yeechen** [scrapy/scrapy#210]
Environment:

Scrapy 0.16.2
Twisted-12.2.0
python 2.7
macosx-10.6

Use Case 1

Run: 

scrapy shell http://aaa.17domn.com/bt9/file.php/MERH77V.html

Error:

[ScrapyHTTPPageGetter,client] Unhandled Error
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Twisted-12.2.0-py2.7-macosx-10.6-intel.egg/twisted/internet/selectreactor.py", line 150, in _doReadOrWrite
        why = getattr(selectable, method)()

```
 ...
```

 File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Twisted-12.2.0-py2.7-macosx-10.6-intel.egg/twisted/web/http.py", line 406, in extractHeader
        key, val = header.split(':',1)
    exceptions.ValueError: need more than 1 value to unpack

Solution:
https://groups.google.com/forum/#!msg/scrapy-users/xFKo8ggzPxs/VXDl3CZ4V4cJ They describe this is caused by twisted. Then I patched function extractHeader in /twisted/web/http.py from http://twistedmatrix.com/trac/ticket/2842. It works

Use Case 2:

Run: 

scrapy shell http://www1.wkdown.info/fs3/file.php/M994ATR.html

Error:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/scrapy", line 5, in <module>
...

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Scrapy-0.16.2-py2.7.egg/scrapy/core/downloader/webclient.py", line 122, in _build_response
    status = int(self.status)

ValueError: invalid literal for int() with base 10: 'html'

unfix!

**Comment by Gallaecio** [comment]
They probably fixed the issue upstream, but the issue still exists on our end.

To be clear, this is a case where the server is in the wrong, but if web browsers support bad server responses like these, ideally Scrapy should too at some point.

To reproduce the issue, run the following Python script, which starts a dumb HTTP server on http://0.0.0.0:8000/ that sends a response with the root issue here (a header line without a colon), and on a separate terminal, in parallel, run `scrapy shell http://0.0.0.0:8000`.

```python
import socket

SERVER_HOST = '0.0.0.0'
SERVER_PORT = 8000

server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
server_socket.bind((SERVER_HOST, SERVER_PORT))
server_socket.listen(1)

while True:
    client_connection, client_address = server_socket.accept()

    request = client_connection.recv(1024).decode()
    print(request)

    response = 'HTTP/1.0 200 OK\nBad header\n\nHello World'
    client_connection.sendall(response.encode())
    client_connection.close()

server_socket.close()
```

(based on https://www.codementor.io/@joaojonesventura/building-a-basic-http-server-from-scratch-in-python-1cedkg0842)

**Comment by vasiliyk** [comment]
We can catch and process that ResponseFailed with "ValueError: not enough values to unpack (expected 2, got 1)" in:
1. download handlers download_request() of http11 handler (current default handler)
2. downloader middlewares using process_exception()

I think it should be a downloader middleware framework:
* we keep following Twisted without modifications 
* non common flow, an option for users to decide if they want to use servers with non-compliant headers anyway

**Comment by vasiliyk** [comment]
Based on the suggestion from @wRAR, the approach has been changed to -
creation of an additional HTTP download handler.
I will create a hybrid downloader which will rely on http11 handler for common flow and will process only requests with non-compliant responses from servers using raw sockets (to avoid usage of additional libraries).

**Comment by wRAR** [comment]
> I will create a hybrid downloader which will rely on http11 handler for common flow and will process only requests with non-compliant responses from servers using raw sockets (to avoid usage of additional libraries).

While doing this in a download handler is better than doing it in a middleware, I should explicitly note that Scrapy is not a place for such a handler either. If you need to scrape such a website you can include it in your project.

(for the record, `aiohttp`, `httpx` and the curl command-line all fail on the example server provided above, while `requests` works)
