### ISSUE TITLE
ImportError: No module named 'sgmllib' on ubuntu and python 3.4

### ISSUE THREAD

**Issue by foebu** [scrapy/scrapy#2114]
On Ubuntu 14.04 with python 3.4 I get the following error:
`ImportError: No module named 'sgmllib'`

I installed as suggested in the [documentation](http://doc.scrapy.org/en/latest/intro/install.html):
```
sudo apt-get install python-dev python-pip libxml2-dev libxslt1-dev zlib1g-dev libffi-dev libssl-dev
pip install Scrapy
```

Any idea?

**Comment by redapple** [comment]
hi @foebu , thanks for reporting.
[`sgmllib` has been removed in Python 3](https://docs.python.org/2/library/sgmllib.html) and should not be required when running Scrapy with Python 3
Can you share the whole console logs to see where your installation breaks?

**Comment by foebu** [comment]
Hi, it's not the installation that breaks, but it breaks if I try to run the shell or if I try to start a project:
```
scrapy startproject testproj
]/home/fbe/venv/lib/python3.4/importlib/_bootstrap.py:321: ScrapyDeprecationWarning: Module `scrapy.contrib.spiders` is deprecated, use `scrapy.spiders` instead
  return f(*args, **kwds)
/home/fbe/venv/lib/python3.4/importlib/_bootstrap.py:321: ScrapyDeprecationWarning: Module `scrapy.contrib.spiders.init` is deprecated, use `scrapy.spiders.init` instead
  return f(*args, **kwds)
/home/fbe/venv/lib/python3.4/importlib/_bootstrap.py:321: ScrapyDeprecationWarning: Module `scrapy.contrib.linkextractors` is deprecated, use `scrapy.linkextractors` instead
  return f(*args, **kwds)
/home/fbe/venv/lib/python3.4/importlib/_bootstrap.py:321: ScrapyDeprecationWarning: Module `scrapy.contrib.linkextractors.sgml` is deprecated, use `scrapy.linkextractors.sgml` instead
  return f(*args, **kwds)
Traceback (most recent call last):
  File "/home/fbe/venv/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/home/fbe/venv/lib/python3.4/site-packages/scrapy/cmdline.py", line 141, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "/home/fbe/venv/lib/python3.4/site-packages/scrapy/crawler.py", line 238, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "/home/fbe/venv/lib/python3.4/site-packages/scrapy/crawler.py", line 129, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "/home/fbe/venv/lib/python3.4/site-packages/scrapy/crawler.py", line 325, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "/home/fbe/venv/lib/python3.4/site-packages/scrapy/spiderloader.py", line 33, in from_settings
    return cls(settings)
  File "/home/fbe/venv/lib/python3.4/site-packages/scrapy/spiderloader.py", line 20, in __init__
    self._load_all_spiders()
  File "/home/fbe/venv/lib/python3.4/site-packages/scrapy/spiderloader.py", line 28, in _load_all_spiders
    for module in walk_modules(name):
  File "/home/fbe/venv/lib/python3.4/site-packages/scrapy/utils/misc.py", line 71, in walk_modules
    submod = import_module(fullpath)
  File "/home/fbe/venv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/fbe/gits/jrc/jrc/spiders/JRSpider.py", line 5, in <module>
    from scrapy.contrib.linkextractors.sgml import SgmlLinkExtractor
  File "/home/fbe/venv/lib/python3.4/site-packages/scrapy/contrib/linkextractors/sgml.py", line 7, in <module>
    from scrapy.linkextractors.sgml import *
  File "/home/fbe/venv/lib/python3.4/site-packages/scrapy/linkextractors/sgml.py", line 6, in <module>
    from sgmllib import SGMLParser
ImportError: No module named 'sgmllib'
```

**Comment by redapple** [comment]
Are you sure the logs are continuous?
`scrapy startproject testproj` and `spiders/JRSpider.py` don't seem related.

`spiders/JRSpider.py` is using `scrapy.contrib.linkextractors.sgml.SgmlLinkExtractor` which doesn't work with Python 3 (it was deprecated in Scrapy 1.0 -- http://doc.scrapy.org/en/latest/news.html?highlight=sgmllinkextractor#changelog) ;
replace its use with `from scrapy.linkextractors import LinkExtractor`

**Comment by foebu** [comment]
I solved it. I was launching the command `scrapy startproject testproj` inside another project which was created with python 2. Out of that folder it started working properly.

Anyway the log was continuous, maybe due to the fact that I was in a project created with a previous version of python?

**Comment by redapple** [comment]
Alright. Interesting. I wonder if `startproject` could detect it's running inside a project and fail early with a proper message.

**Comment by Dev-Gaju** [comment]
Please install sgmllib3k, which will resolve this issue

**Comment by java-code-former** [comment]
> Please install sgmllib3k, which will resolve this issue
useful
