### ISSUE TITLE
How to handle exception like this?

### ISSUE THREAD

**Issue by gamelife1314** [scrapy/scrapy#2132]
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.5/site-packages/Twisted-16.3.0-py3.5.egg/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/python3/lib/python3.5/site-packages/Twisted-16.3.0-py3.5.egg/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/python3/lib/python3.5/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
# twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.
2016-07-19 17:01:57 [scrapy] INFO: Closing spider (finished)
2016-07-19 17:01:57 [sogou_weixin] INFO: spider 完成所有请求关闭!
2016-07-19 17:01:57 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 1,
 'downloader/exception_type_count/twisted.internet.error.ConnectionRefusedError': 1,
 'downloader/request_bytes': 450,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2016, 7, 19, 9, 1, 57, 30101),
 'log_count/ERROR': 1,
 'log_count/INFO': 9,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2016, 7, 19, 9, 1, 55, 597143)}
2016-07-19 17:01:57 [scrapy] INFO: Spider closed (finished)

**Comment by redapple** [comment]
@gamelife1314 , please provide more details on your setup, settings, pipelines, spider code, where you are calling synchronous DB operations etc.
As it is, your issue is not a reproducible example of a faulty scrapy behavior.
Troubleshooting topics are a better fit for [StackOverflow](https://stackoverflow.com/questions/tagged/scrapy) or [scrapy-users mailing list](https://groups.google.com/d/forum/scrapy-users).

**Comment by redapple** [comment]
This is a variant of the [errback example from the scrapy docs](http://doc.scrapy.org/en/latest/topics/request-response.html#using-errbacks-to-catch-exceptions-in-request-processing), with added case of connection refused:

```
import scrapy

from scrapy.spidermiddlewares.httperror import HttpError
from twisted.internet.error import DNSLookupError
from twisted.internet.error import TimeoutError, TCPTimedOutError, ConnectionRefusedError


class ErrbackSpider(scrapy.Spider):
    name = "errback_example"
    start_urls = [
        "http://www.httpbin.org/",
        "http://localhost:12345/",
    ]

    def start_requests(self):
        for u in self.start_urls:
            yield scrapy.Request(u, callback=self.parse_response,
                                    errback=self.errback_for_failure,
                                    dont_filter=True)

    def parse_response(self, response):
        self.logger.info('Got successful response from {}'.format(response.url))
        # do something useful here...

    def errback_for_failure(self, failure):
        # log all failures
        self.logger.error(repr(failure))

        # in case you want to do something special for some errors,
        # you may need the failure's type:

        if failure.check(HttpError):
            # these exceptions come from HttpError spider middleware
            # you can get the non-200 response
            response = failure.value.response
            self.logger.error('HttpError on %s', response.url)

        elif failure.check(DNSLookupError):
            # this is the original request
            request = failure.request
            self.logger.error('DNSLookupError on %s', request.url)

        elif failure.check(TimeoutError, TCPTimedOutError):
            request = failure.request
            self.logger.error('TimeoutError on %s', request.url)

        elif failure.check(ConnectionRefusedError):
            request = failure.request
            self.logger.error('ConnectionRefusedError on %s', request.url)
```

It produces this:

```
$ scrapy runspider err.py 
2016-07-19 13:00:36 [scrapy] INFO: Scrapy 1.1.0 started (bot: scrapybot)
2016-07-19 13:00:36 [scrapy] INFO: Overridden settings: {}
2016-07-19 13:00:36 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.logstats.LogStats', 'scrapy.extensions.corestats.CoreStats']
2016-07-19 13:00:36 [scrapy] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.chunked.ChunkedTransferMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2016-07-19 13:00:36 [scrapy] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2016-07-19 13:00:36 [scrapy] INFO: Enabled item pipelines:
[]
2016-07-19 13:00:36 [scrapy] INFO: Spider opened
2016-07-19 13:00:36 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2016-07-19 13:00:36 [scrapy] DEBUG: Retrying <GET http://localhost:12345/> (failed 1 times): Connection was refused by other side: 111: Connection refused.
2016-07-19 13:00:36 [scrapy] DEBUG: Retrying <GET http://localhost:12345/> (failed 2 times): Connection was refused by other side: 111: Connection refused.
2016-07-19 13:00:36 [scrapy] DEBUG: Gave up retrying <GET http://localhost:12345/> (failed 3 times): Connection was refused by other side: 111: Connection refused.
2016-07-19 13:00:36 [errback_example] ERROR: <twisted.python.failure.Failure twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.>
2016-07-19 13:00:36 [errback_example] ERROR: ConnectionRefusedError on http://localhost:12345/
2016-07-19 13:00:36 [scrapy] DEBUG: Crawled (200) <GET http://www.httpbin.org/> (referer: None)
2016-07-19 13:00:36 [errback_example] INFO: Got successful response from http://www.httpbin.org/
2016-07-19 13:00:36 [scrapy] INFO: Closing spider (finished)
2016-07-19 13:00:36 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 3,
 'downloader/exception_type_count/twisted.internet.error.ConnectionRefusedError': 3,
 'downloader/request_bytes': 834,
 'downloader/request_count': 4,
 'downloader/request_method_count/GET': 4,
 'downloader/response_bytes': 12333,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2016, 7, 19, 11, 0, 36, 709189),
 'log_count/DEBUG': 4,
 'log_count/ERROR': 2,
 'log_count/INFO': 8,
 'response_received_count': 1,
 'scheduler/dequeued': 4,
 'scheduler/dequeued/memory': 4,
 'scheduler/enqueued': 4,
 'scheduler/enqueued/memory': 4,
 'start_time': datetime.datetime(2016, 7, 19, 11, 0, 36, 289975)}
2016-07-19 13:00:36 [scrapy] INFO: Spider closed (finished)
```
