### ISSUE TITLE
Scrapy ignoring AWS S3 KEY settings

### ISSUE THREAD

**Issue by rezhajulio** [scrapy/scrapy#2133]
I am running single spider with custom setting per this [documentation](http://doc.scrapy.org/en/1.1/topics/settings.html#settings-per-spider). However it keep looking everywhere else. Here is part of the log:

```
2016-07-19 20:30:21 [scrapy] INFO: Scrapy 1.1.1 started (bot: scrapybot)
2016-07-19 20:30:21 [scrapy] INFO: Overridden settings: {}
2016-07-19 20:30:21 [botocore.credentials] DEBUG: Skipping environment variable credential check because profile name was explicitly set.
2016-07-19 20:30:21 [botocore.credentials] DEBUG: Looking for credentials via: env
2016-07-19 20:30:21 [botocore.credentials] DEBUG: Looking for credentials via: assume-role
2016-07-19 20:30:21 [botocore.credentials] DEBUG: Looking for credentials via: shared-credentials-file
2016-07-19 20:30:21 [botocore.credentials] DEBUG: Looking for credentials via: config-file
2016-07-19 20:30:21 [botocore.credentials] DEBUG: Looking for credentials via: ec2-credentials-file
2016-07-19 20:30:21 [botocore.credentials] DEBUG: Looking for credentials via: boto-config
2016-07-19 20:30:21 [botocore.credentials] DEBUG: Looking for credentials via: container-role
2016-07-19 20:30:21 [botocore.credentials] DEBUG: Looking for credentials via: iam-role
2016-07-19 20:30:21 [botocore.vendored.requests.packages.urllib3.connectionpool] INFO: Starting new HTTP connection (1): 169.254.169.254
2016-07-19 20:30:22 [botocore.utils] DEBUG: Caught exception while trying to retrieve credentials: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/iam/security-credentials/ (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7f09baf77a90>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))
Traceback (most recent call last):
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/utils.py", line 159, in _get_request
    response = requests.get(url, timeout=timeout)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/vendored/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/vendored/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py", line 419, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/iam/security-credentials/ (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7f09baf77a90>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))
2016-07-19 20:30:22 [botocore.utils] DEBUG: Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
2016-07-19 20:30:22 [botocore.loaders] DEBUG: Loading JSON file: /home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/data/endpoints.json
2016-07-19 20:30:22 [botocore.loaders] DEBUG: Loading JSON file: /home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/data/s3/2006-03-01/service-2.json
2016-07-19 20:30:22 [botocore.loaders] DEBUG: Loading JSON file: /home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/data/_retry.json
2016-07-19 20:30:22 [botocore.client] DEBUG: Registering retry handlers for service: s3
2016-07-19 20:30:22 [botocore.hooks] DEBUG: Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f09baf92320>
2016-07-19 20:30:22 [botocore.hooks] DEBUG: Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f09baf8fa28>
2016-07-19 20:30:22 [botocore.client] DEBUG: The s3 config key is not a dictionary type, ignoring its value of: None
2016-07-19 20:30:22 [botocore.endpoint] DEBUG: Setting s3 timeout as (60, 60)
2016-07-19 20:30:22 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2016-07-19 20:30:22 [py.warnings] WARNING: /home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/scrapy/utils/deprecate.py:156: ScrapyDeprecationWarning: `scrapy.contrib.downloadermiddleware.useragent.UserAgentMiddleware` class is deprecated, use `scrapy.downloadermiddlewares.useragent.UserAgentMiddleware` instead
  ScrapyDeprecationWarning)

2016-07-19 20:30:22 [py.warnings] WARNING: /home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/scraper-0.0.1-py2.7.egg/scraper/middlewares.py:2: ScrapyDeprecationWarning: Module `scrapy.contrib.downloadermiddleware.useragent` is deprecated, use `scrapy.downloadermiddlewares.useragent` instead
  from scrapy.contrib.downloadermiddleware.useragent import UserAgentMiddleware

2016-07-19 20:30:22 [scrapy] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scraper.middlewares.RotateUserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.chunked.ChunkedTransferMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2016-07-19 20:30:22 [scrapy] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2016-07-19 20:30:22 [scrapy] INFO: Enabled item pipelines:
[]
2016-07-19 20:30:22 [scrapy] INFO: Spider opened
2016-07-19 20:30:22 [botocore.credentials] DEBUG: Skipping environment variable credential check because profile name was explicitly set.
2016-07-19 20:30:22 [botocore.credentials] DEBUG: Looking for credentials via: env
2016-07-19 20:30:22 [botocore.credentials] DEBUG: Looking for credentials via: assume-role
2016-07-19 20:30:22 [botocore.credentials] DEBUG: Looking for credentials via: shared-credentials-file
2016-07-19 20:30:22 [botocore.credentials] DEBUG: Looking for credentials via: config-file
2016-07-19 20:30:22 [botocore.credentials] DEBUG: Looking for credentials via: ec2-credentials-file
2016-07-19 20:30:22 [botocore.credentials] DEBUG: Looking for credentials via: boto-config
2016-07-19 20:30:22 [botocore.credentials] DEBUG: Looking for credentials via: container-role
2016-07-19 20:30:22 [botocore.credentials] DEBUG: Looking for credentials via: iam-role
2016-07-19 20:30:22 [botocore.vendored.requests.packages.urllib3.connectionpool] INFO: Starting new HTTP connection (1): 169.254.169.254
2016-07-19 20:30:23 [botocore.utils] DEBUG: Caught exception while trying to retrieve credentials: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/iam/security-credentials/ (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7f09ba27f050>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))
Traceback (most recent call last):
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/utils.py", line 159, in _get_request
    response = requests.get(url, timeout=timeout)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/vendored/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/vendored/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py", line 419, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/iam/security-credentials/ (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x7f09ba27f050>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))
2016-07-19 20:30:23 [botocore.utils] DEBUG: Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
2016-07-19 20:30:23 [botocore.loaders] DEBUG: Loading JSON file: /home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/data/endpoints.json
2016-07-19 20:30:23 [botocore.loaders] DEBUG: Loading JSON file: /home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/data/s3/2006-03-01/service-2.json
2016-07-19 20:30:23 [botocore.loaders] DEBUG: Loading JSON file: /home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/data/_retry.json
2016-07-19 20:30:23 [botocore.client] DEBUG: Registering retry handlers for service: s3
2016-07-19 20:30:23 [botocore.hooks] DEBUG: Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f09baf92320>
2016-07-19 20:30:23 [botocore.hooks] DEBUG: Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f09baf8fa28>
2016-07-19 20:30:23 [botocore.client] DEBUG: The s3 config key is not a dictionary type, ignoring its value of: None
2016-07-19 20:30:23 [botocore.endpoint] DEBUG: Setting s3 timeout as (60, 60)


==== log is too long


Traceback (most recent call last):
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/scrapy/extensions/feedexport.py", line 118, in _store_in_thread
    Bucket=self.bucketname, Key=self.keyname, Body=file)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/client.py", line 278, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/client.py", line 561, in _make_api_call
    operation_model, request_dict)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/endpoint.py", line 117, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/endpoint.py", line 142, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/endpoint.py", line 126, in create_request
    operation_name=operation_model.name)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/signers.py", line 147, in sign
    auth.add_auth(request)
  File "/home/rezha.pradana/Envs/traveloka/lib/python2.7/site-packages/botocore/auth.py", line 665, in add_auth
    raise NoCredentialsError
NoCredentialsError: Unable to locate credentials
2016-07-19 20:30:43 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 55517,
 'downloader/request_count': 72,
 'downloader/request_method_count/GET': 72,
 'downloader/response_bytes': 2529033,
 'downloader/response_count': 72,
 'downloader/response_status_count/200': 72,
 'dupefilter/filtered': 20,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2016, 7, 19, 13, 30, 43, 867304),
 'item_scraped_count': 1196,
 'log_count/DEBUG': 1322,
 'log_count/ERROR': 1,
 'log_count/INFO': 9,
 'log_count/WARNING': 2,
 'request_depth_max': 20,
 'response_received_count': 72,
 'scheduler/dequeued': 72,
 'scheduler/dequeued/memory': 72,
 'scheduler/enqueued': 72,
 'scheduler/enqueued/memory': 72,
 'start_time': datetime.datetime(2016, 7, 19, 13, 30, 23, 900947)}
2016-07-19 20:30:43 [scrapy] INFO: Spider closed (finished)

```

**Comment by redapple** [comment]
Where are you using S3? feed export? images/files pipeline?
So you're using a spider class `custom_settings` attribute
```
class MySpider(scrapy.Spider):
    name = 'myspider'

    custom_settings = {
        'SOME_SETTING': 'some value',
    }
```
Are you able to test with AWS credentials within `settings.py`? Does it change anything?

**Comment by cathalgarvey** [comment]
Hi, I'm closing this as stale, but if it's still affecting you with the most recent version of Scrapy or the most recent revision, feel free to reopen and provide more information. Thank you for contributing to Scrapy!
