### ISSUE TITLE
This issue is very strange centos 6.8

### ISSUE THREAD

**Issue by shahidkarimi** [scrapy/scrapy#2203]
When I check version using scapy -V or run any command, I get the following error, Please help

```
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 3, in <module>
    from scrapy.cmdline import execute
  File "/usr/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 7, in <module>
    from scrapy.crawler import CrawlerProcess
  File "/usr/local/lib/python2.7/site-packages/scrapy/crawler.py", line 5, in <module>
    from scrapy.core.engine import ExecutionEngine
  File "/usr/local/lib/python2.7/site-packages/scrapy/core/engine.py", line 14, in <module>
    from scrapy.core.downloader import Downloader
  File "/usr/local/lib/python2.7/site-packages/scrapy/core/downloader/__init__.py", line 16, in <module>
    from .middleware import DownloaderMiddlewareManager
  File "/usr/local/lib/python2.7/site-packages/scrapy/core/downloader/middleware.py", line 7, in <module>
    from scrapy.http import Request, Response
  File "/usr/local/lib/python2.7/site-packages/scrapy/http/__init__.py", line 11, in <module>
    from scrapy.http.request.form import FormRequest
  File "/usr/local/lib/python2.7/site-packages/scrapy/http/request/form.py", line 9, in <module>
    import lxml.html
  File "/usr/local/lib/python2.7/site-packages/lxml-3.4.4-py2.7-linux-x86_64.egg/lxml/html/__init__.py", line 42, in <module>
    from lxml import etree
  File "lxml.etree.pyx", line 161, in init lxml.etree (src/lxml/lxml.etree.c:198847)
TypeError: encode() argument 1 must be string without null bytes, not unicode
```

**Comment by redapple** [comment]
@shahidkarimi ,  it fails at `lxml.html` import?
can you try in a regular Python shell `import lxml.html`, i.e. without any scrapy related things?

How did you install `scrapy`?

**Comment by shahidkarimi** [comment]
I install scrapy using pip command.
When I import lxml.html in python  shell, it works. @redapple

**Comment by redapple** [comment]
I found [this question on StackOverflow](https://stackoverflow.com/questions/9465248/runtimewarning-compiletime-version-2-6-of-module-lxml-etree-does-not-match-ru). Could it be related?

**Comment by redapple** [comment]
@shahidkarimi , it's not explanation for the issue, but I'd recommend that you try using a virtualenv and install scrapy in it.

**Comment by redapple** [comment]
@shahidkarimi are you still having the issue?

**Comment by cathalgarvey** [comment]
Hi folks, I'm closing this as stale. Feel free to re-open if it still affects you on the most recent version/revision of Scrapy. Thanks!
