### ISSUE TITLE
[Python 2] scrapy crawl does not work with non-ASCII spider names

### ISSUE THREAD

**Issue by redapple** [scrapy/scrapy#2251]
I don't know if this is an already documented issue, but when a project has a spider with a non-ASCII name, `scrapy crawl` fails with error `KeyError: 'Spider not found: ara\xc3\xb1a'`

The following fails with Python 2 (but works with Python 3):

```
$ scrapy version -v
Scrapy    : 1.1.2
lxml      : 3.6.4.0
libxml2   : 2.9.4
Twisted   : 16.4.0
Python    : 2.7.11+ (default, Apr 17 2016, 14:00:29) - [GCC 5.3.1 20160413]
pyOpenSSL : 16.1.0 (OpenSSL 1.0.2g-fips  1 Mar 2016)
Platform  : Linux-4.4.0-36-generic-x86_64-with-Ubuntu-16.04-xenial


$ scrapy list
araña

$ cat unicodename/spiders/example.py
# -*- coding: utf-8 -*-
import scrapy


class ExampleSpider(scrapy.Spider):
    name = u"araña"
    allowed_domains = ["example.com"]
    start_urls = (
        'http://www.example.com/',
    )

    def parse(self, response):
        yield {"url": response.url}

$ scrapy crawl araña
2016-09-15 22:46:35 [scrapy] INFO: Scrapy 1.1.2 started (bot: unicodename)
2016-09-15 22:46:35 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'unicodename.spiders', 'SPIDER_MODULES': ['unicodename.spiders'], 'ROBOTSTXT_OBEY': True, 'BOT_NAME': 'unicodename'}
Traceback (most recent call last):
  File "/home/paul/.virtualenvs/scrapy11.py2/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/home/paul/.virtualenvs/scrapy11.py2/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 142, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/home/paul/.virtualenvs/scrapy11.py2/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 88, in _run_print_help
    func(*a, **kw)
  File "/home/paul/.virtualenvs/scrapy11.py2/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 149, in _run_command
    cmd.run(args, opts)
  File "/home/paul/.virtualenvs/scrapy11.py2/local/lib/python2.7/site-packages/scrapy/commands/crawl.py", line 57, in run
    self.crawler_process.crawl(spname, **opts.spargs)
  File "/home/paul/.virtualenvs/scrapy11.py2/local/lib/python2.7/site-packages/scrapy/crawler.py", line 162, in crawl
    crawler = self.create_crawler(crawler_or_spidercls)
  File "/home/paul/.virtualenvs/scrapy11.py2/local/lib/python2.7/site-packages/scrapy/crawler.py", line 190, in create_crawler
    return self._create_crawler(crawler_or_spidercls)
  File "/home/paul/.virtualenvs/scrapy11.py2/local/lib/python2.7/site-packages/scrapy/crawler.py", line 194, in _create_crawler
    spidercls = self.spider_loader.load(spidercls)
  File "/home/paul/.virtualenvs/scrapy11.py2/local/lib/python2.7/site-packages/scrapy/spiderloader.py", line 43, in load
    raise KeyError("Spider not found: {}".format(spider_name))
KeyError: 'Spider not found: ara\xc3\xb1a'

```
with Python 3:
```
$ scrapy version -v
Scrapy    : 1.1.2
lxml      : 3.6.4.0
libxml2   : 2.9.4
Twisted   : 16.4.0
Python    : 3.5.1+ (default, Mar 30 2016, 22:46:26) - [GCC 5.3.1 20160330]
pyOpenSSL : 16.1.0 (OpenSSL 1.0.2g-fips  1 Mar 2016)
Platform  : Linux-4.4.0-36-generic-x86_64-with-Ubuntu-16.04-xenial


$ scrapy list
araña


$ scrapy crawl araña
2016-09-15 22:48:10 [scrapy] INFO: Scrapy 1.1.2 started (bot: unicodename)
2016-09-15 22:48:10 [scrapy] INFO: Overridden settings: {'ROBOTSTXT_OBEY': True, 'BOT_NAME': 'unicodename', 'SPIDER_MODULES': ['unicodename.spiders'], 'NEWSPIDER_MODULE': 'unicodename.spiders'}
2016-09-15 22:48:11 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole']
2016-09-15 22:48:11 [scrapy] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.chunked.ChunkedTransferMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2016-09-15 22:48:11 [scrapy] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2016-09-15 22:48:11 [scrapy] INFO: Enabled item pipelines:
[]
2016-09-15 22:48:11 [scrapy] INFO: Spider opened
2016-09-15 22:48:11 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2016-09-15 22:48:11 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6023
2016-09-15 22:48:11 [scrapy] DEBUG: Crawled (404) <GET http://www.example.com/robots.txt> (referer: None)
2016-09-15 22:48:12 [scrapy] DEBUG: Crawled (200) <GET http://www.example.com/> (referer: None)
2016-09-15 22:48:12 [scrapy] DEBUG: Scraped from <200 http://www.example.com/>
{'url': 'http://www.example.com/'}
2016-09-15 22:48:12 [scrapy] INFO: Closing spider (finished)
2016-09-15 22:48:12 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 436,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 1916,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 1,
 'downloader/response_status_count/404': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2016, 9, 15, 20, 48, 12, 221767),
 'item_scraped_count': 1,
 'log_count/DEBUG': 4,
 'log_count/INFO': 7,
 'response_received_count': 2,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2016, 9, 15, 20, 48, 11, 433975)}
2016-09-15 22:48:12 [scrapy] INFO: Spider closed (finished)
```

**Comment by kmike** [comment]
My vote is not to worry about this issue - workaround for user is very easy (don't use non-ascii name), and workaround in Scrapy could be hairy.

**Comment by redapple** [comment]
It's not so much of a worry, more of documenting the limitation, especially since I stopped Python 3 port of scrapyd because I thought it was a scrapyd problem only: https://github.com/scrapy/scrapyd/pull/179#issuecomment-245556877
