### ISSUE TITLE
RedirectMiddleware does not respect spider's crawling rules

### ISSUE THREAD

**Issue by djunzu** [scrapy/scrapy#2303]
As described in #15, some links to offsite domains may be crawled via redirects. For example:

```python
# in spider:
allowed_domains = ['xxx.com']
```

```bash
# in log, offsite domain crawled:
Filtered offsite request to 'www.yyy.com': <GET http://www.yyy.com/foo>
Redirecting (302) to <GET http://www.yyy.com/> from <GET http://www.xxx.com/bar/>
Crawled (200) <GET http://www.yyy.com/> (referer: http://www.xxx.com/bar/>)
```

But the problem also affects `rules` from `CrawlSpider`:
1. `deny` is not respected.
2. (worse) a response may be parsed by the wrong function.

For example:
```python
# in spider:
rules = (Rule(LinkExtractor(deny='forbidden', allow='drinks'), callback='parse_drinks', follow=True),
         Rule(LinkExtractor(deny='forbidden', allow='food'), callback='parse_food', follow=True)
        )
```

```bash
# in log:

# deny regexp crawled:
Redirecting (302) to <GET http://www.xxx.com/forbidden> from <GET http://www.xxx.com/bar/>
Crawled (200) <GET http://www.xxx.com/forbidden> (referer: http://www.xxx.com/bar/>)

# http://www.xxx.com/drink/bar should be parsed by parse_drinks but it will be parsed by parse_food:
Redirecting (302) to <GET http://www.xxx.com/drink/bar> from <GET http://www.xxx.com/food/bar>
Crawled (200) <GET http://www.xxx.com/drink/bar> (referer: http://www.xxx.com/food/bar>)
```

A somewhat related discussion is going on #2241.

**Comment by redapple** [comment]
@djunzu , `deny` is in essence an argument of the link extractor, to filter links from pages and only that, not an instruction on the `RedirectMiddleware`.
Having the filtering directives "leak" way down to `RedirectMiddleware` feels like a stretch to me.

On the other had, having more control over what `RedirectMiddleware` does with redirected requests can be improved quite a bit, I agree (cf. your comment https://github.com/scrapy/scrapy/issues/2241#issuecomment-251213143)

Therefore, regarding using `deny/allow` arguments to prevent redirected requests being parsed with `CrawlSpider`, I think this could be done with new `Rule` arguments, say, something like `redirect_allow/_deny`, that `CrawlSpider` would translate in some `meta` info for the generated `Request`, for `RedirectMiddleware` to abide by. (this would need changes to `RedirectMiddleware` of course since it only "understands" `dont_redirect`)

Regarding redirections being parsed by the "wrong" rule, it seems hard to get right for all use-cases: should it switch rule and send it to that other callback? or should you not send it to any callback?
I believe this can be implemented with a custom `CrawlSpider` subclass.
IMHO, following a link, expecting some entity A, and in the end receiving an entity B, it's more about building robust extraction than relying on too much magic from `CrawlSpider`.

All this is arguable, I'm not a heavy `CrawlSpider` myself.

**Comment by leeprevost** [comment]
Something like this:
```
class RedirectMiddleware(BaseRedirectMiddleware):
    """
    Handle redirection of requests based on response status
    and meta-refresh html tag.

    added: avoid PDF redirects
    """

    def process_response(self, request, response, spider):
        p = re.compile(r"\.pdf$", re.IGNORECASE)

        if p.search(request.url):
            raise IgnoreRequest("Found in request url: {}".format(p.findall(request.url)))

        super().process_response(self, request, response, spider)
```

**Comment by leeprevost** [comment]
I'm missing something on my CustomRedirect, i get:
`scrapy.exceptions._InvalidOutput: Middleware CustomRedirectMiddleware.process_response must return Response or Request, got <class 'NoneType'>`

**Comment by leeprevost** [comment]
A few more alternatives from discussing with Zyte Support Engineers to item 1 and 2 above:

3. Consider looking at content-type in redirect header as discussed in #1312.
4. Set  DOWNLOAD_MAXSIZE to a lower limit than defaults.  This may work for me as I don't care about images or files.  Only trying to follow links and capture outbound/external links.

**Comment by leeprevost** [comment]
> For choice 2 in above, something like this:
> 
> ```
> class CustomRedirectMiddleware(RedirectMiddleware):
>     """
>     Handle redirection of requests based on response status
>     and meta-refresh html tag.
> 
>     added: avoid PDF redirects
>     """
> 
This did not work as expected.  I'm missing something about how the RedirectMiddleware works to either redirect or pass on a redirect.  I thought my return response would inhibit the redirect.   I ran a small test on 5 sites with known redirects.  I got high quality capture using method 1 (dont_redirect in meta) and almost no errors. But method 2 (custom middleware) resulted in over 600 errors but also with high quality link capture.  high quality capture:  I'm capturing links from target websites that are pointing outwards (ie. don't have the TLD of the target URL).   

Example errors:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/scrapy/core/downloader/[middleware.py](http://middleware.py/)", line 54, in process_request
    return (yield download_func(request=request, spider=spider))
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]
```

```
File "/usr/local/lib/python3.11/site-packages/scrapy/http/response/__init__.py", line 137, in text
    raise AttributeError("Response content isn't text")
AttributeError: Response content isn't text
```
(This is similar to my original problem telling me that my CustomRedirectMIddleware is not doing what I expected it to do)

Method 1 seems to be my "least worst" work around option other than the linkextractor denying extensions like I thought it would.  I was not able to successfully test method 2 but think this may be cleanest to avoid missing anything but would have to dig deeper to understand how the RedirectMiddleware methods work (specifically how to inhibit a redirect).   I did not explore 3 or 4.

**Comment by leeprevost** [comment]
Thanks to Alexander on [SO](https://stackoverflow.com/a/77582140/7397195) and some tips from @Gallaecio,  I was able to solve this with the Custom middleware on redirect option (choice 2 above).  This seems to work best for my usecase.  It avoids all those heavy PDF/docx/xlsx or media downloads that are just informational forms not useful for my application.   This appraoch also seems to flow with the intended use of the deny_extensions default in the linkextractors.

I added some logic to use the built in default DENY_EXTENSIONS list used by the link extractors as well as added a setting to enable the custom vs. the default.   

This middleware sets up a regex pattern using DENY_EXTENSIONS and checks the header on the redirect for the extension at the end of the URL.  If it sees it, it ignores the request and logs it.   Also, the "from_crawler" initializes the middleware either with the default or the custom depending on settings keyword DENY_EXTENSIONS_REDIRECT=True/False and logs on startup.

```
class DenyExtensionsRedirectMiddleware(RedirectMiddleware):
    """
    Handle redirection of requests based on response status
    and meta-refresh html tag.

    added: avoid redirects to scrapy's default IGNORED_EXTENSIONS
    """
    # using scrapy default IGNORED -- from scrapy.linkextractors import IGNORED_EXTENSIONS
    # or add my own list
    ignored_ext = IGNORED_EXTENSIONS
    _ext_or_patt = "|".join(ignored_ext)
    deny_extensions = re.compile(r"\.(" + _ext_or_patt + r")$")

    def process_response(self, request, response, spider):

        location = response.headers.get("Location", b"").decode()
        ignored_extensions_found = self.deny_extensions.findall(location.lower())
        if ignored_extensions_found:
            reason = f"Ignoring redirect to {location} from {response} due to {ignored_extensions_found} found"
            logger.debug(
                reason,
                extra = {"spider": spider}
            )
            spider.crawler.stats.inc_value("deny_extension_redirect")
            raise IgnoreRequest(reason)
        return super().process_response(request, response, spider)

    @classmethod
    def from_crawler(cls, crawler):
        if not crawler.settings.get("DENY_EXTENSIONS_REDIRECT"):
            logger.info(f"{cls.__name__} being instantiated with default process_response method")
            cls.process_response = super().process_response   #goes back to default method
        else:
            logger.info(f"{cls.__name__} being instantiated with extension aware process_response")
            logger.info(f"{cls.__name__} will deny extensions with pattern {cls.deny_extensions}")
        return cls(crawler.settings)
```

And, in settings:
```
DOWNLOADER_MIDDLEWARES.update(
    {
    "scrapy.downloadermiddlewares.redirect.RedirectMiddleware": None,
    edtech.middlewares.DenyExtensionsRedirectMiddleware: 600,
    }
)
```

In spider (or settings):
```
custom_settings = dict(
        DENY_EXTENSIONS_REDIRECT=True
    )
```

**Comment by leeprevost** [comment]
> I was able to solve this with the Custom middleware on redirect option (choice 2 above).

Not so fast.  This half solved it:

Still getting errors here:
```
2023-12-06 01:05:29 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.gaston.k12.nc.us/site/handlers/filedownload.ashx?moduleinstanceid=5330&dataid=32810&FileName=6th%20Supply%20List.png> (referer: https://www.gaston.k12.nc.us/domain/3156)
Traceback (most recent call last):
  File "C:\Users\lee\PycharmProjects\scrapy\edtech\venv\lib\site-packages\scrapy\utils\defer.py", line 279, in iter_errback
    yield next(it)
  File "C:\Users\lee\PycharmProjects\scrapy\edtech\venv\lib\site-packages\scrapy\utils\python.py", line 350, in __next__
    return next(self.data)
  File "C:\Users\lee\PycharmProjects\scrapy\edtech\venv\lib\site-packages\scrapy\utils\python.py", line 350, in __next__
    return next(self.data)
  File "C:\Users\lee\PycharmProjects\scrapy\edtech\venv\lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    for r in iterable:
  File "C:\Users\lee\PycharmProjects\scrapy\edtech\venv\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "C:\Users\lee\PycharmProjects\scrapy\edtech\venv\lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    for r in iterable:
  File "C:\Users\lee\PycharmProjects\scrapy\edtech\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 352, in <genexpr>
    return (self._set_referer(r, response) for r in result or ())
  File "C:\Users\lee\PycharmProjects\scrapy\edtech\venv\lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    for r in iterable:
  File "C:\Users\lee\PycharmProjects\scrapy\edtech\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 27, in <genexpr>
    return (r for r in result or () if self._filter(r, spider))
  File "C:\Users\lee\PycharmProjects\scrapy\edtech\venv\lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    for r in iterable:
  File "C:\Users\lee\PycharmProjects\scrapy\edtech\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 31, in <genexpr>
    return (r for r in result or () if self._filter(r, response, spider))
  File "C:\Users\lee\PycharmProjects\scrapy\edtech\venv\lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    for r in iterable:
  File "C:\Users\lee\PycharmProjects\scrapy\edtech\edtech\spiders\edcrawler.py", line 150, in parse
    ex_links = external_le.extract_links(response)
  File "C:\Users\lee\PycharmProjects\scrapy\edtech\venv\lib\site-packages\scrapy\linkextractors\lxmlhtml.py", line 239, in extract_links
    base_url = get_base_url(response)
  File "C:\Users\lee\PycharmProjects\scrapy\edtech\venv\lib\site-packages\scrapy\utils\response.py", line 26, in get_base_url
    text = response.text[0:4096]
  File "C:\Users\lee\PycharmProjects\scrapy\edtech\venv\lib\site-packages\scrapy\http\response\__init__.py", line 137, in text
    raise AttributeError("Response content isn't text")
AttributeError: Response content isn't text
```
png is in DENY_EXTENSIONS

Yet, middleware blocks this:
`2023-12-05 22:17:06 [edcrawler] ERROR: <twisted.python.failure.Failure scrapy.exceptions.IgnoreRequest: Ignoring redirect to https://www.gaston.k12.nc.us/cms/lib/NC01911153/Centricity/Domain/3866/2023-2024%20Student%20Code%20of%20Conduct%20and%20Annual%20Notification%20to%20Parents.pdf from <302 https://www.gaston.k12.nc.us/Page/7930> due to ['pdf'] found>`

I'm officially stumped.   Not sure how the top one gets around my middleware.  Not handled by redirect?

**Comment by leeprevost** [comment]
> Not so fast. This half solved it:

I was getting inconsistent results with the above.   This seems to solve my problem:

```
from w3lib.url import safe_url_string
location = safe_url_string(response.headers.get("Location", b""))
```
then do the regex work to check for extensions....

**Comment by AdrianAtZyte** [comment]
The offsite part of this is fixed: since Scrapy 2.11.2, offsite filtering happens in a
downloader middleware, `scrapy.downloadermiddlewares.offsite.OffsiteMiddleware`, which
also filters redirect requests (#2241, #6358).

For the rest, I agree with @redapple:

-   `allow` and `deny` are arguments of the link extractor, i.e. they define which links
    to extract from a response, and I don’t think they should leak into
    `RedirectMiddleware`. To prevent redirects to certain URLs, a `RedirectMiddleware`
    subclass is the right place, as @leeprevost ended up doing. Filtering redirects by
    file extension or content type, which was the actual use case there, is a separate
    topic: #1312.

-   Re-matching a redirected response against the rules to choose a callback is not
    something we can get right for every use case: the response would silently go to a
    different callback, or to no callback at all. The callback is bound when the request
    is created, and I think that is the sane default. If the response you get may not be
    the entity you expected, check `response.url` in your callback.
