### ISSUE TITLE
TypeError: normalize() argument 2 must be unicode, not str

### ISSUE THREAD

**Issue by ricoxor** [scrapy/scrapy#2304]
My crawler do lot of errors like this : 

```
2016-10-04 21:21:24 [scrapy] ERROR: Spider error processing <GET http://xxxx.com/> (referer:)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spiders/crawl.py", line 78, in _parse_response
    for request_or_item in self._requests_to_follow(response):
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spiders/crawl.py", line 56, in _requests_to_follow
    links = [lnk for lnk in rule.link_extractor.extract_links(response)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/linkextractors/lxmlhtml.py", line 111, in extract_links
    all_links.extend(self._process_links(links))
  File "/usr/local/lib/python2.7/dist-packages/scrapy/linkextractors/__init__.py", line 104, in _process_links
    link.url = canonicalize_url(urlparse(link.url))
  File "/usr/local/lib/python2.7/dist-packages/w3lib/url.py", line 354, in canonicalize_url
    parse_url(url), encoding=encoding)
  File "/usr/local/lib/python2.7/dist-packages/w3lib/url.py", line 298, in _safe_ParseResult
    netloc = parts.netloc.encode('idna')
  File "/usr/lib/python2.7/encodings/idna.py", line 164, in encode
    result.append(ToASCII(label))
  File "/usr/lib/python2.7/encodings/idna.py", line 76, in ToASCII
    label = nameprep(label)
  File "/usr/lib/python2.7/encodings/idna.py", line 21, in nameprep
    newlabel.append(stringprep.map_table_b2(c))
  File "/usr/lib/python2.7/stringprep.py", line 197, in map_table_b2
    b = unicodedata.normalize("NFKC", al)
TypeError: normalize() argument 2 must be unicode, not str
```

Can someone help me to fix that ?
Thank's

**Comment by redapple** [comment]
Can you provide us with your spider code and the source URL where you're getting these errors?
(You can send these details by email to me if you don't want to diclose this).
Also, can you provide the output of `scrapy version -v`?

**Comment by ricoxor** [comment]
Hello,

Thank's for your help !

```
scrapy version -v :

Scrapy    : 1.2.0
lxml      : 3.6.4.0
libxml2   : 2.9.3
Twisted   : 16.4.1
Python    : 2.7.12 (default, Jul  1 2016, 15:12:24) - [GCC 5.4.0 20160609]
pyOpenSSL : 16.1.0 (OpenSSL 1.0.2g  1 Mar 2016)
Platform  : Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Ubuntu-16.04-xenial
```

The code : https://gist.github.com/ricoxor/a817bc6f62f81486dfed1d7eb118f2af

**Comment by redapple** [comment]
@ricoxor , thanks. Though I don't think I can run your spider the way you do without the input domains.
Maybe you can send me one of the URLs where you got this error (it seems to happen when extracting links from it)

As a workaround, you can try adding [`canonicalize=False`](https://docs.scrapy.org/en/latest/topics/link-extractors.html#scrapy.linkextractors.lxmlhtml.LxmlLinkExtractor) as argument to your link extractor in your rule.
(But I'd really want to get to the bottom of the issue with some sample URL.)

**Comment by ricoxor** [comment]
Error with the link : https://gist.github.com/ricoxor/1016ab066c627068a2a0af3747784ac0

**Comment by ricoxor** [comment]
Unfortunately `canonicalize=False` don't fix the issue.

**Comment by redapple** [comment]
I've identified the bug in `w3lib.url.canonicalize_url`: it's about calling `canonicalize_url()` with the result of `urlparse()` on a bytes URL (what `LinkExtractor` does), at least when a non-ASCII domain is there:

```
# canonicalize_url() can handle unicode or bytes URLs directly,
# and also with urlparse'd unicode URLs:

>>> from w3lib.url import canonicalize_url
>>> canonicalize_url(u'http://la_bande_à_mia.blogator.net')
'http://xn--la_bande__mia-xdb.blogator.net/'
>>> canonicalize_url(u'http://la_bande_à_mia.blogator.net'.encode('utf-8'))
'http://xn--la_bande__mia-xdb.blogator.net/'

>>> from six.moves.urllib.parse import urlparse
>>> canonicalize_url(urlparse(u'http://la_bande_à_mia.blogator.net'))
'http://xn--la_bande__mia-xdb.blogator.net/'

# but when going through `urlparse` with bytes input, it chokes:

>>> canonicalize_url(urlparse(u'http://la_bande_à_mia.blogator.net'.encode('utf-8')))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/paul/.virtualenvs/scrapy12/local/lib/python2.7/site-packages/w3lib/url.py", line 354, in canonicalize_url
    parse_url(url), encoding=encoding)
  File "/home/paul/.virtualenvs/scrapy12/local/lib/python2.7/site-packages/w3lib/url.py", line 298, in _safe_ParseResult
    netloc = parts.netloc.encode('idna')
  File "/home/paul/.virtualenvs/scrapy12/lib/python2.7/encodings/idna.py", line 164, in encode
    result.append(ToASCII(label))
  File "/home/paul/.virtualenvs/scrapy12/lib/python2.7/encodings/idna.py", line 76, in ToASCII
    label = nameprep(label)
  File "/home/paul/.virtualenvs/scrapy12/lib/python2.7/encodings/idna.py", line 21, in nameprep
    newlabel.append(stringprep.map_table_b2(c))
  File "/usr/lib/python2.7/stringprep.py", line 197, in map_table_b2
    b = unicodedata.normalize("NFKC", al)
TypeError: normalize() argument 2 must be unicode, not str
>>> 
```

@ricoxor , the workaround with `canonicalize=False` works for me (without a fix on `w3lib.url.canonicalize_url` which I'll submit soon). See Below.
Could you be having a different issue?

```
$ scrapy shell http://blogs.blogator.net/eternity_golden/
2016-10-05 12:13:54 [scrapy] INFO: Scrapy 1.2.0 started (bot: scrapybot)
2016-10-05 12:13:54 [scrapy] DEBUG: Crawled (200) <GET http://blogs.blogator.net/eternity_golden/> (referer: None)
>>> from scrapy.linkextractors import LinkExtractor
>>> for link in LinkExtractor().extract_links(response):
...     print(link.url)
... 
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/paul/.virtualenvs/scrapy12/local/lib/python2.7/site-packages/scrapy/linkextractors/lxmlhtml.py", line 111, in extract_links
    all_links.extend(self._process_links(links))
  File "/home/paul/.virtualenvs/scrapy12/local/lib/python2.7/site-packages/scrapy/linkextractors/__init__.py", line 104, in _process_links
    link.url = canonicalize_url(urlparse(link.url))
  File "/home/paul/.virtualenvs/scrapy12/local/lib/python2.7/site-packages/w3lib/url.py", line 354, in canonicalize_url
    parse_url(url), encoding=encoding)
  File "/home/paul/.virtualenvs/scrapy12/local/lib/python2.7/site-packages/w3lib/url.py", line 298, in _safe_ParseResult
    netloc = parts.netloc.encode('idna')
  File "/home/paul/.virtualenvs/scrapy12/lib/python2.7/encodings/idna.py", line 164, in encode
    result.append(ToASCII(label))
  File "/home/paul/.virtualenvs/scrapy12/lib/python2.7/encodings/idna.py", line 76, in ToASCII
    label = nameprep(label)
  File "/home/paul/.virtualenvs/scrapy12/lib/python2.7/encodings/idna.py", line 21, in nameprep
    newlabel.append(stringprep.map_table_b2(c))
  File "/usr/lib/python2.7/stringprep.py", line 197, in map_table_b2
    b = unicodedata.normalize("NFKC", al)
TypeError: normalize() argument 2 must be unicode, not str
>>> for link in LinkExtractor(canonicalize=False).extract_links(response):
...     print(link.url)
... 
http://www.blogator.net
http://serenitegolden.blogator.net
http://closdesjeubes.blogator.net
http://neepnoy.blogator.net
http://lebonheurestdanslejardin.blogator.net
http://au_bonheur_des_4_pattes.blogator.net
http://voxanesetterirlandais.blogator.net
http://le_sel_de_la_vie.blogator.net
http://vaniksettergordon.blogator.net
http://arvernechichisgirls.blogator.net
http://goldenment_votre.blogator.net
http://golden_nolane.blogator.net
http://cannelledelacolombedor.blogator.net
http://les_2_calinous.blogator.net
http://au_fil_du_temps.blogator.net
http://les_jaunes_de_laube.blogator.net
http://hohoho.blogator.net
http://bubu.blogator.net
http://anjimon_epagneul.blogator.net
http://chachadu45.blogator.net
http://dawson-et-yankee.blogator.net
http://la_bande_à_mia.blogator.net
http://meschiens_et_chat.blogator.net
http://marie_colley57.blogator.net
http://les_zanimaux_a_titi.blogator.net
http://lespetitsangesnoirs.blogator.net
http://of-lady-woodcock.blogator.net
http://salomé.blogator.net
http://ethan.blogator.net
http://le_domaine_des_marmottes.blogator.net
http://toutoudog.blogator.net
http://show-training-namur.blogator.net
http://zommpartibebe.blogator.net
http://setterdelanneaudukerry.blogator.net
http://dobyork.blogator.net
http://lewis-olw.blogator.net
http://www.paroles-musique.com/
http://www.xiti.com/xiti.asp?s=227243
http://www.blogator.net/inscription_blog.php
http://blogs.blogator.net/eternity_golden/?page=4,4
http://blogs.blogator.net/eternity_golden/?page=4428,3
http://www.google.com/
http://www.blogator-script.com
http://www.netvador.fr
>>> 
```

**Comment by ricoxor** [comment]
I'm using LxmlLinkExtractor I don't know if it could change anything ?
But I alway have the `TypeError: normalize() argument 2 must be unicode, not str` error.

```
    rules = (
        Rule(
            LxmlLinkExtractor(
                allow=('.com', '.fr', '.net', '.org', '.info', '.casino', '.eu', '.tv'),
                deny=('facebook', 'amazon', 'wordpress', 'blogspot', 'free', 'reddit', 'fnac', 'wiki',
                      'tumblr', 'videos', 'google', 'youtube', 'doubleclick', 'microsoft', 'yahoo',
                      'bing', 'znet', 'stackexchang', 'twitter', 'wikipedia', 'creativecommons',
                      'mediawiki', 'wikidata'), canonicalize=False, ),
            callback='parse_obj',
            process_request='add_errback',
            follow=True),
    )
```

**Comment by redapple** [comment]
`LinkExtractor` is the same as `LxmlLinkExtractor`, [it's an alias](https://github.com/scrapy/scrapy/blob/241bd00e76df142a24699819f8496bdec8f5c83a/scrapy/linkextractors/__init__.py#L113).

I cannot reproduce the bug with `canonicalize=False`:

```
$ scrapy shell http://blogs.blogator.net/eternity_golden/
2016-10-05 13:00:17 [scrapy] INFO: Scrapy 1.2.0 started (bot: scrapybot)
2016-10-05 13:00:17 [scrapy] DEBUG: Crawled (200) <GET http://blogs.blogator.net/eternity_golden/> (referer: None)
>>> lxe = scrapy.linkextractors.lxmlhtml.LxmlLinkExtractor(
...                 allow=('.com', '.fr', '.net', '.org', '.info', '.casino', '.eu', '.tv'),
...                 deny=('facebook', 'amazon', 'wordpress', 'blogspot', 'free', 'reddit', 'fnac', 'wiki',
...                       'tumblr', 'videos', 'google', 'youtube', 'doubleclick', 'microsoft', 'yahoo',
...                       'bing', 'znet', 'stackexchang', 'twitter', 'wikipedia', 'creativecommons',
...                       'mediawiki', 'wikidata'), canonicalize=False, )
>>> lxe
<scrapy.linkextractors.lxmlhtml.LxmlLinkExtractor object at 0x7f5854af3e50>
>>> lxe.extract_links(response)
[Link(url='http://www.blogator.net', text=u'', fragment='', nofollow=False), Link(url='http://serenitegolden.blogator.net', text='serenitegolden', fragment='', nofollow=False), Link(url='http://closdesjeubes.blogator.net', text='closdesjeubes', fragment='', nofollow=False), Link(url='http://neepnoy.blogator.net', text='neepnoy', fragment='', nofollow=False), Link(url='http://lebonheurestdanslejardin.blogator.net', text='lebonheurestdanslejardin', fragment='', nofollow=False), Link(url='http://au_bonheur_des_4_pattes.blogator.net', text='au_bonheur_des_4_pattes', fragment='', nofollow=False), Link(url='http://voxanesetterirlandais.blogator.net', text='voxanesetterirlandais', fragment='', nofollow=False), Link(url='http://le_sel_de_la_vie.blogator.net', text='le_sel_de_la_vie', fragment='', nofollow=False), Link(url='http://vaniksettergordon.blogator.net', text='vaniksettergordon', fragment='', nofollow=False), Link(url='http://arvernechichisgirls.blogator.net', text='arvernechichisgirls', fragment='', nofollow=False), Link(url='http://goldenment_votre.blogator.net', text='goldenment_votre', fragment='', nofollow=False), Link(url='http://golden_nolane.blogator.net', text='golden_nolane', fragment='', nofollow=False), Link(url='http://cannelledelacolombedor.blogator.net', text='cannelledelacolombedor', fragment='', nofollow=False), Link(url='http://les_2_calinous.blogator.net', text='les_2_calinous', fragment='', nofollow=False), Link(url='http://au_fil_du_temps.blogator.net', text='au_fil_du_temps', fragment='', nofollow=False), Link(url='http://les_jaunes_de_laube.blogator.net', text='les_jaunes_de_laube', fragment='', nofollow=False), Link(url='http://hohoho.blogator.net', text='hohoho', fragment='', nofollow=False), Link(url='http://bubu.blogator.net', text='bubu', fragment='', nofollow=False), Link(url='http://anjimon_epagneul.blogator.net', text='anjimon_epagneul', fragment='', nofollow=False), Link(url='http://chachadu45.blogator.net', text='chachadu45', fragment='', nofollow=False), Link(url='http://dawson-et-yankee.blogator.net', text='dawson-et-yankee', fragment='', nofollow=False), Link(url='http://la_bande_\xc3\xa0_mia.blogator.net', text=u'la_bande_\xe0_mia', fragment='', nofollow=False), Link(url='http://meschiens_et_chat.blogator.net', text='meschiens_et_chat', fragment='', nofollow=False), Link(url='http://marie_colley57.blogator.net', text='marie_colley57', fragment='', nofollow=False), Link(url='http://les_zanimaux_a_titi.blogator.net', text='les_zanimaux_a_titi', fragment='', nofollow=False), Link(url='http://lespetitsangesnoirs.blogator.net', text='lespetitsangesnoirs', fragment='', nofollow=False), Link(url='http://of-lady-woodcock.blogator.net', text='of-lady-woodcock', fragment='', nofollow=False), Link(url='http://salom\xc3\xa9.blogator.net', text=u'salom\xe9', fragment='', nofollow=False), Link(url='http://ethan.blogator.net', text='ethan', fragment='', nofollow=False), Link(url='http://le_domaine_des_marmottes.blogator.net', text='le_domaine_des_marmottes', fragment='', nofollow=False), Link(url='http://toutoudog.blogator.net', text='toutoudog', fragment='', nofollow=False), Link(url='http://show-training-namur.blogator.net', text='show-training-namur', fragment='', nofollow=False), Link(url='http://zommpartibebe.blogator.net', text='zommpartibebe', fragment='', nofollow=False), Link(url='http://setterdelanneaudukerry.blogator.net', text='setterdelanneaudukerry', fragment='', nofollow=False), Link(url='http://dobyork.blogator.net', text='dobyork', fragment='', nofollow=False), Link(url='http://lewis-olw.blogator.net', text='lewis-olw', fragment='', nofollow=False), Link(url='http://www.paroles-musique.com/', text='Paroles et traductions', fragment='', nofollow=False), Link(url='http://www.xiti.com/xiti.asp?s=227243', text='\n\n<!--\nXt_param = \'s=227243&p=\';\ntry {Xt_r = top.document.referrer;}\ncatch(e) {Xt_r = document.referrer; }\nXt_h = new Date();\nXt_i = \'<img width="80" height="15" border="0" alt="" \';\nXt_i += \'src="http://logv30.xiti.com/bcg.xiti?\'+Xt_param;\nXt_i += \'&hl=\'+Xt_h.getHours()+\'x\'+Xt_h.getMinutes()+\'x\'+Xt_h.getSeconds();\nif(parseFloat(navigator.appVersion)>=4)\n{Xt_s=screen;Xt_i+=\'&r=\'+Xt_s.width+\'x\'+Xt_s.height+\'x\'+Xt_s.pixelDepth+\'x\'+Xt_s.colorDepth;}\ndocument.write(Xt_i+\'&ref=\'+Xt_r.replace(/[<>"]/g, \'\').replace(/&/g, \'$\')+\'" title="Internet Audience">\');\n//-->\n\n\nMesure d\'audience ROI statistique webanalytics par \n', fragment='', nofollow=False), Link(url='http://www.blogator.net/inscription_blog.php', text=u'Je cr\xe9e mon Blogator gratuit !', fragment='', nofollow=False), Link(url='http://blogs.blogator.net/eternity_golden/?page=4,4', text='Page 2', fragment='', nofollow=False), Link(url='http://blogs.blogator.net/eternity_golden/?page=4428,3', text='Fin', fragment='', nofollow=False), Link(url='http://www.blogator-script.com', text='Blogator-script', fragment='', nofollow=False), Link(url='http://www.netvador.fr', text='NET VADOR', fragment='', nofollow=False)]
>>> 
```

Can you post the full stacktrace? The exception could be happening in some other part of the code.

**Comment by ricoxor** [comment]
You can find the full stacktrace here : 

```
2016-10-05 13:15:55 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2016-10-05 13:16:05 [scrapy] ERROR: Spider error processing <GET https://www.intenseblog.com/wordpress/optimize-wordpress-speed.html> (referer: https://www.intenseblog.com/reviews/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spiders/crawl.py", line 72, in _parse_response
    cb_res = callback(response, **cb_kwargs) or ()
  File "/home/CrawlerNDD/dirbot/spiders/expired_one.py", line 70, in parse_obj
    for link in LxmlLinkExtractor(allow=(), deny=self.allowed_domains).extract_links(response):
  File "/usr/local/lib/python2.7/dist-packages/scrapy/linkextractors/lxmlhtml.py", line 111, in extract_links
    all_links.extend(self._process_links(links))
  File "/usr/local/lib/python2.7/dist-packages/scrapy/linkextractors/__init__.py", line 104, in _process_links
    link.url = canonicalize_url(urlparse(link.url))
  File "/usr/local/lib/python2.7/dist-packages/w3lib/url.py", line 354, in canonicalize_url
    parse_url(url), encoding=encoding)
  File "/usr/local/lib/python2.7/dist-packages/w3lib/url.py", line 298, in _safe_ParseResult
    netloc = parts.netloc.encode('idna')
  File "/usr/lib/python2.7/encodings/idna.py", line 164, in encode
    result.append(ToASCII(label))
  File "/usr/lib/python2.7/encodings/idna.py", line 76, in ToASCII
    label = nameprep(label)
  File "/usr/lib/python2.7/encodings/idna.py", line 21, in nameprep
    newlabel.append(stringprep.map_table_b2(c))
  File "/usr/lib/python2.7/stringprep.py", line 197, in map_table_b2
    b = unicodedata.normalize("NFKC", al)
TypeError: normalize() argument 2 must be unicode, not str

```

**Comment by ricoxor** [comment]
Everything is fix ! 
Thank you for your help.

**Comment by anynomousaccount** [comment]
@ricoxor Hello, could you please clarify the solution? I'm not sure how to fix it.

**Comment by wRAR** [comment]
@anynomousaccount if you are using package versions as old as this bug report then you need to update them. Otherwise you are likely to have a differnet problem.
