### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by ricoxor** [scrapy/scrapy#2311]
I have lot of errors with SSL websites.
For exemple, when I call : `scrapy shell https://subscribe.wsj.com/printpack/`

I have this error : 

```
2016-10-06 22:15:40 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6043
2016-10-06 22:15:40 [scrapy] INFO: Spider opened
2016-10-06 22:15:40 [scrapy] DEBUG: Retrying <GET https://subscribe.wsj.com/printpack/> (failed 1 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'SSL23_GET_SERVER_HELLO', 'sslv3 alert handshake failure')]>]
2016-10-06 22:15:40 [scrapy] DEBUG: Retrying <GET https://subscribe.wsj.com/printpack/> (failed 2 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'SSL23_GET_SERVER_HELLO', 'sslv3 alert handshake failure')]>]
2016-10-06 22:15:40 [scrapy] DEBUG: Gave up retrying <GET https://subscribe.wsj.com/printpack/> (failed 3 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'SSL23_GET_SERVER_HELLO', 'sslv3 alert handshake failure')]>]
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 142, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 88, in _run_print_help
    func(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 149, in _run_command
    cmd.run(args, opts)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/commands/shell.py", line 71, in run
    shell.start(url=url)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/shell.py", line 47, in start
    self.fetch(url, spider)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/shell.py", line 112, in fetch
    reactor, self._schedule, request, spider)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/threads.py", line 122, in blockingCallFromThread
    result.raiseException()
  File "<string>", line 2, in raiseException
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'SSL23_GET_SERVER_HELLO', 'sslv3 alert handshake failure')]>]
```

How fix that ?

**Comment by redapple** [comment]
Hi @ricoxor ,

It seems that Scrapy (via Twisted) is not sending a CipherSuite that suits the remote `subscribe.wsj.com` server. It's the server closing the TLS connection with a handshake failure message.

`curl -v https://subscribe.wsj.com/printpack/` and `openssl s_client -connect subscribe.wsj.com:443` manage to connect.

So Scrapy should be able to connect though, because `openssl s_client` (on the same machine) can.
It should be possible to configure the TLS ClientHello initiated by Scrapy with these cipher suites.
Although I'm not sure how to do that yet.

I've put all the Wiresharp/tcpdump and console logs at https://github.com/redapple/scrapy-issues/tree/master/2311

Note that https://www.ssllabs.com/ssltest/analyze.html?d=subscribe.wsj.com&hideResults=on states that the server is using insecure cipher suites and grades it "C":

```
(...)
TLS_RSA_WITH_RC4_128_MD5 (0x4)   INSECURE	128
TLS_RSA_WITH_RC4_128_SHA (0x5)   INSECURE	128
TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa)	112
```


Some logs from curl and openssl s_client:

```
$ curl -v https://subscribe.wsj.com/printpack/
* Connected to subscribe.wsj.com (205.203.148.137) port 443 (#0)
* ALPN, offering http/1.1
* SSL connection using TLS1.0 / RSA_3DES_EDE_CBC_SHA1
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: subscribe.wsj.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=US,ST=New Jersey,L=Princeton,O=Dow Jones and Company,OU=EIS SUB PRINT WEB,CN=subscribe.wsj.com
* 	 start date: Wed, 21 Sep 2016 00:00:00 GMT
* 	 expire date: Fri, 22 Sep 2017 23:59:59 GMT
* 	 issuer: C=US,O=Symantec Corporation,OU=Symantec Trust Network,CN=Symantec Class 3 Secure Server CA - G4
* 	 compression: NULL
```
```
$ openssl s_client -connect subscribe.wsj.com:443
(...)
New, TLSv1/SSLv3, Cipher is RC4-MD5
(...)
```

**Comment by redapple** [comment]
Oh, and Scrapy 1.0.6 is able to connect, so it's a regression.

```
$ scrapy shell https://subscribe.wsj.com/printpack/ 
2016-10-07 10:58:21 [scrapy] INFO: Scrapy 1.0.6 started (bot: scrapybot)
2016-10-07 10:58:21 [scrapy] INFO: Optional features available: ssl, http11
2016-10-07 10:58:21 [scrapy] INFO: Overridden settings: {'LOGSTATS_INTERVAL': 0, 'DUPEFILTER_CLASS': 'scrapy.dupefilters.BaseDupeFilter'}
2016-10-07 10:58:22 [scrapy] INFO: Enabled extensions: CloseSpider, TelnetConsole, CoreStats, SpiderState
2016-10-07 10:58:22 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2016-10-07 10:58:22 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2016-10-07 10:58:22 [scrapy] INFO: Enabled item pipelines: 
2016-10-07 10:58:22 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6024
2016-10-07 10:58:22 [scrapy] INFO: Spider opened
2016-10-07 10:58:23 [scrapy] DEBUG: Redirecting (meta refresh) to <GET https://buy.wsj.com/wsjcol16v2?inttrackingCode=aaqnz43b&icid=WSJ_ON_PHP_ACQ_NA> from <GET https://subscribe.wsj.com/printpack/>
2016-10-07 10:58:24 [scrapy] DEBUG: Redirecting (301) to <GET https://buy.wsj.com/wsjcol16v2/?inttrackingCode=aaqnz43b&icid=WSJ_ON_PHP_ACQ_NA> from <GET https://buy.wsj.com/wsjcol16v2?inttrackingCode=aaqnz43b&icid=WSJ_ON_PHP_ACQ_NA>
2016-10-07 10:58:25 [scrapy] DEBUG: Crawled (200) <GET https://buy.wsj.com/wsjcol16v2/?inttrackingCode=aaqnz43b&icid=WSJ_ON_PHP_ACQ_NA> (referer: None)
[s] Available Scrapy objects:
[s]   crawler    <scrapy.crawler.Crawler object at 0x7f6f3d36e090>
[s]   item       {}
[s]   request    <GET https://subscribe.wsj.com/printpack/>
[s]   response   <200 https://buy.wsj.com/wsjcol16v2/?inttrackingCode=aaqnz43b&icid=WSJ_ON_PHP_ACQ_NA>
[s]   settings   <scrapy.settings.Settings object at 0x7f6f35461b50>
[s]   spider     <DefaultSpider 'default' at 0x7f6f33d89910>
[s] Useful shortcuts:
[s]   shelp()           Shell help (print this help)
[s]   fetch(req_or_url) Fetch request (or URL) and update local objects
[s]   view(response)    View response in a browser
2016-10-07 10:58:26 [root] DEBUG: Using default logger
2016-10-07 10:58:26 [root] DEBUG: Using default logger
```

**Comment by redapple** [comment]
@ricoxor , the patch in https://github.com/scrapy/scrapy/pull/2314 did the trick for me with https://subscribe.wsj.com/printpack/
If you have other domains that fail with TLS errors, I'd be happy to test them.

**Comment by minispeck** [comment]
@redapple i'm having a similar problem on the latest scrapy trying to scrape

https://www1.apply2jobs.com/jupitermed/ProfExt/index.cfm?fuseaction=mExternal.returnToResults

no matter what i get an error 'connection closed in non-clean fashion'

[thanks to some comments over on my stackoverflow question](https://stackoverflow.com/questions/45924568/scrapy-twisted-connection-lost-in-non-clean-fashion-no-proxy-already-tried-hea) we found that openssl 1.1.0 doesnt support rc4-md5 out of the box which is what the site uses.

what can i do about this besides downgrading?

**Comment by redapple** [comment]
@minispeck , I was following on StackOverflow. (I was the one commenting on RC4-MD5 not being in OpenSSL 1.1.0 by default.)
You can try downgrading [cryptography to a version before 2.0](https://cryptography.io/en/latest/changelog/#v1-9). This worked for me locally.

The other option would be to [build a static wheel cryptography](https://cryptography.io/en/latest/installation/#static-wheels) with OpenSSL 1.1.0 with `enable-weak-ssl-ciphers`. I'll try that tomorrow myself.

**Comment by redapple** [comment]
What I tried locally:
```
$ pip install --upgrade 'cryptography<2'
$ $ scrapy shell "https://www5.apply2jobs.com/jupitermed/ProfExt/index.cfm?fuseaction=mExternal.searchJobs" -s RETRY_TIMES=0 -s DOWNLOADER_CLIENT_TLS_METHOD=TLSv1.0
```

**Comment by redapple** [comment]
@minispeck , I tried compiling OpenSSL 1.1.0f with `enable-weak-ssl-ciphers` to [build a static wheel](https://cryptography.io/en/latest/installation/#static-wheels),
but I didn't manage to have it support TLS_RSA_WITH_RC4_128_MD5 as [ssllabs.com reports](https://www.ssllabs.com/ssltest/analyze.html?d=www5.apply2jobs.com&hideResults=on) for some reason. I'm laking OpenSSL building knowledge apparently.
So the only option I see is to use a virtualenv with 'cryptography<2' for scraping that website.

**Comment by minispeck** [comment]
@redapple thanks. if you want to collect this info into an answer on stackoverflow i'm happy to accept it if you want the points

**Comment by derrickmar** [comment]
Hmm I also tried pip install --upgrade 'cryptography<2' but I'm getting an error when running
`scrapy shell "https://www5.apply2jobs.com/jupitermed/ProfExt/index.cfm?fuseaction=mExternal.searchJobs" -s RETRY_TIMES=0 -s DOWNLOADER_CLIENT_TLS_METHOD=TLSv1.0`

```
scrapy version -v
Scrapy    : 1.4.0
lxml      : 4.1.1.0
libxml2   : 2.9.7
cssselect : 1.0.1
parsel    : 1.2.0
w3lib     : 1.18.0
Twisted   : 17.9.0
Python    : 2.7.10 (default, Sep 23 2015, 04:34:14) - [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]
pyOpenSSL : 17.5.0 (OpenSSL 1.1.0f  25 May 2017)
Platform  : Darwin-16.7.0-x86_64-i386-64bit
```

```
pip freeze
asn1crypto==0.23.0
attrs==17.3.0
Automat==0.6.0
cffi==1.11.2
constantly==15.1.0
cryptography==1.9
cssselect==1.0.1
enum34==1.1.6
hyperlink==17.3.1
idna==2.6
incremental==17.5.0
ipaddress==1.0.18
lxml==4.1.1
parsel==1.2.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycparser==2.18
PyDispatcher==2.0.5
pyOpenSSL==17.5.0
queuelib==1.4.2
Scrapy==1.4.0
service-identity==17.0.0
six==1.11.0
Twisted==17.9.0
w3lib==1.18.0
zope.interface==4.4.3
```
