### ISSUE TITLE
twisted.internet.error with bindaddress with scrapy.Request

### ISSUE THREAD

**Issue by dingld** [scrapy/scrapy#2356]
## Python3.5 with latest Scrapy

I was trying to set the bindaddress with Request.meta , whatever (host, port) I  chose, the program always complained about 

```
Traceback (most recent call last):
  File "/Users/ld/.virtualenvs/scrapy/lib/python3.5/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/Users/ld/.virtualenvs/scrapy/lib/python3.5/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/Users/ld/.virtualenvs/scrapy/lib/python3.5/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.internet.error.ConnectBindError: Couldn't bind: 48: Address already in use.
```

Is there any approach to that?

**Comment by redapple** [comment]
@dingld , passing something like `meta={"bindaddress": ('192.168.0.15', 0)}` works for me in both Python 2 and Python 3.
Can you share some code how you are setting the `meta` argument?

**Comment by cathalgarvey** [comment]
Hi @dingld - I'm closing this as it's gone stale, but feel free to re-open if you are still affected by this on the most recent version of Scrapy (or ideally, the latest git revision).
