### ISSUE TITLE
Permissions issue when installing attrs during pip install scrapy

### ISSUE THREAD

**Issue by chrisfromthelc** [scrapy/scrapy#2370]
OS: Rasbian Jessie 4.4

When using a virtualenv (Python 2.7), there's an error that seems to be permissions-related during the `pip install scrapy` installation.

```
Collecting attrs
  Using cached attrs-16.2.0-py2.py3-none-any.whl
Installing collected packages: attrs
Exception:
Traceback (most recent call last):
  File "/home/pi/TEST/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/pi/TEST/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/home/pi/TEST/local/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/home/pi/TEST/local/lib/python2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/pi/TEST/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/home/pi/TEST/local/lib/python2.7/site-packages/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/pi/TEST/local/lib/python2.7/site-packages/pip/wheel.py", line 317, in clobber
    ensure_dir(destdir)
  File "/home/pi/TEST/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/home/pi/TEST/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/pi/TEST/lib/python2.7/site-packages/attrs-16.2.0.dist-info'
```

Using `chmod`  on /lib/python2.7/site-packages/ to open up permissions allows installation of `attrs`.

**Comment by redapple** [comment]
@chrisfromthelc , I'm not sure what scrapy can do or document.
Are you seeing this with other modules that scrapy depends on? (by the way, scrapy depends on `attrs` through `service-identity` it seems)
Could it be Rasbian Jessie specific?
