### ISSUE TITLE
Invalid Codepoint in robots.txt

### ISSUE THREAD

**Issue by mohmad-null** [scrapy/scrapy#2377]
During my scraping I had this error get thrown.

Pages that triggered it:
https://www.gpo.gov:/robots.txt
https://www.gpo.gov:/fdsys/pkg/FR-2006-12-28/html/E6-22242.htm
https://www.gpo.gov:/fdsys/pkg/FR-2006-07-20/html/E6-11541.htm
https://www.gpo.gov:/fdsys/pkg/FR-2006-05-10/html/06-4319.htm
https://www.gpo.gov:/fdsys/pkg/FR-2006-08-02/html/E6-12432.htm

Python 2.7.12
Scrapy 1.2.1

```
2016-11-02 15:30:04 [scrapy] ERROR: Error downloading <GET https://www.gpo.gov:/robots.txt>: Codepoint U+003A at position 4 of u'gov:' not allowed
Traceback (most recent call last):
  File "c:\python27_internet\lib\site-packages\twisted\internet\defer.py", line 1183, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "c:\python27_internet\lib\site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "c:\python27_internet\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "c:\python27_internet\lib\site-packages\scrapy\utils\defer.py", line 45, in mustbe_deferred
    result = f(*args, **kw)
  File "c:\python27_internet\lib\site-packages\scrapy\core\downloader\handlers\__init__.py", line 65, in download_request
    return handler.download_request(request, spider)
  File "c:\python27_internet\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 60, in download_request
    return agent.download_request(request)
  File "c:\python27_internet\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 285, in download_request
    method, to_bytes(url, encoding='ascii'), headers, bodyproducer)
  File "c:\python27_internet\lib\site-packages\twisted\web\client.py", line 1596, in request
    endpoint = self._getEndpoint(parsedURI)
  File "c:\python27_internet\lib\site-packages\twisted\web\client.py", line 1580, in _getEndpoint
    return self._endpointFactory.endpointForURI(uri)
  File "c:\python27_internet\lib\site-packages\twisted\web\client.py", line 1456, in endpointForURI
    uri.port)
  File "c:\python27_internet\lib\site-packages\scrapy\core\downloader\contextfactory.py", line 59, in creatorForNetloc
    return ScrapyClientTLSOptions(hostname.decode("ascii"), self.getContext())
  File "c:\python27_internet\lib\site-packages\twisted\internet\_sslverify.py", line 1198, in __init__
    self._hostnameBytes = _idnaBytes(hostname)
  File "c:\python27_internet\lib\site-packages\twisted\internet\_sslverify.py", line 86, in _idnaBytes
    return idna.encode(text)
  File "c:\python27_internet\lib\site-packages\idna\core.py", line 355, in encode
    result.append(alabel(label))
  File "c:\python27_internet\lib\site-packages\idna\core.py", line 276, in alabel
    check_label(label)
  File "c:\python27_internet\lib\site-packages\idna\core.py", line 253, in check_label
    raise InvalidCodepoint('Codepoint {0} at position {1} of {2} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
InvalidCodepoint: Codepoint U+003A at position 4 of u'gov:' not allowed
```

**Comment by kmike** [comment]
Hm, browsers strip `:` character at the end of netloc, but it seems Python urlparse thinks this is a part of it.

**Comment by kmike** [comment]
Where did you get these URLs from? `https://www.gpo.gov/robots.txt` should work fine. But if browsers handle `https://www.gpo.gov:/robots.txt` so should Scrapy.

**Comment by redapple** [comment]
@kmike , are you thinking of fixing this in `w3lib.url.safe_url_string()` perhaps?

**Comment by kmike** [comment]
@redapple yep

**Comment by xiusir** [comment]
Browser will normalize url before sending requests.

**Comment by kmike** [comment]
@xiusir yeah, Scrapy also normalizes URL, but this particular case was missing. It is fixed in https://github.com/scrapy/w3lib/pull/78. We haven't done w3lib release though, so I'm reopening the issue (it was closed automatically when I hit 'merge' button).

**Comment by mohmad-null** [comment]
All of the URLs above were picked up by Scrapy using a simple xpath:
`response..xpath('//a/@href').extract()`

**Comment by redapple** [comment]
[w3lib v1.16](https://w3lib.readthedocs.io/en/latest/#changelog) has been released with a fix for this issue.
