### ISSUE TITLE
est() method with telnet access crash because of py3

### ISSUE THREAD

**Issue by rolele** [scrapy/scrapy#2379]
I run a spider in console (1) and try to connect using telnet access on console (2).
I run the command est() on console (2) to get back some useful metrics
```
>>> est()
```

Here is the stack, I am pretty sure it is related to the py3 migration on console (1)
```
2016-11-06 10:40:06 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2016-11-06 10:40:16 [scrapy] INFO: Crawled 3 pages (at 18 pages/min), scraped 1 items (at 6 items/min)
q2016-11-06 10:40:26 [scrapy] INFO: Crawled 6 pages (at 18 pages/min), scraped 3 items (at 12 items/min)
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/local/lib/python3.5/dist-packages/twisted/conch/telnet.py", line 636, in dataReceived
    self.applicationDataReceived(b''.join(appDataBuffer))
  File "/usr/local/lib/python3.5/dist-packages/twisted/conch/telnet.py", line 988, in applicationDataReceived
    self.protocol.dataReceived(data)
  File "/usr/local/lib/python3.5/dist-packages/twisted/conch/telnet.py", line 1035, in dataReceived
    self.protocol.dataReceived(data)
  File "/usr/local/lib/python3.5/dist-packages/twisted/conch/insults/insults.py", line 537, in dataReceived
    self.terminalProtocol.keystrokeReceived(ch, None)
  File "/usr/local/lib/python3.5/dist-packages/twisted/conch/recvline.py", line 220, in keystrokeReceived
    m()
  File "/usr/local/lib/python3.5/dist-packages/twisted/conch/recvline.py", line 369, in handle_RETURN
    return RecvLine.handle_RETURN(self)
  File "/usr/local/lib/python3.5/dist-packages/twisted/conch/recvline.py", line 287, in handle_RETURN
    self.lineReceived(line)
  File "/usr/local/lib/python3.5/dist-packages/twisted/conch/manhole.py", line 235, in lineReceived
    more = self.interpreter.push(line)
  File "/usr/local/lib/python3.5/dist-packages/twisted/conch/manhole.py", line 87, in push
    source = "\n".join(self.buffer)
builtins.TypeError: sequence item 0: expected str instance, bytes found

2016-11-06 10:40:33 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/local/lib/python3.5/dist-packages/twisted/conch/telnet.py", line 636, in dataReceived
    self.applicationDataReceived(b''.join(appDataBuffer))
  File "/usr/local/lib/python3.5/dist-packages/twisted/conch/telnet.py", line 988, in applicationDataReceived
    self.protocol.dataReceived(data)
  File "/usr/local/lib/python3.5/dist-packages/twisted/conch/telnet.py", line 1035, in dataReceived
    self.protocol.dataReceived(data)
  File "/usr/local/lib/python3.5/dist-packages/twisted/conch/insults/insults.py", line 537, in dataReceived
    self.terminalProtocol.keystrokeReceived(ch, None)
  File "/usr/local/lib/python3.5/dist-packages/twisted/conch/recvline.py", line 220, in keystrokeReceived
    m()
  File "/usr/local/lib/python3.5/dist-packages/twisted/conch/recvline.py", line 369, in handle_RETURN
    return RecvLine.handle_RETURN(self)
  File "/usr/local/lib/python3.5/dist-packages/twisted/conch/recvline.py", line 287, in handle_RETURN
    self.lineReceived(line)
  File "/usr/local/lib/python3.5/dist-packages/twisted/conch/manhole.py", line 235, in lineReceived
    more = self.interpreter.push(line)
  File "/usr/local/lib/python3.5/dist-packages/twisted/conch/manhole.py", line 87, in push
    source = "\n".join(self.buffer)
builtins.TypeError: sequence item 0: expected str instance, bytes found

2016-11-06 10:40:36 [scrapy] INFO: Crawled 8 pages (at 12 pages/min), scraped 5 items (at 12 items/min)
```

I get disconnected from the telnet console (1)
```
>>> est()Connection closed by foreign host.
```

I tried other command like engine but still got the same result 
```
>>> engineConnection closed by foreign host.
```

scrapy version
```
Scrapy 1.2.1
```
installed using ```pip3 install scrapy```

**Comment by kmike** [comment]
It is surprising you were able to run telnet at all - previously twisted.conch was not ported to Python 3, and so nor was Scrapy telnet extension.

 It seems there is some progress on manhole porting in latest Twisted version. We should take a look at it, maybe it is possible to make scrapy telnet extension working in Python 3.

**Comment by rolando** [comment]
I had the same issue. I'm able to telnet but crash with `est()`.

**Comment by rolando** [comment]
See https://github.com/scrapy/scrapy/issues/2155#issuecomment-268820758

**Comment by redapple** [comment]
The telnet console works for me with Python 3.5; Twisted 17.1+ and Scrapy 1.3.2.
@rolele , could you confirm on your end? Thanks.

**Comment by kmike** [comment]
It seems we can't fix it in Scrapy, and that it is fixed by upgrading Twisted, so I'm closing this issue.
