### ISSUE TITLE
ImportError: No module named web

### ISSUE THREAD

**Issue by cmdbdu** [scrapy/scrapy#2412]
$ scrapy --version
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 7, in <module>
    from scrapy.cmdline import execute
  File "/usr/local/lib/python2.7/dist-packages/scrapy/__init__.py", line 34, in <module>
    from scrapy.spiders import Spider
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spiders/__init__.py", line 10, in <module>
    from scrapy.http import Request
  File "/usr/local/lib/python2.7/dist-packages/scrapy/http/__init__.py", line 11, in <module>
    from scrapy.http.request.form import FormRequest
  File "/usr/local/lib/python2.7/dist-packages/scrapy/http/request/form.py", line 14, in <module>
    from scrapy.utils.response import get_base_url
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/response.py", line 10, in <module>
    from twisted.web import http
ImportError: No module named web

how ？

and the os info

 $ uname -a
Linux ubuntu 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Python 2.7.6

Ubuntu server 14.04

**Comment by cmdbdu** [comment]
You must have python-twisted-web package installed under Ubuntu

[http://stackoverflow.com/questions/19317087/twisted-web-not-found-when-importing](http://stackoverflow.com/questions/19317087/twisted-web-not-found-when-importing)
