### ISSUE TITLE
runspider failed on ubuntu

### ISSUE THREAD

**Issue by kingflight** [scrapy/scrapy#2426]
I followed the [tutorial](https://doc.scrapy.org/en/1.2/intro/overview.html) to make a simple spider on ubuntu and when I ran `scrapy runspider quotes_spider.py -o quotes.json` I got this error message:
```

Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 7, in <module>
    from scrapy.cmdline import execute
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 9, in <module>
    from scrapy.crawler import CrawlerProcess
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 7, in <module>
    from twisted.internet import reactor, defer
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/default.py", line 44, in _getInstallFunction
    from twisted.internet.epollreactor import install
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 24, in <module>
    from twisted.internet import posixbase
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 28, in <module>
    from twisted.internet._newtls import (
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 65, in <module>
    from twisted.internet._sslverify import _setAcceptableProtocols
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 204, in <module>
    verifyHostname, VerificationError = _selectVerifyImplementation(OpenSSL)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 179, in _selectVerifyImplementation
    from service_identity import VerificationError
  File "/usr/local/lib/python2.7/dist-packages/service_identity/__init__.py", line 7, in <module>
    from . import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/service_identity/pyopenssl.py", line 14, in <module>
    from .exceptions import SubjectAltNameWarning
  File "/usr/local/lib/python2.7/dist-packages/service_identity/exceptions.py", line 21, in <module>
    @attr.s
AttributeError: 'module' object has no attribute 's'

```

Twisted and service_identity are installed by  `pip install twisted` and `pip install service_identity`.

Python verison is 2.7.6

**Comment by kmike** [comment]
It happens because version of `attrs` package is not right; I'm not 100% sure, but `pip install -U attrs` could fix that. 

Based on import paths (dist-packages) it looks like you've installed Scrapy sistem-wide; usually it is a better idea to use virtualenv - with virtualenvs all packages must be installed explicitly, so there are less problems with outdated or incompatible package versions from dist-packages.

**Comment by kingflight** [comment]
`pip install -U attrs ` solves my problem. Thank you very much.
