### ISSUE TITLE
Half the time stats.get_value('finish_time') returns None

### ISSUE THREAD

**Issue by theotheo** [scrapy/scrapy#2465]
Hi there! I'm trying to add time of scraping to stats. So I create Extension class with spider_closed callback:

```
    def spider_closed(self, spider):
        stats = self.stats
        ...
        finish_time = stats.get_value('finish_time')
```

Surprisingly half the time `stats.get_value('finish_time')` returns `None`, but at the same time in the dump from `scrapy.statscollectors` finish_time is ok. 

```
2016-12-23 21:25:30 hp spider[28062] DEBUG finish_time None
2016-12-23 21:25:30 hp scrapy.utils.signal[28062] ERROR Error caught on signal handler: <bound method Ext.spider_closed of <spider.Ext object at 0x7f7358c33400>>
Traceback (most recent call last):
  File "/home/i/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/i/.local/lib/python3.5/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/home/i/LABS/FAQ/spider.py", line 117, in spider_closed
    delta = finish_time - start_time
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime'
2016-12-23 21:25:30 hp scrapy.statscollectors[28062] INFO Dumping Scrapy stats:
{'downloader/request_bytes': 5481,
 'downloader/request_count': 17,
 'downloader/request_method_count/GET': 17,
 'downloader/response_bytes': 101049,
 'downloader/response_count': 17,
 'downloader/response_status_count/200': 10,
 'downloader/response_status_count/302': 1,
 'downloader/response_status_count/404': 6,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2016, 12, 23, 18, 25, 30, 724220),
 'item_scraped_count': 9,
 'log_count/DEBUG': 21,
 'log_count/ERROR': 1,
 'log_count/INFO': 11,
 'request_depth_max': 1,
 'response_received_count': 11,
 'scheduler/dequeued': 17,
 'scheduler/dequeued/memory': 17,
 'scheduler/enqueued': 17,
 'scheduler/enqueued/memory': 17,
 'start_time': datetime.datetime(2016, 12, 23, 18, 25, 26, 649006)}
```

What I do wrong? Is it a bug?

**Comment by kmike** [comment]
`finish_time` is set by CoreStats extension on spider_closed signal; it seems the signal handler of your extension is called before CoreStats. You can change extension order using values in settings; see https://doc.scrapy.org/en/latest/topics/extensions.html

**Comment by theotheo** [comment]
Wow! Thank you for a such quick answer. I've changed loading order  and everything seems ok now.

**Comment by sfandrew** [comment]
Also found another workaround on getting the [Finish stats.](https://stackoverflow.com/questions/31210345/cant-access-the-scrapy-stats-that-are-dumped-on-finish-eg-finish-time?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)
