### ISSUE TITLE
exceptions.AttributeError: '_SIGCHLDWaker' object has no attribute 'doWrite'

### ISSUE THREAD

**Issue by cp2587** [scrapy/scrapy#2499]
Hello,

Thank your for your fantastic project. We are facing a really hard to solve bug while running scapy inside celery task. Sometimes we get this error:
```
Unhandled Error
Traceback (most recent call last):
  File "/home/wirebot/.virtualenvs/cayzn_tracking.scraping/local/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/wirebot/.virtualenvs/cayzn_tracking.scraping/local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/wirebot/.virtualenvs/cayzn_tracking.scraping/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/wirebot/.virtualenvs/cayzn_tracking.scraping/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/wirebot/.virtualenvs/cayzn_tracking.scraping/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 602, in _doReadOrWrite
    why = selectable.doWrite()
exceptions.AttributeError: '_SIGCHLDWaker' object has no attribute 'doWrite'
```
I think it's related to a threading problem (I am not sure twisted is very thread safe) but maybe you already have an explanation ? Anyway, it seems bloated to run scrapy inside celery tasks because we need to recreate the crawler for each task, do you have any good advice on how to built a system to distribute crawls ? We are open to use scrapinghub but we have some very specific pipelines & download middlewares which prevent us to do so :(

**Comment by kmike** [comment]
Hey @cp2587,

There are several third-party projects which allow to distribute crawls, e.g.:

* https://github.com/scrapinghub/frontera
* https://github.com/istresearch/scrapy-cluster
* https://github.com/rolando/scrapy-redis
* https://github.com/scrapy-plugins/scrapy-hcf

The main idea is to start multiple Scrapy spiders and override a scheduler, so that it gets URLs from a centralized source for all these spiders.

If you have a limited set of seed URLs to crawl you can also just split them into N parts and start N crawls, using e.g. https://github.com/scrapy/scrapyd to manage spiders. A similar option it to use a load-balanced https://github.com/scrapinghub/scrapyrt instance.

Parallelizing Scrapy using multiple threads doesn't make much sense because Scrapy uses event loop, so it already can download multiple requests in parallel, and threads usually don't help to scale to multiple cores in Python because of GIL.

**Comment by kc1212** [comment]
It seems Twisted is not compatible with multiprocess (if that's what celery uses). [Here](https://stackoverflow.com/questions/11272874/is-twisted-incompatible-with-multiprocessing-events-and-queues)'s a detailed explanation.

**Comment by cp2587** [comment]
Yes celery uses multiprocess but also have an eventlet implementation... 
Using celery is still the most straight forward solution for us right now because its comes with its own scheduler (celery beat) and so it's really easy to schedule a task and ensure that no more than x crawls run at the same time. Since we have a lot of spiders (more than 50), i doubt that we could all run them in the background waiting to receive new orders but maybe i am wrong ? 
On the twisted bug, i am really not sure what are the implications because we are using celery + scrapy for more than one year now and this bug doesn't seem to impact any of our crawl... Do any of you have any idea on what lead to this bug and what happen next (as i say, the spider doesn't seem to stop afterward)

I may try eventlet, @kmike do you know if scrapy/twisted can be interfaced with eventlet ?

**Comment by mou55** [comment]
It seems that the new release (3 days ago) has fixed the issue for me. can you please confirm if you are still getting that.

- https://github.com/twisted/twisted/releases/tag/twisted-17.5.0
- https://github.com/twisted/twisted/commit/c6a2e0b134a5bb56763eeb42e9fdfa9703f8f6d5

**Comment by dtrckd** [comment]
Hello,

I have exactly the same exception happening at sparse time and which seems to be unpredictable. 
The main difference is that I run spiders in my own asynchronous framework using multiprocessing lib. 

In order to help solving this issue I show how I interfaced scrapy code with multirprocessing lib: 

```python
import multiprocessing as mp

class SimpleFifo(object):
    def __init__(self):
        self._cpt = 0

    def crawl_next(self):
            def crawl_next(self):     
                spider, settings = next_params(spider, settings)
                def update_queue(aspider):
                    [...some logics....]

                crawler = Crawler(spider, settings)
                crawler.signals.connect(update_queue, signals.spider_closed)

                runner = CrawlerRunner(settings)
                runner.crawl(crawler, params, settings=settings)
                d = runner.join()
                d.addBoth(lambda _: reactor.stop())

                if self._ncrawl == 0:
                    # Seems to be already started by CrawlerProcess..
                    reactor.run()

                self._ncrawl += 1
                return True

    def next(self):
        def _next(queue):
            res = self.crawl_next()
            queue.put(res)

        q = mp.Queue()
        #q = mp.Manager().Queue() # ?
        p = mp.Process(target=_next, args=(q,))
        p.start()

        try:
            res = q.get(False)
        except mp.queues.Empty:
            res = None
                                                                                                                                                         
        return res

```

**Comment by chainstair** [comment]
I am still having issues at the moment. First I thought that it had to do with Python 3.8. I tried now with Python 3.7 and I still experience the same issues with Multiprocessing and ThreadPool.

Please get this fixed. 🙏

**Comment by wRAR** [comment]
"Twisted is not compatible with multiprocess" looks to me like the correct explanation of the problems happening so I'm not sure what should we fix this and how?
