### ISSUE TITLE
twisted error in log

### ISSUE THREAD

**Issue by whwq2012** [scrapy/scrapy#2513]
> 2017-01-19 14:41:21 [twisted] CRITICAL: Unhandled Error
> Traceback (most recent call last):
> Failure: twisted.internet.error.ConnectionDone: Connection was closed cleanly.

This is error, I check my code, and I think the error that from scrapy

scrapy version:1.30
os:centos7.0
python version: 2.7.11

**Comment by redapple** [comment]
@whwq2012 , thanks for reporting.
In fact, this error is raised at Twisted HTTP state machine level.
I've seen this happen when the webservers do not send as many bytes as they should ([this is a recent example](https://github.com/scrapy/scrapy/pull/2493#issuecomment-272294062))
Does it happen with the same website(s) all the time?
If yes, would you mind sharing some of the URL for which you see these `twisted.internet.error.ConnectionDone` messages?
A priori, it's a web server issue, but there might be something else.

**Comment by whwq2012** [comment]
@redapple 
1、There is the only bug in log, and it repeat 268 times.
2、The error happen  when my spider have ran 2 days.
3、if you need I can proive my spider code.

**Comment by whwq2012** [comment]
@redapple This is my error log. [https://drive.google.com/open?id=0B7iXisqaWzlENHFjT2ZHQzlOY0k](url).
The log contain two type of error, one is the twisted error, another is redis auth error.

**Comment by redapple** [comment]
@whwq2012 , you probably ran your crawl with LOG_LEVEL=ERROR
Unfortunately, this does not give enough information on what website you are accessing.
If you can run with LOG_LEVEL=DEBUG , it may give more information.
Your spider code may help. I will probably not run it as-is though.
I do not know if running with your custom stats collector using Redis has any influence.

**Comment by whwq2012** [comment]
@redapple OK, I try to use LOG_LEVEL=DEBUG. But please give me some time. Because my server have no transfer until next month. I will run spider in 2.1. About 2.3~2.6. I will you send you log

**Comment by redapple** [comment]
@whwq2012 , I don't know what you mean by 2.1, 2.3 and 2.6

**Comment by whwq2012** [comment]
@redapple it means February 1st, February 3rd, February 6th. Sorry My English is poor

**Comment by redapple** [comment]
Understood.

**Comment by whwq2012** [comment]
@redapple here is log. https://drive.google.com/file/d/0B7iXisqaWzlEZEd6dTlSSlNqS1U/view?usp=sharing

**Comment by redapple** [comment]
Thanks @whwq2012 ,
I'm afraid I don't know where this log line comes from, from Scrapy or not.

From your log:
```
2017-02-10 22:09:37 [requests.packages.urllib3.connectionpool] DEBUG: Starting new HTTP connection (1): taocan.ctrip.com
2017-02-10 22:09:37 [requests.packages.urllib3.connectionpool] DEBUG: http://taocan.ctrip.com:80 "GET /SH/AJAX/ScenicSpot/AjaxScenicSpotComment.aspx?sightId=137269&type=1&pageIndex=213 HTTP/1.1" 200 88
2017-02-10 22:09:37 [root] INFO: ----------------http://taocan.ctrip.com/sh/25334.html is success-----------------
2017-02-10 22:09:37 [scrapy.extensions.logstats] INFO: Crawled 5 pages (at 5 pages/min), scraped 0 items (at 0 items/min)
2017-02-10 22:09:37 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
Failure: twisted.internet.error.ConnectionDone: Connection was closed cleanly.

2017-02-10 22:09:37 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
Failure: twisted.internet.error.ConnectionDone: Connection was closed cleanly.

2017-02-10 22:09:37 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
Failure: twisted.internet.error.ConnectionDone: Connection was closed cleanly.

2017-02-10 22:09:37 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
Failure: twisted.internet.error.ConnectionDone: Connection was closed cleanly.

2017-02-10 22:09:37 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://taocan.ctrip.com/sh/198271.html> (referer: http://weekend.ctrip.com/around/nanchang/taocan)
```

I thought it was the same issue as in 
but when I try to reproduce the case of a web server not sending enough content (less than Content-Length), I see a different log:

```
2017-02-10 18:47:39 [scrapy.core.scraper] ERROR: Error downloading <GET http://localhost:8080/>
Traceback (most recent call last):
  File "/home/paul/.virtualenvs/scrapy13.py3/lib/python3.5/site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/paul/.virtualenvs/scrapy13.py3/lib/python3.5/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/paul/.virtualenvs/scrapy13.py3/lib/python3.5/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.web._newclient.ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
2017-02-10 18:47:39 [scrapy.core.engine] INFO: Closing spider (finished)
```
I get a similar error in Python 2:
```
2017-02-10 18:56:55 [scrapy.core.scraper] ERROR: Error downloading <GET http://localhost:8080/>: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
```

A couple more questions:

* what's your version of Twisted?
* what are these `[requests.packages.urllib3.connectionpool] DEBUG...`? are you mixing python-requests calls with Scrapy's asynchronous code? This can be dangerous (I'm not suggesting that this may cause `[twisted] CRITICAL: Unhandled Error`)

**Comment by redapple** [comment]
Also, what does `xiecheng.random_ua.RotateUserAgentMiddleware` do? is it makeing some asychronous networking calls?
Are you using some non-Scrapy component that issue network requests?

**Comment by lwchaoyeah** [comment]
I have meet the same error too, do you fix this ! Could you help me .
scrapy 1.5.0
Twisted 17.5.0
pyOpenSSL 17.5.0(OpenSSL 1.0.2o)
Windows-7-6.1.7601-SP1

My error log :
 DEBUG: Retrying <GET https://book.douban.com/subject/3389984/> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>]
I can't crawled any more when meet this error

[scrapy.extensions.logstats] INFO: Crawled 69 pages (at 0 pages/min), scraped 17 items (at 0 items/min)

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback for the questions raised by @redapple.

**Comment by yangkaipeng** [comment]
> Closing due to a lack o

Modified the code according to your suggestion, but it seems to have no effect

**Comment by Gallaecio** [comment]
> > Closing due to a lack o
> 
> Modified the code according to your suggestion, but it seems to have no effect

https://github.com/scrapy/scrapy/issues/2513#issuecomment-279021300

**Comment by hktalent** [comment]
me too
$ scrapy version
2022-02-18 23:00:22 [scrapy.utils.log] INFO: Scrapy 2.5.1 started (bot: pwn4scrapy)
2022-02-18 23:00:22 [scrapy.utils.log] INFO: Versions: lxml 4.6.3.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 21.7.0, Python 3.9.6 (v3.9.6:db3ff76da1, Jun 28 2021, 11:49:53) - [Clang 6.0 (clang-600.0.57)], pyOpenSSL 19.0.0 (OpenSSL 1.1.1m  14 Dec 2021), cryptography 36.0.1, Platform macOS-10.16-x86_64-i386-64bit
2022-02-18 23:00:22 [stdout] INFO: Scrapy 2.5.1

settings.py
```
USER_AGENT = 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36'

HTTPERROR_ALLOWED_CODES  =[404,200,403,500,505]
DEFAULT_REQUEST_HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.9',
    'Accept-Encoding': 'gzip, deflate, br',
    'Connection': 'close'
}
DOWNLOAD_HANDLERS_BASE = {
'https':'scrapy.core.downloader.handlers.http2.H2DownloadHandler',
}
```
