### ISSUE TITLE
Boolean setting on command line fails

### ISSUE THREAD

**Issue by pokkie** [scrapy/scrapy#2517]
When I try to run my crawler from the command line with the command:

`scrapy crawl -sROBOTSTXT_OBEY=True mycrawler`

Then I get the following error message:

`2017-01-29 00:24:24 [scrapy] INFO: Scrapy 1.2.1 started (bot: crawler)
2017-01-29 00:24:24 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'crawler.spiders', 'ROBOTSTXT_OBEY': 'True', 'SPIDER_MODULES': ['crawler.spiders'], 'BOT_NAME': 'crawler'}
2017-01-29 00:24:24 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
Unhandled error in Deferred:
2017-01-29 00:24:24 [twisted] CRITICAL: Unhandled error in Deferred:

2017-01-29 00:24:24 [twisted] CRITICAL:
Traceback (most recent call last):
File "/home/santa/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1260, in _inlineCallbacks
result = g.send(result)
File "/home/santa/.local/lib/python2.7/site-packages/scrapy/crawler.py", line 90, in crawl
six.reraise(*exc_info)
File "/home/santa/.local/lib/python2.7/site-packages/scrapy/crawler.py", line 72, in crawl
self.engine = self._create_engine()
File "/home/santa/.local/lib/python2.7/site-packages/scrapy/crawler.py", line 97, in _create_engine
return ExecutionEngine(self, lambda _: self.stop())
File "/home/santa/.local/lib/python2.7/site-packages/scrapy/core/engine.py", line 68, in __init__
self.downloader = downloader_cls(crawler)
File "/home/santa/.local/lib/python2.7/site-packages/scrapy/core/downloader/__init__.py", line 88, in __init__
self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
File "/home/santa/.local/lib/python2.7/site-packages/scrapy/middleware.py", line 58, in from_crawler
return cls.from_settings(crawler.settings, crawler)
File "/home/santa/.local/lib/python2.7/site-packages/scrapy/middleware.py", line 36, in from_settings
mw = mwcls.from_crawler(crawler)
File "/home/santa/.local/lib/python2.7/site-packages/scrapy/downloadermiddlewares/robotstxt.py", line 33, in from_crawler
return cls(crawler)
File "/home/santa/.local/lib/python2.7/site-packages/scrapy/downloadermiddlewares/robotstxt.py", line 24, in __init__
if not crawler.settings.getbool('ROBOTSTXT_OBEY'):
File "/home/santa/.local/lib/python2.7/site-packages/scrapy/settings/__init__.py", line 129, in getbool
return bool(int(self.get(name, default)))
ValueError: invalid literal for int() with base 10: 'True'`

**Comment by kmike** [comment]
This is expected; see https://github.com/scrapy/scrapy/pull/743

**Comment by pokkie** [comment]
Thanks, I have added my comments to #743

**Comment by kmike** [comment]
Thanks @pokkie!
