### ISSUE TITLE
ImportError: No module named 'twisted.persisted'

### ISSUE THREAD

**Issue by kelein** [scrapy/scrapy#2580]
I haved install scrapy on `Python 3.5.2`, but when I exeute `scrapy -v` on command-line, it occurs:
```
>> scrapy -v
Traceback (most recent call last):
  File "/usr/bin/scrapy", line 7, in <module>
    from scrapy.cmdline import execute
  File "/usr/local/python3.5.2/lib/python3.5/site-packages/scrapy/__init__.py", line 27, in <module>
    from . import _monkeypatches
  File "/usr/local/python3.5.2/lib/python3.5/site-packages/scrapy/_monkeypatches.py", line 20, in <module>
    import twisted.persisted.styles  # NOQA
ImportError: No module named 'twisted.persisted'
```
So I enter ipython3 to ensure whether it's installed porperly:
```
In [2]: import twisted
In [3]: twisted.version
Out[3]: Version('twisted', 15, 2, 1)
```
But when I `import scrapy`, the same as command-line:
```
In [4]: import scrapy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-51c73a18167b> in <module>()
----> 1 import scrapy

/usr/local/python3.5.2/lib/python3.5/site-packages/scrapy/__init__.py in <module>()
     25 
     26 # Apply monkey patches to fix issues in external libraries
---> 27 from . import _monkeypatches
     28 del _monkeypatches
     29 

/usr/local/python3.5.2/lib/python3.5/site-packages/scrapy/_monkeypatches.py in <module>()
     18 # Undo what Twisted's perspective broker adds to pickle register
     19 # to prevent bugs like Twisted#7989 while serializing requests
---> 20 import twisted.persisted.styles  # NOQA
     21 # Remove only entries with twisted serializers for non-twisted types.
     22 for k, v in frozenset(copyreg.dispatch_table.items()):

ImportError: No module named 'twisted.persisted'
```

I'm so confused, I just want to run a spaider, So help me ! :sos:

**Comment by kmike** [comment]
Could you try installing Scrapy in virtualenv (see https://doc.scrapy.org/en/latest/intro/install.html#using-a-virtual-environment-recommended)?

**Comment by Keleir** [comment]
> Could you try installing Scrapy in virtualenv (see https://doc.scrapy.org/en/latest/intro/install.html#using-a-virtual-environment-recommended)?

@kmike I have try to create a venv with `virtualenv -p /usr/bin/python3 even` then active it, then I install scrapy with pip, it remind me to install Twisted, so i did it.
This is my pip freeze output with the venv, as follow:
```
(even) pip freeze
appdirs==1.4.0
attrs==16.3.0
cffi==1.9.1
cryptography==1.7.2
cssselect==1.0.1
idna==2.2
lxml==3.7.3
packaging==16.8
parsel==1.1.0
pyasn1==0.2.2
pyasn1-modules==0.0.8
pycparser==2.17
PyDispatcher==2.0.5
pyOpenSSL==16.2.0
pyparsing==2.1.10
queuelib==1.4.2
Scrapy==1.3.2
service-identity==16.0.0
six==1.10.0
Twisted==15.2.1
w3lib==1.17.0
zope.interface==4.3.3
```
And I want to ensure it on python command-line in venv:
```
(even) python
Python 3.5.2 (default, Nov 30 2016, 21:34:19) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import twisted
>>> import scrapy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/KALLEN/even/lib/python3.5/site-packages/scrapy/__init__.py", line 27, in <module>
    from . import _monkeypatches
  File "/opt/KALLEN/even/lib/python3.5/site-packages/scrapy/_monkeypatches.py", line 20, in <module>
    import twisted.persisted.styles  # NOQA
  File "/root/SOFTS/Packages/Twisted-15.2.1/twisted/persisted/styles.py", line 13, in <module>
    import copy_reg
ImportError: No module named 'copy_reg'
>>>
```
Nothing works.

**Comment by kmike** [comment]
@Keleir something is not right - it shouldn't have asked you to install twisted, it should have installed it automatically. Import paths at the ImportError don't make any sense to me - it still tries to import Twisted from /root/SOFTS/..., not from the virtualenv.

**Comment by kmike** [comment]
Twisted 15.2.1 is not supported by Scrapy, and it is Python 2-only, so it is not surprising it doesn't work in Python 3 environment. But it is not clear for me why isn't a right version of Twisted installed automatically. Could you paste a full log of command line - how you create a virtualenv, install scrapy, etc., with the output?

**Comment by Keleir** [comment]
@kmike Today I'm try to reinstall Twisted as the version `16.3.0`, and it works. I did it as following:
```
wget https://pypi.python.org/packages/c0/7c/c1e5b61e30b7ffc96576d2a922615c8068e6996a622be813fc626cef07aa/Twisted-16.3.0.tar.bz2#md5=e044af844623e9fbcbe29f578db6053a
tar jxvf Twisted-16.3.0.tar.bz2
cd Twisted-16.3.0
python3 setup.py install
```
Add then the `scrapy -v` is enable:
```
Scrapy 1.3.2 - no active project

Usage:
  scrapy <command> [options] [args]

Available commands:
  bench         Run quick benchmark test
  commands      
  fetch         Fetch a URL using the Scrapy downloader
  genspider     Generate new spider using pre-defined templates
  runspider     Run a self-contained spider (without creating a project)
  settings      Get settings values
  shell         Interactive scraping console
  startproject  Create new project
  version       Print Scrapy version
  view          Open URL in browser, as seen by Scrapy

  [ more ]      More commands available when run from project directory

Use "scrapy <command> -h" to see more info about a command
```
I didn't know what is the differences between `Twisted-16.3.0` and `Twisted-15.2.1` :question:

**Comment by kmike** [comment]
Why do you have to install Twisted this way? Isn't just `pip install twisted` (or `pip install -U scrapy`) working?

**Comment by Keleir** [comment]
@kmike When I user pip to install `scrapy`, the output is:
```
>> pip3 install scrapy
Collecting scrapy
  Using cached Scrapy-1.3.2-py2.py3-none-any.whl
Requirement already satisfied: six>=1.5.2 in /usr/local/python3.5.2/lib/python3.5/site-packages (from scrapy)
Collecting service-identity (from scrapy)
  Downloading service_identity-16.0.0-py2.py3-none-any.whl
Collecting parsel>=1.1 (from scrapy)
  Using cached parsel-1.1.0-py2.py3-none-any.whl
Collecting pyOpenSSL (from scrapy)
  Using cached pyOpenSSL-16.2.0-py2.py3-none-any.whl
Collecting Twisted>=13.1.0 (from scrapy)
  Could not find a version that satisfies the requirement Twisted>=13.1.0 (from scrapy) (from versions: )
No matching distribution found for Twisted>=13.1.0 (from scrapy)
```
So I install `twisted` with pip, the output is:
```
>> pip3 install twisted
Collecting twisted
  Could not find a version that satisfies the requirement twisted (from versions: )
No matching distribution found for twisted
```
Due to this, I install `twisted` through a source tar package.

**Comment by kmike** [comment]
I think this is the same issue as https://github.com/scrapy/scrapy/issues/2563

**Comment by kmike** [comment]
I've opened a ticket in twisted bug tracker: http://twistedmatrix.com/trac/ticket/9046

**Comment by rolando** [comment]
@Keleir try using `conda`, see https://conda.io/docs/install/quick.html and https://doc.scrapy.org/en/latest/intro/install.html#anaconda

**Comment by Keleir** [comment]
@rolando Thanks a lot ! `Conda` is useful, my pip works again after installing conda. And it's easy to install scrapy just by `conda install scrapy`. :+1:
