### ISSUE TITLE
Misleading error message about SPIDER_MODULES

### ISSUE THREAD

**Issue by djunzu** [scrapy/scrapy#2602]
This is a side effect from #2433.

```
Traceback (most recent call last):
  File "/home/djunzu/.pyenv/versions/2.7.13/lib/python2.7/site-packages/scrapy/spiderloader.py", line 31, in _load_all_spiders
    for module in walk_modules(name):
  File "/home/djunzu/.pyenv/versions/2.7.13/lib/python2.7/site-packages/scrapy/utils/misc.py", line 63, in walk_modules
    mod = import_module(path)
  File "/home/djunzu/.pyenv/versions/2.7.13/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/djunzu/crawler/crawler/spiders/__init__.py", line 4, in <module>
    from crawler.loaders import PersonLoader
  File "/home/djunzu/crawler/crawler/loaders.py", line 4, in <module>
    from processors.phone import PhoneOutputProcessor, extract_phone
ImportError: cannot import name extract_phone
Could not load spiders from module 'crawler.spiders.development'. Check SPIDER_MODULES setting
  warnings.warn(msg, RuntimeWarning)
```

"Check SPIDER_MODULES setting" is misleading; the error has nothing to do with `SPIDER_MODULES`.

I would suggest to remove this sentence.

(And I guess the last line should not be there, but it shows up in log.)

**Comment by redapple** [comment]
hi @djunzu , indeed, "Check SPIDER_MODULES setting" is not always relevant (see https://github.com/scrapy/scrapy/pull/2433#issuecomment-279451719)

**Comment by djunzu** [comment]
@redapple , [#2433 (comment)](https://github.com/scrapy/scrapy/pull/2433#issuecomment-279451719) is a slightly different problem. Removing message "Check SPIDER_MODULES setting" would not solve his problem. But I think removing it would still solve #2430 (one can clearly see that the problem is "Could not load spiders from module 'crawler.spiders'") and other errors (like a fail to import a loader in the spider itself) would not mislead to the wrong place. What do you think?

I mean, let everything as it is but remove just "Check SPIDER_MODULES setting" from the message.

**Comment by wRAR** [comment]
The message was reworded in #2632.
