### ISSUE TITLE
Scapry does not work with Twisted version 17.1.0

### ISSUE THREAD

**Issue by DarrenWickham** [scrapy/scrapy#2606]
2017-02-28 16:00:20 [scrapy] ERROR: Error downloading <GET >
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 45, in mustbe_deferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/downloader/handlers/__init__.py", line 41, in download_request
    return handler(request, spider)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/downloader/handlers/http11.py", line 44, in download_request
    return agent.download_request(request)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/downloader/handlers/http11.py", line 211, in download_request
    d = agent.request(method, url, headers, bodyproducer)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/client.py", line 1631, in request
    parsedURI.originForm)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/client.py", line 1408, in _requestWithEndpoint
    d = self._pool.getConnection(key, endpoint)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/client.py", line 1294, in getConnection
    return self._newConnection(key, endpoint)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/client.py", line 1306, in _newConnection
    return endpoint.connect(factory)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/endpoints.py", line 1958, in connect
    self._wrapperFactory(protocolFactory)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/endpoints.py", line 788, in connect
    EndpointReceiver, self._hostText, portNumber=self._port
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_resolver.py", line 174, in resolveHostName
    onAddress = self._simpleResolver.getHostByName(hostName)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/resolver.py", line 21, in getHostByName
    d = super(CachingThreadedResolver, self).getHostByName(name, timeout)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 276, in getHostByName
    timeoutDelay = sum(timeout)
TypeError: 'float' object is not iterable

Downgrading to Twisted 16.6.0 solved the issue for now

**Comment by kmike** [comment]
Which Scrapy version are you using?

**Comment by DarrenWickham** [comment]
Scrapy==1.0.5

**Comment by kmike** [comment]
Scrapy 1.0.x is no longer supported; current version is 1.3.2, and it should work with Twisted 17.1.0.

If you're using older Scrapy it is always a good idea to pin other requirements, not only Scrapy version.

I'm closing this issue because we won't be fixing it for 1.0.x.

Thanks for the heads up! I think this ticket could be helpful for Scrapy 1.0.x users who face the same issue - the solution is to either upgrade Scrapy or downgrade Twisted (as you suggested).

**Comment by DarrenWickham** [comment]
Thank you for help.
