### ISSUE TITLE
After adding request flags subclasses of logformatter that rely on 'flags' format string are broken

### ISSUE THREAD

**Issue by pawelmhm** [scrapy/scrapy#2647]
#2082 added flags to request but it also renamed formatting string key from flags to response_flags/request_flags
```
CRAWLEDMSG = u"Crawled (%(status)s) %(request)s (referer: %(referer)s)%(flags)s"
 +CRAWLEDMSG = u"Crawled (%(status)s) %(request)s%(request_flags)s (referer: %(referer)s)%(response_flags)s" 
```

Scrapy allows you to override logformatter and this is what I have in my project. I have logformatter looking rouhgly like this

```python
# dirbot/logf.py
from scrapy.logformatter import LogFormatter


class CustomLogFormatter(LogFormatter):
    def crawled(self, request, response, spider):
        kwargs = super(CustomLogFormatter, self).crawled(
            request, response, spider)
        kwargs['msg'] = (
            u"Crawled (%(status)s) %(request)s "
            u"(referer: %(referer)s, latency: %(latency).2f s)%(flags)s"
        )
        kwargs['args']['latency'] = response.meta.get('download_latency', 0)
        return kwargs
```

now if you enable it in settings `LOG_FORMATTER = 'dirbot.logf.CustomLogFormatter'
` and  try to run it with recent master you'll get KeyError

```
2017-03-13 14:15:26 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
KeyError: u'flags'
Logged from file engine.py, line 238
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
KeyError: u'flags'
Logged from file engine.py, line 238
2017-03-13 14:15:27 [scrapy.core.scraper] DEBUG: Scraped from <200 http://www.dmoz.org/Computers/Programming/Languages/Python/Resources/>
```

So this change that renamed `flags` to `response_flags/request_flags` seems backward incompatible.

**Comment by kmike** [comment]
What do you think about adding 'flags' as an alias?

**Comment by pawelmhm** [comment]
what exactly do you mean @kmike

**Comment by kmike** [comment]
Will passing 'flags' in addition to 'request_flags` [here](https://github.com/scrapy/scrapy/blob/cfb56400b29316a43208053a8ef6d48eb0eb499e/scrapy/logformatter.py#L43) fix it for you?

**Comment by pawelmhm** [comment]
ah yeah that fixes it and looks super simple, should I create patch with unit test or you'd like to fix it

**Comment by kmike** [comment]
Please go on with a pull request! 👍
