### ISSUE TITLE
http11 connections are left opened

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#2653]
I haven't checked it, but there is a https://github.com/scrapy/scrapy/pull/999#discussion_r105122341 by @adiroiban  which suggests HTTP11DownloadHandler.close implementation is not complete.

**Comment by adiroiban** [comment]
Yes. So if the connection will take to long to be closed... the callback used by scrappy to signal that the connection was closed is triggered, but the connection itself is not aborted. 

In the event of a force connection, there should be a call to `self.transport.abortConnection()` which will force closing it and will not wait for a complete TLS shutdown sequence.

**Comment by redapple** [comment]
I'm not sure this is to be dealt with at Scrapy level.

Scrapy `HTTP11DownloadHandler.close()` calls `HTTPConnectionPool.closeCachedConnections()`,
which (with Twisted 17.1 at least, I haven't checked previous versions), calls [`HTTP11ClientProtocol.abort()`](https://github.com/twisted/twisted/blob/dc9880d605d7f3f7610081298a9438c252831351/src/twisted/web/client.py#L1354),
which calls [`transport.loseConnection()`](https://github.com/twisted/twisted/blob/dc9880d605d7f3f7610081298a9438c252831351/src/twisted/web/_newclient.py#L1639)

Twisted docs mention [only this `.closeCachedConnections()` method](https://twistedmatrix.com/documents/current/web/howto/client.html#multiple-connections-to-the-same-server)

I can see with Wireshark that under normal conditions (well-behaving remote web servers), the TCP connection is closed when `HTTP11DownloadHandler.close()` is called.
(I don't know how to reproduce the web server behavior for https://github.com/scrapy/scrapy/issues/985)

@adiroiban , if you are suggesting to change `self.transport.loseConnection()` with `self.transport.abortConnection()` in `HTTP11ClientProtocol.abort()`, I think it needs to be requested to Twisted.
Am I missing something?

**Comment by adiroiban** [comment]
In an ideal world, Scrapy should not deal with this at all and it would only need to call `closeCachedConnections`.

But the implementation in Twisted is not ideal, and if a server fails to complete the TLS shutdown, the connection is left hanging..

I assume that this is why in Scrapy you have this timeout ... and if you want the timeout I assume that you also want to close the connection for real.

------------

The ideal fix, is to fix this in Twisted so that you don't need to add a custom timeout each time you call closeCachedConnection.

Here is the discussion about how and where to fix it.

http://twistedmatrix.com/pipermail/twisted-python/2017-March/031290.html

**Comment by redapple** [comment]
Thanks for the feedback @adiroiban .
I believe the timeout in Scrapy was to not have the engine hanging waiting for the confirmation of close, more than for fiddling with the TCP/TLS connection at a lower level.
It looks like the conversation in Twisted channels is quite active.
I'm confident they'll address the issue soon enough. And we can then remove the timeout on our end.

**Comment by adiroiban** [comment]
yep. It make sense to fix it in Twisted. Feel free to close it.

I only wanted to send a comment in the case in which you care for the low level connections :)

**Comment by walkerqt** [comment]
Anyone else care about this issue?
I am being troubled by this problem.
`Python 3.6.7`
`Scrapy 1.7.3`
`Twisted 19.7.0`

**Comment by walkerqt** [comment]
- Did Scrapy 2.0 solve the problem?

- If it is twisted problem, can it be replaced by asyncio?

**Comment by Gallaecio** [comment]
> If it is twisted problem, can it be replaced by asyncio?

You can use asyncio with Scrapy 2.0. I am not sure that it will fix it, though. It is still using Twisted.

**Comment by qbit-git** [comment]
> You can use asyncio with Scrapy 2.0. I am not sure that it will fix it, though. It is still using Twisted.

I try to add this to settings.py
```
TWISTED_REACTOR = 'twisted.internet.asyncioreactor.AsyncioSelectorReactor'
```
report error
```
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\scrapy.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\scrapy\cmdline.py", line 144, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "c:\python38\lib\site-packages\scrapy\crawler.py", line 265, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "c:\python38\lib\site-packages\scrapy\crawler.py", line 141, in __init__
    self._handle_twisted_reactor()
  File "c:\python38\lib\site-packages\scrapy\crawler.py", line 328, in _handle_twisted_reactor
    install_reactor(self.settings["TWISTED_REACTOR"])
  File "c:\python38\lib\site-packages\scrapy\utils\reactor.py", line 58, in install_reactor
    asyncioreactor.install(asyncio.get_event_loop())
  File "c:\python38\lib\site-packages\twisted\internet\asyncioreactor.py", line 320, in install
    reactor = AsyncioSelectorReactor(eventloop)
  File "c:\python38\lib\site-packages\twisted\internet\asyncioreactor.py", line 69, in __init__
    super().__init__()
  File "c:\python38\lib\site-packages\twisted\internet\base.py", line 571, in __init__
    self.installWaker()
  File "c:\python38\lib\site-packages\twisted\internet\posixbase.py", line 286, in installWaker
    self.addReader(self.waker)
  File "c:\python38\lib\site-packages\twisted\internet\asyncioreactor.py", line 151, in addReader
    self._asyncioEventloop.add_reader(fd, callWithLogger, reader,
  File "c:\python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
```
environment
```
Windows 10
Python 3.8.2
Scrapy 2.0.0
Twisted 19.10.0
```

**Comment by Gallaecio** [comment]
Wow, https://twistedmatrix.com/trac/ticket/9766

https://github.com/scrapy/scrapy/issues/4306 might help once implemented, allow to workaround that Twisted issue.

**Comment by esingtse** [comment]
> yep. It make sense to fix it in Twisted. Feel free to close it.
> 
> I only wanted to send a comment in the case in which you care for the low level connections :)

Did Scrapy 2.4 solve the problem?

I find my server has more than 80000+ socket  connection in `/proc/2666/fd`, most results show a socket connection 3 days or even a week ago.Isn't the connection that TCP establishes will released after the TLS?

**Comment by esingtse** [comment]
btw, my scrapy version is 2.3, python3.8

I use custom proxy middleware:
```
class BaseProxyMiddleware(object):
    def __init__(self, settings):
        self.proxy_key = settings.get("PROXY_KEY") if settings.get("PROXY_KEY") else PROXY_KEY_HASH_COMMON
        self.proxy_skip = settings.getbool("PROXY_SKIP")

    @classmethod
    def from_crawler(cls, crawler):
        return cls(crawler.settings)

    def process_request(self, request, spider):
        if self.proxy_skip or config.TESTING:
            return
        ip_dic = self.get_ip()
        if ip_dic:
            proxy_server = "http://" + ip_dic.get("ip")
            request.meta["proxy"] = proxy_server
            request.meta["proxy_source"] = ip_dic.get("proxy_source")
            spider.logger.info(f"Get proxy {proxy_server} from {ip_dic.get('proxy_source')}")
            return

        
        spider.logger.warning("Get poxy failed, return request")
        return request

    def get_ip(self):
        return get_ip(self.proxy_key)
```

**Comment by PATAPOsha** [comment]
I think I solved it with manually calling `spider.crawler.engine.downloader.handlers._handlers["https"].close()`.
At least my "proxy issue" is solved.
But I'm not sure if it is safe. I only call it on retry inside overriden `RetryMiddleware._retry()`.
