### ISSUE TITLE
Enable DOWNLOADER_MIDDLEWARES  has error for mac

### ISSUE THREAD

**Issue by littlestar1998** [scrapy/scrapy#2693]
```
> scrapy version -v

Scrapy    : 1.3.0
lxml      : 3.7.2.0
libxml2   : 2.9.4
cssselect : 1.0.1
parsel    : 1.1.0
w3lib     : 1.16.0
Twisted   : 16.6.0
Python    : 2.7.10 (default, Jul 30 2016, 19:40:32) - [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
pyOpenSSL : 16.2.0 (OpenSSL 1.0.2j  26 Sep 2016)
Platform  : Darwin-16.4.0-x86_64-i386-64bit
```
Python 2.7.10

But i disable DOWNLOADER_MIDDLEWARES on settings.py  it's ok not error;

enable 
```python
DOWNLOADER_MIDDLEWARES = {
    'tutorial.middlewares.MyCustomDownloaderMiddleware': 543,
}
```
on settings.py 

run again has error

demo
```
xiaoxingxingdeMacBook-Pro:tutorial xiaoxingxing$ scrapy crawl dmoz
2017-04-01 17:49:34 [scrapy.utils.log] INFO: Scrapy 1.3.0 started (bot: tutorial)
2017-04-01 17:49:34 [scrapy.utils.log] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'tutorial.spiders', 'SPIDER_MODULES': ['tutorial.spiders'], 'ROBOTSTXT_OBEY': True, 'BOT_NAME': 'tutorial'}
2017-04-01 17:49:34 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
Unhandled error in Deferred:
2017-04-01 17:49:34 [twisted] CRITICAL: Unhandled error in Deferred:

2017-04-01 17:49:34 [twisted] CRITICAL:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/Library/Python/2.7/site-packages/scrapy/crawler.py", line 90, in crawl
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/scrapy/crawler.py", line 72, in crawl
    self.engine = self._create_engine()
  File "/Library/Python/2.7/site-packages/scrapy/crawler.py", line 97, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/Library/Python/2.7/site-packages/scrapy/core/engine.py", line 69, in __init__
    self.downloader = downloader_cls(crawler)
  File "/Library/Python/2.7/site-packages/scrapy/core/downloader/__init__.py", line 88, in __init__
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "/Library/Python/2.7/site-packages/scrapy/middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/Library/Python/2.7/site-packages/scrapy/middleware.py", line 34, in from_settings
    mwcls = load_object(clspath)
  File "/Library/Python/2.7/site-packages/scrapy/utils/misc.py", line 49, in load_object
    raise NameError("Module '%s' doesn't define any object named '%s'" % (module, name))
NameError: Module 'tutorial.middlewares' doesn't define any object named 'MyCustomDownloaderMiddleware'
```

**Comment by pawelmhm** [comment]
Error complains that you dont have object `MyCustomDownloaderMiddleware`. You need to have this Python object in module tutorial/middleware and Scrapy must be able to import it from there. It doesn't look like Scrapy bug.

**Comment by littlestar1998** [comment]
but i only enable 
```
SPIDER_MIDDLEWARES = {
    'tutorial.middlewares.TutorialSpiderMiddleware': 543,
}
```
the TutorialSpiderMiddleware exit middlewares.py

has this error

```
017-04-04 23:22:33 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'tutorial.middlewares.TutorialSpiderMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2017-04-04 23:22:33 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2017-04-04 23:22:33 [scrapy.core.engine] INFO: Spider opened
Unhandled error in Deferred:
2017-04-04 23:22:33 [twisted] CRITICAL: Unhandled error in Deferred:

2017-04-04 23:22:33 [twisted] CRITICAL:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/site-packages/scrapy/crawler.py", line 90, in crawl
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/scrapy/crawler.py", line 74, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
TypeError: process_start_requests() takes exactly 2 arguments (3 given)
```

**Comment by redapple** [comment]
@littlestar1998 , this error comes from your `TutorialSpiderMiddleware` 's `process_start_requests()` method, how it takes parameters.
I suggest that you move this question to [StackOverflow](https://stackoverflow.com/) (with tag "scrapy") as this does not look like a Scrapy bug per-se.
Thanks.
