### ISSUE TITLE
error at telnet shutdown in Python 3

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#2702]
Scrapy version:

```
Scrapy    : 1.3.3
lxml      : 3.7.3.0
libxml2   : 2.9.3
cssselect : 1.0.1
parsel    : 1.1.0
w3lib     : 1.17.0
Twisted   : 17.1.0
Python    : 3.5.2 (default, Nov 17 2016, 17:05:23) - [GCC 5.4.0 20160609]
pyOpenSSL : 0.15.1 (OpenSSL 1.0.2g  1 Mar 2016)
Platform  : Linux-4.4.0-59-generic-x86_64-with-Ubuntu-16.04-xenial
```

I've got this exception on shutdown:

```
2017-04-05 18:18:10 [scrapy.core.engine] INFO: Spider closed (finished)
2017-04-05 18:18:10 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method TelnetConsole.stop_listening of <scrapy.extensions.telnet.TelnetConsole object at 0x7fbb993bfeb8>>
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/scrapy/extensions/telnet.py", line 63, in stop_listening
    self.port.stopListening()
AttributeError: 'TelnetConsole' object has no attribute 'port'
```

Not sure if it is a real problem, but it'd be nice to shut down without error messages. No idea how to reproduce it, I've only seen it once.

**Comment by timfeirg** [comment]
I'm using scrapy 1.3.3 with python 3.6.1, didn't see this while using the telnet console

**Comment by cclauss** [comment]
This would happen if the TelnetConsole was [initialzed](https://github.com/scrapy/scrapy/blob/master/scrapy/extensions/telnet.py#L39) but never had its [start_listening()](https://github.com/scrapy/scrapy/blob/master/scrapy/extensions/telnet.py#L39) method called because self.port is currently not defined in the former but is only defined in the latter.

Fix proposed in #2892

**Comment by Gallaecio** [comment]
Should we close this until there is a way to reproduce it?

**Comment by cclauss** [comment]
As discussed above, there is a way of reproducing it.  Initialize the TelnetConsole but do not call its `.start_listening()` method.

**Comment by Gallaecio** [comment]
> I don't understand why the error happens in a first place - why can start_listening call be missed
https://github.com/scrapy/scrapy/pull/2892#issuecomment-340736088

**Comment by Gallaecio** [comment]
@cclauss My understanding is that the original issue was triggered without manually interacting with the `TelnetConsole` class. So there is no human interaction with the class itself. Which means that the root issue most likely could be (or have been?) in some other code that directly or indirectly handles the `TelnetConsole` class. And https://github.com/scrapy/scrapy/pull/6224 would hide that issue (again, if such an issue currently exists, which is not clear).

**Comment by cclauss** [comment]
The original request was:
> Not sure if it is a real problem, but it'd be nice to shut down without error messages. No idea how to reproduce it, I've only seen it once.

I broke that down into two requests:
> it'd be nice to shut down without error messages

That was #2892

> No idea how to reproduce it

That was #6224 

If you do not want questions answered then please refrain from opening issues.
