### ISSUE TITLE
Inconsistency while crawling few URLS. ( out of 115 urls i was able to crawl over 108).

### ISSUE THREAD

**Issue by rohitp3** [scrapy/scrapy#2715]
**Log messages for one such URL which I am not able to crawl**

G:\webc\tut>scrapy crawl painting
2017-04-24 03:59:32 [scrapy.utils.log] INFO: Scrapy 1.3.2 started (bot: tut)
2017-04-24 03:59:32 [scrapy.utils.log] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'tut.spiders', 'SPIDER_MODULES': ['tut.spiders'], 'ROBOTSTXT_OBEY': True, 'BOT_NAME': 'tut'}
2017-04-24 03:59:32 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2017-04-24 03:59:32 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2017-04-24 03:59:32 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2017-04-24 03:59:32 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2017-04-24 03:59:32 [scrapy.core.engine] INFO: Spider opened
2017-04-24 03:59:32 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2017-04-24 03:59:32 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6024
2017-04-24 03:59:33 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.saatchiart.com/robots.txt> (referer: None)
2017-04-24 03:59:33 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.saatchiart.com/art/Painting-silence-waters-13/891427/3273220/view> (referer: None)
2017-04-24 03:59:33 **[scrapy.core.scraper] ERROR: Spider error processing <GET https://www.saatchiart.com/art/Painting-silence-waters-13/891427/3273220/view>** (referer: None)
Traceback (most recent call last):
  File "C:\Users\Rohit\AppData\Roaming\Python\Python27\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "G:\webc\tut\tut\spiders\Paintings_spider.py", line 40, in parse
    f.write(str(paintingname)+","+str(("".join(str(e).replace("\n","") for e in authorname).replace(",","").replace("[u'","")).replace("']",""))+","+str(authorcountry)+","+str(sizeheight).replace("H","")+","+str(sizeWidth).replace("W","")+","+str(sizedepth)+","+str(((price).replace(",","")).replace("\n","")).replace("$","")+","+str(views)+","+str(favorites)+","+str(publisheddate)+","+str(modifieddate)+","+str(" ".join(str(e).replace("\n","") for e in paintingtype)).replace("\n","")+","+str(paintingimage)+","+str(Authorurl)+"\n")
  File "G:\webc\tut\tut\spiders\Paintings_spider.py", line 40, in <genexpr>
    f.write(str(paintingname)+","+str(("".join(str(e).replace("\n","") for e in authorname).replace(",","").replace("[u'","")).replace("']",""))+","+str(authorcountry)+","+str(sizeheight).replace("H","")+","+str(sizeWidth).replace("W","")+","+str(sizedepth)+","+str(((price).replace(",","")).replace("\n","")).replace("$","")+","+str(views)+","+str(favorites)+","+str(publisheddate)+","+str(modifieddate)+","+str(" ".join(str(e).replace("\n","") for e in paintingtype)).replace("\n","")+","+str(paintingimage)+","+str(Authorurl)+"\n")
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdf' in position 9: ordinal not in range(128)
2017-04-24 03:59:33 [scrapy.core.engine] INFO: Closing spider (finished)
2017-04-24 03:59:33 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 553,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 26470,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 2,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2017, 4, 24, 7, 59, 33, 946000),
 'log_count/DEBUG': 3,
 'log_count/ERROR': 1,
 'log_count/INFO': 7,
 'response_received_count': 2,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'spider_exceptions/UnicodeEncodeError': 1,
 'start_time': datetime.datetime(2017, 4, 24, 7, 59, 32, 691000)}
2017-04-24 03:59:33 [scrapy.core.engine] INFO: Spider closed (finished)

**Comment by kmike** [comment]
Hi @rohitp3,

There is an exception in the log, and the exception is raised by your spider, not by Scrapy. I suggest debugging and fixing it first. Likely unicode handling is not correct in your case: str converts a value to bytes in Python2, using sys.getdefaultencoding, and likely this fails if there is non-ascii unicode data. We're using Scrapy issue tracker to track Scrapy bugs; you may get better help at [scrapy-users](https://groups.google.com/forum/?fromgroups#!forum/scrapy-users) mailing list, or at https://stackoverflow.com (use "Scrapy" tag when asking a question).

**Comment by rohitp3** [comment]
Hi @kmike
Sorry about raising an Issue. I am new to Python and Scrapy. I thought the code I wrote was correct as I was able to crawl other urls except few.
Thank a lot for that information.
