### ISSUE TITLE
DNSLookupError raises on request cyrillic domains

### ISSUE THREAD

**Issue by shoreward** [scrapy/scrapy#2728]
Hello

I had an error when requesting Cyrillic domains

`scrapy shell 'шанти-шанти.рф'`

```
  File "/www/.venv/lib/python2.7/site-packages/scrapy/shell.py", line 115, in fetch
    reactor, self._schedule, request, spider)
  File "/www/.venv/lib/python2.7/site-packages/twisted/internet/threads.py", line 122, in blockingCallFromThread
    result.raiseException()
  File "<string>", line 2, in raiseException
twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: xn----7sbb4ac0ad0be6cf.xn--p1ai.
```

**Comment by kmike** [comment]
This example works fine on my machine. 
Could you please paste `scrapy version -v` output? 
Are you sure it is not an issue with your DNS setup?

**Comment by redapple** [comment]
I can reproduce this on my local machine:

```
$ scrapy version -v
Scrapy    : 1.3.3
lxml      : 3.7.3.0
libxml2   : 2.9.3
cssselect : 1.0.1
parsel    : 1.1.0
w3lib     : 1.17.0
Twisted   : 17.1.0
Python    : 2.7.12 (default, Nov 19 2016, 06:48:10) - [GCC 5.4.0 20160609]
pyOpenSSL : 17.0.0 (OpenSSL 1.0.2g  1 Mar 2016)
Platform  : Linux-4.8.0-51-generic-x86_64-with-Ubuntu-16.10-yakkety

$ scrapy shell 'шанти-шанти.рф'
2017-05-10 13:45:41 [scrapy.utils.log] INFO: Scrapy 1.3.3 started (bot: scrapybot)
(...)
2017-05-10 13:45:41 [scrapy.core.engine] INFO: Spider opened
2017-05-10 13:45:42 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://xn----7sbb4ac0ad0be6cf.xn--p1ai> (failed 1 times): DNS lookup failed: no results for hostname lookup: xn----7sbb4ac0ad0be6cf.xn--p1ai.
2017-05-10 13:45:42 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://xn----7sbb4ac0ad0be6cf.xn--p1ai> (failed 2 times): DNS lookup failed: no results for hostname lookup: xn----7sbb4ac0ad0be6cf.xn--p1ai.
2017-05-10 13:45:42 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET http://xn----7sbb4ac0ad0be6cf.xn--p1ai> (failed 3 times): DNS lookup failed: no results for hostname lookup: xn----7sbb4ac0ad0be6cf.xn--p1ai.
Traceback (most recent call last):
  File "/home/paul/.virtualenvs/scrapy13/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/home/paul/.virtualenvs/scrapy13/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 142, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/home/paul/.virtualenvs/scrapy13/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 88, in _run_print_help
    func(*a, **kw)
  File "/home/paul/.virtualenvs/scrapy13/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 149, in _run_command
    cmd.run(args, opts)
  File "/home/paul/.virtualenvs/scrapy13/local/lib/python2.7/site-packages/scrapy/commands/shell.py", line 73, in run
    shell.start(url=url, redirect=not opts.no_redirect)
  File "/home/paul/.virtualenvs/scrapy13/local/lib/python2.7/site-packages/scrapy/shell.py", line 48, in start
    self.fetch(url, spider, redirect=redirect)
  File "/home/paul/.virtualenvs/scrapy13/local/lib/python2.7/site-packages/scrapy/shell.py", line 115, in fetch
    reactor, self._schedule, request, spider)
  File "/home/paul/.virtualenvs/scrapy13/local/lib/python2.7/site-packages/twisted/internet/threads.py", line 122, in blockingCallFromThread
    result.raiseException()
  File "<string>", line 2, in raiseException
twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: xn----7sbb4ac0ad0be6cf.xn--p1ai.
```

Opening https://шанти-шанти.рф in my Chrome browser (Version 58.0.3029.110 (64-bit)) works fine.

**Comment by kmike** [comment]
@redapple does opening xn----7sbb4ac0ad0be6cf.xn--p1ai work for you?

**Comment by kmike** [comment]
For the record, `scrapy version -v` output:
```
Scrapy    : 1.3.3
lxml      : 3.7.3.0
libxml2   : 2.9.4
cssselect : 1.0.1
parsel    : 1.1.0
w3lib     : 1.17.0
Twisted   : 17.1.0
Python    : 3.5.2 (default, Jul 28 2016, 21:28:00) - [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
pyOpenSSL : 16.2.0 (OpenSSL 1.1.0e  16 Feb 2017)
Platform  : Darwin-16.5.0-x86_64-i386-64bit
```

**Comment by redapple** [comment]
It's working fine with Python 3.5

```
$ scrapy version -v
Scrapy    : 1.3.3
lxml      : 3.7.3.0
libxml2   : 2.9.3
cssselect : 1.0.1
parsel    : 1.1.0
w3lib     : 1.17.0
Twisted   : 17.1.0
Python    : 3.5.2 (default, Nov 17 2016, 17:05:23) - [GCC 5.4.0 20160609]
pyOpenSSL : 17.0.0 (OpenSSL 1.0.2g  1 Mar 2016)
Platform  : Linux-4.8.0-51-generic-x86_64-with-Ubuntu-16.10-yakkety


$ scrapy shell 'http://шанти-шанти.рф'
2017-05-10 13:54:34 [scrapy.utils.log] INFO: Scrapy 1.3.3 started (bot: scrapybot)
2017-05-10 13:54:34 [scrapy.utils.log] INFO: Overridden settings: {'DUPEFILTER_CLASS': 'scrapy.dupefilters.BaseDupeFilter', 'LOGSTATS_INTERVAL': 0}
2017-05-10 13:54:34 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2017-05-10 13:54:34 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2017-05-10 13:54:34 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2017-05-10 13:54:34 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2017-05-10 13:54:34 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023
2017-05-10 13:54:34 [scrapy.core.engine] INFO: Spider opened
2017-05-10 13:54:34 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (301) to <GET https://xn----7sbb4ac0ad0be6cf.xn--p1ai/> from <GET http://xn----7sbb4ac0ad0be6cf.xn--p1ai>
2017-05-10 13:54:35 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://xn----7sbb4ac0ad0be6cf.xn--p1ai/> (referer: None)
[s] Available Scrapy objects:
[s]   scrapy     scrapy module (contains scrapy.Request, scrapy.Selector, etc)
[s]   crawler    <scrapy.crawler.Crawler object at 0x7f8a48ebe358>
[s]   item       {}
[s]   request    <GET http://xn----7sbb4ac0ad0be6cf.xn--p1ai>
[s]   response   <200 https://xn----7sbb4ac0ad0be6cf.xn--p1ai/>
[s]   settings   <scrapy.settings.Settings object at 0x7f8a430495f8>
[s]   spider     <DefaultSpider 'default' at 0x7f8a432682e8>
[s] Useful shortcuts:
[s]   fetch(url[, redirect=True]) Fetch URL and update local objects (by default, redirects are followed)
[s]   fetch(req)                  Fetch a scrapy.Request and update local objects 
[s]   shelp()           Shell help (print this help)
[s]   view(response)    View response in a browser
>>> 

```

**Comment by redapple** [comment]
@kmike , Python 2.7 and `scrapy shell xn----7sbb4ac0ad0be6cf.xn--p1ai` does not work for me

```
$ scrapy shell xn----7sbb4ac0ad0be6cf.xn--p1ai
2017-05-10 13:56:20 [scrapy.utils.log] INFO: Scrapy 1.3.3 started (bot: scrapybot)
(...)
2017-05-10 13:56:20 [scrapy.core.engine] INFO: Spider opened
2017-05-10 13:56:20 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://xn----7sbb4ac0ad0be6cf.xn--p1ai> (failed 1 times): DNS lookup failed: no results for hostname lookup: xn----7sbb4ac0ad0be6cf.xn--p1ai.
2017-05-10 13:56:20 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://xn----7sbb4ac0ad0be6cf.xn--p1ai> (failed 2 times): DNS lookup failed: no results for hostname lookup: xn----7sbb4ac0ad0be6cf.xn--p1ai.
2017-05-10 13:56:20 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET http://xn----7sbb4ac0ad0be6cf.xn--p1ai> (failed 3 times): DNS lookup failed: no results for hostname lookup: xn----7sbb4ac0ad0be6cf.xn--p1ai.
Traceback (most recent call last):
  File "/home/paul/.virtualenvs/scrapy13/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/home/paul/.virtualenvs/scrapy13/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 142, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/home/paul/.virtualenvs/scrapy13/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 88, in _run_print_help
    func(*a, **kw)
  File "/home/paul/.virtualenvs/scrapy13/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 149, in _run_command
    cmd.run(args, opts)
  File "/home/paul/.virtualenvs/scrapy13/local/lib/python2.7/site-packages/scrapy/commands/shell.py", line 73, in run
    shell.start(url=url, redirect=not opts.no_redirect)
  File "/home/paul/.virtualenvs/scrapy13/local/lib/python2.7/site-packages/scrapy/shell.py", line 48, in start
    self.fetch(url, spider, redirect=redirect)
  File "/home/paul/.virtualenvs/scrapy13/local/lib/python2.7/site-packages/scrapy/shell.py", line 115, in fetch
    reactor, self._schedule, request, spider)
  File "/home/paul/.virtualenvs/scrapy13/local/lib/python2.7/site-packages/twisted/internet/threads.py", line 122, in blockingCallFromThread
    result.raiseException()
  File "<string>", line 2, in raiseException
twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: xn----7sbb4ac0ad0be6cf.xn--p1ai.
```

**Comment by zhongdai** [comment]
It works for me with the url - `xn----7sbb4ac0ad0be6cf.xn--p1ai`

```
Scrapy    : 1.3.3
lxml      : 3.7.2.0
libxml2   : 2.9.4
cssselect : 1.0.0
parsel    : 1.1.0
w3lib     : 1.17.0
Twisted   : 17.1.0
Python    : 3.6.0 |Anaconda 4.3.0 (x86_64)| (default, Dec 23 2016, 13:19:00) - [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
pyOpenSSL : 16.2.0 (OpenSSL 1.0.2k  26 Jan 2017)
Platform  : Darwin-16.5.0-x86_64-i386-64bit
```

```
scrapy shell xn----7sbb4ac0ad0be6cf.xn--p1ai
2017-05-10 22:04:39 [scrapy.utils.log] INFO: Scrapy 1.3.3 started (bot: scrapybot)
2017-05-10 22:04:39 [scrapy.utils.log] INFO: Overridden settings: {'DUPEFILTER_CLASS': 'scrapy.dupefilters.BaseDupeFilter', 'LOGSTATS_INTERVAL': 0}
2017-05-10 22:04:39 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole']
2017-05-10 22:04:39 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2017-05-10 22:04:39 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2017-05-10 22:04:39 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2017-05-10 22:04:39 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6024
2017-05-10 22:04:39 [scrapy.core.engine] INFO: Spider opened
2017-05-10 22:04:40 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (301) to <GET https://xn----7sbb4ac0ad0be6cf.xn--p1ai/> from <GET http://xn----7sbb4ac0ad0be6cf.xn--p1ai>
2017-05-10 22:04:43 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://xn----7sbb4ac0ad0be6cf.xn--p1ai/> (referer: None)
2017-05-10 22:04:43 [traitlets] DEBUG: Using default logger
2017-05-10 22:04:43 [traitlets] DEBUG: Using default logger
[s] Available Scrapy objects:
[s]   scrapy     scrapy module (contains scrapy.Request, scrapy.Selector, etc)
[s]   crawler    <scrapy.crawler.Crawler object at 0x110c06400>
[s]   item       {}
[s]   request    <GET http://xn----7sbb4ac0ad0be6cf.xn--p1ai>
[s]   response   <200 https://xn----7sbb4ac0ad0be6cf.xn--p1ai/>
[s]   settings   <scrapy.settings.Settings object at 0x1116d18d0>
[s]   spider     <DefaultSpider 'default' at 0x11196f4e0>
[s] Useful shortcuts:
[s]   fetch(url[, redirect=True]) Fetch URL and update local objects (by default, redirects are followed)
[s]   fetch(req)                  Fetch a scrapy.Request and update local objects
[s]   shelp()           Shell help (print this help)
[s]   view(response)    View response in a browser
```

**Comment by kmike** [comment]
@zhongdai it seems you're using Python 3.6 in your last example, while it was Python 2.7 in the first example, and it seems the issue is only present in Python 2.x.

**Comment by redapple** [comment]
I'm not sure yet who does what (Scrapy vs. Twisted) but:
- in Python 2.7, Scrapy resolver's `getHostByName()` received a Unicode string:

```
$ scrapy shell xn----7sbb4ac0ad0be6cf.xn--p1ai
(...)
2017-05-10 14:17:40 [scrapy.core.engine] INFO: Spider opened
getHostByName(u'\u0448\u0430\u043d\u0442\u0438-\u0448\u0430\u043d\u0442\u0438.\u0440\u0444')
2017-05-10 14:17:40 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://xn----7sbb4ac0ad0be6cf.xn--p1ai> (failed 1 times): DNS lookup failed: no results for hostname lookup: xn----7sbb4ac0ad0be6cf.xn--p1ai.
```

- and in Python 3, it receives an idna-encoded hostname:
```
$ scrapy shell xn----7sbb4ac0ad0be6cf.xn--p1ai
(...)
2017-05-10 14:19:10 [scrapy.core.engine] INFO: Spider opened
getHostByName('xn----7sbb4ac0ad0be6cf.xn--p1ai')
_cache_result('46.36.218.134', 'xn----7sbb4ac0ad0be6cf.xn--p1ai')
2017-05-10 14:19:10 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (301) to <GET https://xn----7sbb4ac0ad0be6cf.xn--p1ai/> from <GET http://xn----7sbb4ac0ad0be6cf.xn--p1ai>
getHostByName('xn----7sbb4ac0ad0be6cf.xn--p1ai')
2017-05-10 14:19:11 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://xn----7sbb4ac0ad0be6cf.xn--p1ai/> (referer: None)
```

**Comment by redapple** [comment]
Simply encoding the passed hostname using idna seems to work:

```
$ git diff
diff --git a/scrapy/resolver.py b/scrapy/resolver.py
index 4f4f0b0..58c3307 100644
--- a/scrapy/resolver.py
+++ b/scrapy/resolver.py
@@ -14,6 +14,8 @@ class CachingThreadedResolver(ThreadedResolver):
         self.timeout = timeout
 
     def getHostByName(self, name, timeout=None):
+        print("getHostByName(%r)" % name)
+        name = name.encode('idna')
         if name in dnscache:
             return defer.succeed(dnscache[name])
         # in Twisted<=16.6, getHostByName() is always called with
@@ -26,5 +28,6 @@ class CachingThreadedResolver(ThreadedResolver):
         return d
 
     def _cache_result(self, result, name):
+        print("_cache_result(%r, %r)" % (result, name))
         dnscache[name] = result
         return result
```

**Comment by redapple** [comment]
Something got broken with Twisted 17.

Below (again) with Python 2.7, Scrapy 1.3.3 and Twisted 17.1.0:

```
$ scrapy version -v
Scrapy    : 1.3.3
lxml      : 3.7.3.0
libxml2   : 2.9.3
cssselect : 1.0.1
parsel    : 1.1.0
w3lib     : 1.17.0
Twisted   : 17.1.0
Python    : 2.7.12+ (default, Sep 17 2016, 12:08:02) - [GCC 6.2.0 20160914]
pyOpenSSL : 17.0.0 (OpenSSL 1.0.2g  1 Mar 2016)
Platform  : Linux-4.8.0-51-generic-x86_64-with-Ubuntu-16.10-yakkety


$ scrapy shell 'шанти-шанти.рф'
2017-05-11 15:47:06 [scrapy.utils.log] INFO: Scrapy 1.3.3 started (bot: scrapybot)
(...)
2017-05-11 15:47:06 [scrapy.core.engine] INFO: Spider opened
2017-05-11 15:47:06 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://xn----7sbb4ac0ad0be6cf.xn--p1ai> (failed 1 times): DNS lookup failed: no results for hostname lookup: xn----7sbb4ac0ad0be6cf.xn--p1ai.
2017-05-11 15:47:06 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://xn----7sbb4ac0ad0be6cf.xn--p1ai> (failed 2 times): DNS lookup failed: no results for hostname lookup: xn----7sbb4ac0ad0be6cf.xn--p1ai.
2017-05-11 15:47:06 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET http://xn----7sbb4ac0ad0be6cf.xn--p1ai> (failed 3 times): DNS lookup failed: no results for hostname lookup: xn----7sbb4ac0ad0be6cf.xn--p1ai.
Traceback (most recent call last):
  File "/home/paul/.virtualenvs/scrapy13-twisted17/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/home/paul/.virtualenvs/scrapy13-twisted17/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 142, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/home/paul/.virtualenvs/scrapy13-twisted17/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 88, in _run_print_help
    func(*a, **kw)
  File "/home/paul/.virtualenvs/scrapy13-twisted17/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 149, in _run_command
    cmd.run(args, opts)
  File "/home/paul/.virtualenvs/scrapy13-twisted17/local/lib/python2.7/site-packages/scrapy/commands/shell.py", line 73, in run
    shell.start(url=url, redirect=not opts.no_redirect)
  File "/home/paul/.virtualenvs/scrapy13-twisted17/local/lib/python2.7/site-packages/scrapy/shell.py", line 48, in start
    self.fetch(url, spider, redirect=redirect)
  File "/home/paul/.virtualenvs/scrapy13-twisted17/local/lib/python2.7/site-packages/scrapy/shell.py", line 115, in fetch
    reactor, self._schedule, request, spider)
  File "/home/paul/.virtualenvs/scrapy13-twisted17/local/lib/python2.7/site-packages/twisted/internet/threads.py", line 122, in blockingCallFromThread
    result.raiseException()
  File "<string>", line 2, in raiseException
twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: xn----7sbb4ac0ad0be6cf.xn--p1ai.
```

Compared to Python 2.7, Scrapy 1.3.3 and Twisted 16.6.0:

```
$ scrapy version -v
Scrapy    : 1.3.3
lxml      : 3.7.3.0
libxml2   : 2.9.3
cssselect : 1.0.1
parsel    : 1.1.0
w3lib     : 1.17.0
Twisted   : 16.6.0
Python    : 2.7.12+ (default, Sep 17 2016, 12:08:02) - [GCC 6.2.0 20160914]
pyOpenSSL : 17.0.0 (OpenSSL 1.0.2g  1 Mar 2016)
Platform  : Linux-4.8.0-51-generic-x86_64-with-Ubuntu-16.10-yakkety


$ scrapy shell 'шанти-шанти.рф'
2017-05-11 15:49:06 [scrapy.utils.log] INFO: Scrapy 1.3.3 started (bot: scrapybot)
(...)
2017-05-11 15:49:06 [scrapy.core.engine] INFO: Spider opened
2017-05-11 15:49:06 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (301) to <GET https://xn----7sbb4ac0ad0be6cf.xn--p1ai/> from <GET http://xn----7sbb4ac0ad0be6cf.xn--p1ai>
2017-05-11 15:49:07 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://xn----7sbb4ac0ad0be6cf.xn--p1ai/> (referer: None)
[s] Available Scrapy objects:
[s]   scrapy     scrapy module (contains scrapy.Request, scrapy.Selector, etc)
[s]   crawler    <scrapy.crawler.Crawler object at 0x7fc729ef7190>
[s]   item       {}
[s]   request    <GET http://xn----7sbb4ac0ad0be6cf.xn--p1ai>
[s]   response   <200 https://xn----7sbb4ac0ad0be6cf.xn--p1ai/>
[s]   settings   <scrapy.settings.Settings object at 0x7fc729ef7690>
[s]   spider     <DefaultSpider 'default' at 0x7fc72627f790>
[s] Useful shortcuts:
[s]   fetch(url[, redirect=True]) Fetch URL and update local objects (by default, redirects are followed)
[s]   fetch(req)                  Fetch a scrapy.Request and update local objects 
[s]   shelp()           Shell help (print this help)
[s]   view(response)    View response in a browser
>>> 
```

**Comment by redapple** [comment]
I was puzzled by the fact that this simple example works for both Twisted 16.6 and Twisted 17.1, with both Python 2.7 and Python 3:

```
$ cat test.py 
# -*- coding: utf-8 -*-

from __future__ import print_function

from twisted.internet import reactor
from twisted.web.client import Agent
from twisted.web.http_headers import Headers

agent = Agent(reactor)

d = agent.request(
    'GET',
    'https://xn----7sbb4ac0ad0be6cf.xn--p1ai/',
    Headers({'User-Agent': ['Twisted Web Client Example']}),
    None)

def cbResponse(ignored):
    print('Response received')
d.addCallback(cbResponse)

def cbShutdown(ignored):
    reactor.stop()
d.addBoth(cbShutdown)

reactor.run()
```
while `scrapy shell xn----7sbb4ac0ad0be6cf.xn--p1ai` fails with Twisted 17.1 and Python 2.7

But in fact:
* Twisted 17.1+ changed their default name resolver to use `socket.getaddrinfo`
* Scrapy uses its own resolver, based on `twisted.internet.base.ThreadedResolver`, which uses `socket.gethostbyname`
* with Twisted 17.1+, `getHostByName()` receives a Unicode string, even if the URL is indeed passed as idna'd ASCII from Scrapy's downloader
* `socket.getaddrinfo` handles Unicode name as input just fine, with both Python 2.7 and Python 3
* whereas `socket.gethostbyname` does not work with non-ASCII domains as input

```
$ python2
Python 2.7.12+ (default, Sep 17 2016, 12:08:02) 
[GCC 6.2.0 20160914] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.getaddrinfo(u'\u0448\u0430\u043d\u0442\u0438-\u0448\u0430\u043d\u0442\u0438.\u0440\u0444', 80, 0, 0, socket.IPPROTO_TCP)
[(2, 1, 6, '', ('46.36.218.134', 80))]
>>> socket.gethostbyname(u'\u0448\u0430\u043d\u0442\u0438-\u0448\u0430\u043d\u0442\u0438.\u0440\u0444')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
```

With Python 3, all is good with both calls:

```
$ python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.getaddrinfo(u'\u0448\u0430\u043d\u0442\u0438-\u0448\u0430\u043d\u0442\u0438.\u0440\u0444', 80, 0, 0, socket.IPPROTO_TCP)
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('46.36.218.134', 80))]
>>> socket.gethostbyname(u'\u0448\u0430\u043d\u0442\u0438-\u0448\u0430\u043d\u0442\u0438.\u0440\u0444')
'46.36.218.134'
```

**Comment by redapple** [comment]
I just tested scrapy 1.4.0 with [Twisted 17.5.0rc2](https://twistedmatrix.com/pipermail/twisted-python/2017-May/031442.html) and the issue looks fixed.
* https://github.com/twisted/twisted/pull/795
* https://twistedmatrix.com/trac/ticket/9137

**Comment by redapple** [comment]
Twisted 17.5.0 was released and upgrading to it fixes this issue.
