### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'fields'

### ISSUE THREAD

**Issue by hyanx** [scrapy/scrapy#2742]
when I crawl some data happened the  issue of under. I don't known I made what's wrong?

 `2017-05-16 21:03:33 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method ?.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x7f2d0db8e610>>
Traceback (most recent call last):
  File "/root/myproject/scrapy/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/root/myproject/scrapy/local/lib/python2.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/root/myproject/scrapy/local/lib/python2.7/site-packages/scrapy/extensions/feedexport.py", line 221, in item_scraped
    slot.exporter.export_item(item)
  File "/root/myproject/scrapy/local/lib/python2.7/site-packages/scrapy/exporters.py", line 210, in export_item
    values = list(self._build_row(x for _, x in fields))
  File "/root/myproject/scrapy/local/lib/python2.7/site-packages/scrapy/exporters.py", line 214, in _build_row
    for s in values:
  File "/root/myproject/scrapy/local/lib/python2.7/site-packages/scrapy/exporters.py", line 210, in <genexpr>
    values = list(self._build_row(x for _, x in fields))
  File "/root/myproject/scrapy/local/lib/python2.7/site-packages/scrapy/exporters.py", line 63, in _get_serialized_fields
    field_iter = six.iterkeys(item.fields)
AttributeError: 'NoneType' object has no attribute 'fields'
`

**Comment by hyanx** [comment]
similar with _exceptions.AttributeError: 'dict' object has no attribute 'fields
#86 by dfdeshom was closed on May 9 2012_ 

'Cause I set the `FEED_URI` in settings.py .
