### ISSUE TITLE
Images min dimensions cause unhandled exception

### ISSUE THREAD

**Issue by xhujerr** [scrapy/scrapy#2761]
When I enable in settings.py 
IMAGES_MIN_HEIGHT = 350
IMAGES_MIN_WIDTH = 350

I start getting unhandled exceptions:
> Unhandled error in Deferred:
> Failure: scrapy.pipelines.images.ImageException: Image too small (62x59 < 350x350)

The exception looks like this:
```
2017-05-28 19:06:43 [scrapy.pipelines.files] WARNING: File (error): Error processing file from <GET http://example.com/images/0.jpg> referred in <http://www.example.com/>: Image too small (600x200 < 350x350)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/scrapy/pipelines/files.py", line 356, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "/usr/lib/python2.7/dist-packages/scrapy/pipelines/images.py", line 98, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "/usr/lib/python2.7/dist-packages/scrapy/pipelines/images.py", line 102, in image_downloaded
    for path, image, buf in self.get_images(response, request, info):
  File "/usr/lib/python2.7/dist-packages/scrapy/pipelines/images.py", line 120, in get_images
    (width, height, self.min_width, self.min_height))
ImageException: Image too small (600x200 < 350x350)
```

When I comment `except` statements:
https://github.com/scrapy/scrapy/blob/1.3/scrapy/pipelines/files.py#L364
https://github.com/scrapy/scrapy/blob/1.3/scrapy/pipelines/files.py#L372
the exceptions aren't unhandled anymore.

It seems to me like a bug. Isn't is? Or am I doing something wrong?

It may be something similar to:
https://github.com/scrapy/scrapy/issues/1884
but in my case scrapy really crashes

python-w3lib:  1.17.0-1~exp1
python-scrapy: 1.3.3-1~exp1
both from a debian package
Python 2.7.10+

**Comment by redapple** [comment]
I cannot reproduce `Unhandled error in Deferred:` with Scrapy 1.4.0, nor with Scrapy 1.3.3, but I can see that the `ImageException` is handled and that the parent item is properly output. In other words, I do not see Scrapy crashing (just it being quite verbal with the exception)

Here's a sample crawl with a very basic spider to get Yahoo homepage and collecting 1 image:

```
$ scrapy version -v
Scrapy    : 1.4.0
lxml      : 3.7.3.0
libxml2   : 2.9.3
cssselect : 1.0.1
parsel    : 1.2.0
w3lib     : 1.17.0
Twisted   : 17.1.0
Python    : 2.7.12+ (default, Sep 17 2016, 12:08:02) - [GCC 6.2.0 20160914]
pyOpenSSL : 17.0.0 (OpenSSL 1.0.2g  1 Mar 2016)
Platform  : Linux-4.8.0-53-generic-x86_64-with-Ubuntu-16.10-yakkety


# -*- coding: utf-8 -*-
import scrapy


class YahooImageSpider(scrapy.Spider):
    name = 'yahooimg'
    allowed_domains = ['yahoo.com']
    start_urls = ['http://yahoo.com/']

    def parse(self, response):
        yield {'url': response.url,
               'image_urls': [response.urljoin(u) for u in response.css('img::attr(src)').getall()[:1]],
               'title': response.css('title::text').get()}
 ```
with these settings:
```
ITEM_PIPELINES = {
    'scrapy.pipelines.images.ImagesPipeline': 1
}
IMAGES_STORE = '/home/paul/imgpipedwnldr/images'
IMAGES_MIN_WIDTH = 10000  # arbitrarily high min width
```
This is the log I get in Python 2.7 with an extra patch on scrapy to log `item_completed` in the `ImagesPipeline` class:

```
$ scrapy crawl yahooimg
2017-05-31 19:59:56 [scrapy.utils.log] INFO: Scrapy 1.4.0 started (bot: imgpipedwnldr)
(...)
2017-05-31 19:59:57 [scrapy.middleware] INFO: Enabled item pipelines:
['scrapy.pipelines.images.ImagesPipeline']
2017-05-31 19:59:57 [scrapy.core.engine] INFO: Spider opened
2017-05-31 19:59:58 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2017-05-31 19:59:58 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023
2017-05-31 19:59:58 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (301) to <GET https://www.yahoo.com/> from <GET http://yahoo.com/>
2017-05-31 19:59:58 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (302) to <GET https://fr.yahoo.com/?p=us> from <GET https://www.yahoo.com/>
2017-05-31 20:00:00 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://fr.yahoo.com/?p=us> (referer: None)
2017-05-31 20:00:00 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://s.yimg.com/uu/api/res/1.2/BeYO4iliCJT4gN5b0Hc1ZA--/Zmk9c3RyaW07aD0zODg7cHlvZmY9MDtxPTk1O3c9NzIwO3NtPTE7YXBwaWQ9eXRhY2h5b24-/https://s.yimg.com/lo/api/res/1.2/c0yA3sxSnrLN89b.BkcHDg--~C/Zmk9Zml0O3c9OTkyO2g9NTU4O3B4b2ZmPTA7cHlvZmY9MDs7YXBwaWQ9cHJvZGVzazI-/https://s.yimg.com/os/creatr-images/GLB/2017-05-31/8554f9a0-460c-11e7-b8de-87c81fed249d_station-service.jpg.cf.jpg> (referer: None)
2017-05-31 20:00:00 [scrapy.pipelines.files] DEBUG: File (downloaded): Downloaded file from <GET https://s.yimg.com/uu/api/res/1.2/BeYO4iliCJT4gN5b0Hc1ZA--/Zmk9c3RyaW07aD0zODg7cHlvZmY9MDtxPTk1O3c9NzIwO3NtPTE7YXBwaWQ9eXRhY2h5b24-/https://s.yimg.com/lo/api/res/1.2/c0yA3sxSnrLN89b.BkcHDg--~C/Zmk9Zml0O3c9OTkyO2g9NTU4O3B4b2ZmPTA7cHlvZmY9MDs7YXBwaWQ9cHJvZGVzazI-/https://s.yimg.com/os/creatr-images/GLB/2017-05-31/8554f9a0-460c-11e7-b8de-87c81fed249d_station-service.jpg.cf.jpg> referred in <None>
2017-05-31 20:00:00 [scrapy.pipelines.files] WARNING: File (error): Error processing file from <GET https://s.yimg.com/uu/api/res/1.2/BeYO4iliCJT4gN5b0Hc1ZA--/Zmk9c3RyaW07aD0zODg7cHlvZmY9MDtxPTk1O3c9NzIwO3NtPTE7YXBwaWQ9eXRhY2h5b24-/https://s.yimg.com/lo/api/res/1.2/c0yA3sxSnrLN89b.BkcHDg--~C/Zmk9Zml0O3c9OTkyO2g9NTU4O3B4b2ZmPTA7cHlvZmY9MDs7YXBwaWQ9cHJvZGVzazI-/https://s.yimg.com/os/creatr-images/GLB/2017-05-31/8554f9a0-460c-11e7-b8de-87c81fed249d_station-service.jpg.cf.jpg> referred in <None>: Image too small (720x388 < 10000x0)
Traceback (most recent call last):
  File "/home/paul/src/scrapy/scrapy/pipelines/files.py", line 356, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "/home/paul/src/scrapy/scrapy/pipelines/images.py", line 102, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "/home/paul/src/scrapy/scrapy/pipelines/images.py", line 106, in image_downloaded
    for path, image, buf in self.get_images(response, request, info):
  File "/home/paul/src/scrapy/scrapy/pipelines/images.py", line 124, in get_images
    (width, height, self.min_width, self.min_height))
ImageException: Image too small (720x388 < 10000x0)
2017-05-31 20:00:00 [scrapy.pipelines.images] DEBUG: ImagesPipeline.item_completed(results=[(False, <twisted.python.failure.Failure scrapy.pipelines.images.ImageException: Image too small (720x388 < 10000x0)>)], item={'url': 'https://fr.yahoo.com/?p=us', 'image_urls': [u'https://s.yimg.com/uu/api/res/1.2/BeYO4iliCJT4gN5b0Hc1ZA--/Zmk9c3RyaW07aD0zODg7cHlvZmY9MDtxPTk1O3c9NzIwO3NtPTE7YXBwaWQ9eXRhY2h5b24-/https://s.yimg.com/lo/api/res/1.2/c0yA3sxSnrLN89b.BkcHDg--~C/Zmk9Zml0O3c9OTkyO2g9NTU4O3B4b2ZmPTA7cHlvZmY9MDs7YXBwaWQ9cHJvZGVzazI-/https://s.yimg.com/os/creatr-images/GLB/2017-05-31/8554f9a0-460c-11e7-b8de-87c81fed249d_station-service.jpg.cf.jpg'], 'title': u'Yahoo'}, info=<scrapy.pipelines.media.SpiderInfo object at 0x7f901c7817d0>)
2017-05-31 20:00:00 [scrapy.core.scraper] DEBUG: Scraped from <200 https://fr.yahoo.com/?p=us>
{'url': 'https://fr.yahoo.com/?p=us', 'images': [], 'image_urls': [u'https://s.yimg.com/uu/api/res/1.2/BeYO4iliCJT4gN5b0Hc1ZA--/Zmk9c3RyaW07aD0zODg7cHlvZmY9MDtxPTk1O3c9NzIwO3NtPTE7YXBwaWQ9eXRhY2h5b24-/https://s.yimg.com/lo/api/res/1.2/c0yA3sxSnrLN89b.BkcHDg--~C/Zmk9Zml0O3c9OTkyO2g9NTU4O3B4b2ZmPTA7cHlvZmY9MDs7YXBwaWQ9cHJvZGVzazI-/https://s.yimg.com/os/creatr-images/GLB/2017-05-31/8554f9a0-460c-11e7-b8de-87c81fed249d_station-service.jpg.cf.jpg'], 'title': u'Yahoo'}
2017-05-31 20:00:00 [scrapy.core.engine] INFO: Closing spider (finished)
2017-05-31 20:00:00 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 1198,
 'downloader/request_count': 4,
 'downloader/request_method_count/GET': 4,
 'downloader/response_bytes': 165340,
 'downloader/response_count': 4,
 'downloader/response_status_count/200': 2,
 'downloader/response_status_count/301': 1,
 'downloader/response_status_count/302': 1,
 'file_count': 1,
 'file_status_count/downloaded': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2017, 5, 31, 18, 0, 0, 910905),
 'item_scraped_count': 1,
 'log_count/DEBUG': 8,
 'log_count/INFO': 7,
 'log_count/WARNING': 1,
 'memusage/max': 48496640,
 'memusage/startup': 48496640,
 'response_received_count': 2,
 'scheduler/dequeued': 3,
 'scheduler/dequeued/memory': 3,
 'scheduler/enqueued': 3,
 'scheduler/enqueued/memory': 3,
 'start_time': datetime.datetime(2017, 5, 31, 17, 59, 58, 36414)}
2017-05-31 20:00:00 [scrapy.core.engine] INFO: Spider closed (finished)
```

**Comment by redapple** [comment]
@xhujerr , do you have any updates for us?

**Comment by cathalgarvey** [comment]
Hey @xhujerr - I'm going to close the issue, as it's become stale. I'm thinking that perhaps this indicates that image size limits shouldn't lead to exceptions, maybe just debug-level logging. But it appears to me that everything is, currently, working as-intended.

Please check back in with us if you disagree, or if I'm missing something.
Thank you for contributing to Scrapy! :)

**Comment by greyson** [comment]
I am seeing the same as the OP.  I have subclassed the ImagesPipeline to add a Tensorflow step after the image has been downloaded in `item_completed`; as long as the minimum height and width are set, I see both the "Deferred" and "Image too small" exceptions

It appears the Deferred is definitely connected to the ImageException -- which, as mentioned in #1884, I agree should not have a full stack trace in the console log -- it has made visually parsing out my own errors that much more difficult.

**Comment by MihaiWill** [comment]
I get same errors!!

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mihai\anaconda3\lib\site-packages\scrapy\pipelines\files.py", line 419, in media_downloaded
    checksum = self.file_downloaded(response, request, info)
  File "c:\users\mihai\anaconda3\lib\site-packages\scrapy\pipelines\images.py", line 106, in file_downloaded
    return self.image_downloaded(response, request, info)
  File "c:\users\mihai\anaconda3\lib\site-packages\scrapy\pipelines\images.py", line 110, in image_downloaded
    for path, image, buf in self.get_images(response, request, info):
  File "c:\users\mihai\anaconda3\lib\site-packages\scrapy\pipelines\images.py", line 128, in get_images
    (width, height, self.min_width, self.min_height))
scrapy.pipelines.images.ImageException: Image too small (310x310 < 380x500)
2020-01-09 22:14:57 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://cbu01.alicdn.com/img/ibank/2019/258/609/12983906852_916057475.310x310.jpg> (refe                         rer: None)
2020-01-09 22:14:57 [scrapy.pipelines.files] DEBUG: File (downloaded): Downloaded file from <GET https://cbu01.alicdn.com/img/ibank/2019/258/609/1298390685                         2_916057475.310x310.jpg> referred in <None>
2020-01-09 22:14:57 [scrapy.pipelines.files] WARNING: File (error): Error processing file from <GET https://cbu01.alicdn.com/img/ibank/2019/258/609/1298390                         6852_916057475.310x310.jpg> referred in <None>: Image too small (310x310 < 380x500)
Traceback (most recent call last):
  File "c:\users\mihai\anaconda3\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "c:\users\mihai\anaconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "c:\users\mihai\anaconda3\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://cbu01.alicdn.com/img/ibank/2019/258/609/12983906852_916057475.310x310.jpg>
```


also a couple of images escaped my size rules, as you can see in the example


My Custom Pipeline:
```
class MyImagesPipeline(ImagesPipeline):

    def get_media_requests(self, ProductItem, info):
        return [Request(x,meta={'prodId' : ProductItem.get('prodId')}) for x in ProductItem.get(self.images_urls_field, [])]

    def file_path(self, request, response=None, info=None):
        x = request.meta['prodId']
        return '{}/'.format(x) +  os.path.basename(urlparse(request.url).path)
```

My settings:
```
ITEM_PIPELINES = {
   'scraper.pipelines.MyImagesPipeline': 1,
}

# IMG
IMAGES_MIN_HEIGHT = 500
IMAGES_MIN_WIDTH = 380
```

**Comment by Gallaecio** [comment]
The only issue is that a traceback is logged, right? The spider is behaving as expected otherwise, as described in the original issue (https://github.com/scrapy/scrapy/issues/1884).

If so, maybe we can simply reopen https://github.com/scrapy/scrapy/issues/1884 with the goal of avoiding the traceback from being logged.

**Comment by MihaiWill** [comment]
> The only issue is that a traceback is logged, right? The spider is behaving as expected otherwise, as described in the original issue (#1884).
 Yes, but also there ware 2 photos (from 7) of 310px that escaped my size rules:
```
IMAGES_MIN_HEIGHT = 500
IMAGES_MIN_WIDTH = 380
```
You can see that in logs i posted above

**Comment by Gallaecio** [comment]
It is not obvious to me, that second issue about two images escaping your size rules. Could you open a separate ticket about that? It would be great if you could include in that ticket a minimal spider to reproduce the issue.

**Comment by MihaiWill** [comment]
> 
> 
> It is not obvious to me, that second issue about two images escaping your size rules. Could you open a separate ticket about that? It would be great if you could include in that ticket a minimal spider to reproduce the issue.

I cannot reproduce anymore, so is fine now,maybe it was a human error from my part. So it works as it should, it just log the traceback. Cheers!
