### ISSUE TITLE
canonicalize at LinkExtractor works incorrectly

### ISSUE THREAD

**Issue by jenya** [scrapy/scrapy#2779]
First: 
https://github.com/scrapy/scrapy/blob/master/scrapy/linkextractors/lxmlhtml.py#L110
And then: 
https://github.com/scrapy/scrapy/blob/master/scrapy/linkextractors/lxmlhtml.py#L40

So, when `canonicalize = False` (current default value), it will run `canonicalize_url`, but it shouldn't:

> :param canonicalize: canonicalize each extracted url (using w3lib.url.canonicalize_url)

**Comment by kmike** [comment]
Sorry, could you please give an example?

As I recall, the tricky part is that canonicalize is still executed for deduplication purposes, but the results returned to users are not canonicalized. `canonicalize` flag only affects the resulting links, not the way links are deduplicated.

**Comment by redapple** [comment]
I believe now it only runs canonicalization if `unique=True`, which is not the default.

**Comment by kmike** [comment]
It shouldn't return canonicalized URLs even if unique=True though, but it should use canonicalized URLs for deduplication when unique is True.

**Comment by jenya** [comment]
There is a page without `charset` set. Scrapy detect it as utf-8 (but it's 1250). Python 2 btw.
When I set  `canonicalize = False` at LinkExtractor I got:
```
[ERROR] Spider error processing <GET http://www.guiaempresas.info/empresa/elena-cantabria-camargo_315568.html> (referer: http://www.guiaempresas.info/buscarempresas/
pa_pagina_6.html)
Traceback (most recent call last):
  File "c:\...\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\...\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\......\middlewares\spider\offsite.py", line 22, in safe_process_spider_output
    for r in results:
  File "c:\...\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\......\middlewares\spider\meta.py", line 25, in safe_process_spider_output
    for r in results:
  File "c:\......\middlewares\spider\loader.py", line 18, in safe_process_spider_output
    for r in results:
  File "c:\...\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\...\lib\site-packages\scrapy\spiders\crawl.py", line 82, in _parse_response
    for request_or_item in self._requests_to_follow(response):
  File "c:\...\lib\site-packages\scrapy\spiders\crawl.py", line 61, in _requests_to_follow
    links = [lnk for lnk in rule.link_extractor.extract_links(response)
  File "c:\...\lib\site-packages\scrapy\linkextractors\lxmlhtml.py", line 128, in extract_links
    links = self._extract_links(doc, response.url, response.encoding, base_url)
  File "c:\...\lib\site-packages\scrapy\linkextractors\__init__.py", line 109, in _extract_links
    return self.link_extractor._extract_links(*args, **kwargs)
  File "c:\...\lib\site-packages\scrapy\linkextractors\lxmlhtml.py", line 76, in _extract_links
    return self._deduplicate_if_needed(links)
  File "c:\...\lib\site-packages\scrapy\linkextractors\lxmlhtml.py", line 91, in _deduplicate_if_needed
    return unique_list(links, key=self.link_key)
  File "c:\...\lib\site-packages\scrapy\utils\python.py", line 76, in unique
    seenkey = key(item)
  File "c:\...\lib\site-packages\scrapy\linkextractors\lxmlhtml.py", line 43, in <lambda>
    keep_fragments=True)
  File "c:\...\lib\site-packages\w3lib\url.py", line 462, in canonicalize_url
    parse_url(url), encoding=encoding)
  File "c:\...\lib\site-packages\w3lib\url.py", line 539, in parse_url
    return urlparse(to_unicode(url, encoding))
  File "c:\...\lib\site-packages\w3lib\util.py", line 27, in to_unicode
    return text.decode(encoding, errors)
  File "c:\...\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xed in position 15: invalid continuation byte
```
As you can see - it execute `canonicalize_url`
Set `canonicalize = True` solve problem.

Disabling сanonicalization it's just a workaround to avoid this problem. It should be fixed somewhere here I think: https://github.com/scrapy/w3lib/pull/75

**Comment by kmike** [comment]
There is nothing wrong with calling canonicalize_url when `canonicalize` is set to False, so let's close it in favor of https://github.com/scrapy/w3lib/pull/75.

**Comment by jenya** [comment]
@kmike but why `canonicalize = True` solve problem?

**Comment by redapple** [comment]
This reminds me of https://github.com/scrapy/scrapy/pull/1949 where I had to add the response encoding to the `Link` object to do proper canonicalization.

**Comment by huangxuuun** [comment]
There is wrong if you set `canonicalize = False`.
I change the code in `utf_8.py` like this:
```
def decode(input, errors='strict'):
    print input, input.decode('gbk')
    return codecs.utf_8_decode(input, errors, True)
```
and this is output:
```
http://dota2.uuu9.com/url/dota2������Ѷ.url http://dota2.uuu9.com/url/dota2最新资讯.url
2017-11-23 16:23:13 [scrapy.core.scraper] ERROR: Spider error processing <GET http://dota2.uuu9.com/List/List_7598.shtml> (referer: http://dota2.uuu9.com)
Traceback (most recent call last):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Phthon27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Phthon27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Phthon27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Phthon27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Phthon27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Phthon27\lib\site-packages\scrapy\spiders\crawl.py", line 82, in _parse_response
    for request_or_item in self._requests_to_follow(response):
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Phthon27\lib\site-packages\scrapy\spiders\crawl.py", line 61, in _requests_to_follow
    links = [lnk for lnk in rule.link_extractor.extract_links(response)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Phthon27\lib\site-packages\scrapy\linkextractors\lxmlhtml.py", line 128, in extract_links
    links = self._extract_links(doc, response.url, response.encoding, base_url)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Phthon27\lib\site-packages\scrapy\linkextractors\__init__.py", line 109, in _extract_links
    return self.link_extractor._extract_links(*args, **kwargs)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Phthon27\lib\site-packages\scrapy\linkextractors\lxmlhtml.py", line 76, in _extract_links
    return self._deduplicate_if_needed(links)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Phthon27\lib\site-packages\scrapy\linkextractors\lxmlhtml.py", line 91, in _deduplicate_if_needed
    return unique_list(links, key=self.link_key)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Phthon27\lib\site-packages\scrapy\utils\python.py", line 76, in unique
    seenkey = key(item)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Phthon27\lib\site-packages\scrapy\linkextractors\lxmlhtml.py", line 43, in <lambda>
    keep_fragments=True)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Phthon27\lib\site-packages\w3lib\url.py", line 433, in canonicalize_url
    parse_url(url), encoding=encoding)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Phthon27\lib\site-packages\w3lib\url.py", line 510, in parse_url
    return urlparse(to_unicode(url, encoding))
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Phthon27\lib\site-packages\w3lib\util.py", line 27, in to_unicode
    return text.decode(encoding, errors)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Phthon27\lib\encodings\utf_8.py", line 17, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd7 in position 31: invalid continuation byte
```
