### ISSUE TITLE
ImportError: No module named settings

### ISSUE THREAD

**Issue by ikirollosmagdy** [scrapy/scrapy#2790]
Hello guys, I'm suffering from this error

```Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/scrapy/cmdline.py", line 161, in <module>
    execute()
  File "/Library/Python/2.7/site-packages/scrapy/cmdline.py", line 108, in execute
    settings = get_project_settings()
  File "/Users/kdawod/.virtualenvs/python2.7/lib/python2.7/site-packages/scrapy/utils/project.py", line 68, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/Users/kdawod/.virtualenvs/python2.7/lib/python2.7/site-packages/scrapy/settings/__init__.py", line 292, in setmodule
    module = import_module(module)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named settings 
```

it's only happening while running in pycharm, however, it was working just fine the previous day.
I would be glad if you can help me figure out this issue and prevent it from happening in the feature.

**Comment by redapple** [comment]
Hi @ikirollosmagdy ,
can I ask you to ask this on [StackOverflow](https://stackoverflow.com/questions/tagged/scrapy) or [/r/scrapy/](https://www.reddit.com/r/scrapy/)? They are better suited for this kind of troubleshooting. Thanks.
