### ISSUE TITLE
scrapy can't run

### ISSUE THREAD

**Issue by zangree** [scrapy/scrapy#2794]
Traceback (most recent call last):
  File "e:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "e:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "E:\Python27\Scripts\scrapy.exe\__main__.py", line 5, in <module>
  File "e:\python27\lib\site-packages\scrapy\cmdline.py", line 9, in <module>
    from scrapy.crawler import CrawlerProcess
  File "e:\python27\lib\site-packages\scrapy\crawler.py", line 7, in <module>
    from twisted.internet import reactor, defer
  File "e:\python27\lib\site-packages\twisted\internet\reactor.py", line 38, in <module>
    from twisted.internet import default
  File "e:\python27\lib\site-packages\twisted\internet\default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "e:\python27\lib\site-packages\twisted\internet\default.py", line 50, in _getInstallFunction
    from twisted.internet.selectreactor import install
  File "e:\python27\lib\site-packages\twisted\internet\selectreactor.py", line 18, in <module>
    from twisted.internet import posixbase
  File "e:\python27\lib\site-packages\twisted\internet\posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "e:\python27\lib\site-packages\twisted\internet\tcp.py", line 28, in <module>
    from twisted.internet._newtls import (
  File "e:\python27\lib\site-packages\twisted\internet\_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "e:\python27\lib\site-packages\twisted\protocols\tls.py", line 63, in <module>
    from twisted.internet._sslverify import _setAcceptableProtocols
  File "e:\python27\lib\site-packages\twisted\internet\_sslverify.py", line 157, in <module>
    verifyHostname, VerificationError = _selectVerifyImplementation()
  File "e:\python27\lib\site-packages\twisted\internet\_sslverify.py", line 140, in _selectVerifyImplementation
    from service_identity import VerificationError
  File "e:\python27\lib\site-packages\service_identity\__init__.py", line 7, in <module>
    from . import cryptography, pyopenssl
  File "e:\python27\lib\site-packages\service_identity\cryptography.py", line 9, in <module>
    from cryptography.x509 import (
  File "e:\python27\lib\site-packages\cryptography\x509\__init__.py", line 9, in <module>
    from cryptography.x509.base import (
  File "e:\python27\lib\site-packages\cryptography\x509\base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "e:\python27\lib\site-packages\cryptography\x509\extensions.py", line 13, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "e:\python27\lib\site-packages\asn1crypto\keys.py", line 22, in <module>
    from ._elliptic_curve import (
  File "e:\python27\lib\site-packages\asn1crypto\_elliptic_curve.py", line 51, in <module>
    from ._int import inverse_mod
  File "e:\python27\lib\site-packages\asn1crypto\_int.py", line 56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "e:\python27\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py", line 31, in <module>
    libcrypto_path = find_library('crypto')
  File "e:\python27\lib\ctypes\util.py", line 54, in find_library
    fname = os.path.join(directory, name)
  File "e:\python27\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 7: ordinal not in range(128)

When I update scrapy from 1.3.3 to 1.4.0, this Error happed. Could someone help to fix it? Thank you.

**Comment by Parth-Vader** [comment]
This could happen when your default encoding isn't `utf-8`. Try adding ` # -*- coding: utf-8 -*-` on top of your spider program and running again.

**Comment by zangree** [comment]
@Parth-Vader Thank you very much. Now I just can't run scrapy. For example, when I run "scrapy -V", this error shows up.

**Comment by kmike** [comment]
Hey @zangree,

This question looks better suited for https://stackoverflow.com/ (use "scrapy" tag) - this is our official support channel.

The error message suggests there is something wrong either with `cryptography` library, or with service_identity library - can you try running `import cryptography.x509` in Python console - does it work? If it raises an exception then it is better to raise an issue at https://github.com/pyca/cryptography/issues (or try to look for existing tickets there). 

It doesn't look like a Scrapy issue, so I'm closing it. Likely the problem was caused not by upgrading Scrapy itself - the reason is likely that cryptography (and/or service_identity) library got updated as well, and it didn't went well.
