### ISSUE TITLE
Error with yield from on scrapy.Request object

### ISSUE THREAD

**Issue by reyman** [scrapy/scrapy#2795]
Hi,

I try to use some imbricated/recursive `scrapy.Request(...)` (scrapy 1.4.0) using the [new `yield from` keyword of python 3.3](https://docs.python.org/3/whatsnew/3.3.html), without success.

I test my algorithm with [simple example and fixed data](https://gist.github.com/reyman/dbb04fe2e79c0343cb4ae55722fb02bd), it works, but i cannot reproduce the same algorithm using yield from on Scrapy Request : 

```
2017-06-16 15:20:45 [scrapy.core.scraper] ERROR: Spider error processing <GET https://api.flightradar24.com/common/v1/airport.json?code=VAR&plugin%5C%5B%5C%5D=&plugin-setting%5C%5Bschedule%5C%5D%5C%5Bmode%5C%5D=&plugin-setting%5C%5Bschedule%5C%5D%5C%5Btimestamp%5C%5D=1493251200&page=1&limit=100&token=> (referer: https://www.flightradar24.com/data/airports/bulgaria)
Traceback (most recent call last):
  File "/home/reyman/.pyenv/versions/venv352/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/home/reyman/.pyenv/versions/venv352/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/home/reyman/.pyenv/versions/venv352/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/home/reyman/.pyenv/versions/venv352/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/reyman/.pyenv/versions/venv352/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/reyman/Projets/Flight-Scrapping/flight/flight_project/spiders/AirportsSpider.py", line 209, in parse_schedule
    yield from scrapy.Request(url, self.parse_schedule, meta={'airport_item': item, 'airport_urls': urls, 'i': i + 1})
TypeError: 'Request' object is not iterable
2017-06-16 15:20:45 [scrapy.core.engine] INFO: Closing spider (finished)
2017-06-16 15:20:45 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
```
You could find [the original script here ](https://github.com/IDEES-Rouen/Flight-Scrapping), do you have an idea to help me on this point ?

**Comment by kmike** [comment]
Hey @reyman,

You're using yield from wrong: `yield from foo` is roughly the same as 

```py
for elem in foo:
    yield elem
```

so `foo` must be an iterable. For example, it can be an output of a parse method which yields Request objects.

https://stackoverflow.com/ is a better way to debug such problems (use "Scrapy' tag to create a question).

**Comment by reyman** [comment]
I already ask the question on SO, i finally found some path to do that with yield from recursive call, the post is here : https://stackoverflow.com/questions/43667622/yield-request-call-produce-weird-result-in-recursive-method-with-scrapy
