### ISSUE TITLE
error filedescriptor out of range in select()

### ISSUE THREAD

**Issue by echoocking** [scrapy/scrapy#2806]
2017-06-29 22:21:36 [crawler.download_middlewares.RetryMiddleware] DEBUG: Gave up retrying <GET https://club.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv986&productId=1540024&score=0&sortType=6&page=88&pageSize=10&isShadowSku=0> (failed 3 times): An error occurred while connecting: [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: filedescriptor out of range in select()

i use python 2.7 and scrapy 1.3.3
if you want ,i can upload my code
if you are interest in,and want more information ,please email:echooc@outlook.com 👍

**Comment by redapple** [comment]
Hm, I've never seen this error.
I cannot reproduce it with scrapy shell.
Was there anything else (longer) in the traceback?

```
$ scrapy version -v
Scrapy    : 1.3.3
lxml      : 3.7.3.0
libxml2   : 2.9.3
cssselect : 1.0.1
parsel    : 1.2.0
w3lib     : 1.17.0
Twisted   : 17.1.0
Python    : 2.7.12 (default, Nov 19 2016, 06:48:10) - [GCC 5.4.0 20160609]
pyOpenSSL : 17.0.0 (OpenSSL 1.0.2g  1 Mar 2016)
Platform  : Linux-4.8.0-56-generic-x86_64-with-Ubuntu-16.10-yakkety



$ scrapy shell 'https://club.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv986&productId=1540024&score=0&sortType=6&page=88&pageSize=10&isShadowSku=0'
2017-06-29 18:04:03 [scrapy.utils.log] INFO: Scrapy 1.3.3 started (bot: scrapybot)
(...)
2017-06-29 18:04:03 [scrapy.core.engine] INFO: Spider opened
2017-06-29 18:04:05 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://club.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv986&productId=1540024&score=0&sortType=6&page=88&pageSize=10&isShadowSku=0> (referer: None)
[s] Available Scrapy objects:
[s]   scrapy     scrapy module (contains scrapy.Request, scrapy.Selector, etc)
[s]   crawler    <scrapy.crawler.Crawler object at 0x7f08243a99d0>
[s]   item       {}
[s]   request    <GET https://club.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv986&productId=1540024&score=0&sortType=6&page=88&pageSize=10&isShadowSku=0>
[s]   response   <200 https://club.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv986&productId=1540024&score=0&sortType=6&page=88&pageSize=10&isShadowSku=0>
[s]   settings   <scrapy.settings.Settings object at 0x7f08243a9c50>
[s]   spider     <DefaultSpider 'default' at 0x7f082072ee90>
[s] Useful shortcuts:
[s]   fetch(url[, redirect=True]) Fetch URL and update local objects (by default, redirects are followed)
[s]   fetch(req)                  Fetch a scrapy.Request and update local objects 
[s]   shelp()           Shell help (print this help)
[s]   view(response)    View response in a browser
>>> 
```

**Comment by echoocking** [comment]
2017-07-11 20:54:04 [crawler.download_middlewares.RetryMiddleware] DEBUG: Retrying <GET http://item.jd.com/12796913728.html> (failed 4 times): An error occurred while connecting: [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: filedescriptor out of range in select()
type is <class 'scrapy.http.request.Request'>
].
enter middleware~~~~
2017-07-11 20:54:04 [crawler.download_middlewares.RetryMiddleware] DEBUG: Retrying <GET http://item.jd.com/12947667879.html> (failed 5 times): An error occurred while connecting: [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: filedescriptor out of range in select()
].
2017-07-11 20:54:04 [scrapy.core.scraper] ERROR: Error downloading <GET http://item.jd.com/10652113899.html>: An error occurred while connecting: [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: filedescriptor out of range in select()
].
2017-07-11 20:54:04 [requests.packages.urllib3.connectionpool] DEBUG: Starting new HTTP connection (1): api.ip.data5u.com
2017-07-11 20:54:04 [requests.packages.urllib3.connectionpool] DEBUG: http://api.ip.data5u.com:80 "GET /dynamic/get.html?order=c7e52476eefb5bbf7a899265d274368d&ttl HTTP/1.1" 200 None
2017-07-11 20:54:04 [crawler.download_middlewares.RetryMiddleware] DEBUG: Retrying <GET http://item.jd.com/10079698928.html> (failed 5 times): An error occurred while connecting: [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: filedescriptor out of range in select()

2017-07-11 20:55:27 [crawler.download_middlewares.RetryMiddleware] DEBUG: Retrying <GET http://item.jd.com/11262125609.html> (failed 1 times): An error occurred while connecting: [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: filedescriptor out of range in select()
].
2017-07-11 20:55:27 [crawler.download_middlewares.RetryMiddleware] DEBUG: Retrying <GET http://item.jd.com/11840342414.html> (failed 7 times): An error occurred while connecting: [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: filedescriptor out of range in select()
].
2017-07-11 20:55:27 [scrapy.core.scraper] ERROR: Error downloading <GET http://item.jd.com/11519873118.html>: User timeout caused connection failure.
2017-07-11 20:55:27 [requests.packages.urllib3.connectionpool] DEBUG: Starting new HTTP connection (1): api.ip.data5u.com

my version is ..when i want use scrapy version -v to show my version .i got this!(i still can run scrapy project, so i always thought my scrapy is working fine!)
(scrapy) (scrapy) spin master ✗ 1d △ ◒ ⍉ ➜ scrapy version -v
Traceback (most recent call last):
  File "/Users/echoocking/workspace/scrapy/bin/scrapy", line 11, in <module>
    load_entry_point('Scrapy==1.3.3', 'console_scripts', 'scrapy')()
  File "/Users/echoocking/workspace/scrapy/lib/python2.7/site-packages/scrapy/cmdline.py", line 108, in execute
    settings = get_project_settings()
  File "/Users/echoocking/workspace/scrapy/lib/python2.7/site-packages/scrapy/utils/project.py", line 68, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/Users/echoocking/workspace/scrapy/lib/python2.7/site-packages/scrapy/settings/__init__.py", line 292, in setmodule
    module = import_module(module)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/echoocking/projects/spin/crawler/settings.py", line 84, in <module>
    if os.path.exists(prefix):
  File "/Users/echoocking/workspace/scrapy/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found


this scrapy project can working about an hour in my project, and this error will show,  just always loop print error...
sorry ,i  am not keep looking the progress about this issue,it is being a long time ...i am so sorry, and thank you for your concerning 👍 .i will check this issue in torrow. thanks again!

**Comment by redapple** [comment]
It may or may not be related to this issue, but what are you using `python-requests` for? (`[requests.packages.urllib3.connectionpool]` to http://api.ip.data5u.com)
It's not recommended to mix synchronous networking calls (like python-requests .get()) and asynchronous code using scrapy/twisted

**Comment by echoocking** [comment]
i am reply in a proxy api.and i want immediately get this proxy information,(do not want to cross other step in scrapy frame).so i use python-request.thank you for Your quick reply ， is very surprise!

**Comment by echoocking** [comment]
and about asynchronous code, i want keep monitoring the proxy status and get new proxy.for example is the proxy are out of time,if proxy is invalid，delete it.
    def proxy_checker(cls):
        while cls.spider_is_running:
            # cls.proxy_dict[cls.data()[0]] = datetime.datetime.now()
            proxy, time_list = cls.data().items()[0]
            print '>>>>>>>>>>>>>>>>>>>monitor  get  new proxy {}<<<<<<<<<<< '.format(proxy)
            cls.proxy_dict[proxy] = time_list  # 1 is ttl
            time.sleep(4.5)
            print '>>>>>>>>>>>.sleep over <<<<<<<<<<<<<<<<<<<<<<<'
            print '>>>>>>>>>>>>>PROXY EXIST, {}<<<<<<<<<<<<<<<<<<<<<<'.format(len(cls.proxy_dict))
            print '>>>>>>>>.proxy is {}'.format(cls.proxy_dict, datetime.datetime.now()).


**and the thread is defined at this area**
class JdSpider(CrawlSpider):
    name = 'jindong_classification'
    allow_domains = ['https://search.jd.com']
    started_on = datetime.datetime.now()
    import threading
    monitor = threading.Thread(target=HttpProxy.proxy_checker, name='proxy_monitor')
    monitor.start()

   def from_crawler
           ....

**Comment by redapple** [comment]
Something must be leaking file descriptiors. Your setup looks very custom. I don't think I can help you investigate. Again, mixing synchronous/blocking networking code (or sleep calls) is not recommended withing scrapy projects.

**Comment by echoocking** [comment]
oh,it's fine.anyway thank you ,it is my first get help back in git issue. have a good day:)
