### ISSUE TITLE
SyntaxError: invalid syntax when installing from pip, python3.5

### ISSUE THREAD

**Issue by gajop** [scrapy/scrapy#2863]
```
$ pip install scrappy
Collecting scrappy
  Using cached Scrappy-0.3.0.alpha.4.tar.gz
Collecting guessit (from scrappy)
  Using cached guessit-2.1.4.tar.gz
Collecting tvdb_api (from scrappy)
  Using cached tvdb_api-1.10.tar.gz
Collecting hachoir-metadata (from scrappy)
  Using cached hachoir-metadata-1.3.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-e218slx9/hachoir-metadata/setup.py", line 65
        except OSError, err:
                      ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-e218slx9/hachoir-metadata/
```

Edit: it installs fine on python 2.7

**Comment by kmike** [comment]
Hey, 

Proper package name is scrapy, no scrappy. "scrappy" is an unrelated package which we don't own or support.

**Comment by gajop** [comment]
Ohh, sorry, and thanks!
