### ISSUE TITLE
Python 3.6 type hinting exception

### ISSUE THREAD

**Issue by IaroslavR** [scrapy/scrapy#2914]
Got error with code:
```python
def strip_text(data) -> list:
    if isinstance(data, str):
        return [data.strip()]
    else:
        return [s.strip() for s in data if s.strip()]
```

Traceback (most recent call last):
  File "/home/elruso/.virtualenvs/3.6.1/lib/python3.6/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/home/elruso/.virtualenvs/3.6.1/lib/python3.6/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/home/elruso/.virtualenvs/3.6.1/lib/python3.6/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/home/elruso/.virtualenvs/3.6.1/lib/python3.6/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/elruso/.virtualenvs/3.6.1/lib/python3.6/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/elruso/projects/shopify/shopify/spiders/countdown.py", line 40, in level_2
    il.add_value('url', response.url)
  File "/home/elruso/.virtualenvs/3.6.1/lib/python3.6/site-packages/scrapy/loader/__init__.py", line 77, in add_value
    self._add_value(field_name, value)
  File "/home/elruso/.virtualenvs/3.6.1/lib/python3.6/site-packages/scrapy/loader/__init__.py", line 91, in _add_value
    processed_value = self._process_input_value(field_name, value)
  File "/home/elruso/.virtualenvs/3.6.1/lib/python3.6/site-packages/scrapy/loader/__init__.py", line 150, in _process_input_value
    return proc(value)
  File "/home/elruso/.virtualenvs/3.6.1/lib/python3.6/site-packages/scrapy/loader/processors.py", line 45, in __call__
    wrapped_funcs = [wrap_loader_context(f, context) for f in self.functions]
  File "/home/elruso/.virtualenvs/3.6.1/lib/python3.6/site-packages/scrapy/loader/processors.py", line 45, in <listcomp>
    wrapped_funcs = [wrap_loader_context(f, context) for f in self.functions]
  File "/home/elruso/.virtualenvs/3.6.1/lib/python3.6/site-packages/scrapy/loader/common.py", line 10, in wrap_loader_context
    if 'loader_context' in get_func_args(function):
  File "/home/elruso/.virtualenvs/3.6.1/lib/python3.6/site-packages/scrapy/utils/python.py", line 201, in get_func_args
    func_args, _, _, _ = inspect.getargspec(func)
  File "/usr/lib/python3.6/inspect.py", line 1072, in getargspec
    raise ValueError("Function has keyword-only parameters or annotations"
ValueError: Function has keyword-only parameters or annotations, use getfullargspec() API which can support them

**Comment by redapple** [comment]
@IaroslavR , thanks for reporting.
A recent fix was submitted: https://github.com/scrapy/scrapy/pull/2864
But there's no official version of Scrapy with this change.
Could you try with the current master branch?

**Comment by IaroslavR** [comment]
@redapple With current master branch works excellent. Thank you
