### ISSUE TITLE
SSLv3 method is no longer available

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapy#2951]
DOWNLOADER_CLIENT_TLS_METHOD='SSLv3' no longer works with recent Twisted, PyOpenSSL, OpenSSL, etc.:

```
scrapy shell 'https://example.com' -s DOWNLOADER_CLIENT_TLS_METHOD=SSLv3
2017-10-03 13:17:49 [scrapy.utils.log] INFO: Scrapy 1.4.0 started (bot: scrapybot)
2017-10-03 13:17:49 [scrapy.utils.log] INFO: Versions: lxml 4.0.0.0, libxml2 2.9.5, cssselect 1.0.1, parsel 1.2.0, w3lib 1.18.0, Twisted 17.9.0, Python 3.6.1 (default, Apr  4 2017, 09:40:21) - [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)], pyOpenSSL 17.3.0 (OpenSSL 1.1.0f  25 May 2017), cryptography 2.0.3, Platform Darwin-16.7.0-x86_64-i386-64bit
2017-10-03 13:17:49 [scrapy.crawler] INFO: Overridden settings: {'DOWNLOADER_CLIENT_TLS_METHOD': 'SSLv3', 'DUPEFILTER_CLASS': 'scrapy.dupefilters.BaseDupeFilter', 'EDITOR': 'nano', 'LOGSTATS_INTERVAL': 0}
2017-10-03 13:17:49 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage']
2017-10-03 13:17:49 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2017-10-03 13:17:49 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2017-10-03 13:17:49 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2017-10-03 13:17:49 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023
2017-10-03 13:17:49 [scrapy.core.engine] INFO: Spider opened
Traceback (most recent call last):
  File "/Users/kmike/envs/deepdeep/lib/python3.6/site-packages/OpenSSL/SSL.py", line 618, in __init__
    method_func = self._methods[method]
KeyError: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kmike/envs/deepdeep/bin/scrapy", line 11, in <module>
    load_entry_point('Scrapy', 'console_scripts', 'scrapy')()
  File "/Users/kmike/svn/scrapy/scrapy/cmdline.py", line 150, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/Users/kmike/svn/scrapy/scrapy/cmdline.py", line 90, in _run_print_help
    func(*a, **kw)
  File "/Users/kmike/svn/scrapy/scrapy/cmdline.py", line 157, in _run_command
    cmd.run(args, opts)
  File "/Users/kmike/svn/scrapy/scrapy/commands/shell.py", line 73, in run
    shell.start(url=url, redirect=not opts.no_redirect)
  File "/Users/kmike/svn/scrapy/scrapy/shell.py", line 48, in start
    self.fetch(url, spider, redirect=redirect)
  File "/Users/kmike/svn/scrapy/scrapy/shell.py", line 115, in fetch
    reactor, self._schedule, request, spider)
  File "/Users/kmike/envs/deepdeep/lib/python3.6/site-packages/twisted/internet/threads.py", line 122, in blockingCallFromThread
    result.raiseException()
  File "/Users/kmike/envs/deepdeep/lib/python3.6/site-packages/twisted/python/failure.py", line 385, in raiseException
    raise self.value.with_traceback(self.tb)
ValueError: No such protocol
```

**Comment by vshlapakov** [comment]
I'm pretty sure it's not a bug, after some tests and investigation I learned that `cryptography` package is linked on top of its own `openssl` package. And based on [documentation](https://cryptography.io/en/latest/installation/#building-cryptography-on-linux) and [build logs](https://ci.cryptography.io/job/cryptography-support-jobs/job/openssl-release-1.1/11/) for the openssl version, the package is built w/o SSlv3 support enabled:
```
[2010-x86_64]     no-ssl3         [default]  OPENSSL_NO_SSL3
[2010-x86_64]     no-ssl3-method  [default]  OPENSSL_NO_SSL3_METHOD
```
It [should be possible](https://stackoverflow.com/a/47351944) to recompile OpenSSL with enabled SSLv3, but not sure it's worth it: as almost everywhere([1](https://stackoverflow.com/a/45409087), [2](https://github.com/pyca/pyopenssl/issues/558#issuecomment-254058741) etc) I see that it's just unsafe to use it and believe the best we can do is officially drop its support for Scrapy.

**Comment by kmike** [comment]
👍 I think we can add a note to docs about your findings - something like "this method is usually not available in OpenSSL > ..., unless it is built with ... flags". Currently we list this method as supported ( https://doc.scrapy.org/en/latest/topics/settings.html#std:setting-DOWNLOADER_CLIENT_TLS_METHOD ).

**Comment by Kenith** [comment]
same issue here

**Comment by wRAR** [comment]
We no longer mention this methoid in the docs. #5634
