### ISSUE TITLE
Scrapy response status lines without a Reason phrase

### ISSUE THREAD

**Issue by jiayunyan** [scrapy/scrapy#2987]
C:\Users\PycharmProjects\untitled\first>scrapy crawl yjy
2017-10-31 22:12:22 [scrapy] INFO: Scrapy 1.1.0rc3 started (bot: first)
2017-10-31 22:12:22 [scrapy] INFO: Overridden settings: {'AUTOTHROTTLE_ENABLED': True, 'BOT_NAME': 'first', 'CONCURRENT_REQUESTS_PER_DOMAIN': 16, 'CONCURRENT_REQUESTS_PER_IP': 16, 'COOKIES_ENABLED': False, 'NEWSPIDER_MODULE': 'first.spiders', 'SPIDER_MODULES': ['first.spiders'], 'TELNETCONSOLE_ENABLED': False, 'USER_AGENT': 'first (+http://www.baidu.com)'}
2017-10-31 22:12:23 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.throttle.AutoThrottle']
2017-10-31 22:12:25 [scrapy] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.chunked.ChunkedTransferMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2017-10-31 22:12:25 [scrapy] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2017-10-31 22:12:25 [scrapy] INFO: Enabled item pipelines:
['first.pipelines.FirstPipeline']
2017-10-31 22:12:25 [scrapy] INFO: Spider opened
2017-10-31 22:12:25 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2017-10-31 22:12:25 [scrapy] ERROR: Error downloading <GET http://www.baidu.com/>
Traceback (most recent call last):
  File "e:\python\lib\site-packages\twisted\internet\defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "e:\python\lib\site-packages\twisted\python\failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "e:\python\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "e:\python\lib\site-packages\scrapy\utils\defer.py", line 45, in mustbe_deferred
    result = f(*args, **kw)
  File "e:\python\lib\site-packages\scrapy\core\downloader\handlers\__init__.py", line 65, in download_request
    return handler.download_request(request, spider)
  File "e:\python\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 60, in download_request
    return agent.download_request(request)
  File "e:\python\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 264, in download_request
    method, to_bytes(url, encoding='ascii'), headers, bodyproducer)
  File "e:\python\lib\site-packages\twisted\web\client.py", line 1655, in request
    parsedURI.originForm)
  File "e:\python\lib\site-packages\twisted\web\client.py", line 1432, in _requestWithEndpoint
    d = self._pool.getConnection(key, endpoint)
  File "e:\python\lib\site-packages\twisted\web\client.py", line 1318, in getConnection
    return self._newConnection(key, endpoint)
  File "e:\python\lib\site-packages\twisted\web\client.py", line 1330, in _newConnection
    return endpoint.connect(factory)
  File "e:\python\lib\site-packages\twisted\internet\endpoints.py", line 903, in connect
    EndpointReceiver, self._hostText, portNumber=self._port
  File "e:\python\lib\site-packages\twisted\internet\_resolver.py", line 189, in resolveHostName
    onAddress = self._simpleResolver.getHostByName(hostName)
  File "e:\python\lib\site-packages\scrapy\resolver.py", line 21, in getHostByName
    d = super(CachingThreadedResolver, self).getHostByName(name, timeout)
  File "e:\python\lib\site-packages\twisted\internet\base.py", line 276, in getHostByName
    timeoutDelay = sum(timeout)
TypeError: 'float' object is not iterable
2017-10-31 22:12:25 [scrapy] INFO: Closing spider (finished)
2017-10-31 22:12:25 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 1,
 'downloader/exception_type_count/builtins.TypeError': 1,
 'downloader/request_bytes': 207,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2017, 10, 31, 14, 12, 25, 541215),
 'log_count/ERROR': 1,
 'log_count/INFO': 7,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2017, 10, 31, 14, 12, 25, 126226)}
2017-10-31 22:12:25 [scrapy] INFO: Spider closed (finished)

**Comment by kmike** [comment]
I think it is fixed by https://github.com/scrapy/scrapy/pull/2496. We backported the fix to Scrapy 1.2.x, but not to 1.1.x which you're using. I suggest either upgrading Scrapy or downgrading Twisted. We won't fix it for 1.1.x.
