### ISSUE TITLE
How do I package the Scrapy project into exe?

### ISSUE THREAD

**Issue by panjunbing** [scrapy/scrapy#3007]
i try to use pyinstaller,but failed

**Comment by rmnd551** [comment]
What version of Python are you using? py2exe and pyinstaller do not seem to be working with Python 3.

**Comment by panjunbing** [comment]
@rmnd551 `win10`+`python2.7`+`scrapy1.2.2`.
I have a `setup.py` file as the program entry.this is my codes

```
# coding=utf-8


from scrapy.crawler import CrawlerProcess
from Github.spiders.Github_spider import GithubSpider
from Github.spiders.Zhihu_spider import ZhihuSpider


spider1 = GithubSpider()
spider2 = ZhihuSpider()
process = CrawlerProcess({
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Encoding": "gzip, deflate",
    "Accept-Language": "zh-CN,zh;q=0.8,en;q=0.6",
    "Cache-Control": "no-cache",
    "Connection": "keep-alive",
    "Content-Type": "application/x-www-form-urlencoded",
    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36",
    "Referer": "https://github.com/"})
process.crawl(spider1)
process.crawl(spider2)
process.start()
```
Then,i used `pyinstaller `to package `setup.py`.However,when i run the executor.It show some errors:
```
Traceback (most recent call last):
  File "Github\setup.py", line 4, in <module>
  File "c:\users\panpan\appdata\local\temp\pip-build-jzyyo4\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\scrapy\__init__.py", line 10, in <module>
  File "pkgutil.py", line 591, in get_data
  File "c:\users\panpan\appdata\local\temp\pip-build-jzyyo4\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 479, in get_data
IOError: [Errno 2] No such file or directory: 'C:\\Users\\panpan\\dist\\setup\\scrapy\\VERSION'
[5792] Failed to execute script setup
```
Please help me.

**Comment by kmike** [comment]
We're using Scrapy issue tracker for bugs and feature proposals; for general Scrapy help there are better channels like https://stackoverflow.com (use tag "Scrapy") or https://www.reddit.com/r/scrapy/.
