### ISSUE TITLE
startproject command does not work for latest pyOpenSSL version

### ISSUE THREAD

**Issue by cisko3000** [scrapy/scrapy#3024]
I did an install of scrapy on virtualenv, upgraded all packages and command "startproject" did not work.
I would get his error:
```
Traceback (most recent call last):
  File "/home/me/sites/cot/env/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/home/me/sites/cot/env/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 121, in execute
    cmds = _get_commands_dict(settings, inproject)
  File "/home/me/sites/cot/env/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 45, in _get_commands_dict
    cmds = _get_commands_from_module('scrapy.commands', inproject)
  File "/home/me/sites/cot/env/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 28, in _get_commands_from_module
    for cmd in _iter_command_classes(module):
  File "/home/me/sites/cot/env/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 19, in _iter_command_classes
    for module in walk_modules(module_name):
  File "/home/me/sites/cot/env/local/lib/python2.7/site-packages/scrapy/utils/misc.py", line 71, in walk_modules
    submod = import_module(fullpath)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/me/sites/cot/env/local/lib/python2.7/site-packages/scrapy/commands/version.py", line 6, in <module>
    import OpenSSL
  File "/home/me/sites/cot/env/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/home/me/sites/cot/env/local/lib/python2.7/site-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/home/me/sites/cot/env/local/lib/python2.7/site-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509 import certificate_transparency
ImportError: cannot import name certificate_transparency

```
So I went to an environment where I was able to do startproject (over a year ago), and noticed it has pyOpenSSL version 16.0.0. and then installed this version and then I was able to startproject using latest environment and latest scrapy.

What is up with this? Is this something I can fix here in this scrapy repo?

**Comment by dhruv-aggarwal** [comment]
@cisko3000 what version of cryptography are you using?

**Comment by cisko3000** [comment]
@dhruv-aggarwal I ran pip freeze and it says cryptography==2.1.4
