### ISSUE TITLE
Exception raises on scrapy shell.

### ISSUE THREAD

**Issue by PerezFederico** [scrapy/scrapy#3032]
**Running:**

    scrapy shell "https://pcsupport.lenovo.com/ar/en/"

**Rises:**

> Traceback (most recent call last):
>   File "/usr/local/bin/scrapy", line 11, in <module>
>     sys.exit(execute())
>   File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 149, in execute
>     _run_print_help(parser, _run_command, cmd, args, opts)
>   File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 89, in _run_print_help
>     func(*a, **kw)
>   File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 156, in _run_command
>     cmd.run(args, opts)
>   File "/usr/local/lib/python2.7/dist-packages/scrapy/commands/shell.py", line 73, in run
>     shell.start(url=url, redirect=not opts.no_redirect)
>   File "/usr/local/lib/python2.7/dist-packages/scrapy/shell.py", line 48, in start
>     self.fetch(url, spider, redirect=redirect)
>   File "/usr/local/lib/python2.7/dist-packages/scrapy/shell.py", line 115, in fetch
>     reactor, self._schedule, request, spider)
>   File "/usr/local/lib/python2.7/dist-packages/twisted/internet/threads.py", line 122, in blockingCallFromThread
>     result.raiseException()
>   File "<string>", line 2, in raiseException
> AttributeError: 'module' object has no attribute 'OP_SINGLE_ECDH_USE'

I can help fixing it if you can give me some insight on what can be happening. Thanks.

**Comment by PerezFederico** [comment]
Sorry, not a bug.
Fixed:

    sudo apt-get install libssl-dev
    pip install pyopenssl --upgrade

I have two suggestions:

- Scrapy should automatically install dependencies because I have encountered several cases when this is not happening.
- This dependencies should be checked to avoid this cryptic messages for the newbies and unaware ones.

Anyway, very good job with this tool. Thanks
