### ISSUE TITLE
Can I get some guidance for outputting scraped data and images to a GCP bucket?

### ISSUE THREAD

**Issue by zinyosrim** [scrapy/scrapy#3044]
managed S3 through settings.py but still struggling with Google cloud.
Thanks
Zin

**Comment by kmike** [comment]
For images and files Scrapy master (not 1.4 release) has GCS support - see https://doc.scrapy.org/en/master/topics/media-pipeline.html#id1. There is no GCS support for feed exports yet, you'll need to write custom code for this.

**Comment by zinyosrim** [comment]
I installed Scrapy from master with `pip install git+git://github.com/scrapy/scrapy.git`
included the GCP params in settings.py
```
IMAGES_STORE = 'gs://xxxx/xxxxx'
GCS_PROJECT_ID = 'xxxxx' 
```
exported API credentials `export GOOGLE_APPLICATION_CREDENTIALS=Google-Api-Key.json`
and ran the crawler `scrapy crawl phillips -o tuto.json`
My scraping data output looks ok:
```
   ...
   "width": 181.0,
   "size_unit": "cm",
   "image_urls": [
        "https://assets.phillips.com/image/upload/f_auto,t_Website_LotDetailMainImage/v1/auctions/UK010417/2_001.jpg"
    ],
    "images": [
        {
            "url": "https://assets.phillips.com/image/upload/f_auto,t_Website_LotDetailMainImage/v1/auctions/UK010417/2_001.jpg",
            "path": "full/c1d029d83c289392f86476203bbd26b21baad724.jpg",
            "checksum": "c466f616e0f4196f1172340b40e3dd77"
        }
    ]
    ...
```
But the images aren't uploaded to the bucket. I see following error messages in the scraping log:
```
Unhandled error in Deferred:
2017-12-21 09:59:30 [twisted] CRITICAL: Unhandled error in Deferred:

2017-12-21 09:59:30 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/Users/dtm/anaconda/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 946, in upload_from_file
    client, file_obj, content_type, size, num_retries)
  File "/Users/dtm/anaconda/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 867, in _do_upload
    client, stream, content_type, size, num_retries)
  File "/Users/dtm/anaconda/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 700, in _do_multipart_upload
    transport, data, object_metadata, content_type)
  File "/Users/dtm/anaconda/lib/python3.6/site-packages/google/resumable_media/requests/upload.py", line 98, in transmit
    self._process_response(result)
  File "/Users/dtm/anaconda/lib/python3.6/site-packages/google/resumable_media/_upload.py", line 110, in _process_response
    response, (http_client.OK,), self._get_status_code)
  File "/Users/dtm/anaconda/lib/python3.6/site-packages/google/resumable_media/_helpers.py", line 93, in require_status_code
    status_code, u'Expected one of', *status_codes)
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>)

```
plus a number of other _During handling of the above exception, another exception occurred_ messages.

Any idea what's going wrong here?
Zin

**Comment by dangra** [comment]
hi @zinyosrim, for support request please use [stackoverflow](https://stackoverflow.com/tags/scrapy) or https://reddit.com/r/scrapy.

I dont have much experience with GCS but the error suggests the GCS bucket doesn't exists or the credentials are not valid.
