### ISSUE TITLE
`Connection to the other side was lost` for older French site

### ISSUE THREAD

**Issue by autumnjolitz** [scrapy/scrapy#3065]
Hi,

I'm attempting to run scrapy on `https://agences.creditfoncier.fr/credit-immobilier/toutes-nos-agences`.

Despite upgrading all my brew packages, scrapy installation via `pip install -U scrapy`, the website disconnects uncleanly. Specifying `-s DOWNLOADER_CLIENT_TLS_METHOD=TLSv1.0` makes no difference to the following run. Neither does a user-agent clear things up with `-s USER_AGENT="Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.93 Safari/537.36"`

I am uncertain as how to debug this further.

`scrapy shell https://agences.creditfoncier.fr/credit-immobilier/toutes-nos-agences`

```
2018-01-09 18:03:33 [scrapy.utils.log] INFO: Scrapy 1.5.0 started (bot: scrapybot)
2018-01-09 18:03:33 [scrapy.utils.log] INFO: Versions: lxml 4.1.1.0, libxml2 2.9.7, cssselect 1.0.3, parsel 1.3.1, w3lib 1.18.0, Twisted 17.9.0, Python 3.6.2 (default, Jul 17 2017, 16:44:45) - [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)], pyOpenSSL 17.5.0 (OpenSSL 1.1.0g  2 Nov 2017), cryptography 2.1.4, Platform Darwin-16.7.0-x86_64-i386-64bit
2018-01-09 18:03:33 [scrapy.crawler] INFO: Overridden settings: {'DOWNLOADER_CLIENT_TLS_METHOD': 'TLSv1.0', 'DUPEFILTER_CLASS': 'scrapy.dupefilters.BaseDupeFilter', 'LOGSTATS_INTERVAL': 0}
2018-01-09 18:03:33 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage']
2018-01-09 18:03:33 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-01-09 18:03:33 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-01-09 18:03:33 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2018-01-09 18:03:33 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023
2018-01-09 18:03:33 [scrapy.core.engine] INFO: Spider opened
2018-01-09 18:03:34 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://agences.creditfoncier.fr/credit-immobilier/toutes-nos-agences> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]
2018-01-09 18:03:34 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://agences.creditfoncier.fr/credit-immobilier/toutes-nos-agences> (failed 2 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]
2018-01-09 18:03:35 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET https://agences.creditfoncier.fr/credit-immobilier/toutes-nos-agences> (failed 3 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]
Traceback (most recent call last):
  File "/Users/BenJolitz/.virtualenvs/cpython36/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/Users/BenJolitz/.virtualenvs/cpython36/lib/python3.6/site-packages/scrapy/cmdline.py", line 150, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/Users/BenJolitz/.virtualenvs/cpython36/lib/python3.6/site-packages/scrapy/cmdline.py", line 90, in _run_print_help
    func(*a, **kw)
  File "/Users/BenJolitz/.virtualenvs/cpython36/lib/python3.6/site-packages/scrapy/cmdline.py", line 157, in _run_command
    cmd.run(args, opts)
  File "/Users/BenJolitz/.virtualenvs/cpython36/lib/python3.6/site-packages/scrapy/commands/shell.py", line 73, in run
    shell.start(url=url, redirect=not opts.no_redirect)
  File "/Users/BenJolitz/.virtualenvs/cpython36/lib/python3.6/site-packages/scrapy/shell.py", line 48, in start
    self.fetch(url, spider, redirect=redirect)
  File "/Users/BenJolitz/.virtualenvs/cpython36/lib/python3.6/site-packages/scrapy/shell.py", line 115, in fetch
    reactor, self._schedule, request, spider)
  File "/Users/BenJolitz/.virtualenvs/cpython36/lib/python3.6/site-packages/twisted/internet/threads.py", line 122, in blockingCallFromThread
    result.raiseException()
  File "/Users/BenJolitz/.virtualenvs/cpython36/lib/python3.6/site-packages/twisted/python/failure.py", line 385, in raiseException
    raise self.value.with_traceback(self.tb)
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]
```

`scrapy version -v`:
```
Scrapy       : 1.5.0
lxml         : 4.1.1.0
libxml2      : 2.9.7
cssselect    : 1.0.3
parsel       : 1.3.1
w3lib        : 1.18.0
Twisted      : 17.9.0
Python       : 3.6.2 (default, Jul 17 2017, 16:44:45) - [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
pyOpenSSL    : 17.5.0 (OpenSSL 1.1.0g  2 Nov 2017)
cryptography : 2.1.4
Platform     : Darwin-16.7.0-x86_64-i386-64bit
```

`curl -sLv https://agences.creditfoncier.fr/credit-immobilier/toutes-nos-agences 2>&1 | head -20`:
```
*   Trying 160.92.134.3...
* TCP_NODELAY set
* Connected to agences.creditfoncier.fr (160.92.134.3) port 443 (#0)
* TLS 1.0 connection using TLS_RSA_WITH_3DES_EDE_CBC_SHA
* Server certificate: agences.creditfoncier.fr
* Server certificate: RapidSSL RSA CA 2018
* Server certificate: DigiCert Global Root CA
> GET /credit-immobilier/toutes-nos-agences HTTP/1.1
> Host: agences.creditfoncier.fr
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Wed, 10 Jan 2018 02:06:54 GMT
< Server: Microsoft-IIS/6.0
< X-Powered-By: ASP.NET
< Content-Length: 35884
< Content-Type: text/html
< Set-Cookie: ASPSESSIONIDQQBACDTS=JHOJNNCCJNIFABOPLNCEEAFH; path=/
< Cache-control: private
```

**Comment by benjolitz** [comment]
Requests seems to have trouble talking to that site as well:

```
(cpython27) btj-gt:~/software/scrapy [staging]$ python
Python 2.7.13 (default, Jul 18 2017, 09:17:00)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
re>>> requests.get('https://agences.creditfoncier.fr/credit-immobilier/toutes-nos-agences')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/BenJolitz/.virtualenvs/cpython27/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/BenJolitz/.virtualenvs/cpython27/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/BenJolitz/.virtualenvs/cpython27/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/BenJolitz/.virtualenvs/cpython27/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/BenJolitz/.virtualenvs/cpython27/lib/python2.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='agences.creditfoncier.fr', port=443): Max retries exceeded with url: /credit-immobilier/toutes-nos-agences (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))
>>>
```

**Comment by cathalgarvey** [comment]
Hey @benjolitz - I followed your progress through the other libraries. I think this raises an interesting problem for Scrapy, all right. And it keeps coming up, too. Our upstream SSL/TLS libraries are removing bad cipher-sets for security reasons, and that's the right call in most cases. But, when Scraping we are often not concerned with confidentiality, and sometimes not even message integrity. So, it would be nice if Scrapy could ignore the badness of a cipher-suite, if it has to be used to visit the site successfully.

Were you able to solve your problem in the end? Did it require custom builds of the affected libraries, or were you able to get them to work without needing anything to be recompiled?

**Comment by benjolitz** [comment]
I use this helper function to validate input ciphers:

```
from scrapy.core.downloader.tls import AcceptableCiphers

def detect_missing_ciphers(ciphers: str):
    '''
    Given a list of EXTRA_CIPHERS, test if each one exists inside our
    bundled OpenSSL for cryptography.
    '''
    missing_ciphers = set()
    for cipher in frozenset(ciphers.split(':')):
        try:
            if not AcceptableCiphers.fromOpenSSLCipherString(cipher)._ciphers:
                missing_ciphers.add(cipher)
        except ValueError as e:
            if 'no usable ciphers' in str(e).lower():
                missing_ciphers.add(cipher)
                continue
            raise
    return frozenset(missing_ciphers)
```

In my framework which translates imperative BS4/requests scrapers to Scrapy ones, I support cipher overrides through use of a phase that calls the above helper, raises a ValueError if there are any missing ciphers, then make use of a custom HTTPDownloadHandler that passes the `ciphers` to the downloader's `_contextFactoryClass`, and said contextFactoryClass which is overridden and specified in Scrapy settings.

That `CustomClientContextFactory` effectively ends up passing the valid ciphers through setting `self.ciphers = AcceptableCiphers.fromOpenSSLCipherString(ciphers + ':DEFAULT')` in the constructor, then passes `self.ciphers` to the `getCertificateOptions` method in the `CertificateOptions(acceptableCiphers=self.ciphers, ...)` return value.

**Comment by vionemc** [comment]
Is it possible to just create a setting to turn off security on some? Sometimes we are scraping sites that are our partner and of course we trust each other. There is no need for security.

**Comment by Laerte** [comment]
> Does anyone have a solution? I am still facing this issue.

What is the endpoint? It works via browser?

**Comment by hamzathul** [comment]
> > Does anyone have a solution? I am still facing this issue.
> 
> What is the endpoint? It works via browser?

This is the link: https://www.olx.in/
it works via browser

![Screenshot from 2024-11-29 07-55-55](https://github.com/user-attachments/assets/f28e7b4c-60f3-4d64-8414-6be1053d1d6f)

**Comment by Laerte** [comment]
@hamzathul Can you try using this setting below? Worked like a charm to me.

```python
  custom_settings = {
      "DOWNLOADER_CLIENTCONTEXTFACTORY": "scrapy.core.downloader.contextfactory.BrowserLikeContextFactory"
  }
```
