### ISSUE TITLE
install scrapy failed on Mac OS X High Sierra

### ISSUE THREAD

**Issue by kintela** [scrapy/scrapy#3088]
Hi
I'm trying to install Scarpy in Mac OSX High Sierra after install python by Homebrew but always start with this warning:

"The directory '/Users/kintela/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag."

I have checked that the current user "Kintela" is owner and has read/write permissons in that folders.

After the process i get this error
Installing collected packages: six, w3lib, cssselect, lxml, parsel, attrs, pyasn1, pyasn1-modules, service-identity, queuelib, PyDispatcher, constantly, incremental, hyperlink, Automat, Twisted, scrapy
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-M8QFCu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

Any idea please?

Regards

**Comment by kintela** [comment]
Hi
I have solved trying this other command: sudo pip install scrapy --ignore-installed six
Regards

**Comment by kmike** [comment]
Glad you've resolved it! Though a better way is to create a virtualenv, as described in Scrapy docs (e.g. https://doc.scrapy.org/en/latest/intro/install.html#using-a-virtual-environment-recommended).
