### ISSUE TITLE
url_is_from_spider fails if allowed_domains defined with @property decorator

### ISSUE THREAD

**Issue by pawelmhm** [scrapy/scrapy#3119]
I got some unusual spider that was getting allowed domains like this

```python
@property 
def allowed_domains(self):
    # 2nd domain generated dynamically
     return ['domain1com', self.generate_2nd_domain]
```

This was failing in scrapy shell:

```
Traceback (most recent call last):
  File "/home/pawel/.virtualenvs/scrapy/bin/scrapy", line 11, in <module>
    load_entry_point('Scrapy', 'console_scripts', 'scrapy')()
  File "/home/pawel/prog_langs/py/dev_scrapy/scrapy/scrapy/cmdline.py", line 149, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/home/pawel/prog_langs/py/dev_scrapy/scrapy/scrapy/cmdline.py", line 89, in _run_print_help
    func(*a, **kw)
  File "/home/pawel/prog_langs/py/dev_scrapy/scrapy/scrapy/cmdline.py", line 156, in _run_command
    cmd.run(args, opts)
  File "/home/pawel/prog_langs/py/dev_scrapy/scrapy/scrapy/commands/shell.py", line 61, in run
    spidercls, log_multiple=True)
  File "/home/pawel/prog_langs/py/dev_scrapy/scrapy/scrapy/utils/spider.py", line 43, in spidercls_for_request
    snames = spider_loader.find_by_request(request)
  File "/home/pawel/prog_langs/py/dev_scrapy/scrapy/scrapy/spiderloader.py", line 78, in find_by_request
    if cls.handles_request(request)]
  File "/home/pawel/prog_langs/py/dev_scrapy/scrapy/scrapy/spiders/__init__.py", line 98, in handles_request
    return url_is_from_spider(request.url, cls)
  File "/home/pawel/prog_langs/py/dev_scrapy/scrapy/scrapy/utils/url.py", line 31, in url_is_from_spider
    [spider.name] + list(getattr(spider, 'allowed_domains', [])))
TypeError: 'property' object is not iterable
````

It turns out that `url_is_from_spider` is called with class and not with instance, and in Python 2.7 this works like this

```python
In [1]: class alfa(object):
   ...:     @property
   ...:     def malta(self):
   ...:         return "a"
   ...:     

In [2]: alfa.malta
Out[2]: <property at 0x7f8fda62c470>

In [3]: alfa().malta
Out[3]: 'a'
```

so property of class is not iterable.

Our tests are not detecting this case. They always test with spider instance, and utility is also called with spider class. 

I created following (failing) unit test in tests/test_utils_url.py

```python
    def test_url_is_from_spider_allowed_domains_property(self):
        class PropertySpider(Spider):
            @property
            def allowed_domains(self):
                return ['example.com']

        spider = PropertySpider
        self.assertTrue(url_is_from_spider('http://www.example.com/some/page.html', spider))
        self.assertTrue(url_is_from_spider('http://sub.example.com/some/page.html', spider))
        self.assertFalse(url_is_from_spider('http://www.example.org/some/page.html', spider))
        self.assertFalse(url_is_from_spider('http://www.example.net/some/page.html', spider))
```

so now question how to solve this. 

For me this **only affected scrapy shell**, so it is not urgent, I already fixed that by reworking spider, but potentially it could have some side effects somewhere?

**Comment by kmike** [comment]
See also: https://github.com/scrapy/scrapy/pull/1640.
