### ISSUE TITLE
Unable to parse shift_jis encoded page that doesn't specify encoding

### ISSUE THREAD

**Issue by nickhall-m3** [scrapy/scrapy#3135]
I'm trying to get data from this page: http://www.dis.h.u-tokyo.ac.jp/byomei/icd10_2013/index.html . The markup is ancient and it doesn't properly set its character encoding, but it is shift jis according to Chrome.

```
document.characterSet
"Shift_JIS"
```

I get the page with this scrapy call.

```
yield scrapy.Request(url=url, callback=self.parse, encoding='shift-jis')
```

I manually set the encoding, but the output is nonetheless garbled:

```
2018-02-22 16:14:09 [scrapy.core.scraper] DEBUG: Scraped from <200 http://www.dis.h.u-tokyo.ac.jp/byomei/icd10_2013/index.html>
{'code': 'A00-B99', 'name': '��������������������'}
```

Likewise from the shell:

```
In [1]: response.css('title::text').extract()
Out[1]: ['ICD10 �������a������10��2013�N��']
```

The parse runs as follows:

```
    def parse(self, response):
        for row in response.css('table:nth-of-type(2) tr'):
            yield {
                'code': row.css('td:nth-child(2) font::text').extract_first(),
                'name': row.css('td:nth-child(3) b::text').extract_first()
            }
```

How can I get the proper output?

python 3.6.4, scrapy 1.5.0

**Comment by kmike** [comment]
So, this page doesn't declare its encoding, neither in HTTP headers, nor in html. Chrome uses char statistics in this case to set an encoding; by default Scrapy uses utf-8 in this case. I think using some encoding-detection library as a fallback can be an improvement for Scrapy.

Request encoding defines how request parameters are going to be encoded, it doesn't affect response encoding.

To get proper output construct Selector manually, with properly decoded body - don't rely on response.css shortcut:

```
>>> from parsel import Selector
>>> sel = Selector(response.body.decode('shift-jis'))
>>> sel.css('title::text').get()
'ICD10 国際疾病分類第10版2013年版'
```

**Comment by nickhall-m3** [comment]
Fantastic, thank you. That should work for now. My question then transitions to what the point of passing `endocing='shift-jis'` to the `Request` was. My assumption was that manually specifying the encoding would override the default/lack of setting in the page itself.

**Comment by cathalgarvey** [comment]
Hi @nickhall-m3 - The `encoding` argument instructs the `Request` type to encode the request body using that encoding, and to add appropriate headers to the Request for the server to use. See [here](https://scrapy.readthedocs.io/en/latest/topics/request-response.html) for more information.

But, the server is still free to return whatever encoding it likes. It _should_ return that with a header or meta tag to tell you what it's sending, but some servers don't, like this one.

If you're looking for a way to auto-detect encoding, kinda like how Chrome does it, the popular answer in Python land is to use [`chardet`](https://github.com/chardet/chardet). Using that and @kmike's example code above, you should be able to get it right 99% of the time when no header is provided by the server.

I hope that helps; is it OK if we close this issue?

**Comment by kmike** [comment]
> The encoding argument instructs the Request type to encode the request body using that encoding, and to add appropriate headers to the Request for the server to use.
> But, the server is still free to return whatever encoding it likes. It should return that with a header or meta tag to tell you what it's sending, but some servers don't, like this one.

`encoding` argument is not used to add any additional headers; it doesn't affect what server returns, besides encoding request parameters to this specified encoding. This argument is useful when server expects non-UTF8 encoded data, e.g. latin1.

I think there are things to improve in Scrapy regarding this issue, so maybe we shouldn't close it right now:

1) Maybe request.encoding should be used as a fallback for response.encoding when encoding can't be detected?
2) Maybe we should provide encoding auto-detection by default? If so, which library to use? Is the performance penalty acceptable? I'm not sure we can use chardet as it is LGPL - if I'm not mistaken, there are different opinions on how it works in such cases.
3) Maybe there should be an easier, official way to override response encoding?

**Comment by nickhall-m3** [comment]
My issue is, given the provided solution, effectively solved, but I do have to echo the sentiment that some sort of handling of this kind of case from within scrapy would have saved me a few headaches. So the decision of whether or not to close is now in your hands.

**Comment by cathalgarvey** [comment]
@kmike - My understanding of the LGPL is that it would permit use of the library without concern for our own licensing. LGPL licensed code can even be used by fully proprietary projects without issue.

If we're concerned about the ambiguity of LGPL language like "linking" WRT to Python, or we're worried the authors might object, we could always ask. :)

I do think auto-detection of encoding would be a big improvement to Scrapy, so I'd be happy to see `chardet` added.

**Comment by petervandenabeele** [comment]
A related issue, or not (?), is that sometimes this assignment from `response.encoding` fails because that attribute is not defined. I obviously can build a try-catch block around it. But maybe setting the attribute anyway, to  an empty string or "unknown" would be easier to process?

```
2020-01-23 23:54:44 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.____.com/docs/view/5e25aa7ec4e74-en> (referer: None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/usr/local/lib/python3.7/dist-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.7/dist-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/usr/local/lib/python3.7/dist-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.7/dist-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/usr/local/lib/python3.7/dist-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.7/dist-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python3.7/dist-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.7/dist-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python3.7/dist-packages/scrapy/spiders/crawl.py", line 108, in _parse_response
    for requests_or_item in iterate_spider_output(cb_res):
  File "/root/scraper/scraper/spiders/broadSpider.py", line 175, in parse_item
    item['encoding'] = response.encoding
AttributeError: 'Response' object has no attribute 'encoding'
```
