### ISSUE TITLE
Incorrect return code for spiders with exception raising in __init__ or from_crawler

### ISSUE THREAD

**Issue by whalebot-helmsman** [scrapy/scrapy#3211]
Sometimes you raise an exception from spider `__init__` or `from_crawler` methods. Exit code of `scrapy runspider discovery.py` process is 0 in such case. This behaviour prevents correct management of spider runs by any supervisor.  

Should scrapy report such problems using non-zero exit code?

E.g. for spider
```
import scrapy

class DiscoverySpider(scrapy.Spider):
    name = 'discovery'

    @classmethod
    def from_crawler(cls, crawler, *args, **kwargs):
        raise ValueError('Exception in from_crawler method')
```

output is 

```
[]$  scrapy runspider discovery.py 
2018-04-11 12:51:22 [scrapy.utils.log] INFO: Scrapy 1.5.0 started (bot: scrapybot)
2018-04-11 12:51:22 [scrapy.utils.log] INFO: Versions: lxml 4.0.0.0, libxml2 2.9.5, cssselect 1.0.1, parsel 1.2.0, w3lib 1.18.0, Twisted 17.9.0, Python 3.4.3 (default, Nov 17 2016, 01:08:31) - [GCC 4.8.4], pyOpenSSL 17.3.0 (OpenSSL 1.1.0f  25 May 2017), cryptography 2.0.3, Platform Linux-4.4.0-96-generic-x86_64-with-Ubuntu-14.04-trusty
2018-04-11 12:51:22 [scrapy.crawler] INFO: Overridden settings: {'SPIDER_LOADER_WARN_ONLY': True}
2018-04-11 12:51:22 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.memusage.MemoryUsage']
Unhandled error in Deferred:
2018-04-11 12:51:22 [twisted] CRITICAL: Unhandled error in Deferred:

2018-04-11 12:51:22 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "python3.4/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "python3.4/site-packages/scrapy/crawler.py", line 79, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "python3.4/site-packages/scrapy/crawler.py", line 102, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)
  File "fail/discovery.py", line 9, in from_crawler
    raise ValueError('Exception in from crawler method')
ValueError: Exception in from crawler method

[]$ echo $?
0
```

**Comment by kmike** [comment]
+1 to have a non-zero code for `scrapy runspider` when spider fails in from_crawler or `__init__` methods. See also: https://github.com/scrapy/scrapy/issues/1241.

**Comment by whalebot-helmsman** [comment]
Added https://github.com/scrapy/scrapy/pull/3226

**Comment by kmike** [comment]
Fixed by https://github.com/scrapy/scrapy/pull/3226.
