### ISSUE TITLE
Can't run `scrapy startproject tutorial`

### ISSUE THREAD

**Issue by dustinmichels** [scrapy/scrapy#3215]
I can't seem to run the `scrapy startproject tutorial` command successfully (though I've been to in the past).

- I'm using macOS High Sierra, 10.13.4 (recently updated)
- I created a fresh conda environment with `conda create --name scrape python=3.6` and `source activate scrape`
- I ran `conda install -c conda-forge scrapy` then `scrapy startproject tutorial`

I get this error:

```
Traceback (most recent call last):
  File "/Users/dustymichels/miniconda3/bin/scrapy", line 7, in <module>
    from scrapy.cmdline import execute
  File "/Users/dustymichels/miniconda3/lib/python3.6/site-packages/scrapy/__init__.py", line 34, in <module>
    from scrapy.spiders import Spider
  File "/Users/dustymichels/miniconda3/lib/python3.6/site-packages/scrapy/spiders/__init__.py", line 10, in <module>
    from scrapy.http import Request
  File "/Users/dustymichels/miniconda3/lib/python3.6/site-packages/scrapy/http/__init__.py", line 11, in <module>
    from scrapy.http.request.form import FormRequest
  File "/Users/dustymichels/miniconda3/lib/python3.6/site-packages/scrapy/http/request/form.py", line 11, in <module>
    import lxml.html
  File "/Users/dustymichels/miniconda3/lib/python3.6/site-packages/lxml/html/__init__.py", line 54, in <module>
    from .. import etree
ImportError: dlopen(/Users/dustymichels/miniconda3/lib/python3.6/site-packages/lxml/etree.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libicui18n.58.dylib
  Referenced from: /Users/dustymichels/miniconda3/lib/libxslt.1.dylib
  Reason: image not found
```

Also: `xcode-select --install` returns
> `xcode-select: error: command line tools are already installed, use "Software Update" to install updates`

**Comment by lopuhin** [comment]
@dustinmichels this looks like one of scrapy dependencies, ``lxml`` library, did not get installed correctly. Unfortunately I'm not a conda user, but lxml installed with ``pip`` coming from python3.6 works for me on OS X in a virtual environment.

**Comment by dustinmichels** [comment]
@lopuhin , computer said `lxml` was already installed. But it seems the command mysteriously works now! The problem may have been fixed by simply deactivating and reactivating the conda virtual environment? Thank you very much for your reply.

**Comment by lopuhin** [comment]
Glad that you solved it @dustinmichels !
