### ISSUE TITLE
Using twisted threads inside parse function

### ISSUE THREAD

**Issue by richa-saraf** [scrapy/scrapy#3236]
I have a blocking and time consuming method which needs to be invoked from parse() function.
I wanted another thread to handle the above function. Going through the comments, my guess is I need to use twisted thread to perform this. I was wondering if anyone could point me toward the documentation which list examples of how this can be achieved?

**Comment by grammy-jiang** [comment]
Hi, @richa-saraf ,

Your question is interesting. Scrapy is built on [Twisted](https://twistedmatrix.com/trac/), so the relative documentations are all recorded there:

- [Using Threads in Twisted — Twisted 17.9.0 documentation](https://twistedmatrix.com/documents/current/core/howto/threading.html)
- [twisted.internet.threads.deferToThread : API documentation](https://twistedmatrix.com/documents/current/api/twisted.internet.threads.deferToThread.html)

**Comment by richa-saraf** [comment]
Yeah, I keep getting the following error when I do 
d = threads.deferToThread(ractor, my_func())
d.addCallback(func_name)

I am unable to understand how can I use the twisted functions inside parse()

2018-04-24 16:28:00 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/richa/ENV/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/richa/ENV/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/richa/ENV/local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/richa/ENV/local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
TypeError: 'EPollReactor' object is not callable

**Comment by ShadowAZL** [comment]
I think you did not use deferToThread correctly !
The first arg of deferToThread is the function you want run in other thread.
You should do follow:
`d = threads.deferToThread(my_func, args, kwargs)
`

**Comment by AdrianAtZyte** [comment]
Fixed in #7349, released in Scrapy 2.15.0 (2026-04-09).
