### ISSUE TITLE
Scrapy in High Sierra

### ISSUE THREAD

**Issue by canonlp** [scrapy/scrapy#3286]
I'm getting this error when I run scrapy. Any ideas how to solve this?

`Unhandled error in Deferred:
2018-06-09 16:48:56 [twisted] CRITICAL: Unhandled error in Deferred:

2018-06-09 16:48:56 [twisted] CRITICAL:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/site-packages/scrapy/crawler.py", line 98, in crawl
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/scrapy/crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "/usr/local/lib/python2.7/site-packages/scrapy/crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/local/lib/python2.7/site-packages/scrapy/core/engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "/usr/local/lib/python2.7/site-packages/scrapy/core/scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/usr/local/lib/python2.7/site-packages/scrapy/middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/local/lib/python2.7/site-packages/scrapy/middleware.py", line 36, in from_settings
    mw = mwcls.from_crawler(crawler)
  File "/usr/local/lib/python2.7/site-packages/scrapy/pipelines/media.py", line 68, in from_crawler
    pipe = cls.from_settings(crawler.settings)
  File "/usr/local/lib/python2.7/site-packages/scrapy/pipelines/images.py", line 98, in from_settings
    return cls(store_uri, settings=settings)
  File "/usr/local/lib/python2.7/site-packages/scrapy/pipelines/images.py", line 52, in __init__
    download_func=download_func)
  File "/usr/local/lib/python2.7/site-packages/scrapy/pipelines/files.py", line 276, in __init__
    self.store = self._get_store(store_uri)
  File "/usr/local/lib/python2.7/site-packages/scrapy/pipelines/files.py", line 315, in _get_store
    return store_cls(uri)
  File "/usr/local/lib/python2.7/site-packages/scrapy/pipelines/files.py", line 48, in __init__
    self._mkdir(self.basedir)
  File "/usr/local/lib/python2.7/site-packages/scrapy/pipelines/files.py", line 77, in _mkdir
    os.makedirs(dirname)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 45] Operation not supported: '/home/admin'`

**Comment by wRAR** [comment]
Hello @canonlp, the error arises when creating a dir for your `IMAGES_STORE` settings value. Looks like it is just `"/home/admin"`? This looks wrong.
