### ISSUE TITLE
Not able to install scrapy via pip in macOS Sierra

### ISSUE THREAD

**Issue by Amithsk** [scrapy/scrapy#3290]
Hello,
I am trying to install scrapy via pip,but getting an error
Command: pip install Scrapy
o/p
(scrapy) apples-MacBook-Air:scrapy Amith$ pip install Scrapy
Collecting Scrapy
  Using cached https://files.pythonhosted.org/packages/db/9c/cb15b2dc6003a805afd21b9b396e0e965800765b51da72fe17cf340b9be2/Scrapy-1.5.0-py2.py3-none-any.whl
Requirement already satisfied: lxml in /Library/Python/2.7/site-packages (from Scrapy) (4.2.1)
Collecting PyDispatcher>=2.0.5 (from Scrapy)
  Using cached https://files.pythonhosted.org/packages/cd/37/39aca520918ce1935bea9c356bcbb7ed7e52ad4e31bff9b943dfc8e7115b/PyDispatcher-2.0.5.tar.gz
Collecting Twisted>=13.1.0 (from Scrapy)
  Using cached https://files.pythonhosted.org/packages/12/2a/e9e4fb2e6b2f7a75577e0614926819a472934b0b85f205ba5d5d2add54d0/Twisted-18.4.0.tar.bz2
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/incremental/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'incremental' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
    No local packages or download links found for incremental>=16.10.1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vk/wbp690w965gcdvmg_67chy380000gn/T/pip-install-9zdxXV/Twisted/setup.py", line 21, in <module>
        setuptools.setup(**_setup["getSetupArgs"]())
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 843, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1088, in best_match
        return self.obtain(req, installer)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1100, in obtain
        return installer(requirement)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 632, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('incremental>=16.10.1')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vk/wbp690w965gcdvmg_67chy380000gn/T/pip-install-9zdxXV/Twisted/

**Comment by Amithsk** [comment]
Got the solution

**pip install --upgrade incremental**
Able to solve the error  :)

**Comment by Amithsk** [comment]
Third error:
Command: sudo pip install Scrapy
Error:
Installing collected packages: attrs, Automat, idna, hyperlink, constantly, zope.interface, Twisted, queuelib, cssselect, w3lib, parsel, pyasn1, pyasn1-modules, service-identity, Scrapy
  Found existing installation: zope.interface 4.1.1
    Uninstalling zope.interface-4.1.1:
Could not install packages due to an EnvironmentError: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/zope/__init__.py', '/private/tmp/pip-uninstall-c_liNS/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/zope/__init__.py', "[Errno 1] Operation not permitted: '/private/tmp/pip-uninstall-c_liNS/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/zope/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Ver

**Comment by Amithsk** [comment]
Solution:
Command:sudo pip install --ignore-installed zope.interface
o/p:
Installing collected packages: setuptools, zope.interface
Successfully installed setuptools-39.2.0 zope.interface-4.5.0

Finally **Successfully installed Scrapy-1.5.0 **
