### ISSUE TITLE
Download Middleware HTTPCache pickle error

### ISSUE THREAD

**Issue by yvmarques** [scrapy/scrapy#3295]
Recently I found that my crawler is generating some errors with the HTTPCache extension. 

Here is the config of HTTPCache:

```
HTTPCACHE_ENABLED = True
HTTPCACHE_EXPIRATION_SECS = 0
HTTPCACHE_DIR = 'httpcache'
HTTPCACHE_IGNORE_HTTP_CODES = []
HTTPCACHE_STORAGE = 'scrapy.extensions.httpcache.DbmCacheStorage'
HTTPCACHE_POLICY = 'scrapy.extensions.httpcache.RFC2616Policy'
```

And here is one error I got

```
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/root/.local/share/virtualenvs/lib/python3.6/site-packages/scrapy/core/downloader/middleware.py", line 37, in process_request
    response = yield method(request=request, spider=spider)
  File "/root/.local/share/virtualenvs/lib/python3.6/site-packages/scrapy/downloadermiddlewares/httpcache.py", line 50, in process_request
    cachedresponse = self.storage.retrieve_response(spider, request)
  File "/root/.local/share/virtualenvs/lib/python3.6/site-packages/scrapy/extensions/httpcache.py", line 233, in retrieve_response
    data = self._read_data(spider, request)
  File "/root/.local/share/virtualenvs/lib/python3.6/site-packages/scrapy/extensions/httpcache.py", line 266, in _read_data
    return pickle.loads(db['%s_data' % key])
_pickle.UnpicklingError: pickle data was truncated
```

```
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/root/.local/share/virtualenvs/lib/python3.6/site-packages/scrapy/core/downloader/middleware.py", line 37, in process_request
    response = yield method(request=request, spider=spider)
  File "/root/.local/share/virtualenvs/lib/python3.6/site-packages/scrapy/downloadermiddlewares/httpcache.py", line 50, in process_request
    cachedresponse = self.storage.retrieve_response(spider, request)
  File "/root/.local/share/virtualenvs/lib/python3.6/site-packages/scrapy/extensions/httpcache.py", line 233, in retrieve_response
    data = self._read_data(spider, request)
  File "/root/.local/share/virtualenvs/lib/python3.6/site-packages/scrapy/extensions/httpcache.py", line 266, in _read_data
    return pickle.loads(db['%s_data' % key])
EOFError: Ran out of input
```

My feeling is that my cache database got corrupted somehow or the fact that I have my crawler working for a month and I never cleaned the cache database.

**Comment by realslimshanky** [comment]
Your assumption might be correct as the documentation for pickle shows the same reason for [UnpickingError](https://docs.python.org/3/library/pickle.html#pickle.UnpicklingError).

**Comment by Gallaecio** [comment]
What behavior would you expect as a solution, what should Scrapy do? Would it be better if the cache was automatically destroyed when this happens and Scrapy resumed activity with an empty cache?

**Comment by yvmarques** [comment]
I think depending on the kind of crawl you are doing you might need different strategies how to handle this.

From the top of my head, I would think that this could be mitigated by deleting old records that have not been updated for a while (configurable).

And in case there is still a crash then the solution of automatically destroy the cache and rebuild should be considered.
