### ISSUE TITLE
Crawled (200) then returns Error downloading the page that was just crawled?

### ISSUE THREAD

**Issue by daffychuy** [scrapy/scrapy#3297]
While I was writing a script to get links from the page when I run it, it seemed fine at first.
It crawled the page given with response (200) so that means page worked, but after 1 second, it returns Error downloading the page and keyError gives a <GET URL>.

Here's the log

`2018-06-16 14:33:51 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.masterani.me/api/anime/search?search=M%C3%A4rchen%20M%C3%A4dchen%20Specials> (referer: https://www.masterani.me/api/anime/search?search=)
2018-06-16 14:33:52 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.masterani.me/anime/watch/1544-aa-megami-sama-tv/1> (referer: https://www.masterani.me/api/anime/search?search=Aa!%20Megami-sama!%20(TV))
2018-06-16 14:33:52 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.masterani.me/anime/watch/1544-aa-megami-sama-tv/1>
{'episodes': {'1': [{'host': {'embed_prefix': 'https://mp4upload.com/embed-',
                              'embed_suffix': '.html',
                              'id': 1,
                              'name': 'MP4Upload'},
                     'host_id': 1,
                     'quality': 720},
                    {'host': {'embed_prefix': 'https://mp4upload.com/embed-',
                              'embed_suffix': '.html',
                              'id': 1,
                              'name': 'MP4Upload'},
                     'host_id': 1,
                     'quality': 720},
                    {'host': {'embed_prefix': 'https://mp4upload.com/embed-',
                              'embed_suffix': '.html',
                              'id': 1,
                              'name': 'MP4Upload'},
                     'host_id': 1,
                     'quality': 480},
                    {'host': {'embed_prefix': 'https://mp4upload.com/embed-',
                              'embed_suffix': '.html',
                              'id': 1,
                              'name': 'MP4Upload'},
                     'host_id': 1,
                     'quality': 480}]},
 'name': 'Aa! Megami-sama! (TV)',
 'startDate': '2005-01-07'}
2018-06-16 14:33:52 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.masterani.me/anime/watch/246-hacksign/1> (referer: https://www.masterani.me/api/anime/search?search=.hack//Sign)
2018-06-16 14:33:52 [scrapy.core.scraper] DEBUG: Scraped from <200 https://www.masterani.me/anime/watch/246-hacksign/1>
{'episodes': {'1': [{'quality': 480},
                    {'host': {'embed_prefix': 'https://mp4upload.com/embed-',
                              'embed_suffix': '.html',
                              'id': 1,
                              'name': 'MP4Upload'},
                     'host_id': 1,
                     'quality': 480},
                    {'host': {'embed_prefix': 'https://streamango.com/embed/',
                              'embed_suffix': None,
                              'id': 18,
                              'name': 'Streamango'},
                     'host_id': 2,
                     'quality': 480},
                    {'quality': 480},
                    {'host': {'embed_prefix': 'https://mp4upload.com/embed-',
                              'embed_suffix': '.html',
                              'id': 1,
                              'name': 'MP4Upload'},
                     'host_id': 1,
                     'quality': 480}]},
 'name': '.hack//Sign',
 'startDate': '2002-04-04'}
2018-06-16 14:33:52 [scrapy.core.scraper] ERROR: Error downloading <GET https://www.masterani.me/api/anime/search?search=M%C3%A4rchen%20M%C3%A4dchen%20Specials>
KeyError: <GET https://www.masterani.me/api/anime/search?search=M%C3%A4rchen%20M%C3%A4dchen%20Specials>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/daffy/Developer/gitlab/full_stack_anime/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/daffy/Developer/gitlab/full_stack_anime/lib/python3.6/site-packages/scrapy/core/downloader/__init__.py", line 94, in _deactivate
    self.active.remove(request)
KeyError: <GET https://www.masterani.me/api/anime/search?search=M%C3%A4rchen%20M%C3%A4dchen%20Specials>
2018-06-16 14:33:52 [scrapy.core.engine] INFO: Error while removing request from slot
Traceback (most recent call last):
  File "/Users/daffy/Developer/gitlab/full_stack_anime/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/daffy/Developer/gitlab/full_stack_anime/lib/python3.6/site-packages/scrapy/core/engine.py", line 157, in <lambda>
    d.addBoth(lambda _: slot.remove_request(request))
  File "/Users/daffy/Developer/gitlab/full_stack_anime/lib/python3.6/site-packages/scrapy/core/engine.py", line 39, in remove_request
    self.inprogress.remove(request)
KeyError: <GET https://www.masterani.me/api/anime/search?search=M%C3%A4rchen%20M%C3%A4dchen%20Specials>
2018-06-16 14:33:53 [scrapy.core.scraper] ERROR: Error downloading <GET https://www.masterani.me/api/anime/search?search=M%C3%A4rchen%20M%C3%A4dchen%20Specials>
KeyError: <GET https://www.masterani.me/api/anime/search?search=M%C3%A4rchen%20M%C3%A4dchen%20Specials>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/daffy/Developer/gitlab/full_stack_anime/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/daffy/Developer/gitlab/full_stack_anime/lib/python3.6/site-packages/scrapy/core/downloader/__init__.py", line 94, in _deactivate
    self.active.remove(request)
KeyError: <GET https://www.masterani.me/api/anime/search?search=M%C3%A4rchen%20M%C3%A4dchen%20Specials>
2018-06-16 14:33:53 [scrapy.core.engine] INFO: Error while removing request from slot
Traceback (most recent call last):
  File "/Users/daffy/Developer/gitlab/full_stack_anime/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/daffy/Developer/gitlab/full_stack_anime/lib/python3.6/site-packages/scrapy/core/engine.py", line 157, in <lambda>
    d.addBoth(lambda _: slot.remove_request(request))
  File "/Users/daffy/Developer/gitlab/full_stack_anime/lib/python3.6/site-packages/scrapy/core/engine.py", line 39, in remove_request
    self.inprogress.remove(request)
KeyError: <GET https://www.masterani.me/api/anime/search?search=M%C3%A4rchen%20M%C3%A4dchen%20Specials>`

It then keeps repeating the same error and gives the same for the next couple of pages as well.

**Comment by kmike** [comment]
That looks like a Scrapy bug. Do you have a small reproducable example by chance? :)

**Comment by Gallaecio** [comment]
I’m not sure if we should close this due to not having any means to reproduce the issue. The alternative seems to be to blindly ‘fix’ the `KeyError` without really understanding the underlying issue, which is probably not a good idea.
