### ISSUE TITLE
Memusage extension AssertionError

### ISSUE THREAD

**Issue by nadzimo** [scrapy/scrapy#3343]
I was testing the default configuration of the `scrapy.extensions.memusage.MemoryUsage` extension which is enabled by default. In `settings.py` I set `MEMUSAGE_LIMIT_MB = 10`, a low number to test it out so it gets triggered.
Then I run `scrapy crawl prettylittlething` and the process gives an `AssertionError`. The extension keeps checking every minute the memory usage and repeats the message `ERROR: Memory usage exceeded 8M. Shutting down Scrapy...`

```
2018-07-19 19:05:53 [scrapy.extensions.memusage] ERROR: Memory usage exceeded 8M. Shutting down Scrapy...
2018-07-19 19:05:53 [scrapy.core.engine] INFO: Closing spider (memusage_exceeded)
2018-07-19 19:05:53 [prettylittlething] INFO: Spider closed: prettylittlething because memusage_exceeded
2018-07-19 19:05:53 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'finish_reason': 'memusage_exceeded',
 'finish_time': datetime.datetime(2018, 7, 19, 15, 5, 53, 236830),
 'log_count/DEBUG': 1,
 'log_count/ERROR': 1,
 'log_count/INFO': 10,
 'memusage/limit_reached': 1,
 'memusage/max': 78512128,
 'memusage/startup': 78512128,
 'start_time': datetime.datetime(2018, 7, 19, 15, 5, 53, 235177)}
2018-07-19 19:05:53 [scrapy.core.engine] INFO: Spider closed (memusage_exceeded)
Unhandled error in Deferred:
2018-07-19 19:05:53 [twisted] CRITICAL: Unhandled error in Deferred:

2018-07-19 19:05:53 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/Users/nadima/Dropbox/Local-backup/fashion-app/app/venv-app/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/Users/nadima/Dropbox/Local-backup/fashion-app/app/venv-app/lib/python3.6/site-packages/scrapy/core/engine.py", line 85, in stop
    assert self.running, "Engine not running"
AssertionError: Engine not running
2018-07-19 19:06:53 [scrapy.extensions.memusage] ERROR: Memory usage exceeded 8M. Shutting down Scrapy...
2018-07-19 19:07:53 [scrapy.extensions.memusage] ERROR: Memory usage exceeded 8M. Shutting down Scrapy...
2018-07-19 19:08:53 [scrapy.extensions.memusage] ERROR: Memory usage exceeded 8M. Shutting down Scrapy...


```

**Comment by wRAR** [comment]
I find [this piece of code](https://github.com/scrapy/scrapy/blob/1.5.0/scrapy/core/engine.py#L73) strange:

```python
    @defer.inlineCallbacks
    def start(self):
        """Start the execution engine"""
        assert not self.running, "Engine already running"
        self.start_time = time()
        yield self.signals.send_catch_log_deferred(signal=signals.engine_started)
        self.running = True
        self._closewait = defer.Deferred()
        yield self._closewait

```

It fires `engine_started` and only then sets `self.running` so it's not possible to stop the engine from an `engine_started` handler. I've moved the signal emission before `yield self._closewait` and this test case works correctly, but of course I don't know what can be broken by this change.

**Comment by AdrianAtZyte** [comment]
#7161
