### ISSUE TITLE
Scrapy installed successfully, but error occurred at crawl.

### ISSUE THREAD

**Issue by kenneth663** [scrapy/scrapy#3389]
0
down vote
favorite
I built the scrapy framework on my mac, and everything went well, but when I followed the tutorial in scrapy, it went wrong when I typed in scrapy crawl dmoz. My Python version was 3.6 Mac version was 10.13.6. How do I fix it? The error message is as follows:

kennethdeMBP:spiders kenneth$ scrapy crawl dmoz
2018-08-15 17:56:28 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: tutorial)
2018-08-15 17:56:28 [scrapy.utils.log] INFO: Versions: lxml 4.2.3.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.4.0, w3lib 1.19.0, Twisted 18.7.0, Python 3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08) - [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0h  27 Mar 2018), cryptography 2.2.2, Platform Darwin-17.7.0-x86_64-i386-64bit
2018-08-15 17:56:28 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'tutorial', 'NEWSPIDER_MODULE': 'tutorial.spiders', 'ROBOTSTXT_OBEY': True, 'SPIDER_MODULES': ['tutorial.spiders']}
2018-08-15 17:56:28 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats']
Unhandled error in Deferred:
2018-08-15 17:56:28 [twisted] CRITICAL: Unhandled error in Deferred:

2018-08-15 17:56:28 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/core/engine.py", line 69, in __init__
    self.downloader = downloader_cls(crawler)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/core/downloader/__init__.py", line 88, in __init__
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/middleware.py", line 34, in from_settings
    mwcls = load_object(clspath)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scrapy/downloadermiddlewares/httpproxy.py", line 5, in <module>
    from urllib2 import _parse_proxy
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib2.py", line 220
    raise AttributeError, attr
                        ^
SyntaxError: invalid syntax
kennethdeMBP:spiders kenneth$

**Comment by Chelsea31** [comment]
Can you share the github link of the code you wrote. I can take a look at it.

**Comment by wRAR** [comment]
For some reason you have python3.6/site-packages/urllib2.py. This shouldn't happen.

**Comment by realslimshanky** [comment]
@kenneth663 try using a virtual environment.

**Comment by steverpalmer** [comment]
I just got a similar error while using a virtual environment...
`$ mkdir scrapy_test`

`$ mkvirtualenv -a scrapy_test ScrapyTest`
`Using base prefix '/usr'`
...
`Setting project for ScrapyTest to /home/steve/workspace/scrapy_test`

`(ScrapyTest) [steve@desktop scrapy_test]$ pip install Scrapy`
`Collecting Scrapy`
...
`Successfully installed Automat-0.7.0 PyDispatcher-2.0.5 PyHamcrest-1.9.0 Scrapy-1.5.1 Twisted-18.7.0 asn1crypto-0.24.0 attrs-18.2.0 cffi-1.11.5 constantly-15.1.0 cryptography-2.3.1 cssselect-1.0.3 hyperlink-18.0.0 idna-2.7 incremental-17.5.0 lxml-4.2.5 parsel-1.5.0 pyOpenSSL-18.0.0 pyasn1-0.4.4 pyasn1-modules-0.2.2 pycparser-2.19 queuelib-1.5.0 service-identity-17.0.0 six-1.11.0 w3lib-1.19.0 zope.interface-4.5.0`

`(ScrapyTest) [steve@desktop scrapy_test]$ scrapy startproject tutorial`
`New Scrapy project 'tutorial', using template directory '/home/steve/.virtualenvs/ScrapyTest/lib/python3.7/site-packages/scrapy/templates/project', created in:`
...

`(ScrapyTest) [steve@desktop scrapy_test]$ cd tutorial`

`(ScrapyTest) [steve@desktop tutorial]$ emacs tutorial/spiders/quotes_spider.py`
... cut'n'paste from Scrapy tutorial

`(ScrapyTest) [steve@desktop tutorial]$ scrapy crawl quotes`
2018-09-27 10:33:09 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: tutorial)
2018-09-27 10:33:09 [scrapy.utils.log] INFO: Versions: lxml 4.2.5.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.5.0, w3lib 1.19.0, Twisted 18.7.0, Python 3.7.0 (default, Jul 15 2018, 10:44:58) - [GCC 8.1.1 20180531], pyOpenSSL 18.0.0 (OpenSSL 1.1.0i  14 Aug 2018), cryptography 2.3.1, Platform Linux-4.14.71-1-MANJARO-x86_64-with-arch-Manjaro-Linux
2018-09-27 10:33:09 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'tutorial', 'EDITOR': '/usr/bin/nano', 'NEWSPIDER_MODULE': 'tutorial.spiders', 'ROBOTSTXT_OBEY': True, 'SPIDER_MODULES': ['tutorial.spiders']}
Traceback (most recent call last):
  File "/home/steve/.virtualenvs/ScrapyTest/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/home/steve/.virtualenvs/ScrapyTest/lib/python3.7/site-packages/scrapy/cmdline.py", line 150, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/home/steve/.virtualenvs/ScrapyTest/lib/python3.7/site-packages/scrapy/cmdline.py", line 90, in _run_print_help
    func(*a, **kw)
  File "/home/steve/.virtualenvs/ScrapyTest/lib/python3.7/site-packages/scrapy/cmdline.py", line 157, in _run_command
    cmd.run(args, opts)
  File "/home/steve/.virtualenvs/ScrapyTest/lib/python3.7/site-packages/scrapy/commands/crawl.py", line 57, in run
    self.crawler_process.crawl(spname, **opts.spargs)
  File "/home/steve/.virtualenvs/ScrapyTest/lib/python3.7/site-packages/scrapy/crawler.py", line 170, in crawl
    crawler = self.create_crawler(crawler_or_spidercls)
  File "/home/steve/.virtualenvs/ScrapyTest/lib/python3.7/site-packages/scrapy/crawler.py", line 198, in create_crawler
    return self._create_crawler(crawler_or_spidercls)
  File "/home/steve/.virtualenvs/ScrapyTest/lib/python3.7/site-packages/scrapy/crawler.py", line 203, in _create_crawler
    return Crawler(spidercls, self.settings)
  File "/home/steve/.virtualenvs/ScrapyTest/lib/python3.7/site-packages/scrapy/crawler.py", line 55, in __init__
    self.extensions = ExtensionManager.from_crawler(self)
  File "/home/steve/.virtualenvs/ScrapyTest/lib/python3.7/site-packages/scrapy/middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/home/steve/.virtualenvs/ScrapyTest/lib/python3.7/site-packages/scrapy/middleware.py", line 34, in from_settings
    mwcls = load_object(clspath)
  File "/home/steve/.virtualenvs/ScrapyTest/lib/python3.7/site-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/home/steve/.virtualenvs/ScrapyTest/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/steve/.virtualenvs/ScrapyTest/lib/python3.7/site-packages/scrapy/extensions/telnet.py", line 12, in <module>
    from twisted.conch import manhole, telnet
  File "/home/steve/.virtualenvs/ScrapyTest/lib/python3.7/site-packages/twisted/conch/manhole.py", line 154
    def write(self, data, async=False):
                              ^
SyntaxError: invalid syntax

**Comment by lopuhin** [comment]
@steverpalmer your's error is a different one, please see #3143

**Comment by steverpalmer** [comment]
@lopuhin Thanks - after reviewing #3143 I tweaked manhole.py to replace async with isAsync and now it seems to work.  Cheers.

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback from the original author.
