### ISSUE TITLE
Resuming crawls gives the error: self.size, = struct.unpack(self.SIZE_FORMAT, qsize)

### ISSUE THREAD

**Issue by foomoto** [scrapy/scrapy#3413]
I am running out of memory after crawling 60k pages on an 8GB server, so I am attempting the JOBSDIR settings to reduce memory consumption. If I stop scrapy and attempt to resume I get the below error: Please help.

2018-09-03 21:24:06 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.therosefactory.com/bloom-box> (referer: None)
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/octopus-gatherer/venv1/lib/python3.6/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
GeneratorExit
Exception ignored in: <generator object iter_errback at 0x109230a98>
RuntimeError: generator ignored GeneratorExit
Exception ignored in: <generator object GlobalSpider.parse_new at 0x108aff1a8>
RuntimeError: generator ignored GeneratorExit
Unhandled error in Deferred:
2018-09-03 21:24:06 [twisted] CRITICAL: Unhandled error in Deferred:

2018-09-03 21:24:06 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/Users/mrfobilli/IdeaProjects/octopus-gatherer/venv1/lib/python3.6/site-packages/twisted/internet/task.py", line 517, in _oneWorkUnit
    result = next(self._iterator)
  File "/Users/mrfobilli/IdeaProjects/octopus-gatherer/venv1/lib/python3.6/site-packages/scrapy/utils/defer.py", line 63, in <genexpr>
    work = (callable(elem, *args, **named) for elem in iterable)
  File "/Users/mrfobilli/IdeaProjects/octopus-gatherer/venv1/lib/python3.6/site-packages/scrapy/core/scraper.py", line 183, in _process_spidermw_output
    self.crawler.engine.crawl(request=output, spider=spider)
  File "/Users/mrfobilli/IdeaProjects/octopus-gatherer/venv1/lib/python3.6/site-packages/scrapy/core/engine.py", line 210, in crawl
    self.schedule(request, spider)
  File "/Users/mrfobilli/IdeaProjects/octopus-gatherer/venv1/lib/python3.6/site-packages/scrapy/core/engine.py", line 216, in schedule
    if not self.slot.scheduler.enqueue_request(request):
  File "/Users/mrfobilli/IdeaProjects/octopus-gatherer/venv1/lib/python3.6/site-packages/scrapy/core/scheduler.py", line 57, in enqueue_request
    dqok = self._dqpush(request)
  File "/Users/mrfobilli/IdeaProjects/octopus-gatherer/venv1/lib/python3.6/site-packages/scrapy/core/scheduler.py", line 86, in _dqpush
    self.dqs.push(reqd, -request.priority)
  File "/Users/mrfobilli/IdeaProjects/octopus-gatherer/venv1/lib/python3.6/site-packages/queuelib/pqueue.py", line 33, in push
    self.queues[priority] = self.qfactory(priority)
  File "/Users/mrfobilli/IdeaProjects/octopus-gatherer/venv1/lib/python3.6/site-packages/scrapy/core/scheduler.py", line 114, in _newdq
    return self.dqclass(join(self.dqdir, 'p%s' % priority))
  File "/Users/mrfobilli/IdeaProjects/octopus-gatherer/venv1/lib/python3.6/site-packages/queuelib/queue.py", line 142, in __init__
    self.size, = struct.unpack(self.SIZE_FORMAT, qsize)
struct.error: unpack requires a buffer of 4 bytes

**Comment by foomoto** [comment]
Upon investigation this happens when request priority is set e.g yield Request(url=parsed_url, callback=self.parse_new, priority=1000)

**Comment by foomoto** [comment]
Upon further investigation setting priority to a multiple of 4 bytes fixed the issue

**Comment by wRAR** [comment]
Hello @foomoto , I couldn't reproduce this issue. Actually, I could get a similar error, but only by somehow managing to get  `requests.queue/p0` of zero size, most likely by stopping a spider in some specific moment. It doesn't look like the priority value should matter in this, as it's not even serialized, and this unpacking error should only happen when a file is of size less than 4 bytes. But it is possible I just didn't find the way to reproduce it, so if you can provide a minimal working example it would be great.

**Comment by foomoto** [comment]
@wRAR to reproduce set the jobsdir, and yield Request (url=url, callback="callback", priority=number that keeps increasing)

When there are lots of priority values this happens. Also I notice that scrapy creates a new file for each priority, which makes  the server run out of file handlers.

**Comment by foomoto** [comment]
@wRAR this error may not happen until you try to resume a crawl.

**Comment by Rossonero** [comment]
2018-09-15 23:48:42 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <POST http://ris.szpl.gov.cn/bol/index.aspx> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>]
2018-09-15 23:48:42 [scrapy.core.engine] INFO: Error while handling downloader output
Traceback (most recent call last):
  File "/Users/Rossonero/anaconda/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/Users/Rossonero/anaconda/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/Users/Rossonero/anaconda/lib/python3.6/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Rossonero/anaconda/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/Rossonero/anaconda/lib/python3.6/site-packages/scrapy/core/engine.py", line 171, in _handle_downloader_output
    self.crawl(response, spider)
  File "/Users/Rossonero/anaconda/lib/python3.6/site-packages/scrapy/core/engine.py", line 210, in crawl
    self.schedule(request, spider)
  File "/Users/Rossonero/anaconda/lib/python3.6/site-packages/scrapy/core/engine.py", line 216, in schedule
    if not self.slot.scheduler.enqueue_request(request):
  File "/Users/Rossonero/anaconda/lib/python3.6/site-packages/scrapy/core/scheduler.py", line 57, in enqueue_request
    dqok = self._dqpush(request)
  File "/Users/Rossonero/anaconda/lib/python3.6/site-packages/scrapy/core/scheduler.py", line 86, in _dqpush
    self.dqs.push(reqd, -request.priority)
  File "/Users/Rossonero/anaconda/lib/python3.6/site-packages/queuelib/pqueue.py", line 33, in push
    self.queues[priority] = self.qfactory(priority)
  File "/Users/Rossonero/anaconda/lib/python3.6/site-packages/scrapy/core/scheduler.py", line 114, in _newdq
    return self.dqclass(join(self.dqdir, 'p%s' % priority))
  File "/Users/Rossonero/anaconda/lib/python3.6/site-packages/queuelib/queue.py", line 142, in __init__
    self.size, = struct.unpack(self.SIZE_FORMAT, qsize)
struct.error: unpack requires a bytes object of length 4

**Comment by Rossonero** [comment]
the same. only happen wen resume a job.
scrapy crawl <spider> is ok
resume by "scrapy crawl <spider>  -s " is bad

**Comment by Rossonero** [comment]
there are something left on the requests.queue folder. 
i used to see two files, "p0", "p1" in it. 
when the job stoped, p0 is gone, only the p1 file left, and its size is 0kb
i delete p1, then the job resumes and works again.

**Comment by wRAR** [comment]
@Rossonero are there any exceptions during the first run or any other interesting specifics? I don't think zero-length files should happen normally.

**Comment by Trim21** [comment]
Did you stop your spider gracefully?I meet the same problem if I force scrapy to exit.

**Comment by ydanilin** [comment]
> there are something left on the requests.queue folder.
> i used to see two files, "p0", "p1" in it.
> when the job stoped, p0 is gone, only the p1 file left, and its size is 0kb
> i delete p1, then the job resumes and works again.

Make sure you have also deleted the file scrapy.state in your jobdir to get him work again.

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.

**Comment by manoadamro** [comment]
This happens to me when windows remote connection crashes
