### ISSUE TITLE
Is it possible to close the spider at spider_opened signal?

### ISSUE THREAD

**Issue by pauloromeira** [scrapy/scrapy#3435]
Hello,

I'm working on a middleware that loads some resources at `spider_opened` handler method. If those resources can't be loaded, I need the spider to be closed.

I tried to do that by raising the `CloseSpider` exception and also by calling `crawler.engine.close_spider(...)`, but none of them works.

Is there a way to do that?

Thanks!

**Comment by pauloromeira** [comment]
Hello @wRAR, thanks for the reply. Sorry I didn't put more details.

Example code:
```py
def spider_opened(self, spider):
    if condition:
        self.crawler.engine.close_spider(spider)
```

Failure:
```sh
  File "/usr/lib/python2.7/site-packages/scrapy/core/engine.py", line 298, in close_spider
    dfd = slot.close()
  File "/usr/lib/python2.7/site-packages/scrapy/core/engine.py", line 44, in close
    self._maybe_fire_closing()
  File "/usr/lib/python2.7/site-packages/scrapy/core/engine.py", line 51, in _maybe_fire_closing
    self.heartbeat.stop()
  File "/usr/lib/python2.7/site-packages/twisted/internet/task.py", line 202, in stop
    assert self.running, ("Tried to stop a LoopingCall that was "
AssertionError: Tried to stop a LoopingCall that was not running.
```
Versions
|-|
Python  2.7.15
Scrapy 1.1.3
Twisted 16.4.1

Probably the error is similar to #3343 but differs a bit because of `twisted` version. Do you have any idea of how can I implement such behavior?

**Comment by wRAR** [comment]
@pauloromeira more likely because of the Scrapy version. Anyway, the situation when you can't stop a thing which is not fully started yet sounds quite common in programming, I don't know what are the proper solutions.

**Comment by Gallaecio** [comment]
Does https://stackoverflow.com/a/50977016/939364 work?

**Comment by AntonGsv** [comment]
@Gallaecio Doesn't work on the current version (2.5.0). Is there another solution to the question above?

```
from scrapy.exceptions import CloseSpider
from scrapy import signals

class CustomDownloaderMiddleware:
    @classmethod
    def from_crawler(cls, crawler):
        middleware = cls()
        crawler.signals.connect(middleware.spider_opened, signal=signals.spider_opened)
        return middleware
    
    def spider_opened(self, spider):
          raise CloseSpider("reason")

```

**Comment by Gallaecio** [comment]
There may be another way to do it, but this hack should work: https://stackoverflow.com/a/9699317/939364

However, I’m reopening this issue as I think supporting `CloseSpider` in `spider_opened` signal handlers is a valid request.

**Comment by wRAR** [comment]
So what's the current behavior and/or errors in this case?

**Comment by Gallaecio** [comment]
I’m not sure, but I’m guessing either it works as expected by stopping the crawl or it does not stop the crawl at all (which would be my guess based on reports), but even if it stopped the crawl it probably also logs the exception with a traceback, which is something we should probably avoid in the case of `CloseSpider`, and the documentation should also explicitly indicate that this is a valid way to stop a spider.

**Comment by AntonGsv** [comment]
@wRAR 
spider:
```
from scrapy import signals, Spider, Request
from scrapy.exceptions import CloseSpider


class CustomDownloaderMiddleware:
    @classmethod
    def from_crawler(cls, crawler):
        middleware = cls()
        crawler.signals.connect(middleware.spider_opened, signal=signals.spider_opened)
        return middleware

    def spider_opened(self, spider):
        spider.logger.info('before CloseSpider')
        raise CloseSpider("reason")


class CustomSpider(Spider):
    name = 'custom'
    custom_settings = {
        'DOWNLOADER_MIDDLEWARES': {
            ".".join([CustomDownloaderMiddleware.__module__, CustomDownloaderMiddleware.__name__]): 1,
        }
    }

    def start_requests(self):
        yield Request('https://api.myip.com/')

    def parse(self, response, **kwargs):
        self.logger.info(f'{self.__class__.__name__}.parse')

```
logs:
```
scrapy crawl custom
2021-04-13 17:46:36 [scrapy.utils.log] INFO: Scrapy 2.5.0 started (bot: scrapybot)
2021-04-13 17:46:36 [scrapy.utils.log] INFO: Versions: lxml 4.6.3.0, libxml2 2.9.5, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 21.2.0, Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)], pyOpenSSL 20.0.1 (OpenSSL 1.1.1k
 25 Mar 2021), cryptography 3.4.7, Platform Windows-10-10.0.19041-SP0
2021-04-13 17:46:36 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.selectreactor.SelectReactor
2021-04-13 17:46:36 [scrapy.crawler] INFO: Overridden settings:
{'SPIDER_MODULES': ['app.spiders.test']}
2021-04-13 17:46:36 [scrapy.extensions.telnet] INFO: Telnet Password: eb324b745c4d2fa0
2021-04-13 17:46:36 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2021-04-13 17:46:37 [scrapy.middleware] INFO: Enabled downloader middlewares:
['app.spiders.test.custom.CustomDownloaderMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2021-04-13 17:46:37 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2021-04-13 17:46:37 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2021-04-13 17:46:37 [scrapy.core.engine] INFO: Spider opened
2021-04-13 17:46:37 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2021-04-13 17:46:37 [custom] INFO: before CloseSpider
2021-04-13 17:46:37 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method CustomDownloaderMiddleware.spider_opened of <app.spiders.test.custom.CustomDownloaderMiddleware object at 0x0000029DA879C7F0>>
Traceback (most recent call last):
  File "d:\host\www\shelf-conscious-python-scrapers\src\.venv\lib\site-packages\scrapy\utils\defer.py", line 157, in maybeDeferred_coro
    result = f(*args, **kw)
  File "d:\host\www\shelf-conscious-python-scrapers\src\.venv\lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "D:\host\www\shelf-conscious-python-scrapers\src\app\spiders\test\custom.py", line 14, in spider_opened
    raise CloseSpider("reason")
scrapy.exceptions.CloseSpider
2021-04-13 17:46:37 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2021-04-13 17:46:37 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://api.myip.com/> (referer: None)
2021-04-13 17:46:37 [custom] INFO: CustomSpider.parse
2021-04-13 17:46:37 [scrapy.core.engine] INFO: Closing spider (finished)
2021-04-13 17:46:37 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 212,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 1215,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 0.717408,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2021, 4, 13, 14, 46, 37, 751142),
 'httpcompression/response_bytes': 52,
 'httpcompression/response_count': 1,
 'log_count/DEBUG': 1,
 'log_count/ERROR': 1,
 'log_count/INFO': 12,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2021, 4, 13, 14, 46, 37, 33734)}
2021-04-13 17:46:37 [scrapy.core.engine] INFO: Spider closed (finished)
```

**Comment by yash-fn** [comment]
Okay, so I have figured out what my problem may be:
raise CloseSpider does work, but only if my download isn't very large. Since I am downloading large media files on a very slow connection the downloader middleware keeps running. So it will basically close after n+1 requests n being the request that triggers the closespider. How can I before running CloseSpider cancel the downloader middleware?

**Comment by Gallaecio** [comment]
I guess when we implement https://github.com/scrapy/scrapy/issues/4749 we can, as part of that, allow a CloseSpider attribute that determines whether the spider should stop right away or wait for pending requests (the latter being the current behavior).

**Comment by yash-fn** [comment]
ah gotcha. Thank you!

**Comment by rileypeterson** [comment]
I wanted to do something similar, but for an Item Pipeline. I did the following and it seems to work fine. Might work for the Middleware as well:

```
import logging
from twisted.internet import reactor

logger = logging.getLogger(__name__)


class CloseSpiderIfNotOnVPNPipeline:
    @classmethod
    def from_crawler(cls, crawler):
        return cls()

    def open_spider(self, spider):
        spider.crawler.is_ready = False
        _is_on_vpn, message = is_on_vpn(getattr(spider, "name", None))
        if not _is_on_vpn:
            logger.error("Shutting down Spider because not on VPN!")
            reactor.callLater(
                0,
                spider.crawler.engine.close_spider,
                spider,
                reason=message,
            )
        else:
            spider.crawler.is_ready = True

    def process_item(self, item, spider):
        pass
```

**Comment by dream2333** [comment]
> I wanted to do something similar, but for an Item Pipeline. I did the following and it seems to work fine. Might work for the Middleware as well:
> 
> ```
> import logging
> from twisted.internet import reactor
> 
> logger = logging.getLogger(__name__)
> 
> 
> class CloseSpiderIfNotOnVPNPipeline:
>     @classmethod
>     def from_crawler(cls, crawler):
>         return cls()
> 
>     def open_spider(self, spider):
>         spider.crawler.is_ready = False
>         _is_on_vpn, message = is_on_vpn(getattr(spider, "name", None))
>         if not _is_on_vpn:
>             logger.error("Shutting down Spider because not on VPN!")
>             reactor.callLater(
>                 0,
>                 spider.crawler.engine.close_spider,
>                 spider,
>                 reason=message,
>             )
>         else:
>             spider.crawler.is_ready = True
> 
>     def process_item(self, item, spider):
>         pass
> ```


It works.
Spider closed immediately after call 
```
reactor.callLater(
  0,
  spider.crawler.engine.close_spider,
  spider,
  reason=message,
)
```

I use the above code to close the spider when the connection to the Redis server fails.

```
async def spider_opened(self, spider):
    try:
        self.redis_client = redis.Redis.from_url(self.redis_url, socket_timeout=10, protocol=3)
        is_connected = await self.redis_client.ping()
        if is_connected:
            logger.info("Redis连接成功")
        else:
            reactor.callLater(
                0, spider.crawler.engine.close_spider, spider, reason="ping Redis服务器失败"
            )
    except redis.ConnectionError:
        reactor.callLater(0, spider.crawler.engine.close_spider, spider, reason="Redis服务器连接失败")
