### ISSUE TITLE
ImportError: dlopen failed: library "libssl.so.1.0.0" not found

### ISSUE THREAD

**Issue by eaze999** [scrapy/scrapy#3438]
when i run ' scrapy crawl xxspider.py ' in Termux envirement of my moible phone,  it run's well befor i run ' pkg upgrade ' command. 
	I find that openssl become to openssl/stable,now 1.1.1-2 aarch64 [installed]
	Plsease help me, thanks a lot!

'''
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scrapy/cmdline.py", line 149, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scrapy/crawler.py", line 252, in __init__
    log_scrapy_info(self.settings)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scrapy/utils/log.py", line 149, in log_scrapy_info
    for name, version in scrapy_components_versions()
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scrapy/utils/versions.py", line 35, in scrapy_components_versions
    ("pyOpenSSL", _get_openssl_version()),
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scrapy/utils/versions.py", line 43, in _get_openssl_version
    import OpenSSL
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/OpenSSL/crypto.py", line 16, in <module>
    from OpenSSL._util import (
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: dlopen failed: library "libssl.so.1.0.0" not found
'''

then when i want to install libssl by apt-get or pkg, it cann't find it:

'$ apt-get install libssl
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libssl'

**Comment by wRAR** [comment]
This is not a Scrapy problem. You need to rebuild (or update or whatever, I don't know how did you install them) your Python modules which use OpenSSL to use the new library version. Please refer to documentation and support channels of whatever are you using (Termux probably?) to get help with that.

**Comment by eaze999** [comment]
ok, i will try it , thanks a lot~
