### ISSUE TITLE
twisted error stack trace doesn't output when the spider is using proxymiddleware

### ISSUE THREAD

**Issue by VikShiv** [scrapy/scrapy#3457]
I am using ProxyMiddleware in scrapy , and its throwing error.
Here is Traceback : 
Unhandled error in Deferred:
2018-10-06 14:15:31 [twisted] CRITICAL: Unhandled error in Deferred:

2018-10-06 14:15:31 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.5/dist-packages/scrapy/crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "/usr/local/lib/python3.5/dist-packages/scrapy/crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/local/lib/python3.5/dist-packages/scrapy/core/engine.py", line 69, in __init__
    self.downloader = downloader_cls(crawler)
  File "/usr/local/lib/python3.5/dist-packages/scrapy/core/downloader/__init__.py", line 88, in __init__
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "/usr/local/lib/python3.5/dist-packages/scrapy/middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/local/lib/python3.5/dist-packages/scrapy/middleware.py", line 40, in from_settings
    mw = mwcls()
TypeError: __init__() missing 1 required positional argument: 'arg' 

I have attached screenshot of my proxymiddleware and setting.py file 

Thanks in advance.
![screenshot from 2018-10-06 14-24-17](https://user-images.githubusercontent.com/9248624/46569485-87b4df80-c973-11e8-8339-23f468fcbbd9.png)

![screenshot from 2018-10-06 14-22-00](https://user-images.githubusercontent.com/9248624/46569466-39074580-c973-11e8-8095-197e14e892e8.png)

**Comment by wRAR** [comment]
Not sure what are you asking as the error message says it all: you are expecting an arg that won't be provided. This is a problem with your code, not with Scrapy.

**Comment by VikShiv** [comment]
My bad..closing the issue..
