### ISSUE TITLE
Scrapy view <url> causing TypeError

### ISSUE THREAD

**Issue by vionemc** [scrapy/scrapy#3481]
`scrapy view https://example.com`

When I run the command line above, I get this error:

```
2018-11-01 20:49:29 [twisted] CRITICAL: Unhandled error in Deferred:

2018-11-01 20:49:29 [twisted] CRITICAL:
Traceback (most recent call last):
  File "d:\kerja\hit\python projects\my_project\my_project-env\lib\site-packages\twisted\internet\defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "d:\kerja\hit\python projects\my_project\my_project-env\lib\site-packages\scrapy\crawler.py", line 98, in crawl
    six.reraise(*exc_info)
  File "d:\kerja\hit\python projects\my_project\my_project-env\lib\site-packages\scrapy\crawler.py", line 79, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "d:\kerja\hit\python projects\my_project\my_project-env\lib\site-packages\scrapy\crawler.py", line 102, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)
  File "d:\kerja\hit\python projects\my_project\my_project-env\lib\site-packages\scrapy\spiders\__init__.py", line 51, in from_crawler
    spider = cls(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'start_requests'
'page' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by starrify** [comment]
Might not be a Scrapy issue.

For details, please check [this question on Stackoverflow](https://stackoverflow.com/questions/53102677/i-got-typeerror-when-using-scrapy-view/) and [its answer](https://stackoverflow.com/a/53111329/466611).

**Comment by vionemc** [comment]
**UPDATE:**

I get that error on one of my Scrapy project but I don't get any error when using my other Scrapy project. It seems to be a problem in the spider.

**Comment by vionemc** [comment]
It is solved [in this Stackoverflow answer](https://stackoverflow.com/questions/53102677/i-got-typeerror-when-using-scrapy-view/53111329#53111329) by @starrify 😄
