### ISSUE TITLE
retry middleware add EOFError

### ISSUE THREAD

**Issue by baby5** [scrapy/scrapy#3506]
`[Failure instance: Traceback: <class 'EOFError'>: Compressed file ended before the end-of-stream marker was reached`

i got this log from scrapy, i deal with it by adding EOFError to retry middleware `EXCEPTIONS_TO_RETRY` 
manually

in deep, provide a setting for user to custom retry error maybe better

**Comment by Gallaecio** [comment]
[The list became configurable in 2.10](https://github.com/scrapy/scrapy/pull/5929).

However, I think it would make sense to add `EOFError` to the list by default, mentioning it could happen due to partial compressed responses.

**Comment by Gallaecio** [comment]
Let’s keep this open to add `EOFError` to the list by default.

**Comment by holymonson** [comment]
@Gallaecio We encounter this issue too. Correct me if I'm wrong, `process_exception()` only handles exceptions during `process_request()`, not those during `process_response()`, so adding `EOFError` to `RETRY_EXCEPTIONS` won't help.
Is there any plan for `process_request()` handling both, or a new handler for exceptions during `process_response()`?

https://github.com/scrapy/scrapy/blob/812fd2368f705d033f5f39c152130b12a0fe9b1e/scrapy/core/downloader/middleware.py#L101-L104

**Comment by Gallaecio** [comment]
> @Gallaecio We encounter this issue too. Correct me if I'm wrong, `process_exception()` only handles exceptions during `process_request()`, not those during `process_response()`, so adding `EOFError` to `RETRY_EXCEPTIONS` won't help.

Yes, I learned recently that this is the case.

However, it’s not clear to me from the original report that the issue happened in a `process_response` call. If it happens in the download handler itself, before reaching `process_response`, the exception will be handled.

> Is there any plan for `process_request()` handling both, or a new handler for exceptions during `process_response()`?

It’s certainly one option if the exception happens in `process_response`, but not a trivial one. It might be easier to modify the middleware where the exception happens to let it retry that request (maybe with a setting to toggle that behavior).

**Comment by holymonson** [comment]
> However, it’s not clear to me from the original report that the issue happened in a process_response call. If it happens in the download handler itself, before reaching process_response, the exception will be handled.

It did happen in `HttpCompressionMiddleware.process_response()`.

> It might be easier to modify the middleware where the exception happens to let it retry that request (maybe with a setting to toggle that behavior).

IMHO, it may be wired giving a middleware a separated retry policy rather than following those existing in `RetryMiddleware`. But yes, we are now using a workaround `HttpCompressionMiddleware` to yield rety by itself.

At present, the `process_request()` is made as deferred execution, while `process_response()` is immediate execution. It may be a proper way that making `process_response()`as deferred and throwing failures to `process_exception()` too.

```log
Traceback (most recent call last):
  File "/usr/local/conda/envs/mas/lib/python3.12/site-packages/twisted/internet/defer.py", line 2003, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/Users/monson/Projects/scrapy/scrapy/core/downloader/middleware.py", line 69, in process_response
    method(request=request, response=response, spider=spider)
  File "/Users/monson/Projects/scrapy/scrapy/downloadermiddlewares/httpcompression.py", line 112, in process_response
    decoded_body, content_encoding = self._handle_encoding(
  File "/Users/monson/Projects/scrapy/scrapy/downloadermiddlewares/httpcompression.py", line 155, in _handle_encoding
    body = self._decode(body, encoding, max_size)
  File "/Users/monson/Projects/scrapy/scrapy/downloadermiddlewares/httpcompression.py", line 176, in _decode
    return gunzip(body, max_size=max_size)
  File "/Users/monson/Projects/scrapy/scrapy/utils/gz.py", line 21, in gunzip
    chunk = f.read1(_CHUNK_SIZE)
  File "/usr/local/conda/envs/mas/lib/python3.12/gzip.py", line 337, in read1
    return self._buffer.read1(size)
  File "/usr/local/conda/envs/mas/lib/python3.12/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/local/conda/envs/mas/lib/python3.12/gzip.py", line 547, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```
