### ISSUE TITLE
should scrapy catch the exception that timeout raised by itself ?

### ISSUE THREAD

**Issue by NewUserHa** [scrapy/scrapy#3510]
setting:
`'DOWNLOAD_TIMEOUT': 6,`
spider:
```    def start_requests(self):
        yield scrapy.Request('https://httpbin.org/delay/20', self.parse, priority=1, dont_filter=True)
```
```
2018-11-28 11:11:40 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://httpbin.org/delay/20> (failed 1 times): User timeout caused connection failure: Getting https://httpbin.org/delay/20 took longer than 6.0 seconds..
2018-11-28 11:11:46 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://httpbin.org/delay/20> (failed 2 times): User timeout caused connection failure: Getting https://httpbin.org/delay/20 took longer than 6.0 seconds..
2018-11-28 11:11:52 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET https://httpbin.org/delay/20> (failed 3 times): User timeout caused connection failure: Getting https://httpbin.org/delay/20 took longer than 6.0 seconds..
.......................................no
2018-11-28 11:11:52 [scrapy.core.scraper] ERROR: Error downloading <GET https://httpbin.org/delay/20>
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\twisted\internet\defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "C:\Program Files\Python37\lib\site-packages\twisted\python\failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "C:\Program Files\Python37\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "C:\Program Files\Python37\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "C:\Program Files\Python37\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 351, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://httpbin.org/delay/20 took longer than 6.0 seconds..
```

**Comment by NewUserHa** [comment]
#2442

**Comment by NewUserHa** [comment]
the errback will handle `connection lost` and etc. exception after `httperror` so can it if something scrapy built in middleware catch the `traceback ...` raised by timeout a few times TO supress the traceback log of that

**Comment by elacuesta** [comment]
I'm sorry but I'm having trouble understanding what you mean. Are you trying to completely suppress the "retrying" and "gave up retrying" messages from the crawl logs?

**Comment by NewUserHa** [comment]
i mean: scrapy should suppress the 'traceback ...twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://httpbin.org/delay/20 took longer than 6.0 seconds..' log which raised by scrapy itself.

**Comment by elacuesta** [comment]
In the examples I posted there is no traceback in the logs, only `DEBUG` messages are shown.

Why should Scrapy suppress the full traceback by default? I think it's ok to show them for unhandled exceptions.

**Comment by elacuesta** [comment]
I do agree that **unhandled** exceptions are displayed in full, all exceptions are logged when they reach the engine (except for `scrapy.exceptions.IgnoreRequest`, that's a special case). See https://github.com/scrapy/scrapy/blob/1.5/scrapy/core/scraper.py#L198-L217
What I mean is that if you handle the exceptions, either by setting a request errback or by plugging a custom middleware, only `DEBUG` messages are logged.

**Comment by NewUserHa** [comment]
my point is traceback of built-in retry that gave up should be a handled exception, like those `scrapy.exceptions.IgnoreRequest` exception

**Comment by elacuesta** [comment]
I respectfully disagree. What are your arguments to support that it should be considered _handled_?
`scrapy.exceptions.IgnoreRequest` is raised in certain circumstances, usually from user code, it's used to explicitly indicate a desired behaviour (a request that should be ignored).
Once the RetryMiddleware stops retrying a request (that is not meant to be ignored), it passes the exception over the middleware chain. If that exception reaches the Scrapy engine without being intercepted by another middleware, it is by definition _unhandled_.

Scrapy provides ways to hide the tracebacks from the logs (like the code snippets I shared in my previous comments).
You could also rely on other Python features like setting [`sys.tracebacklimit = 0`](https://docs.python.org/3.1/library/sys.html#sys.tracebacklimit) or setting the level of the `scrapy.core.scraper` logger to a value higher than `ERROR` (https://doc.scrapy.org/en/latest/topics/logging.html):
```
import logging
logger = logging.getLogger('scrapy.core.scraper')
logger.setLevel(logging.CRITICAL)
```
I wouldn't recommend doing the above though, you could be missing important information.

**Comment by NewUserHa** [comment]
so why does a new installed library have some secret exception waiting user to catch?
can't I search `gave up...` to konw if any was gave up by `retry`?
why are there garbage msgs when someone search `traceback ..` to find if there is any traceback from spider code??

**Comment by elacuesta** [comment]
There are no secret exceptions, the ones I've been testing are defined and documented in Twisted, the asynchronous networking framework Scrapy is built upon: https://twistedmatrix.com/documents/current/api/twisted.internet.error.html

Some requests should be expected to work after they're retried, e.g. those which fail because of temporary network problems. In that case you would see some DEBUG messages but no ERROR.
Furthermore, the "Gave up retrying" DEBUG message and the "Error downloading" ERROR message come from different components, and are logged at different times: former one from the retry middleware, later one from `scrapy.core.scraper`. Some things can happen in between those steps, like a request errback or custom middleware performing some specific action (requesting a different URL, logging the error to a remote server, etc).

Personally, I believe the default logging behaviour is a reasonable one, also considering that there are ways to customize it. For instance, setting `LOG_LEVEL = 'INFO'` would prevent the DEBUG messages (which can be quiet verbose) from appearing.

**Comment by AdrianAtZyte** [comment]
Shall we close this?
