### ISSUE TITLE
should raise `AttributeError: Response.meta not available` when access response.meta in `process_resonse`?

### ISSUE THREAD

**Issue by NewUserHa** [scrapy/scrapy#3516]
should raise `AttributeError: Response.meta not available` when access response.meta in `process_resonse`?

```
2018-12-03 23:12:47 [scrapy.core.scraper] ERROR: Error downloading <GET https://httpbin.org/status/200>
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\Python37\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "C:\Program Files\Python37\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 https://httpbin.org/status/200>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\scrapy\http\response\__init__.py", line 30, in meta
    return self.request.meta
AttributeError: 'NoneType' object has no attribute 'meta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Program Files\Python37\lib\site-packages\scrapy\core\downloader\middleware.py", line 53, in process_response
    spider=spider)
  File "C:\Users\user\Desktop\try_scrapy_Snippet.py", line 11, in process_response
    print('in response:', response.url, response.meta)
  File "C:\Program Files\Python37\lib\site-packages\scrapy\http\response\__init__.py", line 33, in meta
    "Response.meta not available, this response "
AttributeError: Response.meta not available, this response is not tied to any request
```

Is this right behavior?  `process_response` can't access `response.meta`???

**Comment by elacuesta** [comment]
`response.meta` is a reference to the request's `meta` dictionary (see https://github.com/scrapy/scrapy/blob/1.5/scrapy/http/response/__init__.py#L28 and https://github.com/scrapy/scrapy/blob/1.5/scrapy/core/engine.py#L236).
The signature for the Dowloader Middleware's `process_response` method is `process_response(request, response, spider)`, you can access the `meta` dictionary with `request.meta`

**Comment by NewUserHa** [comment]
right. but is the traceback above a BUG?

**Comment by NewUserHa** [comment]
make sense.
but do you know where the response.meta is setted and could you point it out please?
thanks

**Comment by elacuesta** [comment]
`response.meta` is a shortcut for `response.request.meta`, and `response.request` is set in the Scrapy engine. Please check my first comment above for links to the relevant parts of the code.

**Comment by NewUserHa** [comment]
you're right!
Thanks!
