### ISSUE TITLE
scrapy crawl quotes in the docs gives a traceback still I cd to the desired directory

### ISSUE THREAD

**Issue by Naba7** [scrapy/scrapy#3535]
Traceback (most recent call last):
  File "/home/chad7/ENV/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/home/chad7/ENV/lib/python3.6/site-packages/scrapy/cmdline.py", line 149, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "/home/chad7/ENV/lib/python3.6/site-packages/scrapy/crawler.py", line 249, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "/home/chad7/ENV/lib/python3.6/site-packages/scrapy/crawler.py", line 137, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "/home/chad7/ENV/lib/python3.6/site-packages/scrapy/crawler.py", line 336, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "/home/chad7/ENV/lib/python3.6/site-packages/scrapy/spiderloader.py", line 61, in from_settings
    return cls(settings)
  File "/home/chad7/ENV/lib/python3.6/site-packages/scrapy/spiderloader.py", line 25, in __init__
    self._load_all_spiders()
  File "/home/chad7/ENV/lib/python3.6/site-packages/scrapy/spiderloader.py", line 47, in _load_all_spiders
    for module in walk_modules(name):
  File "/home/chad7/ENV/lib/python3.6/site-packages/scrapy/utils/misc.py", line 71, in walk_modules
    submod = import_module(fullpath)
  File "/home/chad7/ENV/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/chad7/tutorial/tutorial/spiders/quote_spider.py", line 18
    ~                                        
                                            ^
SyntaxError: invalid syntax

**Comment by elacuesta** [comment]
Seems like you have a `~` character in the line 18 of `/home/chad7/tutorial/tutorial/spiders/quote_spider.py`. I assume you are referring to the examples in https://doc.scrapy.org/en/latest/intro/tutorial.html, however I cannot find that char in those spiders. Could you share the complete code of the spider you are running?

**Comment by Naba7** [comment]
The commands I type:
chad7@superuser:~$ cd tutorial/
chad7@superuser:~/tutorial$ cd tutorial/spiders/
chad7@superuser:~/tutorial/tutorial/spiders$ vim quote_spider.py
chad7@superuser:~/tutorial/tutorial/spiders$ cd ..
chad7@superuser:~/tutorial/tutorial$ cd ..
chad7@superuser:~/tutorial$ scrapy crawl quotes
Traceback (most recent call last):
  File "/home/chad7/anaconda3/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/home/chad7/anaconda3/lib/python3.6/site-packages/scrapy/cmdline.py", line 122, in execute
    cmds = _get_commands_dict(settings, inproject)
  File "/home/chad7/anaconda3/lib/python3.6/site-packages/scrapy/cmdline.py", line 46, in _get_commands_dict
    cmds = _get_commands_from_module('scrapy.commands', inproject)
  File "/home/chad7/anaconda3/lib/python3.6/site-packages/scrapy/cmdline.py", line 29, in _get_commands_from_module
    for cmd in _iter_command_classes(module):
  File "/home/chad7/anaconda3/lib/python3.6/site-packages/scrapy/cmdline.py", line 21, in _iter_command_classes
    for obj in vars(module).itervalues():
AttributeError: 'dict' object has no attribute 'itervalues'



my code:

import scrapy
class QuotesSpider(scrapy.Spider):
    name="quotes"
    def start_requests(self):
        urls=[
                'http://quotes.toscrape.com/page/1/',
                'http://quotes.toscrape.com/page/2/'
                ]
        for url in urls:
            yield scrapy.Request(url=url,callback=self.parse)

    def parse(self,response):
        page=response.url.split("/")[-2]
        filename='quotes-%s.html'%page
        with open(filename, 'wb') as f:
            f.write(response.body)
        self.log('Saved file %s'%filename)

~

**Comment by Naba7** [comment]
I have scrapy.cnf file in tutorial directory

**Comment by Naba7** [comment]
The code here isn't containing tabs,but the real code contains proper tabs.

**Comment by maramsumanth** [comment]
@Naba7 you should save your python spider file to spiders folder in your tutorial project ```.....\tutorial\tutorial\spiders``` , and then run ```scrapy crawl quotes``` command from this directory. :)

**Comment by Gallaecio** [comment]
My two cents:
- Why is the first exception you posted different from the second one?
- Your second exception suggest that you are using Python 3 but you have installed an old version of Scrapy that does not support Python 3 (as it does not include [this change](https://github.com/scrapy/scrapy/commit/3e6d6c43ac0763adf2cd92efdb4a1dc2ba165440)).

**Comment by Naba7** [comment]
@maramsumanth  I have saved it.
@Gallaecio  yeah! I solved the initial problem,and I have reinstalled it. Still,It gives the error.
