### ISSUE TITLE
How can i fix this？

### ISSUE THREAD

**Issue by lovezeropython** [scrapy/scrapy#3556]
```
SyntaxError: invalid syntax
➜  Desktop python3 -V
Python 3.6.5 :: Anaconda, Inc.
➜  Desktop pip3 -V
pip 18.0 from /Users/songhao/anaconda3/lib/python3.6/site-packages/pip (python 3.6)
➜  Desktop
```

`➜  Desktop scrapy startproject scrapyuniversal
Traceback (most recent call last):
  File "/Users/songhao/anaconda3/bin/scrapy", line 7, in <module>
    from scrapy.cmdline import execute
  File "/Users/songhao/anaconda3/lib/python3.6/site-packages/scrapy/__init__.py", line 34, in <module>
    from scrapy.spiders import Spider
  File "/Users/songhao/anaconda3/lib/python3.6/site-packages/scrapy/spiders/__init__.py", line 10, in <module>
    from scrapy.http import Request
  File "/Users/songhao/anaconda3/lib/python3.6/site-packages/scrapy/http/__init__.py", line 10, in <module>
    from scrapy.http.request import Request
  File "/Users/songhao/anaconda3/lib/python3.6/site-packages/scrapy/http/request/__init__.py", line 17
    scrclass Request(object_ref):
                   ^
SyntaxError: invalid syntax

`

**Comment by maramsumanth** [comment]
I think this ```scrclass Request(object_ref):``` should be changed to ```class Request(object_ref):```

**Comment by Gallaecio** [comment]
I suggest you reinstall Scrapy altogether. It sounds like you accidentally edited the Scrapy sources (maybe some king of string replacement, and you might have made other changes as well.

**Comment by joaquingx** [comment]
Do you have any progress @lovezeropython? If you solved it you could close issue :smile:
