### ISSUE TITLE
CRITICAL : Unhandled Error

### ISSUE THREAD

**Issue by xyhuang1116** [scrapy/scrapy#3594]
It seems like every time I use telnet to print stats info,it comes the error.
I looked privious issues，and I can‘t find a solution.

**scrapy -version -v gives me**
2019-01-22 10:45:11,125 : INFO : Scrapy 1.5.1 started (bot: kantest3) 
2019-01-22 10:45:11,131 : INFO : Versions: lxml 4.2.1.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.5.1, w3lib 1.19.0, Twisted 18.9.0, Python 3 .6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) - [GCC 7.2.0], pyOpenSSL 18.0.0 (OpenSSL 1.0.2o  27 Mar 2018), cryptography 2.2.2, Pla tform Linux-4.4.0-130-generic-x86_64-with-debian-stretch-sid 
Scrapy       : 1.5.1 
lxml         : 4.2.1.0 
libxml2      : 2.9.8 
cssselect    : 1.0.3 
parsel       : 1.5.1 
w3lib        : 1.19.0 
Twisted      : 18.9.0 
Python       : 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) - [GCC 7.2.0] 
pyOpenSSL    : 18.0.0 (OpenSSL 1.0.2o  27 Mar 2018) 
cryptography : 2.2.2 
Platform     : Linux-4.4.0-130-generic-x86_64-with-debian-stretch-sid 

**When I connect to telnet,info is:**
ubuntu@VM-0-20-ubuntu:/data/xxx/xxx$ telnet 127.0.0.1 6025 
Trying 127.0.0.1... 
Connected to 127.0.0.1. 
Escape character is '^]'. 

>>> 
>>> p(stats.get_stats()) 
{'downloader/exception_count': 29, 
 'downloader/exception_type_count/twisted.internet.error.ConnectionRefusedError': 21, 
 'downloader/exception_type_count/twisted.internet.error.TCPTimedOutError': 4, 
 'downloader/exception_type_count/twisted.internet.error.TimeoutError': 2, 
 'downloader/exception_type_count/twisted.web._newclient.ResponseNeverReceived': 2, 

**The full stack trace is :** 
2019-01-22 10:05:25,783 : CRITICAL : Unhandled Error
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/twisted/conch/telnet.py", line 636, in dataReceived
    self.applicationDataReceived(b''.join(appDataBuffer))
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/twisted/conch/telnet.py", line 988, in applicationDataReceived
    self.protocol.dataReceived(data)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/twisted/conch/telnet.py", line 1035, in dataReceived
    self.protocol.dataReceived(data)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/twisted/conch/insults/insults.py", line 537, in dataReceived
    self.terminalProtocol.keystrokeReceived(ch, None)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/twisted/conch/recvline.py", line 225, in keystrokeReceived
    m()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/twisted/conch/recvline.py", line 374, in handle_RETURN
    return RecvLine.handle_RETURN(self)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/twisted/conch/recvline.py", line 292, in handle_RETURN
    self.lineReceived(line)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/twisted/conch/manhole.py", line 267, in lineReceived
    more = self.interpreter.push(line)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/twisted/conch/manhole.py", line 106, in push
    more = self.runsource(source, self.filename)
  File "/home/ubuntu/anaconda3/lib/python3.6/code.py", line 75, in runsource
    self.runcode(code)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/twisted/conch/manhole.py", line 117, in runcode
    code.InteractiveInterpreter.runcode(self, *a, **kw)
  File "/home/ubuntu/anaconda3/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
    
  File "/home/ubuntu/anaconda3/lib/python3.6/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
builtins.SystemExit: None

**Comment by Gallaecio** [comment]
Can you still reproduce this issue? Does it happen with the simplest spider possible, or does the spider need to have some specific code?
