### ISSUE TITLE
Selector Raises lxml.etree.XMLSyntaxError on certain xml

### ISSUE THREAD

**Issue by mohmad-null** [scrapy/scrapy#3642]
```
page = b'\x00\x00ws:ExceptionReport></ows:ExceptionReport>\x00'
response = XmlResponse(
	url='http://example.com',
	body=page,
	encoding='utf-8'
)
if hasattr(response, 'selector'):
	pass
```

This crashes with the below traceback.
Given I'm doing a simple "hasattr" for the selector, I don't think it should be crashing out but should be returnin False.
scrapy==1.5.0
lxml==4.1.1

Traceback:

		  File "c:\proj\src\spider_aux_funcs.py", line 1335, in get_resp_content_type
			if hasattr(response, 'selector'):
		  File "c:\proj\venv\lib\site-packages\scrapy\http\response\text.py", line 115, in selector
			self._cached_selector = Selector(self)
		  File "c:\proj\venv\lib\site-packages\scrapy\selector\unified.py", line 71, in __init__
			super(Selector, self).__init__(text=text, type=st, root=root, **kwargs)
		  File "c:\proj\venv\lib\site-packages\parsel\selector.py", line 180, in __init__
			root = self._get_root(text, base_url)
		  File "c:\proj\venv\lib\site-packages\parsel\selector.py", line 191, in _get_root
			return create_root_node(text, self._parser, base_url=base_url)
		  File "c:\proj\venv\lib\site-packages\parsel\selector.py", line 43, in create_root_node
			root = etree.fromstring(body, parser=parser, base_url=base_url)
		  File "src\lxml\etree.pyx", line 3230, in lxml.etree.fromstring (src\lxml\etree.c:81056)
		  File "src\lxml\parser.pxi", line 1871, in lxml.etree._parseMemoryDocument (src\lxml\etree.c:121236)
		  File "src\lxml\parser.pxi", line 1759, in lxml.etree._parseDoc (src\lxml\etree.c:119912)
		  File "src\lxml\parser.pxi", line 1125, in lxml.etree._BaseParser._parseDoc (src\lxml\etree.c:114159)
		  File "src\lxml\parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\etree.c:107724)
		  File "src\lxml\parser.pxi", line 709, in lxml.etree._handleParseResult (src\lxml\etree.c:109433)
		  File "src\lxml\parser.pxi", line 638, in lxml.etree._raiseParseError (src\lxml\etree.c:108287)
		  File "http://example.com", line 1
		lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1

**Comment by malberts** [comment]
Is that your actual code? Or a shortened version? Can you show more of the real code? Because I cannot reproduce that error using your code using your versions in Python 2 and Python 3.

**Comment by mohmad-null** [comment]
The entire script  as a script:
```
from scrapy.http import XmlResponse

page = b'\x00\x00ws:ExceptionReport></ows:ExceptionReport>\x00'
response = XmlResponse(
	url='http://example.com',
	body=page,
	encoding='utf-8'
)
if hasattr(response, 'selector'):
	pass
```

Breaks for me:

```
Traceback (most recent call last):
  File "c:/proj/src/tools/testing.py", line 9, in <module>
    if hasattr(response, 'selector'):
  File "c:\proj\venv\lib\site-packages\scrapy\http\response\text.py", line 115, in selector
    self._cached_selector = Selector(self)
  File "c:\proj\venv\lib\site-packages\scrapy\selector\unified.py", line 71, in __init__
    super(Selector, self).__init__(text=text, type=st, root=root, **kwargs)
  File "c:\proj\venv\lib\site-packages\parsel\selector.py", line 180, in __init__
    root = self._get_root(text, base_url)
  File "c:\proj\venv\lib\site-packages\parsel\selector.py", line 191, in _get_root
    return create_root_node(text, self._parser, base_url=base_url)
  File "c:\proj\venv\lib\site-packages\parsel\selector.py", line 43, in create_root_node
    root = etree.fromstring(body, parser=parser, base_url=base_url)
  File "src\lxml\etree.pyx", line 3230, in lxml.etree.fromstring (src\lxml\etree.c:81056)
  File "src\lxml\parser.pxi", line 1871, in lxml.etree._parseMemoryDocument (src\lxml\etree.c:121236)
  File "src\lxml\parser.pxi", line 1759, in lxml.etree._parseDoc (src\lxml\etree.c:119912)
  File "src\lxml\parser.pxi", line 1125, in lxml.etree._BaseParser._parseDoc (src\lxml\etree.c:114159)
  File "src\lxml\parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\etree.c:107724)
  File "src\lxml\parser.pxi", line 709, in lxml.etree._handleParseResult (src\lxml\etree.c:109433)
  File "src\lxml\parser.pxi", line 638, in lxml.etree._raiseParseError (src\lxml\etree.c:108287)
  File "http://example.com", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1

```

**Comment by malberts** [comment]
Running that as-is still doesn't give me an error (on Linux). However, when I create a very minimal lxml-only example I do get the error:

```python
from lxml import etree

page = b'\x00\x00ws:ExceptionReport></ows:ExceptionReport>\x00'
etree.fromstring(page)
```

```
Traceback (most recent call last):
  File "testing2.py", line 4, in <module>
    etree.fromstring(page)
  File "src/lxml/etree.pyx", line 3230, in lxml.etree.fromstring (src/lxml/etree.c:81070)
  File "src/lxml/parser.pxi", line 1871, in lxml.etree._parseMemoryDocument (src/lxml/etree.c:121250)
  File "src/lxml/parser.pxi", line 1759, in lxml.etree._parseDoc (src/lxml/etree.c:119926)
  File "src/lxml/parser.pxi", line 1125, in lxml.etree._BaseParser._parseDoc (src/lxml/etree.c:114173)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1
```

However, the XML you defined is clearly invalid, so this error makes sense.

To answer your questions: No, `hasattr` won't catch that because it only catches `AttributeError`. Also, it will always have the `selector` attribute because it is a member function of `XmlResponse`.

What is your intention here? To check if the XML is actually valid before proceeding?

**Comment by mohmad-null** [comment]
I'm on Windows, maybe that'll make a difference.

This being an XMLResponse is only for testing purposes - all my actual responses are all created as Response objects. My intention is to determine what type of response I've received: HTML, XML, or unknown. To do that I use the selector. The hasattr example code works fine for all other pages but as you note, this particular page is very invalid.

I've worked around the problem with a try/except wrapper, but to me at least I'd expect the response from hasattr(selector) to be False including for this invalid page. I.e., an end-user of scrapy shouldn't have to care about the inner workings of lxml.

**Comment by Gallaecio** [comment]
@mohmad-null Can you still reproduce your issue with the latest version of Scrapy?
