### ISSUE TITLE
[twisted] CRITICAL: Unhandled error in Deferred:

### ISSUE THREAD

**Issue by ArunAug** [scrapy/scrapy#3652]
```
2019-03-04 13:01:00 [scrapy.crawler] INFO: Overridden settings: {}
2019-03-04 13:01:00 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2019-03-04 13:01:01 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2019-03-04 13:01:01 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2019-03-04 13:01:01 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2019-03-04 13:01:01 [scrapy.core.engine] INFO: Spider opened
Unhandled error in Deferred:
2019-03-04 13:01:01 [twisted] CRITICAL: Unhandled error in Deferred:

Traceback (most recent call last):
  File "site-packages\scrapy\crawler.py", line 172, in crawl

  File "site-packages\scrapy\crawler.py", line 176, in _crawl

  File "site-packages\twisted\internet\defer.py", line 1613, in unwindGenerator

  File "site-packages\twisted\internet\defer.py", line 1529, in _cancellableInlineCallbacks

--- <exception caught here> ---
  File "site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks

  File "site-packages\scrapy\crawler.py", line 82, in crawl

builtins.ModuleNotFoundError: No module named '_sqlite3'

```

**Comment by AArruunn** [comment]
I have written the basic scrapy `dmoz_spider` from the scrapy example docs. 
```
import scrapy

class QuotesSpider(scrapy.Spider):
    name = "quotes"

    def start_requests(self):
        urls = [
            'http://quotes.toscrape.com/page/1/'
        ]
        for url in urls:
            yield scrapy.Request(url=url, callback=self.parse)

    def parse(self, response):

        print("test............................................")
        page = response.url.split("/")[-2]
        filename = 'quotes-%s.html' % page
        with open(filename, 'wb') as f:
            f.write(response.body)
        self.log('Saved file %s' % filename)
```

Try to convert to a  windows executable using pyinstaller. Found this error ?

**Comment by AArruunn** [comment]
@redapple  Found similar issue here.
https://github.com/scrapy/scrapy/issues/2402

**Comment by VMRuiz** [comment]
Is it possible that `pyinstaller` is not aware of your python local packages? 
It seems like an error is caused by either missing packages or the python shell not been able to find them.

**Comment by Gallaecio** [comment]
There are [a few related StackOverflow questions](https://stackoverflow.com/search?q=%5Bscrapy%5D+%22_sqlite3%22).

**Comment by ArunAug** [comment]
Since I am not using sqlit3 in my project, by commenting on the imports related to sqlit3 in my site-packages(sqlite3/init.py) resolves the issue for me.
