### ISSUE TITLE
Spider error processing <GET http://blog.jobbole.com/all-posts/> (referer: None)

### ISSUE THREAD

**Issue by zhangxinheng** [scrapy/scrapy#3658]
D:\SoftwareInstall\python3.7\python.exe D:/ScrapyProject/ScrapyText/main.py
2019-03-06 01:17:31 [scrapy.utils.log] INFO: Scrapy 1.6.0 started (bot: ScrapyText)
2019-03-06 01:17:31 [scrapy.utils.log] INFO: Versions: lxml 4.3.2.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.5.1, w3lib 1.20.0, Twisted 18.9.0, Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)], pyOpenSSL 19.0.0 (OpenSSL 1.1.1b  26 Feb 2019), cryptography 2.6.1, Platform Windows-10-10.0.17134-SP0
2019-03-06 01:17:31 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'ScrapyText', 'NEWSPIDER_MODULE': 'ScrapyText.spiders', 'SPIDER_MODULES': ['ScrapyText.spiders']}
2019-03-06 01:17:31 [scrapy.extensions.telnet] INFO: Telnet Password: 8b498bd6e3499fa3
2019-03-06 01:17:31 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2019-03-06 01:17:31 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2019-03-06 01:17:32 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2019-03-06 01:17:32 [scrapy.middleware] INFO: Enabled item pipelines:
['ScrapyText.pipelines.ScrapytextPipeline']
2019-03-06 01:17:32 [scrapy.core.engine] INFO: Spider opened
2019-03-06 01:17:32 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2019-03-06 01:17:32 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2019-03-06 01:17:32 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://blog.jobbole.com/all-posts/> (referer: None)
2019-03-06 01:17:32 [scrapy.core.scraper] ERROR: Spider error processing <GET http://blog.jobbole.com/all-posts/> (referer: None)
Traceback (most recent call last):
  File "D:\SoftwareInstall\python3.7\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "D:\SoftwareInstall\python3.7\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\SoftwareInstall\python3.7\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\SoftwareInstall\python3.7\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\SoftwareInstall\python3.7\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\ScrapyProject\ScrapyText\ScrapyText\spiders\jobbolen.py", line 14, in parse
    image_url=re_node.css("image::attr(src").extract()
  File "D:\SoftwareInstall\python3.7\lib\site-packages\parsel\selector.py", line 262, in css
    return self.xpath(self._css2xpath(query))
  File "D:\SoftwareInstall\python3.7\lib\site-packages\parsel\selector.py", line 265, in _css2xpath
    return self._csstranslator.css_to_xpath(query)
  File "D:\SoftwareInstall\python3.7\lib\site-packages\parsel\csstranslator.py", line 109, in css_to_xpath
    return super(HTMLTranslator, self).css_to_xpath(css, prefix)
  File "D:\SoftwareInstall\python3.7\lib\site-packages\cssselect\xpath.py", line 192, in css_to_xpath
    for selector in parse(css))
  File "D:\SoftwareInstall\python3.7\lib\site-packages\cssselect\parser.py", line 355, in parse
    return list(parse_selector_group(stream))
  File "D:\SoftwareInstall\python3.7\lib\site-packages\cssselect\parser.py", line 368, in parse_selector_group
    yield Selector(*parse_selector(stream))
  File "D:\SoftwareInstall\python3.7\lib\site-packages\cssselect\parser.py", line 376, in parse_selector
    result, pseudo_element = parse_simple_selector(stream)
  File "D:\SoftwareInstall\python3.7\lib\site-packages\cssselect\parser.py", line 444, in parse_simple_selector
    pseudo_element, parse_arguments(stream))
  File "D:\SoftwareInstall\python3.7\lib\site-packages\cssselect\parser.py", line 494, in parse_arguments
    "Expected an argument, got %s" % (next,))
  File "<string>", line None
cssselect.parser.SelectorSyntaxError: Expected an argument, got <EOF at 15>
2019-03-06 01:17:32 [scrapy.core.engine] INFO: Closing spider (finished)
2019-03-06 01:17:32 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 225,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 17774,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2019, 3, 5, 17, 17, 32, 795171),
 'log_count/DEBUG': 1,
 'log_count/ERROR': 1,
 'log_count/INFO': 9,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'spider_exceptions/SelectorSyntaxError': 1,
 'start_time': datetime.datetime(2019, 3, 5, 17, 17, 32, 21952)}
2019-03-06 01:17:32 [scrapy.core.engine] INFO: Spider closed (finished)

Process finished with exit code 0

**Comment by Gallaecio** [comment]
Please, ask your question [through StackOverflow](https://stackoverflow.com/questions/tagged/scrapy) instead.
