### ISSUE TITLE
Return more detailed error message in scrapy check

### ISSUE THREAD

**Issue by Gravellent** [scrapy/scrapy#3716]
When I run `scrapy check myspider`, it returns an error message of
```
Unhandled error in Deferred:


----------------------------------------------------------------------
Ran 0 contracts in 0.000s

OK
```

However, if I run `scrapy crawl myspider`, it returns an error message of 
```
2019-04-02 16:37:21 [twisted] CRITICAL: Unhandled error in Deferred:

2019-04-02 16:37:21 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/scrapy/crawler.py", line 82, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused
```

In the end, it was the database connection that is causing the issue, but in `scrapy check` it doesn't return anything useful for me to debug. I think we should have more details in the error message. 

If you guys think this is a good improvement, I will work on this as my first issue in this project. Thanks!

**Comment by Gravellent** [comment]
I was trying to improve the error message but found out that if I use a virutualenv, the eoror message is shown fine.
```
----------------------------------------------------------------------
Ran 0 contracts in 0.000s

OK
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/Users/Martin/code/personal/mtester/scrapy/scrapy/crawler.py", line 181, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "/Users/Martin/code/personal/mtester/scrapy/scrapy/crawler.py", line 185, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/Users/Martin/code/personal/mtester/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/Users/Martin/code/personal/mtester/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/Users/Martin/code/personal/mtester/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/Users/Martin/code/personal/mtester/scrapy/scrapy/crawler.py", line 87, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
pymongo.errors.OperationFailure: Authentication failed.
```

But I use the global scrapy package, the error message disappear
```
Unhandled error in Deferred:


----------------------------------------------------------------------
Ran 0 contracts in 0.000s

OK

```

Both are running exactly the same version of scrapy 1.6.0 installed with pip. I'm not sure what the issue here is, maybe it's something about my global packages? Any thoughts would be appreciated.

**Comment by Gallaecio** [comment]
Can you provide some minimal code to reproduce the issue?

**Comment by Gravellent** [comment]
The issue I encountered was when I try to connect to database using an existing crawler, but let me check if I reproduce this issue today in some minimal way

**Comment by Gravellent** [comment]
I was able to reproduce the error by putting an error in pipelines.py.

```
scrapy startproject checker
cd checker/
scrapy genspider example example.com
```
Make a very simple spider, make sure no syntax errors
```
# -*- coding: utf-8 -*-
import scrapy

class ExampleSpider(scrapy.Spider):
    name = 'example'
    allowed_domains = ['example.com']
    start_urls = ['http://example.com/']

    def start_requests(self):
        yield scrapy.Request('http://example.com/', callback=self.parse)

    def parse(self, response):
        '''
            @url http://example.com/
            @returns requests 0 1
        '''
        yield scrapy.Request('http://example.com/')
```

Writes a pipeline, put an error in there (import an non-existing package in this case)
```
import wrong_package

class SomePipeline(object):

    pass
```

Enable the pipeline
```
ITEM_PIPELINES = {
   'checker.pipelines.SomePipeline': 300,
}
```

If run `scrapy check example`, then it would return 
```
Unhandled error in Deferred:


----------------------------------------------------------------------
Ran 0 contracts in 0.000s

OK
```

Not sure if I can reproduce in a simpler way, but this seems to be a good example of check command not providing enough information.

**Comment by herodionem** [comment]
I'm still new to this so someone please correct me if I'm wrong but I believe, at least in this case, you aren't ever providing any contracts to be checked.
`ITEM_PIPELINES`  are executed during a `scrapy crawl` after an Item is yielded from the parse function.
If you are wanting to execute a contract, you will need to enable
```SPIDER_CONTRACTS = { 'checker.contracts.SomeContract' }``` in your settings and make sure you have a `Contract` sub-class named `SomeContract` in the `./checker/contracts.py` file.

**Comment by Gallaecio** [comment]
Not really. I believe `SPIDER_CONTRACTS` is only necessary for [custom contracts](https://docs.scrapy.org/en/latest/topics/contracts.html#custom-contracts), builtin contracts require only to be specified in the docstring of a callback.
