### ISSUE TITLE
[twisted] CRITICAL: Unhandled Error

### ISSUE THREAD

**Issue by Huzhonglan** [scrapy/scrapy#3733]
2019-04-09 09:02:21 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
  File "/home/admin/.virtualenvs/yellowpage/lib/python3.4/site-packages/scrapy/commands/crawl.py", line 58, in run
    self.crawler_process.start()
  File "/home/admin/.virtualenvs/yellowpage/lib/python3.4/site-packages/scrapy/crawler.py", line 293, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "/home/admin/.virtualenvs/yellowpage/lib/python3.4/site-packages/twisted/internet/base.py", line 1267, in run
    self.mainLoop()
  File "/home/admin/.virtualenvs/yellowpage/lib/python3.4/site-packages/twisted/internet/base.py", line 1276, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/home/admin/.virtualenvs/yellowpage/lib/python3.4/site-packages/twisted/internet/base.py", line 902, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/admin/.virtualenvs/yellowpage/lib/python3.4/site-packages/scrapy/utils/reactor.py", line 41, in __call__
    return self._func(*self._a, **self._kw)
  File "/home/admin/.virtualenvs/yellowpage/lib/python3.4/site-packages/scrapy/core/engine.py", line 122, in _next_request
    if not self._next_request_from_scheduler(spider):
  File "/home/admin/.virtualenvs/yellowpage/lib/python3.4/site-packages/scrapy/core/engine.py", line 149, in _next_request_from_scheduler
    request = slot.scheduler.next_request()
  File "/home/admin/.virtualenvs/yellowpage/lib/python3.4/site-packages/scrapy/core/scheduler.py", line 71, in next_request
    request = self._dqpop()
  File "/home/admin/.virtualenvs/yellowpage/lib/python3.4/site-packages/scrapy/core/scheduler.py", line 106, in _dqpop
    d = self.dqs.pop()
  File "/home/admin/.virtualenvs/yellowpage/lib/python3.4/site-packages/queuelib/pqueue.py", line 43, in pop
    m = q.pop()
  File "/home/admin/.virtualenvs/yellowpage/lib/python3.4/site-packages/scrapy/squeues.py", line 19, in pop
    s = super(SerializableQueue, self).pop()
  File "/home/admin/.virtualenvs/yellowpage/lib/python3.4/site-packages/queuelib/queue.py", line 162, in pop
    self.f.seek(-size-self.SIZE_SIZE, os.SEEK_END)
builtins.OSError: [Errno 22] Invalid argument

**Comment by Gallaecio** [comment]
@Huzhonglan Can you reproduce this issue reliably, or does it happen randomly? What steps are you following to reproduce this issue?

**Comment by Huzhonglan** [comment]
Thank you, I have found the problem. Because of the state file.

**Comment by 54keesh** [comment]
@InfraBackend I am encountering this issue as well with scheduled crawler. What do you mean by because of the state file? Is there something wrong thats happening there? I have been continuously running the scrapper for 7-ish hours or so. Could that be the reason ?

**Comment by Gallaecio** [comment]
It seems to have to do with the use of `JOBDIR`, and some kind of corruption in that file. Could that be your case?

**Comment by 54keesh** [comment]
@Gallaecio Yes its indeed about `JOBDIR` which i am also using. But I dont know what kind of corruption or issue might have occured. If you resolved it can you point me out what could be going wrong here ?

**Comment by Gallaecio** [comment]
I am not sure what’s going on on your end, and without a minimal reproducible example there is not much we can do. As a work around, you can either remove the JOBDIR folder (if losing that data is OK), otherwise you would need to fix the contents of JOBDIR, which [is not trivial](https://github.com/scrapy/scrapy/issues/4842).

**Comment by 54keesh** [comment]
Can you please point me out where i need to start looking to fix whatever broken here ? The data is quite important to me @Gallaecio

**Comment by Gallaecio** [comment]
The content you mention is also mentioned in the linked ticket:

```\x80\x04}\x94.```

Seems to be as expected. You should restore it.

I think debugging this issue on my end would take time I don’t have. If I were you, I would start by figuring out why `self.f.seek(-size-self.SIZE_SIZE, os.SEEK_END)` raises that exception. You could clone the queuelib repo, add some debugging messages, and install your close in the venv of your spider, see if that helps you figure out the source of the issue.

**Comment by Gallaecio** [comment]
See also https://github.com/scrapy/scrapy/issues/845, which might be the same issue.

**Comment by 54keesh** [comment]
Great thanks a lot, Ill have a look

**Comment by 54keesh** [comment]
I am encountering this issue as well but sadly no way to reciprocate. This is my assumption but i think it might be due to out of scrapper going out of memory as this time i ran my crawler for the maximum time out of all the crawl runs for abt 8 hours or so and my max memory usage was 250 MB on a 1GB memory EC2 instance where 500 or so MB is taken up by the OS.

Fortunately I had a backup of a crawls state directory for a day before and i used that state so only ended up loosing a days worth of crawls.

Using the requests.seen as stated by someone above does seem like a logical solution as it will filter out the dupes upon reprocessing but i guess not all the requests are appended up in requests.seen as my latest requests.seen has only 20k entries while my crawled requests which i am sure are way above 65k including 3x images request per each request and hence this solution didnt work as the metric at the end of job pause did show it filtered dupes but upon inspecting my csvs, it still had dupe entries

**Comment by Gallaecio** [comment]
> it might be due to out of scrapper going out of memory

If that caused the OS to kill the Scrapy process, that could indeed be it.
