### ISSUE TITLE
python 3.7.3 ModuleNotFoundError: No module named 'scrapy.dupefilter'

### ISSUE THREAD

**Issue by lx1054331851** [scrapy/scrapy#3837]
Under python 3.7.3 run scrapy, error occurred as below:
```python
2019-06-22 23:35:14 [scrapy.utils.log] INFO: Scrapy 1.6.0 started (bot: SpeedToMarket)
2019-06-22 23:35:14 [scrapy.utils.log] INFO: Versions: lxml 4.3.2.0, libxml2 2.9.9, cssselect 1.0.3, parsel 1.5.1, w3lib 1.20.0, Twisted 19.2.1, Python 3.7.3 (default, Mar 27 2019, 16:54:48) - [Clang 4.0.1 (tags/RELEASE_401/final)], pyOpenSSL 19.0.0 (OpenSSL 1.1.1c  28 May 2019), cryptography 2.6.1, Platform Darwin-18.6.0-x86_64-i386-64bit
2019-06-22 23:35:14 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'SpeedToMarket', 'CONCURRENT_REQUESTS_PER_DOMAIN': 16, 'COOKIES_ENABLED': False, 'DOWNLOAD_DELAY': 3, 'DUPEFILTER_CLASS': 'scrapy.dupefilter.BaseDupeFilter', 'NEWSPIDER_MODULE': 'SpeedToMarket.spiders', 'SPIDER_MODULES': ['SpeedToMarket.spiders']}
2019-06-22 23:35:14 [scrapy.extensions.telnet] INFO: Telnet Password: 861f841c3fee4b29
2019-06-22 23:35:14 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats']
2019-06-22 23:35:14 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'SpeedToMarket.middlewares.MyUserAgentMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'SpeedToMarket.middlewares.SpeedtomarketCheckRepeatMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2019-06-22 23:35:14 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2019-06-22 23:35:14 [scrapy.middleware] INFO: Enabled item pipelines:
['SpeedToMarket.pipelines.SpeedtomarketPipeline']
2019-06-22 23:35:14 [scrapy.core.engine] INFO: Spider opened
Unhandled error in Deferred:
2019-06-22 23:35:14 [twisted] CRITICAL: Unhandled error in Deferred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/scrapy/crawler.py", line 172, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/scrapy/crawler.py", line 176, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/anaconda3/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/anaconda3/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/anaconda3/lib/python3.7/site-packages/scrapy/crawler.py", line 82, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
builtins.ModuleNotFoundError: No module named 'scrapy.dupefilter'
```

**Comment by njmhnb** [comment]
Hi @lx1054331851
Do you find your problem response?
I have the same problem when I upgrade scrapy from 1.5.2 to 2.0.5

**Comment by Gallaecio** [comment]
That module was deprecated already in 1.5.2, and was removed in 1.6: https://docs.scrapy.org/en/1.6/news.html#deprecation-removals

You should figure out where in your code it is being used, and stop using it.
