### ISSUE TITLE
strip trailing backslashes from domain when redirecting to avoid invalid domains

### ISSUE THREAD

**Issue by ddebernardy** [scrapy/scrapy#3854]
To reproduce:
```$ scrapy shell 'http://mlaib.com'
[...]
2019-07-04 12:04:30 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (301) to <GET http://www.belgoal.com\> from <GET http://mlaib.com>
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 10, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python3.7/site-packages/scrapy/cmdline.py", line 150, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/usr/local/lib/python3.7/site-packages/scrapy/cmdline.py", line 90, in _run_print_help
    func(*a, **kw)
  File "/usr/local/lib/python3.7/site-packages/scrapy/cmdline.py", line 157, in _run_command
    cmd.run(args, opts)
  File "/usr/local/lib/python3.7/site-packages/scrapy/commands/shell.py", line 74, in run
    shell.start(url=url, redirect=not opts.no_redirect)
  File "/usr/local/lib/python3.7/site-packages/scrapy/shell.py", line 48, in start
    self.fetch(url, spider, redirect=redirect)
  File "/usr/local/lib/python3.7/site-packages/scrapy/shell.py", line 115, in fetch
    reactor, self._schedule, request, spider)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/threads.py", line 122, in blockingCallFromThread
    result.raiseException()
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 488, in raiseException
    raise self.value.with_traceback(self.tb)
ValueError: invalid hostname: www.belgoal.com\

$ curl -I http://mlaib.com
HTTP/1.1 301 Moved Permanently
[...]
Location: http://www.belgoal.com\
[...]
```

I presume I can fix it in a downloader middleware, but it should probably get handled by Scrapy.

**Comment by Gallaecio** [comment]
We should probably try to imitate web browsers here.

**Comment by OmarFarrag** [comment]
@Gallaecio @ddebernardy I can work on this, would check `redirected_url` in `process_response()` in `RedirectMiddleware` class.. If you suggest imitating the web browsers no problem working on that but would need to design an approach and confirm it with you first.

**Comment by ddebernardy** [comment]
@OmarFarrag I honestly have no personal say on how it should or whether it even should get fixed, but FWIW on my end I'm going to basically strip the backslash in a middleware so if it gets fixed in Scrapy itself what you suggest sounds right.

Also, fun factoid: Chrome fixes the link, but Safari doesn't.

**Comment by OmarFarrag** [comment]
Another thing is that it looks like twisted doesn't allow urls with backslashes :
```
(base) C:\Users\User>scrapy shell "https://www.google.com\"
2019-07-07 19:31:41 [scrapy.utils.log] INFO: Scrapy 1.5.2 started (bot: scrapybot)
2019-07-07 19:31:41 [scrapy.utils.log] INFO: Versions: lxml 4.3.4.0, libxml2 2.9.9, cssselect 1.0.3, parsel 1.5.1, w3lib 1.20.0, Twisted 19.2.1, Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)], pyOpenSSL 19.0.0 (OpenSSL 1.1.1b  26 Feb 2019), cryptography 2.6.1, Platform Windows-10-10.0.17134-SP0
2019-07-07 19:31:41 [scrapy.crawler] INFO: Overridden settings: {'DUPEFILTER_CLASS': 'scrapy.dupefilters.BaseDupeFilter', 'LOGSTATS_INTERVAL': 0}
2019-07-07 19:31:41 [scrapy.extensions.telnet] INFO: Telnet Password: 7db3e1f43e02339a
2019-07-07 19:31:41 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole']
2019-07-07 19:31:41 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2019-07-07 19:31:41 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2019-07-07 19:31:41 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2019-07-07 19:31:41 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6024
2019-07-07 19:31:41 [scrapy.core.engine] INFO: Spider opened
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\Scripts\scrapy-script.py", line 10, in <module>
    sys.exit(execute())
  File "C:\ProgramData\Miniconda3\lib\site-packages\scrapy\cmdline.py", line 150, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scrapy\cmdline.py", line 90, in _run_print_help
    func(*a, **kw)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scrapy\cmdline.py", line 157, in _run_command
    cmd.run(args, opts)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scrapy\commands\shell.py", line 73, in run
    shell.start(url=url, redirect=not opts.no_redirect)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scrapy\shell.py", line 48, in start
    self.fetch(url, spider, redirect=redirect)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scrapy\shell.py", line 115, in fetch
    reactor, self._schedule, request, spider)
  File "C:\ProgramData\Miniconda3\lib\site-packages\twisted\internet\threads.py", line 122, in blockingCallFromThread
    result.raiseException()
  File "C:\ProgramData\Miniconda3\lib\site-packages\twisted\python\failure.py", line 488, in raiseException
    raise self.value.with_traceback(self.tb)
idna.core.InvalidCodepoint: Codepoint U+0022 at position 4 of 'com"' not allowed
```

So it's not only with redirections, and if this is to be handled, for example convert backslashes to forwardslashes like some browsers, it has to be handled for every request somewhere in the middlewares

**Comment by AdrianAtZyte** [comment]
Fixed by https://github.com/scrapy/w3lib/pull/285.
