### ISSUE TITLE
Installing on CentOS7 (Python 2.7.5)

### ISSUE THREAD

**Issue by Hiroki111** [scrapy/scrapy#3889]
I've run `pip install scrapy`, but it doesn't seem that this has been installed properly.

Now when I ran `scrapy` on CLI, it ends up in the following message.

```
Traceback (most recent call last):
  File "/usr/bin/scrapy", line 6, in <module>
    from scrapy.cmdline import execute
  File "/usr/lib64/python2.7/site-packages/scrapy/cmdline.py", line 10, in <module>
    from scrapy.crawler import CrawlerProcess
  File "/usr/lib64/python2.7/site-packages/scrapy/crawler.py", line 11, in <module>
    from scrapy.core.engine import ExecutionEngine
  File "/usr/lib64/python2.7/site-packages/scrapy/core/engine.py", line 14, in <module>
    from scrapy.core.scraper import Scraper
  File "/usr/lib64/python2.7/site-packages/scrapy/core/scraper.py", line 18, in <module>
    from scrapy.core.spidermw import SpiderMiddlewareManager
  File "/usr/lib64/python2.7/site-packages/scrapy/core/spidermw.py", line 13, in <module>
    from scrapy.utils.conf import build_component_list
  File "/usr/lib64/python2.7/site-packages/scrapy/utils/conf.py", line 4, in <module>
    import configparser
ImportError: No module named configparser
```

I googled `configparser`, and apparently this used to be called `ConfigParser`.

Has anyone seen this issue?
Any advice will be appreciated.

**Comment by marsam** [comment]
addressed by https://github.com/scrapy/scrapy/pull/3887

**Comment by elacuesta** [comment]
Hello @Hiroki111, please see my explanation at https://github.com/scrapy/scrapy/pull/3887#issuecomment-513484840.
As a temporary workaround, I believe you should be able to make it work by installing the `configparser` backport (https://pypi.org/project/configparser/)
