### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by rorat23** [scrapy/scrapy#3895]
!scrapy startproject stack
whenever i run this code in jupyter i get the error:

Traceback (most recent call last):
  File "C:\Users\Rohan\Anaconda3\Scripts\scrapy-script.py", line 10, in <module>
    sys.exit(execute())
  File "C:\Users\Rohan\Anaconda3\lib\site-packages\scrapy\cmdline.py", line 149, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "C:\Users\Rohan\Anaconda3\lib\site-packages\scrapy\crawler.py", line 254, in __init__
    log_scrapy_info(self.settings)
  File "C:\Users\Rohan\Anaconda3\lib\site-packages\scrapy\utils\log.py", line 149, in log_scrapy_info
    for name, version in scrapy_components_versions()
  File "C:\Users\Rohan\Anaconda3\lib\site-packages\scrapy\utils\versions.py", line 35, in scrapy_components_versions
    ("pyOpenSSL", _get_openssl_version()),
  File "C:\Users\Rohan\Anaconda3\lib\site-packages\scrapy\utils\versions.py", line 43, in _get_openssl_version
    import OpenSSL
  File "C:\Users\Rohan\Anaconda3\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "C:\Users\Rohan\Anaconda3\lib\site-packages\OpenSSL\crypto.py", line 16, in <module>
    from OpenSSL._util import (
  File "C:\Users\Rohan\Anaconda3\lib\site-packages\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "C:\Users\Rohan\Anaconda3\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by elacuesta** [comment]
Hello! Please check the Windows-specific notes at https://doc.scrapy.org/en/latest/intro/install.html#windows 

It seems to me like the problem is that some system libraries (DLL files) used by the `OpenSSL` bindings are missing in the system. You might want to take a look at https://wiki.openssl.org/index.php/Binaries.

Are you able to run `scrapy version --verbose`?

Disclaimer: I don't have any experience installing/running Scrapy on Windows, this is just a theoretical approach.

**Comment by rorat23** [comment]
No I am not able to run scrapy version --verbose I am getting the same error as mentioned above. Please help me I need it

**Comment by Gallaecio** [comment]
@rorat23 Did you install as described in https://doc.scrapy.org/en/latest/intro/install.html#windows?

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.
