### ISSUE TITLE
Can't view pdf response in browser

### ISSUE THREAD

**Issue by OmarFarrag** [scrapy/scrapy#3902]
**To reproduce:**
```
scrapy shell http://www.ivoa.net/documents/IVOAIdentifiers/20160523/REC-Identifiers-2.0.pdf
view(response)
```

**The result:**
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "E:\Python\scrapy_dev\lib\site-packages\scrapy-1.7.0-py3.7.egg\scrapy\utils\response.py", line 60, in open_in_browser
    ext = response.extension
  File "E:\Python\scrapy_dev\lib\site-packages\scrapy-1.7.0-py3.7.egg\scrapy\http\response\__init__.py", line 142, in extension
    self.__class__.__name__)
TypeError: Unsupported response type: Response
```

******************************************************************************************************
This issue can be fixed in `open_in_browser` in `scrapy\utils\response` by either:

1. checking the content type in the headers to be `application/pdf`, if so then the extension is `.pdf` and the process continues
2. Creating a pdf response class just like `HtmlResponse`

 But, there is a comment stating that the implementation is a bit dirty and could be imroved, so I have two approaches to refactor this implementation:

1. Add extension property to response classes and then just use `response.extension`
2. Create a dictionary with classes as keys and the extension as value

**Waiting for comment, and then will work on it**

**Comment by sbs2001** [comment]
Just added a PR to fix this  for awhile.PDF,MP3 etc can be viewed in browser but I don't think we can 'scrap' a pdf therefore the devs might have ignored these.Anyway looking forward to feedback.

**Comment by OmarFarrag** [comment]
@sbs2001 Thank you for your effort and considering this issue. But, I think checking for specific types is better than blindly setting the extension from the url, for example checking if the `Content-type` header, and setting the supported extensions accordingly. Anyway, I was working on Refactoring this function in PR[#3909](https://github.com/scrapy/scrapy/pull/3909) where migrated extension revealing to the response classes, so in order to support pdf would have to create a new class `PdfResponse` and make it return the file extension..
This was my approach, anyway it's up to core contributors to decide the appropriate approach :D

**Comment by sbs2001** [comment]
You are correct my approach is likely prone to many bugs I am not aware of.  Anyways I was trying to understand your first  suggested approach. You have mentioned  the 'content-type'  which I assume to be the one  present in  HTTP response header. Is my assumption correct?

```
>>> import requests
>>> r=requests.get('https://geca.ac.in/downloads/240720193502New%20Doc%202019-07-24%2012.28.13_1.pdf')
>>> r.headers['content-type']
'application/pdf'

```
So basically we will check the 'content-type' from  the response header and then set the extensions accordingly. Am I misunderstanding anything?

**Comment by sbs2001** [comment]
Also if it helps, I found on internet that every PDF begins with '%PDF'.I confirmed that on a hex editor.

**Comment by OmarFarrag** [comment]
@sbs2001 Yes, the 'content-type' header was what I meant
