### ISSUE TITLE
Random Twisted error: Builtins.KeyError: -2

### ISSUE THREAD

**Issue by Colafroth** [scrapy/scrapy#3965]
```
2019-08-19 13:20:57 [twisted] CRITICAL: Unhandled Error
2019-08-19T03:20:57.473794+00:00 app[worker.1]: Traceback (most recent call last):
2019-08-19T03:20:57.473796+00:00 app[worker.1]: File "/usr/src/ScrapyProjects/ScrapyController.py", line 37, in execute
2019-08-19T03:20:57.473798+00:00 app[worker.1]: self.crawler.start()
2019-08-19T03:20:57.473800+00:00 app[worker.1]: File "/usr/local/lib/python3.7/site-packages/scrapy/crawler.py", line 293, in start
2019-08-19T03:20:57.473803+00:00 app[worker.1]: reactor.run(installSignalHandlers=False)  # blocking call
2019-08-19T03:20:57.473805+00:00 app[worker.1]: File "/usr/local/lib/python3.7/site-packages/twisted/internet/base.py", line 1272, in run
2019-08-19T03:20:57.473807+00:00 app[worker.1]: self.mainLoop()
2019-08-19T03:20:57.473809+00:00 app[worker.1]: File "/usr/local/lib/python3.7/site-packages/twisted/internet/base.py", line 1281, in mainLoop
2019-08-19T03:20:57.473811+00:00 app[worker.1]: self.runUntilCurrent()
2019-08-19T03:20:57.473813+00:00 app[worker.1]: --- <exception caught here> ---
2019-08-19T03:20:57.473815+00:00 app[worker.1]: File "/usr/local/lib/python3.7/site-packages/twisted/internet/base.py", line 902, in runUntilCurrent
2019-08-19T03:20:57.473817+00:00 app[worker.1]: call.func(*call.args, **call.kw)
2019-08-19T03:20:57.473819+00:00 app[worker.1]: File "/usr/local/lib/python3.7/site-packages/scrapy/utils/reactor.py", line 41, in __call__
2019-08-19T03:20:57.473821+00:00 app[worker.1]: return self._func(*self._a, **self._kw)
2019-08-19T03:20:57.473822+00:00 app[worker.1]: File "/usr/local/lib/python3.7/site-packages/scrapy/core/engine.py", line 122, in _next_request
2019-08-19T03:20:57.473824+00:00 app[worker.1]: if not self._next_request_from_scheduler(spider):
2019-08-19T03:20:57.473825+00:00 app[worker.1]: File "/usr/local/lib/python3.7/site-packages/scrapy/core/engine.py", line 149, in _next_request_from_scheduler
2019-08-19T03:20:57.473827+00:00 app[worker.1]: request = slot.scheduler.next_request()
2019-08-19T03:20:57.473828+00:00 app[worker.1]: File "/usr/local/lib/python3.7/site-packages/scrapy/core/scheduler.py", line 71, in next_request
2019-08-19T03:20:57.473830+00:00 app[worker.1]: request = self._dqpop()
2019-08-19T03:20:57.473831+00:00 app[worker.1]: File "/usr/local/lib/python3.7/site-packages/scrapy/core/scheduler.py", line 106, in _dqpop
2019-08-19T03:20:57.473833+00:00 app[worker.1]: d = self.dqs.pop()
2019-08-19T03:20:57.473834+00:00 app[worker.1]: File "/usr/local/lib/python3.7/site-packages/queuelib/pqueue.py", line 42, in pop
2019-08-19T03:20:57.473836+00:00 app[worker.1]: q = self.queues[self.curprio]
2019-08-19T03:20:57.473837+00:00 app[worker.1]: builtins.KeyError: -2
```

The spider runs smoothly but sometimes this error keeps popping up. I have no clue what it is and couldn't find anything from online.

**Comment by Gallaecio** [comment]
It looks like an issue with the priority queue used for request scheduling.

That part of the code got quite some work in Scrapy 1.7. Could you upgrade to Scrapy 1.7 and see if you still get such an error?

**Comment by elacuesta** [comment]
BTW, this is not a "Twisted" error, it's caught and reported by Twisted but it's a built-in `KeyError`.

If I'm not mistaken, that looks like a Heroku log stream. The following is a long shot, but could it be that you have more than one worker for the same crawler? It seems to me like this could be a race condition produced by having several processes trying to read from the same priority queue. In that case, one worker could be trying to get Requests that were already pulled by another worker. As I said, this is just a theory and it could be _completely_ wrong :-)
