### ISSUE TITLE
Is 'ResponseNeverReceived' retried automatically?

### ISSUE THREAD

**Issue by botzill** [scrapy/scrapy#3997]
I have a spider that is using proxy and I see when finshed this:

```
{'bans/error/twisted.web._newclient.ResponseNeverReceived': 5580,
 'downloader/exception_count': 5580,
 'downloader/exception_type_count/twisted.web._newclient.ResponseNeverReceived': 5580,
 'downloader/request_bytes': 10857668,
 'downloader/request_count': 17877,
 'downloader/request_method_count/GET': 1,
 'downloader/request_method_count/POST': 17876,
 'downloader/response_bytes': 173289486,
 'downloader/response_count': 12297,
 'downloader/response_status_count/200': 11799,
 'downloader/response_status_count/502': 498,
 'elapsed_time_seconds': 1574.070208,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2019, 9, 1, 10, 23, 37, 55794),
 'item_scraped_count': 10669,
 'log_count/DEBUG': 53156,
 'log_count/ERROR': 5580,
 'log_count/INFO': 50,
 'memusage/max': 257974272,
 'memusage/startup': 53932032,
 'proxies/dead': 16,
 'proxies/good': 17,
 'proxies/mean_backoff': 49.755788241608414,
 'proxies/reanimated': 2,
 'proxies/unchecked': 0,
 'request_depth_max': 10,
 'response_received_count': 11799,
 'retry/count': 498,
 'retry/reason_count/502 Bad Gateway': 498,
 'scheduler/dequeued': 17877,
 'scheduler/dequeued/memory': 17877,
 'scheduler/enqueued': 17877,
 'scheduler/enqueued/memory': 17877,
 'start_time': datetime.datetime(2019, 9, 1, 9, 57, 22, 985586)}
2019-09-01 13:23:37 [scrapy.core.engine] INFO: Spider closed (finished)
```

I did update the retry download middleware `retry` to include these exceptions as well :

```python
class RetryMiddleware(retry.RetryMiddleware):
    EXCEPTIONS_TO_RETRY = retry.RetryMiddleware.EXCEPTIONS_TO_RETRY + (
        ConnectBindError,
        ResponseNeverReceived
    )
```

So, does this mean that this error will be retried automatically? 

because I see `'retry/count': 498` is less then `ResponseNeverReceived` count.

Thx!

**Comment by elacuesta** [comment]
Hi @botzill,
Indeed, `ResponseNeverReceived` is not in `RetryMiddleware.EXCEPTIONS_TO_RETRY` so it's not automatically retried.
Regarding your code, are you replacing the built-in `RetryMiddleware` with your own as described in [this section](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#activating-a-downloader-middleware)?
For the record, you should be able to add the exception without subclassing, with something like the following:

```python
from scrapy.downloadermiddlewares.retry import RetryMiddleware
from twisted.web._newclient import ResponseNeverReceived

RetryMiddleware.EXCEPTIONS_TO_RETRY += (ResponseNeverReceived,)
```

**Comment by botzill** [comment]
yes I do add mine and turn off default on:
```
DOWNLOADER_MIDDLEWARES = {
    'scrapy.downloadermiddlewares.retry.RetryMiddleware': None,
    'my_crawler.downloadermiddlewares.retry.RetryMiddleware': 550,
}
```

**Comment by botzill** [comment]
My question is if I have `ResponseNeverReceived: 5580` then I should as well see in the end `retry/count` to include this number as well?

**Comment by elacuesta** [comment]
I think both `retry` and `retry/reason_count/twisted.web._newclient.ResponseNeverReceived` should reflect the amount of caught exceptions. I cannot reproduce the issue, at least without proxies, I'm thinking that might have something to do here.

```python
# retry.py
import scrapy
from scrapy.core.downloader.handlers.http import HTTPDownloadHandler
from twisted.web._newclient import ResponseNeverReceived


class RaiseResponseNeverReceivedDownloadHandler(HTTPDownloadHandler):
    def download_request(self, request, spider):
        raise ResponseNeverReceived('Manually raised from download handler')


class ResponseNeverReceivedSpider(scrapy.Spider):
    name = 'response_never_received'
    start_urls = ['https://example.org']
    custom_settings = {
        'LOG_LEVEL': 'DEBUG',
        'RETRY_TIMES': 10,
        'DOWNLOAD_HANDLERS': {
            'https': __name__ + '.RaiseResponseNeverReceivedDownloadHandler', 
        }
    }

    def parse(self, response):
        pass
```

```
$ scrapy runspider retry.py
(...)
2019-09-02 13:47:40 [scrapy.core.engine] INFO: Spider opened
2019-09-02 13:47:40 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2019-09-02 13:47:40 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2019-09-02 13:47:40 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://example.org> (failed 1 times): Manually raised from download handler
2019-09-02 13:47:40 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://example.org> (failed 2 times): Manually raised from download handler
2019-09-02 13:47:41 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://example.org> (failed 3 times): Manually raised from download handler
2019-09-02 13:47:41 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://example.org> (failed 4 times): Manually raised from download handler
2019-09-02 13:47:41 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://example.org> (failed 5 times): Manually raised from download handler
2019-09-02 13:47:41 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://example.org> (failed 6 times): Manually raised from download handler
2019-09-02 13:47:41 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://example.org> (failed 7 times): Manually raised from download handler
2019-09-02 13:47:41 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://example.org> (failed 8 times): Manually raised from download handler
2019-09-02 13:47:41 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://example.org> (failed 9 times): Manually raised from download handler
2019-09-02 13:47:41 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://example.org> (failed 10 times): Manually raised from download handler
2019-09-02 13:47:41 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET https://example.org> (failed 11 times): Manually raised from download handler
2019-09-02 13:47:41 [scrapy.core.scraper] ERROR: Error downloading <GET https://example.org>
Traceback (most recent call last):
  File "/.../venv-scrapy/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/.../venv-scrapy/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/.../scrapy/core/downloader/middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "/.../scrapy/utils/defer.py", line 45, in mustbe_deferred
    result = f(*args, **kw)
  File "/.../scrapy/core/downloader/handlers/__init__.py", line 71, in download_request
    return handler.download_request(request, spider)
  File "/.../retry.py", line 8, in download_request
    raise ResponseNeverReceived('Manually raised from download handler')
twisted.web._newclient.ResponseNeverReceived: Manually raised from download handler
2019-09-02 13:47:42 [scrapy.core.engine] INFO: Closing spider (finished)
2019-09-02 13:47:42 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 11,
 'downloader/exception_type_count/twisted.web._newclient.ResponseNeverReceived': 11,
 'downloader/request_bytes': 2310,
 'downloader/request_count': 11,
 'downloader/request_method_count/GET': 11,
 'elapsed_time_seconds': 1.347074,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2019, 9, 2, 16, 47, 42, 67293),
 'log_count/DEBUG': 11,
 'log_count/ERROR': 1,
 'log_count/INFO': 10,
 'memusage/max': 53813248,
 'memusage/startup': 53813248,
 'retry/count': 10,
 'retry/max_reached': 1,
 'retry/reason_count/twisted.web._newclient.ResponseNeverReceived': 10,
 'scheduler/dequeued': 11,
 'scheduler/dequeued/memory': 11,
 'scheduler/enqueued': 11,
 'scheduler/enqueued/memory': 11,
 'start_time': datetime.datetime(2019, 9, 2, 16, 47, 40, 720219)}
2019-09-02 13:47:42 [scrapy.core.engine] INFO: Spider closed (finished)
```

The `proxies/*` stats don't seem to come from `scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware`, are you using a custom middleware to handle them?

**Comment by botzill** [comment]
Thx @elacuesta!

Sorry did not mention that I'm using  https://github.com/TeamHG-Memex/scrapy-rotating-proxies.

And my settings are:

```pyhon
DOWNLOADER_MIDDLEWARES = {
    'rotating_proxies.middlewares.RotatingProxyMiddleware': 610,
    'rotating_proxies.middlewares.BanDetectionMiddleware': 620,
    'arbitr_ru_crawler.middlewares.ArbitrRuCrawlerDownloaderMiddleware': 851,
    'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware': None,
    'scrapy_fake_useragent.middleware.RandomUserAgentMiddleware': 400,
    'scrapy.downloadermiddlewares.retry.RetryMiddleware': None,
    'my_project.downloadermiddlewares.retry.RetryMiddleware': 550,
}
```

**Comment by elacuesta** [comment]
The relevant middlewares in this case are the following:

```python
DOWNLOADER_MIDDLEWARES = {
    # Engine side
    'my_project.downloadermiddlewares.retry.RetryMiddleware': 550,
    'rotating_proxies.middlewares.RotatingProxyMiddleware': 610,
    'rotating_proxies.middlewares.BanDetectionMiddleware': 620,
    # Downloader side
}
```

It is not explicitly stated in [the docs](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html), but checking the code ([here](https://github.com/scrapy/scrapy/blob/1.7.3/scrapy/core/downloader/middleware.py#L29-L32) and [here](https://github.com/scrapy/scrapy/blob/1.7.3/scrapy/core/downloader/middleware.py#L74-L75), for instance) you can see that the `process_exception` methods are executed in the same order as the `process_response` ones, i.e., in decreasing numeric order.

Then, if the download handler raises a `ResponseNeverReceived` exception, the flow is as follows:

* [`BanDetectionMiddleware.process_exception`](https://github.com/TeamHG-Memex/scrapy-rotating-proxies/blob/0.6.2/rotating_proxies/middlewares.py#L292-L300) handles the exception, and since it does not have an explicit return value, it implicitly returns `None`, handling the exception to the [next `process_exception` method in the chain](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#scrapy.downloadermiddlewares.DownloaderMiddleware.process_exception)
* [`RotatingProxyMiddleware.process_exception`](https://github.com/TeamHG-Memex/scrapy-rotating-proxies/blob/0.6.2/rotating_proxies/middlewares.py#L151-L152) handles the exception, calling [`RotatingProxyMiddleware._handle_result`](https://github.com/TeamHG-Memex/scrapy-rotating-proxies/blob/0.6.2/rotating_proxies/middlewares.py#L157-L171)
* `RotatingProxyMiddleware._handle_result` is executed, potentially retrying the request at [this line](https://github.com/TeamHG-Memex/scrapy-rotating-proxies/blob/0.6.2/rotating_proxies/middlewares.py#L168). I suspect you would be seeing a lot of messages from [this line](https://github.com/TeamHG-Memex/scrapy-rotating-proxies/blob/0.6.2/rotating_proxies/middlewares.py#L179-L184) if you enabled DEBUG logging.

At this point, the `RetryMiddleware` never gets to do its job.
I don't think this is a bug within Scrapy, instead I believe a new issue should be opened in https://github.com/TeamHG-Memex/scrapy-rotating-proxies. Maybe a solution would be to modify the `RotatingProxyMiddleware._retry` method to update the appropriate stats (`proxies/retried` or something similar?).
