### ISSUE TITLE
ModuleNotFoundError: No module named 'tutsplus'

### ISSUE THREAD

**Issue by tommyamz** [scrapy/scrapy#4004]
Hi please help me on this errror when i trying run project on Mac OS
I install Python 3.7.4 and Scrapy 1.7.3

```
(AMZSpider) ToanVoMBP:tutsplus toanvo$ scrapy crawl tutplus

Traceback (most recent call last):
  File "/Users/toanvo/.virtualenvs/AMZSpider/bin/scrapy", line 10, in <module>
    sys.exit(execute())
  File "/Users/toanvo/.virtualenvs/AMZSpider/lib/python3.7/site-packages/scrapy/cmdline.py", line 114, in execute
    settings = get_project_settings()
  File "/Users/toanvo/.virtualenvs/AMZSpider/lib/python3.7/site-packages/scrapy/utils/project.py", line 68, in get_
project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/Users/toanvo/.virtualenvs/AMZSpider/lib/python3.7/site-packages/scrapy/settings/__init__.py", line 294, in
 setmodule
    module = import_module(module)
  File "/Users/toanvo/.virtualenvs/AMZSpider/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tutsplus'
```

**Comment by omeshomes** [comment]
Could you provide more information about where you're importing `tutsplus`, and what your directory structure is?

Also note that your initial command runs the `tutplus` spider instead of `tutsplus`, so this may just be a spelling error.

**Comment by elacuesta** [comment]
@tommyamz Please, do provide more information. I suspect you might have a problem in the way the settings module is being configured. In particular, check the contents of the `scrapy.cfg` file, and see if you are manually setting a value for the `SCRAPY_SETTINGS_MODULE` environment variable.

I was able to get a similar traceback by setting a bad path in `SCRAPY_SETTINGS_MODULE` (changing the path in `scrapy.cfg` produces the same result)

```
$ SCRAPY_SETTINGS_MODULE=invalid_module scrapy crawl my_spider
Traceback (most recent call last):
 File "/.../venv/bin/scrapy", line 11, in <module>
   sys.exit(execute())
 File "/.../venv/lib/python3.6/site-packages/scrapy/cmdline.py", line 114, in execute
   settings = get_project_settings()
 File "/.../venv/lib/python3.6/site-packages/scrapy/utils/project.py", line 68, in get_project_settings
   settings.setmodule(settings_module_path, priority='project')
 File "/.../venv/lib/python3.6/site-packages/scrapy/settings/__init__.py", line 294, in setmodule
   module = import_module(module)
 File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
   return _bootstrap._gcd_import(name[level:], package, level)
 File "<frozen importlib._bootstrap>", line 994, in _gcd_import
 File "<frozen importlib._bootstrap>", line 971, in _find_and_load
 File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'invalid_module'
```

**Comment by Gallaecio** [comment]
Closing after more than a month without feedback.
