### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'newproject/newproject/settings.py.tmpl'

### ISSUE THREAD

**Issue by ivngithub** [scrapy/scrapy#4019]
### Description

When I do scrapy startproject I got this problem:
FileNotFoundError: [Errno 2] No such file or directory: 'newproject/newproject/settings.py.tmpl'

But this fil is already!

and I use VBox and have share folder from Windows

**Comment by Gallaecio** [comment]
Could you specify how you installed Scrapy, the whole `scrapy startproject` command you are using, and the whole output of that command?

Can you reproduce this issue from scratch? i.e. if you re-install Scrapy and run `scrapy startproject` on a new folder.

**Comment by Gallaecio** [comment]
Closing after a month without feedback.

**Comment by dfriestedt** [comment]
I am getting this same error below.

I have in a vagrant box - ubuntu 18.04 fresh install with scrapy and all the dependancies shown here:  https://docs.scrapy.org/en/latest/intro/install.html

When I run the command it creates the project and folder structure.  But I do get this error message.  

vagrant@vagrant:/vagrant$ scrapy startproject webcam
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python3.6/dist-packages/scrapy/cmdline.py", line 146, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/cmdline.py", line 100, in _run_print_help
    func(*a, **kw)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/cmdline.py", line 154, in _run_command
    cmd.run(args, opts)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/commands/startproject.py", line 109, in run
    ProjectName=string_camelcase(project_name))
  File "/usr/local/lib/python3.6/dist-packages/scrapy/utils/template.py", line 9, in render_templatefile
    with open(path, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'webcam/webcam/settings.py.tmpl'

**Comment by Fortytwoo** [comment]
The above problem can be solved by reinstalling scrapy. The guess is that the environment dependencies are missing.
