### ISSUE TITLE
Scrapy download middelware should pause on  Connection loss and Resume when internet connection is available.

### ISSUE THREAD

**Issue by royahsan** [scrapy/scrapy#4043]
## Summary
 We should make Scrapy downlaoder middleware pause when Internet connection is lost, and wait until it is back and than resume the downlaod middleware. 

## Motivation

Currently scrapy on a connection lost keeps trying to download/fetch the url MAX_RETRIES time and eventually logs the Request as Downloading error. Which is completely undesirable. Why not provide this feature out of the box. 

## Alternatives I have considered

Adding a custom downloader middleware to check the internet connection is possible but quite heavy addittion considering connection drops are somewhat rare.

**Comment by royahsan** [comment]
Currently this is what happens if we intentionally close an internet connection while Scrapy is running.
Removed some of output as it repeated.
```
DEBUG: scrapy.downloadermiddlewares.retry:  Gave up retrying <GET https://mblsportal.sos.state.mn.us//Business/SearchDetails?filingGuid=6f38440e-98d4-e011-a886-001ec94ffe7f> (failed 3 times): An error occurred while connecting: 10065: A socket operation was attempted to an unreachable host..
DEBUG: scrapy.downloadermiddlewares.retry:  Gave up retrying <GET https://mblsportal.sos.state.mn.us//Business/SearchDetails?filingGuid=b39261af-8dd4-e011-a886-001ec94ffe7f> (failed 3 times): An error occurred while connecting: 10065: A socket operation was attempted to an unreachable host..
DEBUG: scrapy.downloadermiddlewares.retry:  Gave up retrying <GET https://mblsportal.sos.state.mn.us//Business/SearchDetails?filingGuid=961e0bf0-8bf1-e711-9154-00155d0d6f70> (failed 3 times): An error occurred while connecting: 10065: A socket operation was attempted to an unreachable host..
DEBUG: scrapy.downloadermiddlewares.retry:  Gave up retrying <GET https://mblsportal.sos.state.mn.us//Business/SearchDetails?filingGuid=9d89bcce-ddee-e611-8169-00155d01d700> (failed 3 times): An error occurred while connecting: 10065: A socket operation was attempted to an unreachable host..
DEBUG: scrapy.downloadermiddlewares.retry:  Gave up retrying <GET https://mblsportal.sos.state.mn.us//Business/SearchDetails?filingGuid=3a42906f-88d4-e011-a886-001ec94ffe7f> (failed 3 times): An error occurred while connecting: 10065: A socket operation was attempted to an unreachable host..
ERROR: scrapy.core.scraper:  Error downloading <GET https://mblsportal.sos.state.mn.us/Business/BusinessSearch?BusinessName=C&IncludePriorNames=False&Status=Active&Type=BeginsWith>
Traceback (most recent call last):
  File "C:\Users\royah\AppData\Local\Programs\Python\Python36\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
twisted.internet.error.ConnectError: An error occurred while connecting: 10065: A socket operation was attempted to an unreachable host..
DEBUG: scrapy.downloadermiddlewares.retry:  Gave up retrying <GET https://mblsportal.sos.state.mn.us//Business/SearchDetails?filingGuid=b8b4678c-b0d4-e011-a886-001ec94ffe7f> (failed 3 times): An error occurred while connecting: 10065: A socket operation was attempted to an unreachable host..
ERROR: scrapy.core.scraper:  Error downloading <GET https://mblsportal.sos.state.mn.us//Business/SearchDetails?filingGuid=7ac7fdab-77f9-e711-9155-00155d0d6f70>
Traceback (most recent call last):
  File "C:\Users\royah\AppData\Local\Programs\Python\Python36\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
twisted.internet.error.ConnectError: An error occurred while connecting: 10065: A socket operation was attempted to an unreachable host..
ERROR: scrapy.core.scraper:  Error downloading <GET https://mblsportal.sos.state.mn.us//Business/SearchDetails?filingGuid=956fa4e2-95d4-e011-a886-001ec94ffe7f>
Traceback (most recent call last):
  File "C:\Users\royah\AppData\Local\Programs\Python\Python36\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
twisted.internet.error.ConnectError: An error occurred while connecting: 10065: A socket operation was attempted to an unreachable host..
DEBUG: scrapy.downloadermiddlewares.retry:  Gave up retrying <GET https://mblsportal.sos.state.mn.us//Business/SearchDetails?filingGuid=e63bb392-20fb-e711-9155-00155d0d6f70> (failed 3 times): An error occurred while connecting: 10065: A socket operation was attempted to an unreachable host..
ERROR: scrapy.core.scraper:  Error downloading <GET https://mblsportal.sos.state.mn.us//Business/SearchDetails?filingGuid=3fdb311c-2a37-e611-816a-00155d01c56d>
Traceback (most recent call last):
  File "C:\Users\royah\AppData\Local\Programs\Python\Python36\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
twisted.internet.error.ConnectError: An error occurred while connecting: 10065: A socket operation was attempted to an unreachable host..
ERROR: scrapy.core.scraper:  Error downloading <GET https://mblsportal.sos.state.mn.us//Business/SearchDetails?filingGuid=4e9b9e77-a00b-e611-8169-00155d01c56d>
Traceback (most recent call last):
  File "C:\Users\royah\AppData\Local\Programs\Python\Python36\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
twisted.internet.error.ConnectError: An error occurred while connecting: 10065: A socket operation was attempted to an unreachable host..
DEBUG: scrapy.downloadermiddlewares.retry:  Gave up retrying <GET https://mblsportal.sos.state.mn.us//Business/SearchDetails?filingGuid=68e4f671-f9b5-e411-b14d-001ec94ffe7f> (failed 3 times): An error occurred while connecting: 10065: A socket operation was attempted to an unreachable host..
ERROR: scrapy.core.scraper:  Error downloading <GET https://mblsportal.sos.state.mn.us//Business/SearchDetails?filingGuid=b18341bb-b6e4-e611-8169-00155d01d700>
Traceback (most recent call last):
  File "C:\Users\royah\AppData\Local\Programs\Python\Python36\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
twisted.internet.error.ConnectError: An error occurred while connecting: 10065: A socket operation was attempted to an unreachable host..
DEBUG: scrapy.downloadermiddlewares.retry:  Gave up retrying <GET https://mblsportal.sos.state.mn.us//Business/SearchDetails?filingGuid=cc86ef81-5e32-e211-bc43-001ec94ffe7f> (failed 3 times): An error occurred while connecting: 10065: A socket operation was attempted to an unreachable host..
ERROR: scrapy.core.scraper:  Error downloading <GET https://mblsportal.sos.state.mn.us//Business/SearchDetails?filingGuid=60be1093-03a0-e311-97ba-001ec94ffe7f>
Traceback (most recent call last):
  File "C:\Users\royah\AppData\Local\Programs\Python\Python36\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
twisted.internet.error.ConnectError: An error occurred while connecting: 10065: A socket operation was attempted to an unreachable host..
DEBUG: scrapy.downloadermiddlewares.retry:  Gave up retrying <GET https://mblsportal.sos.state.mn.us//Business/SearchDetails?filingGuid=c5f00019-92d4-e011-a886-001ec94ffe7f> (failed 3 times): An error occurred while connecting: 10065: A socket operation was attempted to an unreachable host..
ERROR: scrapy.core.scraper:  Error downloading <GET https://mblsportal.sos.state.mn.us//Business/SearchDetails?filingGuid=aae27fa6-e118-e411-ac2f-001ec94ffe7f>
Traceback (most recent call last):
  File "C:\Users\royah\AppData\Local\Programs\Python\Python36\lib\site-packages\scrapy\core\downloader\middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
twisted.internet.error.ConnectError: An error occurred while connecting: 10065: A socket operation was attempted to an unreachable host..

```

Than the spider closes with following stats

```
INFO: scrapy.statscollectors:  Dumping Scrapy stats:
{'crawlera/request': 1685,
 'crawlera/request/method/GET': 1685,
 'crawlera/response': 22,
 'crawlera/response/error': 6,
 'crawlera/response/error/too_many_conns': 6,
 'crawlera/response/status/200': 16,
 'crawlera/response/status/429': 6,
 'downloader/exception_count': 1663,
 'downloader/exception_type_count/twisted.internet.error.ConnectError': 1661,
 'downloader/exception_type_count/twisted.internet.error.TimeoutError': 2,
 'downloader/request_bytes': 1203250,
 'downloader/request_count': 1685,
 'downloader/request_method_count/GET': 1685,
 'downloader/response_bytes': 370067,
 'downloader/response_count': 22,
 'downloader/response_status_count/200': 16,
 'downloader/response_status_count/429': 6,
 'dupefilter/filtered': 12,
 'elapsed_time_seconds': 386.040118,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2019, 9, 29, 0, 51, 50, 769001),
 'item_scraped_count': 11,
 'log_count/CRITICAL': 2,
 'log_count/DEBUG': 1711,
 'log_count/ERROR': 556,
 'log_count/INFO': 28,
 'log_count/WARNING': 10,
 'request_depth_max': 2,
 'response_received_count': 16,
 'retry/count': 1114,
 'retry/max_reached': 555,
 'retry/reason_count/429 Unknown Status': 6,
 'retry/reason_count/twisted.internet.error.ConnectError': 1106,
 'retry/reason_count/twisted.internet.error.TimeoutError': 2,
 'scheduler/dequeued': 1685,
 'scheduler/dequeued/memory': 1685,
 'scheduler/enqueued': 1685,
 'scheduler/enqueued/memory': 1685,
 'start_time': datetime.datetime(2019, 9, 29, 0, 45, 24, 728883)}
INFO: scrapy.core.engine:  Spider closed (finished)

```

**Comment by Gallaecio** [comment]
It might be difficult to implement properly, given solutions that rotate proxies where one request may fail because of a bad proxy and the next may succeed because it uses a different proxy.

But it may be reasonable as an opt-in option.

**Comment by amardeep24** [comment]
@Gallaecio how can we approach this? I don't think simple checking the `ConnectError` and not implementing the retry count would be such a good idea?

**Comment by royahsan** [comment]
@amardeep24  you are right, only not incrementing on a **ConnectError** can potentially lead to an infinite looping over the same request when the target website / host is intentionally rejecting the connections.  Same error is being thrown when the target website actively refuses connection incase it bans an IP.

**Comment by royahsan** [comment]
@Gallaecio I think our approach would be that whenever such error occur , we just make sure that internet is not gone, and our method of making sure that internet is there and our method would be irrelevant to the proxy currently being used, 
So we just check if internet is there:
 If it is, dont do anything, and let the exception go through.
If it is not, wait for the internet to be back, and again let the exception go through. Maybe decrement retry count this time because exception should have been generate by internet not available.

**Comment by Gallaecio** [comment]
I guess checking if internet connection works by requesting a certain URL without proxy that we expect to answer could work. A HEAD request to http://quotes.toscrape.com/ could work. But we would have to allow changing at least the target URL through a setting.

**Comment by ejulio** [comment]
For me it sounds like a `Circuit Breaker` pattern.
Usually, when something fails in a few attempts, you reject/buffer the next calls and try them again after a few moments.
Maybe, retry middleware could handle it, by adding some time intervals.
Otherwise, this could be a behavior with some flag, say, `STOP_AFTER_N_ERRORS` and then, only retry after some time.
