### ISSUE TITLE
replace the twisted reactor to pollreactor

### ISSUE THREAD

**Issue by SyuuGenn** [scrapy/scrapy#4134]
It's related to #2905. When I'm using scrapy, I got the error "Failure instance: Traceback: <class 'ValueError'>: filedescriptor out of range in select()". So I want to try replacing the twisted reactor to pollreactor. However, I cannot use my project settings. When I run

`from twisted.internet import pollreactor
pollreactor.install()
from twisted.internet import reactor
from scrapy.crawler import CrawlerRunner
from scrapy.utils.project import get_project_settings

runner = CrawlerRunner(get_project_settings())`

it raises the error "ReactorAlreadyInstalledError("reactor already installed")
twisted.internet.error.ReactorAlreadyInstalledError: reactor already installed".

Can you help me to fix this?

My environment is MacOS Catalina 10.15.1, Python 3.8.0, twisted 19.7.0, and scrapy 1.8.0.

**Comment by Gallaecio** [comment]
@wRAR something to keep in mind while working on asyncio support, I guess.

**Comment by wRAR** [comment]
Hi @SyuuGenn ! I couldn't reproduce it, can you provide the full traceback please?

**Comment by SyuuGenn** [comment]
@wRAR Thanks for your reply! My traceback were as follows.

Traceback (most recent call last):
  File "sina/spiders/weibo_spider.py", line 282, in <module>
    process = CrawlerProcess(get_project_settings())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/crawler.py", line 267, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/crawler.py", line 145, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/crawler.py", line 347, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/spiderloader.py", line 61, in from_settings
    return cls(settings)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/spiderloader.py", line 25, in __init__
    self._load_all_spiders()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/spiderloader.py", line 47, in _load_all_spiders
    for module in walk_modules(name):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapy/utils/misc.py", line 73, in walk_modules
    submod = import_module(fullpath)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/yuanzhou/Dropbox/Python/WeiboSpider/sina/spiders/weibo_spider.py", line 4, in <module>
    pollreactor.install()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/internet/pollreactor.py", line 186, in install
    installReactor(p)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/internet/main.py", line 32, in installReactor
    raise error.ReactorAlreadyInstalledError("reactor already installed")
twisted.internet.error.ReactorAlreadyInstalledError: reactor already installed

**Comment by wRAR** [comment]
So your `sina/spiders/weibo_spider.py` is at the same time a spider module and an executable script containing code that uses CrawlerProcess, just don't do that? The same code runs twice so of course it fails.

**Comment by SyuuGenn** [comment]
I put `pollreactor.install()` under `if __name__ == '__main__`, but the error still exists.

Traceback (most recent call last):
  File "sina/spiders/weibo_spider.py", line 281, in <module>
    pollreactor.install()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/internet/pollreactor.py", line 186, in install
    installReactor(p)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/internet/main.py", line 32, in installReactor
    raise error.ReactorAlreadyInstalledError("reactor already installed")
twisted.internet.error.ReactorAlreadyInstalledError: reactor already installed

Did I misunderstand what you said?

**Comment by wRAR** [comment]
That's because some imports you have at the top-level already installed the reactor. 

Just make it a separate script. This is not a Scrapy problem, this is a problem with your code organization, which causes Scrapy to execute your code second time, when Scrapy imports all spiders. Scripts shouldn't be put into the spiders directory, they are scripts, not spider modules.

**Comment by SyuuGenn** [comment]
@wRAR Thank you very much! But I still can't understand well. What I want is to evade the ValueError mentioned in #2905. How can I replace the SelectReactor to PollReactor without changing my project settings? If I put the spider script elsewhere, how should I use the middlewares, item pipes and other settings?

**Comment by wRAR** [comment]
Are you saying you didn't previously use a script in this project? If so, I don't know a simple way of fixing this without making a script.

>  how should I use the middlewares, item pipes and other settings?

If you still use the same project settings, they should be used in the same way as when running spiders via scrapy.

**Comment by SyuuGenn** [comment]
@wRAR Yes. I wrote my scrapy project based on other people's work rather than starting from a script.

I just added
`from twisted.internet import pollreactor
from twisted.internet import reactor`
in the beginning and  `pollreactor.install()` under `if __name__ == '__main__':` into my  very first code. I ran  `scrapy crawl weibo_spider` from terminal and it is working. After 10 hours I will know if it solved the ValueError problem. Thanks again!

**Comment by wRAR** [comment]
`scrapy crawl weibo_spider` ignores the `if __name__ == '__main__'` part.

**Comment by SyuuGenn** [comment]
@wRAR Oh, yes. The ValueError happened again. If I move `pollreactor.install()` after `from twisted.internet import pollreactor`, the ReactorAlreadyInstalledError happens. So what should I do?

**Comment by wRAR** [comment]
@SyuuGenn make a script and use it instead of `scrapy crawl`.

**Comment by SyuuGenn** [comment]
@wRAR I'm a beginner in Python programming, and I don't know how to use script to import my project settings. Can you show me an example to do that? The examples in the scrapy documentation (https://docs.scrapy.org/en/latest/topics/practices.html#run-from-script) are either using the default select reactor or without importing project settings.

**Comment by Gallaecio** [comment]
Since this is not a feature request of a bug, @SyuuGenn please move your question to [StackOverflow](https://stackoverflow.com/tags/scrapy). See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).

Mind that “I don't know how to use script to import my project settings” feels like the type of question that must have been asked and answered already, so please search StackOverflow for a bit before you post your question.
