### ISSUE TITLE
SitemapSpider throws lxml.etree.XMLSyntaxError when trying to scrape a blank sitemap page

### ISSUE THREAD

**Issue by Endi1** [scrapy/scrapy#4211]
### Description

`SitemapSpider` throws a `lxml.etree.XMLSyntaxError` when hitting a blank sitemap page while crawling a sitemap. 

### Stack trace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/usr/local/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.8/site-packages/sh_scrapy/middlewares.py", line 30, in process_spider_output
    for x in result:
  File "/usr/local/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.8/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/usr/local/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.8/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/usr/local/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.8/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.8/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python3.8/site-packages/scrapy/spiders/sitemap.py", line 53, in _parse_sitemap
    s = Sitemap(body)
  File "/usr/local/lib/python3.8/site-packages/scrapy/utils/sitemap.py", line 18, in __init__
    self._root = lxml.etree.fromstring(xmltext, parser=xmlp)
  File "src/lxml/etree.pyx", line 3234, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1764, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1
```

### Steps to Reproduce

1. Crawl sitemap with at least a blank `.xml` page

**Expected behavior:** 
Handle the `XMLSyntaxError` by logging a warning for an invalid sitemap page and returning.

**Actual behavior:** 
Throws `XMLSyntaxError`

### Versions

Scrapy version 1.7.2

**Comment by devmodi154** [comment]
@Endi1 I tried to reproduce the error using the given link. But it works fine with the following spider!
`from scrapy.spiders import SitemapSpider

class SiteSpider(SitemapSpider):
    name = 'SiteSpider'
    sitemap_urls = ['https://bikeradar.com/sitemap.xml']
    sitemap_rules = [('trump', 'parse_article')]

    def parse_article(self, response):
        print('parse_article url:', response.url)
        yield {'url': response.url}

# --- it runs without project and saves in `output.csv` ---

from scrapy.crawler import CrawlerProcess

c = CrawlerProcess({
    'USER_AGENT': 'Mozilla/5.0',

    # save in file as CSV, JSON or XML
    'FEED_FORMAT': 'csv',     # csv, json, xml
    'FEED_URI': 'output.csv', # 
})
c.crawl(SiteSpider)
c.start()`

**Comment by Yogita98** [comment]
Is this issue up for grabs?

**Comment by Gallaecio** [comment]
There has been an attempt at it, https://github.com/scrapy/scrapy/pull/4214, but it seems stale. Feel free to give it a try, either from scratch of based on https://github.com/scrapy/scrapy/pull/4214.

**Comment by AdrianAtZyte** [comment]
#7007
