### ISSUE TITLE
Scrapy fails to crawl emoji domains, raises idna.core.InvalidCodepoint

### ISSUE THREAD

**Issue by john-parton** [scrapy/scrapy#4330]
### Description

Scrapy fails to crawl [emoji domains](https://en.wikipedia.org/wiki/Emoji_domain). Specifically, [i❤.ws](https://xn--i-7iq.ws/)

Raises the following:

`idna.core.InvalidCodepoint: Codepoint U+2764 at position 2 of 'i❤' not allowed`

### Steps to Reproduce

1. Create a `CrawlSpider` with `allowed_domains` including an emoji domain, and `start_urls` including an emoji domain.
2. Begin crawl with `scrapy crawl`

**Expected behavior:** Crawl site just like any other domain; do not raise an exception.

**Actual behavior:** Immediately raises exception.

**Reproduces how often:** Fails every time in my environment.

### Versions

```
Scrapy       : 1.8.0
lxml         : 4.4.2.0
libxml2      : 2.9.9
cssselect    : 1.1.0
parsel       : 1.5.2
w3lib        : 1.21.0
Twisted      : 19.10.0
Python       : 3.8.0 (default, Dec  6 2019, 10:12:02) - [GCC 7.4.0]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1d  10 Sep 2019)
cryptography : 2.8
Platform     : Linux-4.15.0-74-generic-x86_64-with-glibc2.27
```

### Additional context

I used the following `CrawlSpider`:

```python
from scrapy.spiders import CrawlSpider, Rule
from scrapy.linkextractors import LinkExtractor


class EmojiCrawlSpider(CrawlSpider):
    name = "emoji_test"
    allowed_domains = ['xn--i-7iq.ws']

    start_urls = ['https://xn--i-7iq.ws/']

    rules = (
        Rule(
            LinkExtractor(),
            callback="parse_items",
            follow=True
        ),
    )

    def parse_items(self, response):
        print(response.url)
```

Traceback:

```
Traceback (most recent call last):
  File "/home/john/Code/venv/scrapy/lib/python3.8/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/john/Code/venv/scrapy/lib/python3.8/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/john/Code/venv/scrapy/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/john/Code/venv/scrapy/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/john/Code/venv/scrapy/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/john/Code/venv/scrapy/lib/python3.8/site-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/home/john/Code/venv/scrapy/lib/python3.8/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/john/Code/venv/scrapy/lib/python3.8/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
    return self._wrappedProtocol.dataReceived(data)
  File "/home/john/Code/venv/scrapy/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http11.py", line 148, in processProxyResponse
    sslOptions = self._contextFactory.creatorForNetloc(self._tunneledHost, self._tunneledPort)
  File "/home/john/Code/venv/scrapy/lib/python3.8/site-packages/scrapy/core/downloader/contextfactory.py", line 61, in creatorForNetloc
    return ScrapyClientTLSOptions(hostname.decode("ascii"), self.getContext(),
  File "/home/john/Code/venv/scrapy/lib/python3.8/site-packages/scrapy/core/downloader/tls.py", line 50, in __init__
    super(ScrapyClientTLSOptions, self).__init__(hostname, ctx)
  File "/home/john/Code/venv/scrapy/lib/python3.8/site-packages/twisted/internet/_sslverify.py", line 1174, in __init__
    self._hostnameBytes = _idnaBytes(hostname)
  File "/home/john/Code/venv/scrapy/lib/python3.8/site-packages/twisted/internet/_idna.py", line 30, in _idnaBytes
    return idna.encode(text)
  File "/home/john/Code/venv/scrapy/lib/python3.8/site-packages/idna/core.py", line 358, in encode
    s = alabel(label)
  File "/home/john/Code/venv/scrapy/lib/python3.8/site-packages/idna/core.py", line 270, in alabel
    ulabel(label)
  File "/home/john/Code/venv/scrapy/lib/python3.8/site-packages/idna/core.py", line 308, in ulabel
    check_label(label)
  File "/home/john/Code/venv/scrapy/lib/python3.8/site-packages/idna/core.py", line 261, in check_label
    raise InvalidCodepoint('Codepoint {0} at position {1} of {2} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
idna.core.InvalidCodepoint: Codepoint U+2764 at position 2 of 'i❤' not allowed
```
Possibly related to https://github.com/scrapy/scrapy/issues/3321, but domain is valid and raises different Exception.

**Comment by mmghannam** [comment]
Hi! I would like to work on this.

**Comment by surajnai567** [comment]
the scapy uses idna library for URL Encoding.
this problem reside in idna itself.

**Comment by john-parton** [comment]
I believe it might be due to this open issue with idna. https://github.com/kjd/idna/issues/61

**Comment by john-parton** [comment]
This _does_ work if you use the built-in `idna` encoding.

```
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 'i❤.ws'.encode('idna')
b'xn--i-7iq.ws'
```

Is there a reason we're using the idna library instead of the built-in encoding?

**Comment by kjd** [comment]
`i❤.ws` doesn't work because it is an illegal domain. See [RFC 5891](https://tools.ietf.org/html/rfc5891), specifically noted in Appendix A, "Disallow symbol and punctuation characters except where special exceptions are necessary". Python's idna codec works because it is from an earlier version of the spec that is now been superseded. The `idna` library exists to implement the modern version of the specification, which supports many more languages.

**Comment by Gallaecio** [comment]
`i❤.ws` works in a web browser. I think it should work in Scrapy as well.

**Comment by nyov** [comment]
@kjd, thanks for commenting. I'm not very knowledgeable w.r.t. IDNA/Unicode.
Are these disallowances here generic blanket restrictions, or for other reasons, perhaps some stated in https://www.iab.org/documents/correspondence-reports-documents/2018-2/iab-statement-on-identifiers-and-unicode/ (which I don't entirely understand, except that it equates to "visual hash collisions" for me, which is bad)?

And would anyone know why browsers behave differently here, are they also still following older IDNA spec or just making allowances for some extra unicode characters or regions there, perhaps?

I'm wondering how we might best handle the issue here, assuming the `idna` library won't address this because it has to follow spec. The emoji regions are not well defined, some are Misc Symbols, some are in Dingbats, others in Transport symbols,... but precluding a manual lookup map (unless one exists), perhaps we might just add the range to PVALID while at the same time limiting it to the few ccTLDs that advertise support for these emoji domains? Then if someone requests bad domain names for invalid pictograms or such, they'll be limited to do so against those TLDs' DNS servers (and let them handle that).
Not sure if that makes sense, since my understanding is quite limited.

Of course anything like that would be another monkeypatch by scrapy to carry, so something generic would be preferrable.

**Comment by nyov** [comment]
A hack for the desperate:

```patch
diff --git a/scrapy/_monkeypatches.py b/scrapy/_monkeypatches.py
index f74f89bd..af9b1f4b 100644
--- a/scrapy/_monkeypatches.py
+++ b/scrapy/_monkeypatches.py
@@ -1,5 +1,17 @@
 import copyreg
 
+try:
+    """ HACK to use python builtin idna lookup for emoji TLD domain names """
+    import idna
+    from idna import encode as iencode, decode as idecode
+    # ccTLD list generated from:
+    # scrapy shell 'https://emojicatch.com/%F0%9F%98%80'
+    # >>> tlds = tuple(response.xpath('//div[@id="results"]/button/p/text()').getall())
+    tlds = ('.ws', '.to', '.ga', '.cf', '.tk', '.ml', '.gq', '.st', '.fm', '.je', '.gg', '.radio.am', '.radio.fm', '.kz', '.com.kz', '.org.kz')
+    tldb = tuple([t.encode() for t in tlds])
+    idna.encode = lambda text: text.encode("idna") if text.endswith(tlds) else iencode(text)
+    idna.decode = lambda octs: octs.decode("idna") if octs.endswith(tldb) else idecode(octs)
+except: pass
 
 # Undo what Twisted's perspective broker adds to pickle register
 # to prevent bugs like Twisted#7989 while serializing requests
```

**Comment by kmike** [comment]
I think the decision to use `idna` package instead of built-in `idna` is made by hyperlink, see https://github.com/python-hyper/hyperlink/pull/56 and https://github.com/python-hyper/hyperlink/issues/19 for motivation.

**Comment by Gallaecio** [comment]
Maybe we could provide some package that implements [UTR46](https://www.unicode.org/reports/tr46/)’s ToASCII and ToUnicode methods, and propose that they be used in the corresponding upstream projects.

Those methods are similar to IDNA’s encode and decode, but can be more lenient. The URL living standard relies on ToASCII, with lenient parameters (not even domain length limits are checked).

I plan to work on a private implementation of ToASCII for https://github.com/scrapy/w3lib/pull/201. Maybe we could add also a ToUnicode implementation, and either make them public within w3lib, or move them to a separate package (a new one called `utr46`?).

Before doing any of it, though, we might want to ask those upstream projects what their thoughts are, i.e. if they would be willing to switch to the more lenient implementation, and under what conditions (e.g. performance and size of this new library).

**Comment by kjd** [comment]
I'd caution that the main reason the the IDNA standard was revised was to remove support for symbols like emoji due to their security risks. Anyone who wants to perpetuate support for them should be explicitly opt-in to accept these security risks, and know what they are doing. Most registries ban registrations of emoji domains and they are overall being phased out. Substituting the older IDNA 2003 implementations will also be incompatible on some domains as some domains will convert differently in the current version.

**Comment by john-parton** [comment]
## Update

Firefox no longer renders the website in my test case with an emoji.

![Screenshot from 2022-11-17 10-32-13](https://user-images.githubusercontent.com/2071543/202503406-f904101f-2554-47ee-a8ca-5134da323824.png)

However, the scraper as it is written still fails.

The correct behavior should be to not decode the punycode and present the URL as it is rendered there rather than raise an exception, imho.

**Comment by john-parton** [comment]
> I'd caution that the main reason the the IDNA standard was revised was to remove support for symbols like emoji due to their security risks. Anyone who wants to perpetuate support for them should be explicitly opt-in to accept these security risks, and know what they are doing. Most registries ban registrations of emoji domains and they are overall being phased out. Substituting the older IDNA 2003 implementations will also be incompatible on some domains as some domains will convert differently in the current version.

The security risks I'm aware of homograph attacks: https://en.wikipedia.org/wiki/IDN_homograph_attack

Given that scrapy is a library for automated processing of websites, it's not particularly vulnerable to attacks like that, and strictly validating URLs literally makes it impossible to process those website in the current state. 

Are there other attacks we should be aware of? That could affect scrapy or a similar tool specifically?

**Comment by kjd** [comment]
It is hard to give a blanket assessment of risk. As a library, in isolation, it probably poses little risk. However I assume the library is not typically used in isolation but common usage would entail 3rd party applications wrapping it with some kind of user interface (web, CLI, etc.) where the domains are presented, which is where the security risks can occur. If a higher-level library effectively masks these security issues by suppressing the security warnings, it could amplify the risk to the consumer of the library who may just naively display the domain without further thought. 

I don't know enough about the usage to know whether it is a good idea or fits with the library's model, but some way of a user of the library explicitly passing a parameter requesting "unsafe" conversions may be something to consider. It is basically what I've been thinking for `idna` to address these kinds of requests — it would at least ensure that those utilizing the library were making an explicit choice to do unsafe conversions before honoring them. Another would be to return some kind of qualifying attribute that the result is an unsafe conversion.

**Comment by wRAR** [comment]
> I believe this is now the most relevant issue: twisted/twisted#10078

This matches my current experience (`ValueError: invalid hostname: xn--i-7iq.ws`).
