### ISSUE TITLE
scrapy hangs requesting http://www.hpe.com/

### ISSUE THREAD

**Issue by blushingpenguin** [scrapy/scrapy#4423]
### Description
Scrapy hangs requesting a couple of sites, namely:

http://www.hpe.com/
and
http://viz.ai/

These work fine in a browser.  Eventually the connection times out (after 3 minutes, which I assume is a default)

### Steps to Reproduce

scrapy shell http://www.hpe.com/
scrapy shell http://viz.ai/

**Expected behavior:** [What you expect to happen]

The pages should load as in a browser

**Actual behavior:** [What actually happens]

The requests time out after 3 minutes

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time

### Versions

Please paste here the output of executing `scrapy version --verbose` in the command line.
Scrapy       : 2.0.0
lxml         : 4.5.0.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.5.2
w3lib        : 1.21.0
Twisted      : 17.9.0
Python       : 3.6.9 (default, Nov  7 2019, 10:44:02) - [GCC 8.3.0]
pyOpenSSL    : 17.5.0 (OpenSSL 1.1.1  11 Sep 2018)
cryptography : 2.1.4
Platform     : Linux-4.15.0-1057-aws-x86_64-with-Ubuntu-18.04-bionic

**Comment by wRAR** [comment]
http://viz.ai/ works (at least with 1.7.3), http://www.hpe.com/ indeed doesn't. But http://www.hpe.com/ doesn't work with curl either. Setting a fake user agent helps both with curl and Scrapy so this is just anti-bot protection.

**Comment by blushingpenguin** [comment]
Right, I hadn't checked that carefully enough.  I have re-checked www.hpe.com and I agree with your findings.  Sorry about the poor bug report.

For https://viz.ai (vs http://viz.ai as originally reported) I get an ssl error:

```
ubuntu:~$ scrapy shell https://viz.ai
2020-03-13 15:35:23 [scrapy.utils.log] INFO: Scrapy 2.0.0 started (bot: scrapybot)
2020-03-13 15:35:23 [scrapy.utils.log] INFO: Versions: lxml 4.5.0.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.5.2, w3lib 1.21.0, Twisted 17.9.0, Python 3.6.9 (default, Nov  7 2019, 10:44:02) - [GCC 8.3.0], pyOpenSSL 17.5.0 (OpenSSL 1.1.1  11 Sep 2018), cryptography 2.1.4, Platform Linux-4.15.0-1057-aws-x86_64-with-Ubuntu-18.04-bionic
2020-03-13 15:35:23 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.epollreactor.EPollReactor
2020-03-13 15:35:23 [scrapy.crawler] INFO: Overridden settings:
{'DUPEFILTER_CLASS': 'scrapy.dupefilters.BaseDupeFilter',
 'LOGSTATS_INTERVAL': 0}
2020-03-13 15:35:23 [scrapy.extensions.telnet] INFO: Telnet Password: 15c186c07af87258
2020-03-13 15:35:23 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage']
2020-03-13 15:35:23 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2020-03-13 15:35:23 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2020-03-13 15:35:23 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2020-03-13 15:35:23 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-03-13 15:35:23 [scrapy.core.engine] INFO: Spider opened
2020-03-13 15:35:23 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://viz.ai> (failed 1 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]
2020-03-13 15:35:24 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://viz.ai> (failed 2 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]
2020-03-13 15:35:24 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET https://viz.ai> (failed 3 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python3.6/dist-packages/scrapy/cmdline.py", line 145, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/cmdline.py", line 99, in _run_print_help
    func(*a, **kw)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/cmdline.py", line 153, in _run_command
    cmd.run(args, opts)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/commands/shell.py", line 74, in run
    shell.start(url=url, redirect=not opts.no_redirect)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/shell.py", line 45, in start
    self.fetch(url, spider, redirect=redirect)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/shell.py", line 113, in fetch
    reactor, self._schedule, request, spider)
  File "/usr/lib/python3/dist-packages/twisted/internet/threads.py", line 122, in blockingCallFromThread
    result.raiseException()
  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 385, in raiseException
    raise self.value.with_traceback(self.tb)
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]
```
This does work in curl:
```
ubuntu:~$ curl -vvv https://viz.ai
* Rebuilt URL to: https://viz.ai/
*   Trying 146.66.112.199...
* TCP_NODELAY set
* Connected to viz.ai (146.66.112.199) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: businessCategory=Private Organization; serialNumber=6070900; jurisdictionC=US; jurisdictionST=Delaware; C=US; ST=CA; L=SAN FRANCISCO; street=555 DE HARO SUITE 400; O=Viz.ai, Inc.; CN=viz.ai
*  start date: Feb  6 16:46:07 2019 GMT
*  expire date: Feb  6 16:46:07 2021 GMT
*  subjectAltName: host "viz.ai" matched cert's "viz.ai"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign Extended Validation CA - SHA256 - G3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* Using Stream ID: 1 (easy handle 0x5570cec3d580)
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
> GET / HTTP/2
> Host: viz.ai
> User-Agent: curl/7.58.0
> Accept: */*
>
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
< HTTP/2 301
< server: nginx
< date: Fri, 13 Mar 2020 15:37:06 GMT
< content-type: text/html; charset=UTF-8
< expires: Thu, 19 Nov 1981 08:52:00 GMT
< cache-control: no-store, no-cache, must-revalidate
< pragma: no-cache
< x-cache-enabled: True
< x-ua-compatible: IE=edge
< x-redirect-by: WordPress
< set-cookie: PHPSESSID=a0b18e81ed5265587257a43fa405f14f; path=/
< set-cookie: wpSGCacheBypass=0; expires=Fri, 13-Mar-2020 14:37:06 GMT; Max-Age=0; path=/
< location: https://www.viz.ai/
< x-proxy-cache: MISS
< alt-svc: quic=":443"; ma=86400; v="43,39"
<
* Connection #0 to host viz.ai left intact
```

**Comment by wRAR** [comment]
Pass `-s DOWNLOADER_CLIENT_TLS_VERBOSE_LOGGING=1`. I suspect your Python libs don't support TLSv1.3 and cannot negotiate an older version for some reason. It works here.

**Comment by wRAR** [comment]
Though I'm not sure if that logging works on connections that get an error.

**Comment by blushingpenguin** [comment]
That didn't seem to elicit any more information unfortunately:
```
ubuntu:~$ scrapy shell -s DOWNLOADER_CLIENT_TLS_VERBOSE_LOGGING=1 https://viz.ai
2020-03-13 16:37:25 [scrapy.utils.log] INFO: Scrapy 2.0.0 started (bot: scrapybot)
2020-03-13 16:37:25 [scrapy.utils.log] INFO: Versions: lxml 4.5.0.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.5.2, w3lib 1.21.0, Twisted 17.9.0, Python 3.6.9 (default, Nov  7 2019, 10:44:02) - [GCC 8.3.0], pyOpenSSL 17.5.0 (OpenSSL 1.1.1  11 Sep 2018), cryptography 2.1.4, Platform Linux-4.15.0-1057-aws-x86_64-with-Ubuntu-18.04-bionic
2020-03-13 16:37:25 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.epollreactor.EPollReactor
2020-03-13 16:37:25 [scrapy.crawler] INFO: Overridden settings:
{'DOWNLOADER_CLIENT_TLS_VERBOSE_LOGGING': '1',
 'DUPEFILTER_CLASS': 'scrapy.dupefilters.BaseDupeFilter',
 'LOGSTATS_INTERVAL': 0}
2020-03-13 16:37:25 [scrapy.extensions.telnet] INFO: Telnet Password: a742be29a2b78ee8
2020-03-13 16:37:25 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage']
2020-03-13 16:37:25 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2020-03-13 16:37:25 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2020-03-13 16:37:25 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2020-03-13 16:37:25 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-03-13 16:37:25 [scrapy.core.engine] INFO: Spider opened
2020-03-13 16:37:25 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://viz.ai> (failed 1 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]
2020-03-13 16:37:25 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://viz.ai> (failed 2 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]
2020-03-13 16:37:25 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET https://viz.ai> (failed 3 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python3.6/dist-packages/scrapy/cmdline.py", line 145, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/cmdline.py", line 99, in _run_print_help
    func(*a, **kw)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/cmdline.py", line 153, in _run_command
    cmd.run(args, opts)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/commands/shell.py", line 74, in run
    shell.start(url=url, redirect=not opts.no_redirect)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/shell.py", line 45, in start
    self.fetch(url, spider, redirect=redirect)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/shell.py", line 113, in fetch
    reactor, self._schedule, request, spider)
  File "/usr/lib/python3/dist-packages/twisted/internet/threads.py", line 122, in blockingCallFromThread
    result.raiseException()
  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 385, in raiseException
    raise self.value.with_traceback(self.tb)
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]
ubuntu@ip-172-31-46-15:~$ scrapy shell -s DOWNLOADER_CLIENT_TLS_VERBOSE_LOGGING=1 https://viz.ai
2020-03-13 16:37:41 [scrapy.utils.log] INFO: Scrapy 2.0.0 started (bot: scrapybot)
2020-03-13 16:37:41 [scrapy.utils.log] INFO: Versions: lxml 4.5.0.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.5.2, w3lib 1.21.0, Twisted 17.9.0, Python 3.6.9 (default, Nov  7 2019, 10:44:02) - [GCC 8.3.0], pyOpenSSL 17.5.0 (OpenSSL 1.1.1  11 Sep 2018), cryptography 2.1.4, Platform Linux-4.15.0-1057-aws-x86_64-with-Ubuntu-18.04-bionic
2020-03-13 16:37:41 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.epollreactor.EPollReactor
2020-03-13 16:37:41 [scrapy.crawler] INFO: Overridden settings:
{'DOWNLOADER_CLIENT_TLS_VERBOSE_LOGGING': '1',
 'DUPEFILTER_CLASS': 'scrapy.dupefilters.BaseDupeFilter',
 'LOGSTATS_INTERVAL': 0}
2020-03-13 16:37:41 [scrapy.extensions.telnet] INFO: Telnet Password: f67d5a86846f8eeb
2020-03-13 16:37:41 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage']
2020-03-13 16:37:41 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2020-03-13 16:37:41 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2020-03-13 16:37:41 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2020-03-13 16:37:41 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-03-13 16:37:41 [scrapy.core.engine] INFO: Spider opened
2020-03-13 16:37:41 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://viz.ai> (failed 1 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]
2020-03-13 16:37:41 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://viz.ai> (failed 2 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]
2020-03-13 16:37:41 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET https://viz.ai> (failed 3 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python3.6/dist-packages/scrapy/cmdline.py", line 145, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/cmdline.py", line 99, in _run_print_help
    func(*a, **kw)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/cmdline.py", line 153, in _run_command
    cmd.run(args, opts)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/commands/shell.py", line 74, in run
    shell.start(url=url, redirect=not opts.no_redirect)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/shell.py", line 45, in start
    self.fetch(url, spider, redirect=redirect)
  File "/usr/local/lib/python3.6/dist-packages/scrapy/shell.py", line 113, in fetch
    reactor, self._schedule, request, spider)
  File "/usr/lib/python3/dist-packages/twisted/internet/threads.py", line 122, in blockingCallFromThread
    result.raiseException()
  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 385, in raiseException
    raise self.value.with_traceback(self.tb)
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]
```

**Comment by wRAR** [comment]
Then I'm afraid you can only use Wireshark to see what protocols/ciphers does Scrapy propose. Or try with upgraded pyOpenSSL/cryptography/Twisted modules.
