### ISSUE TITLE
Spider processing error.

### ISSUE THREAD

**Issue by H-Petes** [scrapy/scrapy#4476]
(scraping_tutorial) C:\Users\Pete\PycharmProjects\scraping_tutorial\quotetutorial>scrapy crawl quotes
2020-04-06 22:10:42 [scrapy.utils.log] INFO: Scrapy 1.6.0 started (bot: quotetutorial)
2020-04-06 22:10:42 [scrapy.utils.log] INFO: Versions: lxml 4.5.0.0, libxml2 2.9.9, cssselect 1.1.0, parsel 1.5.2, w3lib 1.21.0, Twisted 19.10.0, Python 3.7.6 (default, Jan  8 2020, 20:2
3:39) [MSC v.1916 64 bit (AMD64)], pyOpenSSL 19.1.0 (OpenSSL 1.1.1f  31 Mar 2020), cryptography 2.8, Platform Windows-10-10.0.17763-SP0
2020-04-06 22:10:42 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'quotetutorial', 'NEWSPIDER_MODULE': 'quotetutorial.spiders', 'SPIDER_MODULES': ['quotetutorial.spiders']}
2020-04-06 22:10:42 [scrapy.extensions.telnet] INFO: Telnet Password: 1ace5e11f19c6f62
2020-04-06 22:10:42 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2020-04-06 22:10:43 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2020-04-06 22:10:43 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2020-04-06 22:10:44 [scrapy.middleware] INFO: Enabled item pipelines:
['quotetutorial.pipelines.QuotetutorialPipeline']
2020-04-06 22:10:44 [scrapy.core.engine] INFO: Spider opened
2020-04-06 22:10:44 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2020-04-06 22:10:44 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-04-06 22:10:45 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://quotes.toscrape.com/> (referer: None)
2020-04-06 22:10:46 [scrapy.core.scraper] ERROR: Error processing {'author': [],
 'tag': [],
 'title': ['“A day without sunshine is like, you know, night.”']}
Traceback (most recent call last):
  File "C:\Users\Pete\Anaconda3\envs\scraping_tutorial\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "C:\Users\Pete\PycharmProjects\scraping_tutorial\quotetutorial\quotetutorial\pipelines.py", line 38, in process_item
    self.store_db(item)
  File "C:\Users\Pete\PycharmProjects\scraping_tutorial\quotetutorial\quotetutorial\pipelines.py", line 46, in store_db
    item['author'][0],
IndexError: list index out of range
2020-04-06 22:10:46 [scrapy.core.engine] INFO: Closing spider (finished)
2020-04-06 22:10:46 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 218,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 2342,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2020, 4, 6, 19, 10, 46, 25869),
 'log_count/DEBUG': 1,
 'log_count/ERROR': 1,
 'log_count/INFO': 9,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2020, 4, 6, 19, 10, 44, 695033)}
2020-04-06 22:10:46 [scrapy.core.engine] INFO: Spider closed (finished)

**Comment by wRAR** [comment]
This is a tracker for issues in Scrapy itself, not in your code. Please use https://stackoverflow.com/ or other suitable resources to get help with your code.
