### ISSUE TITLE
Scrapy throws timeout with http2 site

### ISSUE THREAD

**Issue by marizaga** [scrapy/scrapy#4531]
**DESCRIPTION**

A Timeout exception raises when crawl https://www.adidas.pe, I suspect the site only supports http2 and scrapy does not, curl can extract the information but if I force it to use http1.1 it also throws timeout.

**settings.py:**

```
LOG_STDOUT = True
MEMDEBUG_ENABLED = True
DOWNLOAD_TIMEOUT = 25
RETRY_ENABLED = False
ROBOTSTXT_OBEY = False
DOWNLOADER_CLIENT_TLS_VERBOSE_LOGGING = True
DEFAULT_REQUEST_HEADERS = {
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Language': 'es-US,es-419;',
        'accept-encoding': 'gzip, deflate'
}
USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36'
```

**Installed packages and versions:**
```
scrapy version -v

Scrapy       : 2.0.1
lxml         : 4.5.0.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.5.2
w3lib        : 1.21.0
Twisted      : 20.3.0
Python       : 3.7.4 (default, Apr  1 2020, 23:03:35) - [GCC 6.3.0 20170516]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1g  21 Apr 2020)
cryptography : 2.9.2
Platform     : Linux-4.9.0-11-amd64-x86_64-with-debian-9.12
```

****
**Testing with Scrapy and CURL:**
```
scrapy shell https://www.adidas.pe

2020-05-01 16:51:32 [scrapy.utils.log] INFO: Scrapy 2.0.1 started (bot: tests)
2020-05-01 16:51:32 [scrapy.utils.log] INFO: Versions: lxml 4.5.0.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.5.2, w3lib 1.21.0, Twisted 20.3.0, Python 3.7.4 (default, Apr  1 2020, 23:03:35) - [GCC 6.3.0 20170516], pyOpenSSL 19.1.0 (OpenSSL 1.1.1g  21 Apr 2020), cryptography 2.9.2, Platform Linux-4.9.0-11-amd64-x86_64-with-debian-9.12
2020-05-01 16:51:32 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.epollreactor.EPollReactor
2020-05-01 16:51:32 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'tests',
 'DOWNLOADER_CLIENT_TLS_VERBOSE_LOGGING': True,
 'DOWNLOAD_TIMEOUT': 25,
 'DUPEFILTER_CLASS': 'scrapy.dupefilters.BaseDupeFilter',
 'LOGSTATS_INTERVAL': 0,
 'LOG_STDOUT': True,
 'MEMDEBUG_ENABLED': True,
 'NEWSPIDER_MODULE': 'tests.spiders',
 'RETRY_ENABLED': False,
 'SPIDER_MODULES': ['tests.spiders'],
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36'}
2020-05-01 16:51:32 [scrapy.extensions.telnet] INFO: Telnet Password: ef6cffde752fb19f
2020-05-01 16:51:32 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.memdebug.MemoryDebugger']
2020-05-01 16:51:32 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2020-05-01 16:51:32 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2020-05-01 16:51:32 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2020-05-01 16:51:32 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6024
2020-05-01 16:51:32 [scrapy.core.engine] INFO: Spider opened
2020-05-01 16:51:32 [scrapy.core.downloader.tls] DEBUG: SSL connection to www.adidas.pe using protocol TLSv1.3, cipher TLS_AES_256_GCM_SHA384
2020-05-01 16:51:32 [scrapy.core.downloader.tls] DEBUG: SSL connection certificate: issuer "/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=GeoTrust RSA CA 2018", subject "/C=DE/ST=Bavaria/L=Herzogenaurach/O=adidas AG/OU=Global IT/CN=www.global.adidas.com"
2020-05-01 16:51:32 [scrapy.core.downloader.tls] DEBUG: SSL temp key: X25519, 253 bits
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 10, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python3.7/site-packages/scrapy/cmdline.py", line 145, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/usr/local/lib/python3.7/site-packages/scrapy/cmdline.py", line 99, in _run_print_help
    func(*a, **kw)
  File "/usr/local/lib/python3.7/site-packages/scrapy/cmdline.py", line 153, in _run_command
    cmd.run(args, opts)
  File "/usr/local/lib/python3.7/site-packages/scrapy/commands/shell.py", line 74, in run
    shell.start(url=url, redirect=not opts.no_redirect)
  File "/usr/local/lib/python3.7/site-packages/scrapy/shell.py", line 45, in start
    self.fetch(url, spider, redirect=redirect)
  File "/usr/local/lib/python3.7/site-packages/scrapy/shell.py", line 113, in fetch
    reactor, self._schedule, request, spider)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/threads.py", line 122, in blockingCallFromThread
    result.raiseException()
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 488, in raiseException
    raise self.value.with_traceback(self.tb)
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting https://www.adidas.pe took longer than 25.0 seconds..
```

**Failed test with CURL:**
```
curl https://www.adidas.pe --http1.1 --max-time 25 -v -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" -H "accept-language: es-US,es-419;" -H "accept-encoding: gzip, deflate" -o adidas.html

* Rebuilt URL to: https://www.adidas.pe/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0*   Trying 104.93.58.229...
* TCP_NODELAY set
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0* Connected to www.adidas.pe (104.93.58.229) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [108 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [5537 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=DE; ST=Bavaria; L=Herzogenaurach; O=adidas AG; OU=Global IT; CN=www.global.adidas.com
*  start date: Jan 30 00:00:00 2020 GMT
*  expire date: Dec 29 12:00:00 2020 GMT
*  subjectAltName: host "www.adidas.pe" matched cert's "www.adidas.pe"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=GeoTrust RSA CA 2018
*  SSL certificate verify ok.
} [5 bytes data]
> GET / HTTP/1.1
> Host: www.adidas.pe
> Accept: */*
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
> accept-language: es-US,es-419;
> accept-encoding: gzip, deflate
>
  0     0    0     0    0     0      0      0 --:--:--  0:00:24 --:--:--     0* Operation timed out after 25000 milliseconds with 0 bytes received
* Curl_http_done: called premature == 1
* stopped the pause stream!
  0     0    0     0    0     0      0      0 --:--:--  0:00:25 --:--:--     0
* Closing connection 0
} [5 bytes data]
* TLSv1.2 (OUT), TLS alert, Client hello (1):
} [2 bytes data]
curl: (28) Operation timed out after 25000 milliseconds with 0 bytes received
```

**Successful test with CURL:**

```
curl https://www.adidas.pe --http2 --max-time 25 -v -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" -H "accept-language: es-US,es-419;" -H "accept-encoding: gzip, deflate" -o adidas.html

* Rebuilt URL to: https://www.adidas.pe/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 104.93.58.229...
* TCP_NODELAY set
* Connected to www.adidas.pe (104.93.58.229) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [102 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [5537 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=DE; ST=Bavaria; L=Herzogenaurach; O=adidas AG; OU=Global IT; CN=www.global.adidas.com
*  start date: Jan 30 00:00:00 2020 GMT
*  expire date: Dec 29 12:00:00 2020 GMT
*  subjectAltName: host "www.adidas.pe" matched cert's "www.adidas.pe"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=GeoTrust RSA CA 2018
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x564dee91eea0)
} [5 bytes data]
> GET / HTTP/1.1
> Host: www.adidas.pe
> Accept: */*
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
> accept-language: es-US,es-419;
> accept-encoding: gzip, deflate
>
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
} [5 bytes data]
< HTTP/2 200
< content-type: text/html; charset=utf-8
< vary: Accept-Encoding
< server-timing: intid;desc=e9079c33383fd210
< x-frame-options: SAMEORIGIN
< x-content-type-options: nosniff
< x-request-id: dd261749a9a43e1b1c4bbf4cda012016
< content-encoding: gzip
< x-akamai-transformed: 9 166248 0 pmb=mTOE,5
< expires: Fri, 01 May 2020 22:31:51 GMT
< cache-control: max-age=0, no-cache, no-store
< pragma: no-cache
< date: Fri, 01 May 2020 22:31:51 GMT
< set-cookie: geo_ip=52.117.61.178
< set-cookie: geo_country=US; path=/
< set-cookie: onesite_country=PE; path=/
< set-cookie: ak_bmsc=F93ABD35DA357BAEF36AA6A747603C0C60074BAE3467000057A3AC5E3F70A018~plPyeQB26uSsj3SNwXXEGgmqgEcFYs7DjwroQ/TdOTJxdXOFbVpxWIwSAe+1fEMXwmoWqosVxPmCFSSHsO/AGq9SuVsUmZy6tLjMWojl1QCPPr7L6RoumvRt4Iizuk5jvPCo15E/WCIbSLf3ue5Cglc5df0DOhriP+/DCZ1d92o2Sw4FaX4LtQ44Vf50ChN+sGv4+8/x0unciIVQaJ/tVNDiJYqOzfYGu5ZNiSctY6MnMSwgOWAHExIoEGv8+23I8OiLka8CZn2T+HRPOvKFgsO+U7AwFhmVxJIdgrW0Oc0LsrMj6X0aIuONH/NQ5tOQE71hw8mrPJyUcPGTJ+2Qzc4g==; expires=Sat, 02 May 2020 00:31:51 GMT; max-age=7200; path=/; domain=.adidas.pe; HttpOnly
< set-cookie: akacd_generic_prod_grayling_adidas=3765825110~rv=4~id=dacf829aefc7506e875ec9bd0f144718; path=/;; Secure; SameSite=None
< remaining_edge_ttl: -655
< access-control-max-age: 86400
< access-control-allow-credentials: true
< access-control-allow-headers: *
< access-control-allow-methods: GET,POST
< strict-transport-security: max-age=31536000 ; includeSubDomains ; preload
< set-cookie: bm_mi=7A66B23220463183ED41658D57D2EA48~mbdQy0MZg88Xo85GAqKOQUJMAhHyJL1bhk8hgmPY82TQAKLe/qALZlxra68PshipWlgaurtbHUPzRoq+vD4/c0ShXR9BT4DSF6BdgxNP7bjNdICgt0InIff5njdti9pTTNmynslfMUbUYjSx72VkUtFr1U3zmcaLzzznsgQs3E9CN+hhUoQk9Im/vbs0L5vjxUX+wRBFrdVr6gqwHLiFqQ==; Domain=.adidas.pe; Path=/; Max-Age=0; HttpOnly
< set-cookie: bm_sz=5F01E98C8428A0DC76CF013A40BD62D9~YAAQrksHYOJCsL5xAQAAqgxe0gexc5CKe71Hfni57eviwp0936qKrsLHSlUbuWhg0b1M7obQRY6N7CYCwX0dlvnfTEPqBMT71ojdLJDtELLpwWNnS8Ey1TW3mZds3Vzont0s/bP7AVAvPCq4bw95/oOir4ycl637c5VYpFqKMMyMPJDaKSkiHdUfcgbPcQ==; Domain=.adidas.pe; Path=/; Expires=Sat, 02 May 2020 02:31:51 GMT; Max-Age=14400; HttpOnly
< set-cookie: _abck=E8982021FDD0A1E2FCF640226FF0AB93~-1~YAAQrksHYONCsL5xAQAAqgxe0gOjHMa9sgBUvVhBCAVEwZkL+YV4MXImLZ2JKWVNxRxnQoBjlFpM0f6RpBLkhXG8Q7Azq9gfav7vL7jFHlo3TiVA6wEnJmLf5fPtn6naBE5BVvtZfeZ3Id/K1qhUOOfrbz/x+//ZTxULMDoKXdCKNghmLSaVlktvI3Q7hde6gRq3pWMi9BMkI/elsORrNm8b4EktKmlpLv8a82e/8ahFV5ZX36wy6t2oPoV5gj0VU6GP0uk8voIzN/jKheLHlxMYUrQQEHaYXIFbHRSABb15/RazJJmPcaA=~-1~-1~-1; Domain=.adidas.pe; Path=/; Expires=Fri, 08 May 2020 22:31:51 GMT; Max-Age=604800; Secure
<
{ [167 bytes data]
* Curl_http_done: called premature == 0
100  156k    0  156k    0     0   453k      0 --:--:-- --:--:-- --:--:--  454k
* Connection #0 to host www.adidas.pe left intact
```

**Comment by elacuesta** [comment]
The lack of HTTP/2 support is a known current limitation of Scrapy. There is a Google Summer of Code project planned (see #1854), if everything goes well we should be getting support in the near future.
