### ISSUE TITLE
Using ":" (colon) in the url raise a error

### ISSUE THREAD

**Issue by crawazaky** [scrapy/scrapy#4601]
### Description

Trying to request google.fr with a search request of this form:

https://www.google.fr/search?q=site:website+keyword

Raise a error:

`Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/vagrant/scrapy/tutorial1/tutorial1/spiders/quotes_spider.py", line 124, in parse_google_to_fb
    request = scrapy.Request(doc['lien_facebook'], meta={'dont_proxy': True}, callback=self.parse_facebook)
  File "/home/vagrant/.local/lib/python2.7/site-packages/scrapy/http/request/__init__.py", line 26, in __init__
    self._set_url(url)
  File "/home/vagrant/.local/lib/python2.7/site-packages/scrapy/http/request/__init__.py", line 64, in _set_url
    raise TypeError('Request url must be str or unicode, got %s:' % type(url).__name__)
`

It seems to come from the ":" (colon) following the "site". Because taking it off fix the issue.

### Steps to Reproduce

1. Request a google search in the following form: https://www.google.fr/search?q=site:website+keyword

**Expected behavior:** [What you expect to happen]

I expect the request to work just the same behavior than without the "site:" at the beginning of my google's search

**Actual behavior:** [What actually happens]

A error appear:

`Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/vagrant/scrapy/tutorial1/tutorial1/spiders/quotes_spider.py", line 124, in parse_google_to_fb
    request = scrapy.Request(doc['lien_facebook'], meta={'dont_proxy': True}, callback=self.parse_facebook)
  File "/home/vagrant/.local/lib/python2.7/site-packages/scrapy/http/request/__init__.py", line 26, in __init__
    self._set_url(url)
  File "/home/vagrant/.local/lib/python2.7/site-packages/scrapy/http/request/__init__.py", line 64, in _set_url
    raise TypeError('Request url must be str or unicode, got %s:' % type(url).__name__)
`

**Reproduces how often:** [What percentage of the time does it reproduce?]
100 % with this kind of url
### Versions

Scrapy       : 1.8.0
lxml         : 4.5.1.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 20.3.0
Python       : 2.7.17 (default, Apr 15 2020, 17:20:14) - [GCC 7.5.0]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1g  21 Apr 2020)
cryptography : 2.9.2
Platform     : Linux-4.15.0-96-generic-x86_64-with-Ubuntu-18.04-bionic

**Comment by GeorgeA92** [comment]
@crawazaky 
On my older environment (based on python 3.x not 2.7.x). I don't have this issue:
```
2020-05-28 20:33:20 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-05-28 20:33:23 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.google.fr/search?q=site:website+keyword> (referer: None)
```

**Versions**

Scrapy 1.8.0 
lxml 4.2.5.0
libxml2 2.9.9
cssselect 1.1.0
parsel 1.5.1
w3lib 1.20.0
Twisted 19.7.0
Python 3.7.1 (default, Nov 24 2018, 22:14:32) [MSC v.1912 64 bit (AMD64)]
pyOpenSSL 19.0.0 (OpenSSL 1.1.1e  17 Mar 2020)
cryptography 2.7
Platform Windows-10-10.0.18362-SP0

**Comment by crawazaky** [comment]
@GeorgeA92 Indeed, the error is gone with python3. Thank you.
