### ISSUE TITLE
Exception leak to start_requests (asyncio-startrequests-asyncgen branch)

### ISSUE THREAD

**Issue by k3kc** [scrapy/scrapy#4648]
### Description

Despite being handled, exception is further leaked upstream to start_requests. After that some strange exception loop begins.

### Steps to Reproduce

1. in start_requests: 
async for item in connect_and_read_websocket():
    ...
2. async def connect_and_read_websocket():
    while True:
        try:
            logger.info("connecting to: %s", WS_URL)
            w = await tornado.websocket.websocket_connect(WS_URL, connect_timeout=5, ping_interval=25)
            logger.info("connected")
        except Exception as ex:
            logger.error("can't connect to websocket: %s", ex)
            await asyncio.sleep(5)
            continue

        while True:
            payload = await w.read_message()
            ...

**Expected behavior:** Exception is caught inside try block

**Actual behavior:** Exception is leaked upstream

**Reproduces how often:** c.5% of the time block is run

### Versions

Scrapy       : 2.1.0
lxml         : 4.5.1.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 20.3.0
Python       : 3.7.7 (default, May 25 2020, 16:33:51) - [GCC 10.1.0]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1g  21 Apr 2020)
cryptography : 2.9.2
Platform     : Linux-5.6.14-arch1-1-x86_64-with-arch

### Additional context

Exception is rare - happens once a week in production, with several passes of the block per day.
Trace: https://pastebin.com/stANAB3y

**Comment by elacuesta** [comment]
I have mixed feeling about this: on the one hand, we are very grateful for the early adoption, this will probably help us improve the feature. On the other hand, I feel like it's a little bit risky to be using code from an unmerged PR in production.
I can't say much about the underlying problem, @wRAR will know more than I do. In the meantime, I can propose a workaround: have you considered starting the crawl with a dummy request and awaiting in `parse`? Something like:

```python
from scrapy import Spider, Request

class AsyncIOSpider(Spider):
    name = "asyncio"
    start_urls = ["data:,"]

    async def parse(self, response):
        try:
            await self.divide_by_zero()
        except ZeroDivisionError:
            self.logger.info("Can't divide by 0")
        yield Request("https://example.org")

    async def divide_by_zero(self):
        1 / 0
```

The exception is indeed caught this way:
```
2020-06-25 19:27:54 [scrapy.core.engine] INFO: Spider opened
2020-06-25 19:27:54 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2020-06-25 19:27:54 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6024
2020-06-25 19:27:54 [scrapy.core.engine] DEBUG: Crawled (200) <GET data:,> (referer: None)
2020-06-25 19:27:54 [asyncio] INFO: Can't divide by 0
2020-06-25 19:27:54 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://example.org> (referer: None)
2020-06-25 19:27:55 [asyncio] INFO: Can't divide by 0
2020-06-25 19:27:55 [scrapy.dupefilters] DEBUG: Filtered duplicate request: <GET https://example.org> - no more duplicates will be shown (see DUPEFILTER_DEBUG to show all duplicates)
2020-06-25 19:27:55 [scrapy.core.engine] INFO: Closing spider (finished)
```

**Comment by k3kc** [comment]
That's ok, I understand the risks of unmerged pulls - was really keen on using it to make the logic beautiful. Thanks for your suggestion - I understand the idea of pushing everything down to parse, but it somewhat defeats the purpose of being elegant :)
Moreover, this solution is not guaranteed to work - I could not reproduce the error with simple division by zero in start_requests either, it works as intented. Maybe it is this weird mix with tornado that causes issues.
Probably the easiest solution would be to try to catch the exception in start_requests itself, which I will try next time I face another crash. Just wanted to flag in advance the unintended behaviour.

**Comment by wRAR** [comment]
Does this happen every time "can't connect to websocket" error happens, or only rarely?

The traceback is interesting, as the `w = await tornado.websocket.websocket_connect` line is two frames below the `await asyncio.sleep(5)` line even though in the code they are on one level and in a different order.

**Comment by k3kc** [comment]
Now when you asked explicitly, I managed to reproduce it, so the answer is definitely not rarely. I just shutdown network interface, and here you are, familiar loop:
```
2020-06-26 17:24:30 [wsock] ERROR: can't connect to websocket: [Errno 101] Network is unreachable
2020-06-26 17:24:31 [scrapy] ERROR: Error while obtaining start requests
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/site-packages/tornado/tcpclient.py", line 143, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/site-packages/scrapy/core/engine.py", line 135, in _next_request
    request = yield deferred_from_coro(slot.start_requests.__anext__())
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/site-packages/twisted/internet/defer.py", line 824, in adapt
    extracted = result.result()
  File "/home/user/project-tracker/project/spiders/spiders.py", line 43, in start_requests
    async for article_header in connect_and_read_websocket():
  File "/home/user/project-tracker/project/websocket.py", line 53, in connect_and_read_websocket
    await asyncio.sleep(5)
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/asyncio/tasks.py", line 595, in sleep
    return await future
  File "/home/user/project-tracker/project/websocket.py", line 49, in connect_and_read_websocket
    w = await tornado.websocket.websocket_connect(WS_URL, connect_timeout=5, ping_interval=25)
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/site-packages/tornado/iostream.py", line 1226, in connect
    self.socket.connect(address)
OSError: [Errno 101] Network is unreachable
2020-06-26 17:24:31 [scrapy] INFO: Closing spider (finished)
2020-06-26 17:24:31 [telegram.vendor.ptb_urllib3.urllib3.connectionpool] WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f085d4ff4d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))': /bot1244233506:AAH8LPHUoVD39ChecR1wN7yo7JAoOQ1L7I8/sendMessage
2020-06-26 17:24:31 [telegram.vendor.ptb_urllib3.urllib3.connectionpool] WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f085fca1190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))': /bot1244233506:AAH8LPHUoVD39ChecR1wN7yo7JAoOQ1L7I8/sendMessage
2020-06-26 17:24:31 [telegram.vendor.ptb_urllib3.urllib3.connectionpool] WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f085fca1d10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))': /bot1244233506:AAH8LPHUoVD39ChecR1wN7yo7JAoOQ1L7I8/sendMessage
2020-06-26 17:24:31 [telegram] ERROR: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot1244233506:AAH8LPHUoVD39ChecR1wN7yo7JAoOQ1L7I8/sendMessage (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f085d97f690>: Failed to establish a new connection: [Errno 101] Network is unreachable')))
2020-06-26 17:25:09 [scrapy] INFO: Dumping Scrapy stats:
...
2020-06-26 17:25:09 [scrapy] INFO: Spider closed (finished)
2020-06-26 17:25:09 [scrapy] ERROR: Error while obtaining start requests
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/site-packages/tornado/tcpclient.py", line 143, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/site-packages/scrapy/core/engine.py", line 135, in _next_request
    request = yield deferred_from_coro(slot.start_requests.__anext__())
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/site-packages/twisted/internet/defer.py", line 824, in adapt
    extracted = result.result()
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/site-packages/scrapy/core/engine.py", line 135, in _next_request
    request = yield deferred_from_coro(slot.start_requests.__anext__())
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/site-packages/twisted/internet/defer.py", line 824, in adapt
    extracted = result.result()
  File "/home/user/project-tracker/project/spiders/spiders.py", line 43, in start_requests
    async for article_header in connect_and_read_websocket():
  File "/home/user/project-tracker/project/websocket.py", line 53, in connect_and_read_websocket
    await asyncio.sleep(5)
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/asyncio/tasks.py", line 595, in sleep
    return await future
  File "/home/user/project-tracker/project/websocket.py", line 49, in connect_and_read_websocket
    w = await tornado.websocket.websocket_connect(WS_URL, connect_timeout=5, ping_interval=25)
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/site-packages/tornado/iostream.py", line 1226, in connect
    self.socket.connect(address)
OSError: [Errno 101] Network is unreachable
2020-06-26 17:25:09 [scrapy] ERROR: Error while obtaining start requests
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/site-packages/tornado/tcpclient.py", line 143, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/site-packages/scrapy/core/engine.py", line 135, in _next_request
    request = yield deferred_from_coro(slot.start_requests.__anext__())
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/site-packages/twisted/internet/defer.py", line 824, in adapt
    extracted = result.result()
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/site-packages/scrapy/core/engine.py", line 135, in _next_request
    request = yield deferred_from_coro(slot.start_requests.__anext__())
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/site-packages/twisted/internet/defer.py", line 824, in adapt
    extracted = result.result()
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/site-packages/scrapy/core/engine.py", line 135, in _next_request
    request = yield deferred_from_coro(slot.start_requests.__anext__())
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/site-packages/twisted/internet/defer.py", line 824, in adapt
    extracted = result.result()
  File "/home/user/project-tracker/project/spiders/spiders.py", line 43, in start_requests
    async for article_header in connect_and_read_websocket():
  File "/home/user/project-tracker/project/websocket.py", line 53, in connect_and_read_websocket
    await asyncio.sleep(5)
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/asyncio/tasks.py", line 595, in sleep
    return await future
  File "/home/user/project-tracker/project/websocket.py", line 49, in connect_and_read_websocket
    w = await tornado.websocket.websocket_connect(WS_URL, connect_timeout=5, ping_interval=25)
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/site-packages/tornado/iostream.py", line 1226, in connect
    self.socket.connect(address)
OSError: [Errno 101] Network is unreachable
2020-06-26 17:25:09 [scrapy] ERROR: Error while obtaining start requests
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.7.7/lib/python3.7/site-packages/tornado/tcpclient.py", line 143, in on_connect_done
    stream = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:
...
```

**Comment by Gallaecio** [comment]
I have not been able to reproduce this issue with #6715 and the following code:

```python
from asyncio import sleep

from scrapy import Spider
from tornado.websocket import websocket_connect


class TestSpider(Spider):
    name = "test"

    async def yield_seeds(self):
        url = "wss://toscrape.com"
        seconds = 0.1
        while True:
            try:
                socket = await websocket_connect(url)
            except Exception:
                self.logger.error(f"Could not connect to {url}, waiting for {seconds} seconds…")
                await sleep(seconds)
        return
        yield
```

I wonder if the example is not a good one to reproduce the issue, or if the issue is gone.

If there is no further feedback before we merge #6715, I think we should close this issue.
