### ISSUE TITLE
scrapy startproject alters executable permissions in local virtualenv

### ISSUE THREAD

**Issue by dhosterman** [scrapy/scrapy#4662]
### Description

When running `scrapy startproject` after creating a virtualenv in .venv in the project directory, the executable files have their permissions changed.

### Steps to Reproduce (using Poetry)

1. Enter new project directory
2. `poetry init -n`
3. `poetry config virtualenvs.in-project true --local`
4. `poetry add scrapy`
5. `poetry shell`
6. `scrapy startproject scraper .`
7. `scrapy` <-- fails
8. `python` <-- fails

**Expected behavior:** [What you expect to happen]

I expect to still be able to execute `scrapy` or `python` commands.

**Actual behavior:** [What actually happens]

I am unable to execute `scrapy` or `python` commands because everything in .venv/bin has had its executable permissions removed including the python executable that is the target of the `python` symlink.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Scrapy       : 2.2.0
lxml         : 4.5.1.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 20.3.0
Python       : 3.8.3 (default, Jun 27 2020, 12:47:10) - [Clang 11.0.0 (clang-1100.0.33.8)]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1g  21 Apr 2020)
cryptography : 2.9.2
Platform     : macOS-10.15.5-x86_64-i386-64bit

**Comment by elacuesta** [comment]
Ouch, seems like the issue appears even earlier. I think this is related to #4604.


```
 eugenio  ~   mkdir asdf
 eugenio  ~   cd asdf
 eugenio  ~/asdf   python3.7 -m venv .venv
 eugenio  ~/asdf   source .venv/bin/activate
 eugenio  ⓔ .venv  ~/asdf   pip install scrapy
Collecting scrapy

(...)

Installing collected packages: itemadapter, lxml, zope.interface, six, w3lib, cssselect, parsel, protego, pycparser, cffi, cryptography, PyDispatcher, pyOpenSSL, attrs, pyasn1, pyasn1-modules, service-identity, Automat, constantly, idna, hyperlink, PyHamcrest, incremental, Twisted, queuelib, scrapy
  Running setup.py install for protego ... done
  Running setup.py install for PyDispatcher ... done
Successfully installed Automat-20.2.0 PyDispatcher-2.0.5 PyHamcrest-2.0.2 Twisted-20.3.0 attrs-19.3.0 cffi-1.14.0 constantly-15.1.0 cryptography-2.9.2 cssselect-1.1.0 hyperlink-19.0.0 idna-2.10 incremental-17.5.0 itemadapter-0.1.0 lxml-4.5.1 parsel-1.6.0 protego-0.1.16 pyOpenSSL-19.1.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.20 queuelib-1.5.0 scrapy-2.2.0 service-identity-18.1.0 six-1.15.0 w3lib-1.22.0 zope.interface-5.1.0
You are using pip version 19.0.3, however version 20.2b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
 eugenio  ⓔ .venv  ~/asdf   scrapy startproject scraper .
Traceback (most recent call last):
  File "/home/eugenio/asdf/.venv/bin/scrapy", line 10, in <module>
    sys.exit(execute())
  File "/home/eugenio/asdf/.venv/lib/python3.7/site-packages/scrapy/cmdline.py", line 143, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/home/eugenio/asdf/.venv/lib/python3.7/site-packages/scrapy/cmdline.py", line 98, in _run_print_help
    func(*a, **kw)
  File "/home/eugenio/asdf/.venv/lib/python3.7/site-packages/scrapy/cmdline.py", line 151, in _run_command
    cmd.run(args, opts)
  File "/home/eugenio/asdf/.venv/lib/python3.7/site-packages/scrapy/commands/startproject.py", line 125, in run
    self._copytree(self.templates_dir, abspath(project_dir))
  File "/home/eugenio/asdf/.venv/lib/python3.7/site-packages/scrapy/commands/startproject.py", line 82, in _copytree
    self._set_rw_permissions(dst)
  File "/home/eugenio/asdf/.venv/lib/python3.7/site-packages/scrapy/commands/startproject.py", line 104, in _set_rw_permissions
    os.chmod(join(root, file), mode_rw)
PermissionError: [Errno 1] Operation not permitted: '/home/eugenio/asdf/.venv/bin/python3.7'
 eugenio  ⓔ .venv  ~/asdf  126   scrapy startproject scraper .
bash: /home/eugenio/asdf/.venv/bin/scrapy: Permission denied
```
