### ISSUE TITLE
lost "</link>" by XMLFeedSpider

### ISSUE THREAD

**Issue by SilentGene** [scrapy/scrapy#4675]
### Description

XMLFeedSpider is always losing `</link>` tags in `parse_node`

### Steps to Reproduce

my code:
```python
from scrapy.spiders import XMLFeedSpider
from myspider.items import myspiderItem


class myspiderSpider(XMLFeedSpider):
    name = 'myspider'
    start_urls = ['https://iopscience.iop.org/journal/rss/0067-0049']

    iterator = 'html'
    itertag = 'item'

    def parse_node(self, response, node):
        response.selector.remove_namespaces()
        item = myspiderItem()
        print(node.get())
        item['link']=node.xpath("link/text()").get()
        return item
```
**Expected behavior:** [What you expect to happen]
The `<link>...</link>` should be printed and extracted

**Actual behavior:** [What actually happens]
The `</link>` tags were ignored by the spider:
```bash
<item rdf:about="http://iopscience.iop.org/0067-0049/249/1/2">
    <title>A Monte Carlo Implementation of Galactic Free–Free Emission for the EoR Foreground Models</title>
    <link>http://iopscience.iop.org/0067-0049/249/1/2
    <description>The overwhelming foreground causes...</description>
...
</item>
```
So the `item['link']` cannot be got:
```bash
{'link': None}
```
**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time. Not only in this RSS feed, but also all the other feeds.

### Versions

Please paste here the output of executing `scrapy version --verbose` in the command line.
I've tried on two machines:
```
Scrapy       : 2.2.0
lxml         : 4.5.1.0
libxml2      : 2.9.5
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 20.3.0
Python       : 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1g  21 Apr 2020)
cryptography : 2.9.2
Platform     : Windows-10-10.0.19041-SP0
```
And:
```
Scrapy       : 2.2.0
lxml         : 4.5.1.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.5.2
w3lib        : 1.21.0
Twisted      : 20.3.0
Python       : 3.8.3 (default, Jul  2 2020, 16:21:59) - [GCC 7.3.0]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1g  21 Apr 2020)
cryptography : 2.9.2
Platform     : Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.10
```

**Comment by SilentGene** [comment]
To make it simple, I also tried the following code to parse a local file:
Local file:
```html
<item>
   <link>http://www.google.com</link>
</item>

<item>
   <linkaaa>http://www.google.com</linkaaa>
</item>
```
And my spider:
```python
from scrapy.spiders import XMLFeedSpider
from myspider.items import myspiderItem

class JournalSpider(XMLFeedSpider):
    name = 'myspider'
    start_urls = ["file:///mnt/e/sample.xml"]

    iterator = 'html'
    itertag = 'item'

    def parse_node(self, response, node):
        item = myspiderItem()
        print(node.get())
        item['link']=node.xpath("link/text()").get()
        return item
```
It returns:
```bash
2020-07-12 06:01:56 [scrapy.core.engine] DEBUG: Crawled (200) <GET file:///mnt/e/sample.xml> (referer: None)
<item>
   <link>http://www.google.com
</item>
2020-07-12 06:01:56 [scrapy.core.scraper] DEBUG: Scraped from <200 file:///mnt/e/sample.xml>
{'link': None}
<item>
   <linkaaa>http://www.google.com</linkaaa>
</item>
2020-07-12 06:01:56 [scrapy.core.scraper] DEBUG: Scraped from <200 file:///mnt/e/sample.xml>
{'link': None}
2020-07-12 06:01:56 [scrapy.core.engine] INFO: Closing spider (finished)
```

This is quite unreasonable. As you can see, the spider ignores `</link>` but works fine with `</linkaaa>`. What is happening here?

**Comment by wRAR** [comment]
The HTML `<link>` tag cannot have text, so `lxml.html.HTMLParser` removes the erroneous closing tag:

```python
In [19]: import lxml.html

In [20]: html = lxml.html.fromstring('<link>foo</link>')

In [21]: lxml.html.tostring(html)
Out[21]: b'<html><head><link></head><body><p>foo</p></body></html>'
```

You shouldn't parse valid XML with a HTML parser, not sure why Scrapy supports that. I think we should add a warning to the docs.

**Comment by Gallaecio** [comment]
It looks like Scrapy is creating an HTML selector instead of an XML one. It may be because Scrapy is failing to detect the response as XML, or that Scrapy loads all responses as HTML.

Workaround:

```python
from parsel import Selector
selector = Selector(respose.text, type='xml')
```

And use `selector` instead of `response` to extract data.

**Comment by wRAR** [comment]
It was requested by `iterator = 'html'`

**Comment by Gallaecio** [comment]
:open_mouth:

My lack of familiarity with `XMLFeedSpider` really shows :disappointed:

**Comment by SilentGene** [comment]
hi @wRAR , thanks for your comment. Yeah the iterator that I choose may cause the problem, but `html` is the only iterator that I found could parse the feed.

Here is the code (using `iterator = 'xml'`):
```python
class myspiderSpider(XMLFeedSpider):
    name = 'myspider'
    start_urls = ['https://iopscience.iop.org/journal/rss/0067-0049']

    iterator = 'xml'
    itertag = 'item'

    def parse_node(self, response, node):
        response.selector.remove_namespaces()
        item = myspiderItem()
        print(node.get())
        item['link']=node.xpath("link/text()").get()
        return item
```
But it showed:
```
2020-07-13 21:50:32 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
```
Do you have any suggestions on this? Thanks in advance!

**Comment by wRAR** [comment]
It's because of namespaces, you can register a prefix for "http://purl.org/rss/1.0/" and use it in `itertag`, as documented at https://docs.scrapy.org/en/latest/topics/spiders.html#scrapy.spiders.XMLFeedSpider.namespaces

**Comment by SilentGene** [comment]
hi @wRAR , thanks for your comment. I've already tried using `response.selector.remove_namespaces()` in the last example, but it didn't work.
Following your suggestion, I tried registering the prefix (btw how to register "http://purl.org/rss/1.0/"):
```python
class myspiderSpider(XMLFeedSpider):
    name = 'myspider'
    start_urls = ["https://iopscience.iop.org/journal/rss/0067-0049"]

    namespaces = [('dc', 'http://purl.org/dc/elements/1.1/'),
                  ('content', 'http://purl.org/rss/1.0/modules/content/'),
                  ('prism', 'http://prismstandard.org/namespaces/basic/2.0/'),
                  ('rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns'),
                   ]
    iterator = 'iternodes'
    itertag = 'item'

    def parse_node(self, response, node):
        response.selector.remove_namespaces()
        item = ChameleonscholarItem()
        print(node.get())
        item['link'] = node.xpath("link/text()").get()
        return item
```
However, it reported:
```bash
2020-07-24 05:08:23 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://iopscience.iop.org/journal/rss/0067-0049> (referer: None)
item
2020-07-24 05:08:23 [scrapy.core.scraper] ERROR: Spider error processing <GET https://iopscience.iop.org/journal/rss/0067-0049> (referer: None)
Traceback (most recent call last):
  File "c:\users\linhe\appdata\local\programs\python\python37\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "c:\users\linhe\appdata\local\programs\python\python37\lib\site-packages\scrapy\utils\python.py", line 346, in __next__
    return next(self.data)
  File "c:\users\linhe\appdata\local\programs\python\python37\lib\site-packages\scrapy\utils\python.py", line 346, in __next__
    return next(self.data)
  File "c:\users\linhe\appdata\local\programs\python\python37\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "c:\users\linhe\appdata\local\programs\python\python37\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\users\linhe\appdata\local\programs\python\python37\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "c:\users\linhe\appdata\local\programs\python\python37\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 340, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\users\linhe\appdata\local\programs\python\python37\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "c:\users\linhe\appdata\local\programs\python\python37\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\linhe\appdata\local\programs\python\python37\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "c:\users\linhe\appdata\local\programs\python\python37\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\linhe\appdata\local\programs\python\python37\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "c:\users\linhe\appdata\local\programs\python\python37\lib\site-packages\scrapy\spiders\feed.py", line 59, in parse_nodes
    for selector in nodes:
  File "c:\users\linhe\appdata\local\programs\python\python37\lib\site-packages\scrapy\spiders\feed.py", line 85, in _iternodes
    for node in xmliter(response, self.itertag):
  File "c:\users\linhe\appdata\local\programs\python\python37\lib\site-packages\scrapy\utils\iterators.py", line 38, in     yield Selector(text=nodetext, type='xml').xpath('//' + nodename)[0]
  File "c:\users\linhe\appdata\local\programs\python\python37\lib\site-packages\parsel\selector.py", line 70, in __getitem__
    o = super(SelectorList, self).__getitem__(pos)
IndexError: list index out of range
```
What should I do next?
