### ISSUE TITLE
How to install with Python 3.4.3 (in Windows XP 32 bits)?

### ISSUE THREAD

**Issue by tellts** [scrapy/scrapy#4713]
Hello. I have problems.
`Microsoft Windows XP [Версия 5.1.2600]
(С) Корпорация Майкрософт, 1985-2001.

C:\Documents and Settings\ia>pip install scrapy==1.7.4
Collecting scrapy==1.7.4
  Downloading https://files.pythonhosted.org/packages/dd/4f/640343805541c782ee49
b14055a85da816cc118a8f48d01b56d2e5d12bf1/Scrapy-1.7.4-py2.py3-none-any.whl (234k
B)
     |████████████████████████████████| 235kB 211kB/s
Collecting PyDispatcher>=2.0.5
  Downloading https://files.pythonhosted.org/packages/cd/37/39aca520918ce1935bea
9c356bcbb7ed7e52ad4e31bff9b943dfc8e7115b/PyDispatcher-2.0.5.tar.gz
Requirement already satisfied: lxml<=4.3.5; python_version == "3.4" in c:\python
34\lib\site-packages (from scrapy==1.7.4) (4.3.1)
Collecting parsel>=1.5
  Downloading https://files.pythonhosted.org/packages/23/1e/9b39d64cbab79d4362cd
d7be7f5e9623d45c4a53b3f7522cd8210df52d8e/parsel-1.6.0-py2.py3-none-any.whl
Collecting service-identity
  Downloading https://files.pythonhosted.org/packages/e9/7c/2195b890023e098f9618
d43ebc337d83c8b38d414326685339eb024db2f6/service_identity-18.1.0-py2.py3-none-an
y.whl
Requirement already satisfied: six>=1.5.2 in c:\python34\lib\site-packages (from
 scrapy==1.7.4) (1.15.0)
Collecting pyOpenSSL
  Downloading https://files.pythonhosted.org/packages/9e/de/f8342b68fa9e981d3480
39954657bdf681b2ab93de27443be51865ffa310/pyOpenSSL-19.1.0-py2.py3-none-any.whl (
53kB)
     |████████████████████████████████| 61kB 218kB/s
Collecting cssselect>=0.9
  Downloading https://files.pythonhosted.org/packages/3b/d4/3b5c17f00cce85b9a1e6
f91096e1cc8e8ede2e1be8e96b87ce1ed09e92c5/cssselect-1.1.0-py2.py3-none-any.whl
Collecting queuelib
  Downloading https://files.pythonhosted.org/packages/4c/85/ae64e9145f39dd6d14f8
af3fa809a270ef3729f3b90b3c0cf5aa242ab0d4/queuelib-1.5.0-py2.py3-none-any.whl
Collecting Twisted<=19.2.0,>=13.1.0; python_version == "3.4"
  Downloading https://files.pythonhosted.org/packages/f8/2b/a80a70f71eb2b86992ff
a5aaae41457791ae67faa70927fd16b76127c2b7/Twisted-19.2.0.tar.bz2 (3.1MB)
     |████████████████████████████████| 3.1MB 52kB/s
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python34\python.exe' -c 'import sys, setuptools, tokenize; sys
.argv[0] = '"'"'C:\\DOCUME~1\\ia\\LOCALS~1\\Temp\\pip-install-ei0jjdyj\\Twisted\
\setup.py'"'"'; __file__='"'"'C:\\DOCUME~1\\ia\\LOCALS~1\\Temp\\pip-install-ei0j
jdyj\\Twisted\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__)
;code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code
, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\DOCUME~1\ia\LOCALS~1\Temp\
pip-install-ei0jjdyj\Twisted\pip-egg-info'
         cwd: C:\DOCUME~1\ia\LOCALS~1\Temp\pip-install-ei0jjdyj\Twisted\
    Complete output (81 lines):
    Traceback (most recent call last):
      File "C:\Python34\lib\urllib\request.py", line 1182, in do_open
        h.request(req.get_method(), req.selector, req.data, headers)
      File "C:\Python34\lib\http\client.py", line 1088, in request
        self._send_request(method, url, body, headers)
      File "C:\Python34\lib\http\client.py", line 1126, in _send_request
        self.endheaders(body)
      File "C:\Python34\lib\http\client.py", line 1084, in endheaders
        self._send_output(message_body)
      File "C:\Python34\lib\http\client.py", line 922, in _send_output
        self.send(msg)
      File "C:\Python34\lib\http\client.py", line 857, in send
        self.connect()
      File "C:\Python34\lib\http\client.py", line 1231, in connect
        server_hostname=server_hostname)
      File "C:\Python34\lib\ssl.py", line 365, in wrap_socket
        _context=self)
      File "C:\Python34\lib\ssl.py", line 583, in __init__
        self.do_handshake()
      File "C:\Python34\lib\ssl.py", line 810, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_s
sl.c:600)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Python34\lib\site-packages\setuptools\package_index.py", line 701
, in open_url
        return open_with_auth(url, self.opener)
      File "C:\Python34\lib\site-packages\setuptools\package_index.py", line 895
, in _socket_timeout
        return func(*args, **kwargs)
      File "C:\Python34\lib\site-packages\setuptools\package_index.py", line 100
8, in open_with_auth
        fp = opener(request)
      File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
        return opener.open(url, data, timeout)
      File "C:\Python34\lib\urllib\request.py", line 463, in open
        response = self._open(req, data)
      File "C:\Python34\lib\urllib\request.py", line 481, in _open
        '_open', req)
      File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
        result = func(*args)
      File "C:\Python34\lib\urllib\request.py", line 1225, in https_open
        context=self._context, check_hostname=self._check_hostname)
      File "C:\Python34\lib\urllib\request.py", line 1184, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certi
ficate verify failed (_ssl.c:600)>

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\DOCUME~1\ia\LOCALS~1\Temp\pip-install-ei0jjdyj\Twisted\setup.py",
 line 20, in <module>
        setuptools.setup(**_setup["getSetupArgs"]())
      File "C:\Python34\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Python34\lib\site-packages\setuptools\dist.py", line 265, in __in
it__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "C:\Python34\lib\site-packages\setuptools\dist.py", line 311, in fetc
h_build_eggs
        replace_conflicting=True,
      File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 797,
in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 1047,
 in best_match
        return self.obtain(req, installer)
      File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 1059,
 in obtain
        return installer(requirement)
      File "C:\Python34\lib\site-packages\setuptools\dist.py", line 378, in fetc
h_build_egg
        return cmd.easy_install(req)
      File "C:\Python34\lib\site-packages\setuptools\command\easy_install.py", l
ine 611, in easy_install
        not self.always_copy, self.local_index
      File "C:\Python34\lib\site-packages\setuptools\package_index.py", line 602
, in fetch_distribution
        return dist.clone(location=self.download(dist.location, tmpdir))
      File "C:\Python34\lib\site-packages\setuptools\package_index.py", line 518
, in download
        found = self._download_url(scheme.group(1), spec, tmpdir)
      File "C:\Python34\lib\site-packages\setuptools\package_index.py", line 759
, in _download_url
        return self._attempt_download(url, filename)
      File "C:\Python34\lib\site-packages\setuptools\package_index.py", line 765
, in _attempt_download
        headers = self._download_to(url, filename)
      File "C:\Python34\lib\site-packages\setuptools\package_index.py", line 665
, in _download_to
        fp = self.open_url(strip_fragment(url))
      File "C:\Python34\lib\site-packages\setuptools\package_index.py", line 715
, in open_url
        % (url, v.reason))
    distutils.errors.DistutilsError: Download error for https://files.pythonhost
ed.org/packages/8f/26/02c4016aa95f45479eea37c90c34f8fab6775732ae62587a874b619ca0
97/incremental-17.5.0.tar.gz#sha256=7b751696aaf36eebfab537e458929e194460051ccad2
79c72b755a167eebd4b3: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed
 (_ssl.c:600)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check th
e logs for full command output.

C:\Documents and Settings\ia>

`

**Comment by wRAR** [comment]
This is an issue tracker for Scrapy and the problem you have is not related to Scrapy but to your ancient OS and/or Python.
