### ISSUE TITLE
KeyError in self.inprogress.remove(request)

### ISSUE THREAD

**Issue by jezifm** [scrapy/scrapy#4779]
Hi, 

Anyone know how can I catch/handle this kind of errors? I'm not really sure why is this showing

```
Traceback (most recent call last):
  File "/home/root/.local/share/virtualenvs/scrapy_proj/lib/python3.6/site-packages/twisted/internet/task.py", line 517, in _oneWorkUnit
    result = next(self._iterator)
StopIteration

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/home/root/.local/share/virtualenvs/scrapy_proj/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/root/.local/share/virtualenvs/scrapy_proj/lib/python3.6/site-packages/scrapy/core/engine.py", line 159, in <lambda>
    d.addBoth(lambda _: slot.remove_request(request))
  File "/home/root/.local/share/virtualenvs/scrapy_proj/lib/python3.6/site-packages/scrapy/core/engine.py", line 39, in remove_request
    self.inprogress.remove(request)
KeyError: <GET http://example.com/ >
```

**Comment by wRAR** [comment]
This is most likely caused by problems in your code. If you think it's really a bug in Scrapy please provide a minimal reproducible example for it.

**Comment by jezifm** [comment]
adding `request = request.copy()` before retrying solved my issue. thank you
