### ISSUE TITLE
scrapy don't load settings from env because sys.path havn't location to project

### ISSUE THREAD

**Issue by alexsok-bit** [scrapy/scrapy#4780]
### Description

After installation scrapy from PyPi and setup new project, if I set `SCRAPY_SETTINGS_MODULE` then scrapy have an error `ModuleNotFoundError`. This behaviour because  an executable `scrapy` file from a python bin directory haven't a current directory in a `sys.path`. Need added a current directory into a `sys.path` for fix set of locations for module imports.

for example I change scrapy script like this
```python
#!/tmp/scrapy_test/.venv/bin/python3

# -*- coding: utf-8 -*-
import re
import sys
import os

from scrapy.cmdline import execute

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    print("Current directory:", os.getcwd())
    print("sys.path:", sys.path)
    # sys.path.append(os.getcwd())
    sys.exit(execute())
```

And this is I get

```

$ scrapy crawl
Current directory: /tmp/scrapy_test/tutorial
sys.path: ['/tmp/scrapy_test/.venv/bin', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/tmp/scrapy_test/.venv/lib/python3.6/site-packages']
```

This is fixed this problem.

```python
import os
import re
import sys

from scrapy.cmdline import execute

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.path.append(os.getcwd())
    sys.exit(execute())
```

But another way is use `scrapy` only as module.

```
python -m scrapy crawl
```

### Steps to Reproduce

```bash
mkdir /tmp/test_scrapy && cd $_
python3 -m venv .venv && source .venv/bin/activate
pip install -U pip && pip install scrapy
scrapy startproject tutorial && cd $_
scrapy genspider example example.com
export SCRAPY_SETTINGS_MODULE=tutorial.settings
scrapy crawl
```

**Expected behavior:** [What you expect to happen]

It's does work)

**Actual behavior:** [What actually happens]

It's doesn't work with error

```
Traceback (most recent call last):
  File "/tmp/test_scrapy/.venv/bin/scrapy", line 8, in <module>
    sys.exit(execute())
  File "/tmp/test_scrapy/.venv/lib/python3.6/site-packages/scrapy/cmdline.py", line 114, in execute
    settings = get_project_settings()
  File "/tmp/test_scrapy/.venv/lib/python3.6/site-packages/scrapy/utils/project.py", line 69, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/tmp/test_scrapy/.venv/lib/python3.6/site-packages/scrapy/settings/__init__.py", line 286, in setmodule
    module = import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tutorial'
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

```
$ scrapy version --verbose    
Scrapy       : 2.3.0
lxml         : 4.5.2.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 20.3.0
Python       : 3.6.9 (default, Jul 17 2020, 12:50:27) - [GCC 8.4.0]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1g  21 Apr 2020)
cryptography : 3.1
Platform     : Linux-5.4.0-42-generic-x86_64-with-LinuxMint-19.3-tricia
```

### Additional context

nothink

###### sorry for my google translate

**Comment by Gallaecio** [comment]
Doesn’t it work if you remove `export SCRAPY_SETTINGS_MODULE=tutorial.settings` from your steps to reproduce? From https://stackoverflow.com/a/48796305/939364 I gather that using `SCRAPY_SETTINGS_MODULE` prevents Scrapy from touching the Python path, which may be on purpose.

**Comment by alexsok-bit** [comment]
if, when using scrapie, I must comply with the preconditions, then indicate these conditions in the documentation. I need this variable. I have 200 spiders and even more different kinds of config files.

if this issue is known, it is worth adding it to the documentation. Or just fix.
