### ISSUE TITLE
ftplib.error_perm: 550

### ISSUE THREAD

**Issue by Apuyuseng** [scrapy/scrapy#4851]
<details>
  <summary>Traceback!</summary>

```cmd
Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/apu/.local/lib/python3.8/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/home/apu/.local/lib/python3.8/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/home/apu/.local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/apu/.local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/apu/.local/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/apu/.local/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/apu/.local/lib/python3.8/site-packages/scrapy/utils/ftp.py", line 34, in ftp_store_file
    ftp_makedirs_cwd(ftp, dirname)
  File "/home/apu/.local/lib/python3.8/site-packages/scrapy/utils/ftp.py", line 15, in ftp_makedirs_cwd
    ftp_makedirs_cwd(ftp, dirname(path), False)
  File "/home/apu/.local/lib/python3.8/site-packages/scrapy/utils/ftp.py", line 15, in ftp_makedirs_cwd
    ftp_makedirs_cwd(ftp, dirname(path), False)
  File "/home/apu/.local/lib/python3.8/site-packages/scrapy/utils/ftp.py", line 15, in ftp_makedirs_cwd
    ftp_makedirs_cwd(ftp, dirname(path), False)
  File "/home/apu/.local/lib/python3.8/site-packages/scrapy/utils/ftp.py", line 15, in ftp_makedirs_cwd
    ftp_makedirs_cwd(ftp, dirname(path), False)
  File "/home/apu/.local/lib/python3.8/site-packages/scrapy/utils/ftp.py", line 16, in ftp_makedirs_cwd
    ftp.mkd(path)
  File "/usr/lib64/python3.8/ftplib.py", line 626, in mkd
    resp = self.voidcmd('MKD ' + dirname)
  File "/usr/lib64/python3.8/ftplib.py", line 280, in voidcmd
    return self.voidresp()
  File "/usr/lib64/python3.8/ftplib.py", line 253, in voidresp
    resp = self.getresp()
  File "/usr/lib64/python3.8/ftplib.py", line 248, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 Create directory operation failed.
```
</details>

**evade way:**
scrapy/utils/ftp.py line 7 revise `ftp_makedirs_cwd` function
```
def ftp_makedirs_cwd(ftp, path, first_call=True):
    """Set the current directory of the FTP connection given in the ``ftp``
    argument (as a ftplib.FTP object), creating all parent directories if they
    don't exist. The ftplib.FTP object must be already connected and logged in.
    """
    path = path.strip('/')
    try:
        ftp.cwd(path)
    except error_perm as error:
        try:
            up_path,new_folder = path.rsplit('/',1)
        except:
            up_path,new_folder = './', path
        ftp_makedirs_cwd(ftp, up_path, True)
        ftp.mkd(new_folder)
        if first_call:
            ftp.cwd(new_folder)
```

**reason:**

`ftp.cwd` is ftp current path start

**yes or no only my have this problem?**

**Comment by wRAR** [comment]
This doesn't look like a Scrapy problem.
