### ISSUE TITLE
twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup

### ISSUE THREAD

**Issue by phongtnit** [scrapy/scrapy#4888]
Hi,

I used broad crawls about 2000 urls with Scrapy 2.4.0, more than 200 urls generated the error "**twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup**" with working urls in my browser like Chrome, Firefox but Scrapy is not. However, I could play these urls with Scrapy shell without the errror via `scrapy shell https://www.downloadcloud.com/learn-chinese.html`. So I guess that the error occur because of my broad crawls. I also configured `REACTOR_THREADPOOL_MAXSIZE = 20` to increase Twisted IO thread.

Please help me to fix that. Many thanks, 

### Description

```
2020-11-14 22:52:28 [scrapy.core.scraper] ERROR: Error downloading <GET https://www.downloadcloud.com/learn-chinese.html>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.9/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.9/site-packages/scrapy/core/downloader/middleware.py", line 45, in process_request
    return (yield download_func(request=request, spider=spider))
  File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.9/site-packages/twisted/internet/endpoints.py", line 981, in startConnectionAttempts
    raise error.DNSLookupError(
twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.downloadcloud.com.
2020-11-14 22:52:28 [scrapy.core.scraper] ERROR: Error downloading <GET https://twitter.com/ECLSchool>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.9/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.9/site-packages/scrapy/core/downloader/middleware.py", line 45, in process_request
    return (yield download_func(request=request, spider=spider))
  File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.9/site-packages/twisted/internet/endpoints.py", line 981, in startConnectionAttempts
    raise error.DNSLookupError(
twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: twitter.com.
2020-11-14 22:52:28 [scrapy.core.scraper] ERROR: Error downloading <GET https://study.com/academy/topic/ancient-china-for-elementary-school.html>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.9/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.9/site-packages/scrapy/core/downloader/middleware.py", line 45, in process_request
    return (yield download_func(request=request, spider=spider))
  File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.9/site-packages/twisted/internet/endpoints.py", line 981, in startConnectionAttempts
    raise error.DNSLookupError(
twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: study.com.
```
### Number of errors
`'downloader/exception_type_count/twisted.internet.error.DNSLookupError': 278,`

### Versions

```
Scrapy       : 2.4.0
lxml         : 4.6.1.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 20.3.0
Python       : 3.9.0 (default, Oct 27 2020, 14:15:17) - [Clang 12.0.0 (clang-1200.0.32.21)]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1h  22 Sep 2020)
cryptography : 3.2.1
Platform     : macOS-10.16-x86_64-i386-64bit
```

Some Scrapy settings
```
DNSCACHE_ENABLED = True
SCHEDULER_PRIORITY_QUEUE = 'scrapy.pqueues.DownloaderAwarePriorityQueue'
REACTOR_THREADPOOL_MAXSIZE = 20
LOG_LEVEL = 'INFO'
COOKIES_ENABLED = False
RETRY_ENABLED = False
DOWNLOAD_TIMEOUT = 15
REDIRECT_ENABLED = False
AJAXCRAWL_ENABLED = True
```

**Comment by Gallaecio** [comment]
You should be able to handle those errors, e.g. with an `errback` to retry those.

Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
