### ISSUE TITLE
TypeError: SelectorEventLoop required, instead got: <uvloop.Loop running=False closed=False debug=False>

### ISSUE THREAD

**Issue by tonal** [scrapy/scrapy#5017]
### Description

Error on startup

### Steps to Reproduce

scrapy version 2.4.1
Twisted version 21.02
uvloop version 0.15.2

Python 3.8
Os: Ubuntu 20.04 with all upgrades

settings:
```python
TWISTED_REACTOR = 'twisted.internet.asyncioreactor.AsyncioSelectorReactor'
ASYNCIO_EVENT_LOOP = 'uvloop.Loop'
```

Traceback:
```
Traceback (most recent call last):
  File "/home/user/projects/test/venv/lib/python3.9/site-packages/scrapy/utils/reactor.py", line 66, in install_reactor
    asyncioreactor.install(eventloop=event_loop)
  File "/home/user/projects/test/venv/lib/python3.9/site-packages/twisted/internet/asyncioreactor.py", line 307, in install
    reactor = AsyncioSelectorReactor(eventloop)
  File "/home/user/projects/test/venv/lib/python3.9/site-packages/twisted/internet/asyncioreactor.py", line 60, in __init__
    raise TypeError(
TypeError: SelectorEventLoop required, instead got: <uvloop.Loop running=False closed=False debug=False>
```

Twisted ticket: https://twistedmatrix.com/trac/ticket/10106#ticket

**Comment by elacuesta** [comment]
I can reproduce with the following snippet:

```python
from scrapy import Spider
from scrapy.crawler import CrawlerProcess

class AsyncioSpider(Spider):
    name = "asyncio"
    start_urls = ["https://example.org"]

    def parse(self, response):
        return {"url": response.url}

if __name__ == "__main__":
    process = CrawlerProcess(
        settings={
            "TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
            "ASYNCIO_EVENT_LOOP": "uvloop.Loop",
        }
    )
    process.crawl(AsyncioSpider)
    process.start()
```

```
$ python asyncio_spider.py 
Traceback (most recent call last):
  File "asyncio_spider.py", line 12, in <module>
    process = CrawlerProcess(
  File "/.../scrapy/scrapy/crawler.py", line 280, in __init__
    super().__init__(settings)
  File "/.../scrapy/scrapy/crawler.py", line 156, in __init__
    self._handle_twisted_reactor()
  File "/.../scrapy/scrapy/crawler.py", line 343, in _handle_twisted_reactor
    install_reactor(self.settings["TWISTED_REACTOR"], self.settings["ASYNCIO_EVENT_LOOP"])
  File "/.../scrapy/scrapy/utils/reactor.py", line 66, in install_reactor
    asyncioreactor.install(eventloop=event_loop)
  File "/.../scrapy/venv-scrapy/lib/python3.8/site-packages/twisted/internet/asyncioreactor.py", line 307, in install
    reactor = AsyncioSelectorReactor(eventloop)
  File "/.../scrapy/venv-scrapy/lib/python3.8/site-packages/twisted/internet/asyncioreactor.py", line 60, in __init__
    raise TypeError(
TypeError: SelectorEventLoop required, instead got: <uvloop.Loop running=False closed=False debug=False>
```

```
Scrapy       : 2.4.1
lxml         : 4.6.2.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 21.2.0
Python       : 3.8.2 (default, Apr 18 2020, 17:39:30) - [GCC 7.5.0]
pyOpenSSL    : 20.0.1 (OpenSSL 1.1.1i  8 Dec 2020)
cryptography : 3.4.5
Platform     : Linux-4.15.0-128-generic-x86_64-with-glibc2.27
```

While we investigate further, please note that downgrading Twisted to 20.3.0 seems to be working.

**Comment by tonal** [comment]
https://github.com/twisted/twisted/releases/tag/twisted-21.7.0:
> twisted.internet.asyncioreactor.AsyncioSelectorReactor will no longer raise a TypeError like "SelectorEventLoop required, instead got: <uvloop.Loop ...>" (broken since 21.2.0). (#10106)

**Comment by Gallaecio** [comment]
Thanks! I’ve verified that https://github.com/scrapy/scrapy/issues/5017#issuecomment-787935098 works with the latest version of both Scrapy and Twisted.
