### ISSUE TITLE
Scrapy 2.4.1 got exception:twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]

### ISSUE THREAD

**Issue by MonkeySuncen** [scrapy/scrapy#5018]
### Description

Hi, i got a exception with scrapy 2.4.1 witch as my title.
I tried the command `scrapy shell "https://hr.jxhrss.gov.cn"` and got the same exception.

> scrapy shell https://hr.jxhrss.gov.cn
2021-03-01 22:25:24 [scrapy.utils.log] INFO: Scrapy 2.4.1 started (bot: scrapybot)
2021-03-01 22:25:24 [scrapy.utils.log] INFO: Versions: lxml 4.6.1.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 20.3.0, Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)], pyOpenSSL 20.0.1 (OpenSSL 1.1.1j  16 Feb 2021), cryptography 3.4.6, Platform Windows-10-10.0.18362-SP0
2021-03-01 22:25:24 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.selectreactor.SelectReactor
2021-03-01 22:25:24 [scrapy.crawler] INFO: Overridden settings:
{'DUPEFILTER_CLASS': 'scrapy.dupefilters.BaseDupeFilter',
 'LOGSTATS_INTERVAL': 0}
2021-03-01 22:25:24 [scrapy.extensions.telnet] INFO: Telnet Password: 67572ed8fdba702d
2021-03-01 22:25:24 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole']
2021-03-01 22:25:25 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2021-03-01 22:25:25 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2021-03-01 22:25:25 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2021-03-01 22:25:25 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2021-03-01 22:25:25 [scrapy.core.engine] INFO: Spider opened
2021-03-01 22:25:25 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://hr.jxhrss.gov.cn> (failed 1 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]
2021-03-01 22:25:25 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://hr.jxhrss.gov.cn> (failed 2 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]
2021-03-01 22:25:25 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET https://hr.jxhrss.gov.cn> (failed 3 times): [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\scrapy.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\cmdline.py", line 145, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\cmdline.py", line 100, in _run_print_help
    func(*a, **kw)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\cmdline.py", line 153, in _run_command
    cmd.run(args, opts)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\commands\shell.py", line 74, in run
    shell.start(url=url, redirect=not opts.no_redirect)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\shell.py", line 43, in start
    self.fetch(url, spider, redirect=redirect)
  File "c:\programdata\anaconda3\lib\site-packages\scrapy\shell.py", line 110, in fetch
    response, spider = threads.blockingCallFromThread(
  File "c:\programdata\anaconda3\lib\site-packages\twisted\internet\threads.py", line 122, in blockingCallFromThread
    result.raiseException()
  File "c:\programdata\anaconda3\lib\site-packages\twisted\python\failure.py", line 488, in raiseException
    raise self.value.with_traceback(self.tb)
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]

### Steps to Reproduce

1. execute scrapy shell "https://hr.jxhrss.gov.cn"
2. got the exception

**Expected behavior:** Get some response. 

**Actual behavior:** exception

**Reproduces how often:** Must appear

### Versions

> scrapy version -v
> Scrapy       : 2.4.1
> lxml         : 4.6.1.0
> libxml2      : 2.9.10
> cssselect    : 1.1.0
> parsel       : 1.6.0
> w3lib        : 1.22.0
> Twisted      : 20.3.0
> Python       : 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
> pyOpenSSL    : 20.0.1 (OpenSSL 1.1.1j  16 Feb 2021)
> cryptography : 3.4.6
>
> Platform     : Windows-10-10.0.18362-SP0

### Additional context
I tried other https page such as https://www.zhipin.com, it work fine.
It should be associated with the Web certificate and Twisted.Maybe i can fix this by disabling SSL validation.

**Comment by wRAR** [comment]
It doesn't work with curl or elinks either and https://www.ssllabs.com/ssltest/analyze.html?d=hr.jxhrss.gov.cn confirms that it shouldn't work with modern OpenSSL (since 1.1.0, [see the announcement](https://www.openssl.org/blog/blog/2016/08/24/sweet32/)). It only supports two crappy 3DES ciphers. I'm afraid Scrapy won't be able to work with this either as it relies on the pre-compiled OpenSSL (either from the system or bundled with pyOpenSSL) for the client-side cipher support.
