### ISSUE TITLE
I got a ValueError: too many file descriptors in select() when I use proxy in my spider

### ISSUE THREAD

**Issue by fendouwhy** [scrapy/scrapy#5024]
### Description
My computer environment is python3.6, Windows 10 and Scrapy2.4.1.
This problem occurs when I add proxy，but I disable proxy Middleware, this problem will not occur. I search this problem in google, but there is not a good answer for Scrapy and Windows 10. That's the problem:

```
Traceback (most recent call last):
  File "D:\spider\collection\spiders\static_spider.py", line 456, in <module>
    raise e
  File "D:\spider\collection\spiders\static_spider.py", line 454, in <module>
    cp.start()
  File "D:\pyenv\python3.6\lib\site-packages\scrapy\crawler.py", line 327, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "D:\pyenv\python3.6\lib\site-packages\twisted\internet\asyncioreactor.py", line 267, in run
    self._asyncioEventloop.run_forever()
  File "d:\python3.6\lib\asyncio\base_events.py", line 438, in run_forever
    self._run_once()
  File "d:\python3.6\lib\asyncio\base_events.py", line 1415, in _run_once
    event_list = self._selector.select(timeout)
  File "d:\python3.6\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "d:\python3.6\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()

```
### This is my settings:
```
{
        'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36',
        'ROBOTSTXT_OBEY': False,
        'CONCURRENT_REQUESTS': 16,
        # 'CONCURRENT_REQUESTS_PER_IP': 16,
        'DOWNLOAD_DELAY': 0.3,
        'DOWNLOAD_TIMEOUT': 20,
        'REACTOR_THREADPOOL_MAXSIZE': 64,
        'ITEM_PIPELINES': {collection.pipelines.CollectionPipeline': 300},
        'DOWNLOADER_MIDDLEWARES': {collection.middlewares.IPProxyMiddleware': 120,
        },
        'RETRY_TIMES': 3,
        'RETRY_HTTP_CODES': [403, 500, 502, 503, 504, 400, 408, 407],
        # 'LOG_FILE': log_file_path,
        # 'LOG_LEVEL': 'INFO'
    }
```

### this is my ProxyMiddleware, and the problem will occur when I use it, on the contrary, no problem will occur
```
class IPProxyMiddleware(object):
    def process_request(self, request, spider):
        proxy_ips = redis_client.execute_command('ZRANGEBYSCORE', redis_key, now_time + t, now_time + expire_interval)
        if proxy_ips:
            ip = random.choice(proxy_ips)
            ip_port = ip.decode()
        else:
            ip_port = None
        if ip_port:
            ip_proxy = 'http://' + ip_port
            request.meta["proxy"] = ip_proxy
```

### and this is my way to start my spider:
```
    settings.setdict(custom_settings)
    cp = CrawlerProcess(settings)
    try:
        cp.crawl(StaticSpider)
        cp.start()
    except Exception as e:
        raise e
```

**Comment by wRAR** [comment]
This is a limitation of Twisted on Windows, I'm not sure if we can do anything about that (and if this is even related to Scrapy). You may try to find why does that middleware require additional fds and try to fix that.

**Comment by Dragon1573** [comment]
I meet the same problem too.

## Details

I'm crawling a domain, which every single data hosts on a unique sub-domain. (Unrelated information are removed)

<details><summary><code>sample.py</code></summary>
<p>

```python
class SampleSpider(Spider):
    name = "sample"
    allowed_domains = ["example.com"]

    def __init__(self, _start_id: str, _end_id: str, *args, **kwargs):
        super().__init__(self.name, *args, **kwargs)
        self.start_id, self.end_id = map(int, (_start_id, _end_id))
        self.start_urls = [
            f"https://{_:06d}.example.com/" for _ in range(self.start_id, self.end_id)
        ]
``` 

</p>
</details>

When I launch the program with some case, Scrapy will crash.

```
PS> python -m scrapy crawl -a _start_id=871000 -a _end_id=871750 -O result.json sample
... (Running for about 1 minute, everything looks perfect)
Traceback (most recent call last):
  File "D:\Applications\Python\v3_10\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Applications\Python\v3_10\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Repository\Sample_Scrapy\.venv\lib\site-packages\scrapy\__main__.py", line 4, in <module>
    execute()
  File "D:\Repository\Sample_Scrapy\.venv\lib\site-packages\scrapy\cmdline.py", line 158, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "D:\Repository\Sample_Scrapy\.venv\lib\site-packages\scrapy\cmdline.py", line 111, in _run_print_help
    func(*a, **kw)
  File "D:\Repository\Sample_Scrapy\.venv\lib\site-packages\scrapy\cmdline.py", line 166, in _run_command
    cmd.run(args, opts)
  File "D:\Repository\Sample_Scrapy\.venv\lib\site-packages\scrapy\commands\crawl.py", line 31, in run
    self.crawler_process.start()
  File "D:\Repository\Sample_Scrapy\.venv\lib\site-packages\scrapy\crawler.py", line 383, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "D:\Repository\Sample_Scrapy\.venv\lib\site-packages\twisted\internet\asyncioreactor.py", line 255, in run
    self._asyncioEventloop.run_forever()
  File "D:\Applications\Python\v3_10\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\Applications\Python\v3_10\lib\asyncio\base_events.py", line 1868, in _run_once
    event_list = self._selector.select(timeout)
  File "D:\Applications\Python\v3_10\lib\selectors.py", line 324, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "D:\Applications\Python\v3_10\lib\selectors.py", line 315, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()
```

```
PS> python -m scrapy crawl -a _start_id=871000 -a _end_id=871500 -O result.json sample
...
2023-03-29 22:02:58 [scrapy.core.engine] INFO: Closing spider (finished)
2023-03-29 22:02:58 [scrapy.extensions.feedexport] INFO: Stored json feed (313 items) in: result.json
2023-03-29 22:02:58 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 389392,
 'downloader/request_count': 500,
 'downloader/request_method_count/GET': 500,
 'downloader/response_bytes': 871490,
 'downloader/response_count': 500,
 'downloader/response_status_count/200': 322,
 'downloader/response_status_count/404': 178,
 'elapsed_time_seconds': 11.388316,
 'feedexport/success_count/FileFeedStorage': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2023, 3, 29, 14, 2, 58, 160259),
 'httpcompression/response_bytes': 1192113,
 'httpcompression/response_count': 500,
 'httperror/response_ignored_count': 178,
 'httperror/response_ignored_status_count/404': 178,
 'item_scraped_count': 313,
 'log_count/DEBUG': 816,
 'log_count/INFO': 187,
 'response_received_count': 500,
 'scheduler/dequeued': 500,
 'scheduler/dequeued/memory': 500,
 'scheduler/enqueued': 500,
 'scheduler/enqueued/memory': 500,
 'start_time': datetime.datetime(2023, 3, 29, 14, 2, 46, 771943)}
2023-03-29 22:02:58 [scrapy.core.engine] INFO: Spider closed (finished)
``` 

## Clues

I search for the error message and get [this](https://blog.csdn.net/ikisstherain/article/details/117480369) (Simplified Chinese only) blog post.

> `select` is used inside `asyncio`, and files "openable" by `select` is limited by the Operating System. For Linux the limitation is default to 1024, and for Windows is default to 509.
>
> You can try to limit the concurrency of `asyncio` with `asyncio.Semaphore()` .

## Environments

- Windows 11 Professional 22H2
- Python v3.10.9
- Scrapy v2.8.0

**Comment by Dragon1573** [comment]
## Walkaround

> This method seems working for me. Can't sure if it's general for any other users.

At the bottom lines of `settings.py` in the project, try to switch reactor instead of using the default one.

I switch it to `twisted.internet.selectreactor.SelectReactor` and nothing wrong there. It DOES stuck in the middle for 15s to 1min, but no exceptions or errors shows up. Scrapy will keep crawling after "the rest" in a high speed (no anti-spider technology was used on the domain).
