### ISSUE TITLE
Potential issue with latest twisted release

### ISSUE THREAD

**Issue by Rafiot** [scrapy/scrapy#5031]
### Description

Somewhat random exception when using this code: https://github.com/Lookyloo/ScrapySplashWrapper

### Steps to Reproduce

I have no idea what triggers this issue, but I'm adding more debug on my side to find at least the URLs that fail.

**Actual behavior:**

```python
09:38:16 scrapy.core.downloader.handlers ERROR:Loading "scrapy.core.downloader.handlers.http.HTTPDownloadHandler" for scheme "http"                                                                             
Traceback (most recent call last):                                                                      
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/__init__.py", line 49, in _load_handler                                   
    dhcls = load_object(path)                                                                           
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/utils/misc.py", line 62, in load_object                                                            
    mod = import_module(module)                                                                         
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http.py", line 2, in <module>
    from scrapy.core.downloader.handlers.http11 import (
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http11.py", line 16, in <module>
    from twisted.web.client import Agent, HTTPConnectionPool, ResponseDone, ResponseFailed, URI
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/twisted/web/client.py", line 2113, in <module>
    class RedirectAgent:
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/twisted/web/client.py", line 2139, in RedirectAgent
    http.PERMANENT_REDIRECT,
AttributeError: module 'twisted.web.http' has no attribute 'PERMANENT_REDIRECT'
```

### Versions

```bash
$ scrapy  version --verbose
Scrapy       : 2.4.1
lxml         : 4.6.2.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 21.2.0
Python       : 3.8.5 (default, Jan 27 2021, 15:41:15) - [GCC 9.3.0]
pyOpenSSL    : 20.0.1 (OpenSSL 1.1.1j  16 Feb 2021)
cryptography : 3.4.6
Platform     : Linux-5.4.0-56-generic-x86_64-with-glibc2.29
```

### Additional context

It seems to have started with the latest release of twisted.

**Comment by Rafiot** [comment]
If you have any question, or need more details please let me know.

**Comment by Rafiot** [comment]
Okay, I'm quite puzzled by the exceptions, I sometimes get the following trace:

```python
02:49:08 scrapy.utils.log INFO:Scrapy 2.4.1 started (bot: scrapybot)                                                                                                                                                                                                                                                        
2021-03-08 14:49:08 [scrapy.utils.log] INFO: Scrapy 2.4.1 started (bot: scrapybot)                                                                            
02:49:08 scrapy.utils.log INFO:Versions: lxml 4.6.2.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 20.3.0, Python 3.8.5 (default, Jul 28 2020, 12:59:40) - [GCC 9.3.0], pyOpenSSL 20.0.0 (OpenSSL 1.1.1h  22 Sep 2020), cryptography 3.2.1, Platform Linux-5.4.0-56-generic-x86_64-with-glibc2.29  
2021-03-08 14:49:08 [scrapy.utils.log] INFO: Versions: lxml 4.6.2.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 20.3.0, Python 3.8.5 (default, Jul 28 2020, 12:59:40) - [GCC 9.3.0], pyOpenSSL 20.0.0 (OpenSSL 1.1.1h  22 Sep 2020), cryptography 3.2.1, Platform Linux-5.4.0-56-generic-x86_64-wi
th-glibc2.29                                                                                                                                                  
02:49:08 scrapy.utils.log DEBUG:Using reactor: twisted.internet.epollreactor.EPollReactor                                                                     
2021-03-08 14:49:08 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.epollreactor.EPollReactor                                                       
02:49:08 scrapy.crawler INFO:Overridden settings:                                                                                                             
{'DEPTH_LIMIT': 1,                                                                                                                                            
 'DUPEFILTER_CLASS': 'scrapy_splash.SplashAwareDupeFilter',                                                                                                   
 'LOG_LEVEL': 'WARNING'}                                                                                                                                      
2021-03-08 14:49:08 [scrapy.crawler] INFO: Overridden settings:                                                                                               
{'DEPTH_LIMIT': 1,                                                                                                                                                                                                                                                                                                          
 'DUPEFILTER_CLASS': 'scrapy_splash.SplashAwareDupeFilter',                                                                                                   
 'LOG_LEVEL': 'WARNING'}                                                                                                                                                                                                                                                                                                    
02:49:08 scrapy.extensions.telnet INFO:Telnet Password: 46eb090114440287                                                                                      
02:49:08 scrapy.middleware INFO:Enabled extensions:                            
['scrapy.extensions.corestats.CoreStats',                                      
 'scrapy.extensions.telnet.TelnetConsole',                                     
 'scrapy.extensions.memusage.MemoryUsage',                                     
 'scrapy.extensions.logstats.LogStats']                                        
02:49:08 scrapy.core.downloader.handlers ERROR:Loading "scrapy.core.downloader.handlers.http.HTTPDownloadHandler" for scheme "http"
Traceback (most recent call last):                                             
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/__init__.py", line 49, in _load_handler
    dhcls = load_object(path)                                                                                                                                                                                                                                                                                    [127/37052]
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/utils/misc.py", line 62, in load_object
    mod = import_module(module)                                                
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module                                                                                 
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                               
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                                                             
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                                                           
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                                                                                  
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                                                                           
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module                                                                                     
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                                                
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http.py", line 2, in <module>
    from scrapy.core.downloader.handlers.http11 import (                                                                                                      
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http11.py", line 16, in <module>
    from twisted.web.client import Agent, HTTPConnectionPool, ResponseDone, ResponseFailed, URI                                                               
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/twisted/web/client.py", line 2113, in <module>
    class RedirectAgent:                                                       
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/twisted/web/client.py", line 2135, in RedirectAgent
    print(http, http.TEMPORARY_REDIRECT, http.PERMANENT_REDIRECT)                                                                                             
AttributeError: module 'twisted.web.http' has no attribute 'PERMANENT_REDIRECT'                                                                               
2021-03-08 14:49:08 [scrapy.core.downloader.handlers] ERROR: Loading "scrapy.core.downloader.handlers.http.HTTPDownloadHandler" for scheme "http"
Traceback (most recent call last):                                             
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/__init__.py", line 49, in _load_handler
    dhcls = load_object(path)                                                  
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/utils/misc.py", line 62, in load_object
    mod = import_module(module)                                                                                                                                                                                                                                                                                  [102/37052]
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module                                                                                 
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                               
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                                                             
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                                                           
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                                                                                  
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                                                                           
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module                                                                                     
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                                                
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http.py", line 2, in <module>
    from scrapy.core.downloader.handlers.http11 import (                                                                                                      
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http11.py", line 16, in <module>
    from twisted.web.client import Agent, HTTPConnectionPool, ResponseDone, ResponseFailed, URI                                                               
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/twisted/web/client.py", line 2113, in <module>
    class RedirectAgent:                                                       
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/twisted/web/client.py", line 2135, in RedirectAgent
    print(http, http.TEMPORARY_REDIRECT, http.PERMANENT_REDIRECT)                                                                                             
AttributeError: module 'twisted.web.http' has no attribute 'PERMANENT_REDIRECT'                                                                               
02:49:08 scrapy.core.downloader.handlers ERROR:Loading "scrapy.core.downloader.handlers.http.HTTPDownloadHandler" for scheme "https"
Traceback (most recent call last):                                             
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/__init__.py", line 49, in _load_handler
    dhcls = load_object(path)                                                  
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/utils/misc.py", line 62, in load_object
    mod = import_module(module)                                                
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                                                                                                                                                   [77/37052]
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                                                             
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                                                           
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                                                                                  
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                                                                           
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module                                                                                     
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                                                
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http.py", line 2, in <module>
    from scrapy.core.downloader.handlers.http11 import (                                                                                                      
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http11.py", line 16, in <module>
    from twisted.web.client import Agent, HTTPConnectionPool, ResponseDone, ResponseFailed, URI                                                               
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/twisted/web/client.py", line 2113, in <module>
    class RedirectAgent:                                                       
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/twisted/web/client.py", line 2135, in RedirectAgent
    print(http, http.TEMPORARY_REDIRECT, http.PERMANENT_REDIRECT)                                                                                             
AttributeError: module 'twisted.web.http' has no attribute 'PERMANENT_REDIRECT'                                                                               
2021-03-08 14:49:08 [scrapy.core.downloader.handlers] ERROR: Loading "scrapy.core.downloader.handlers.http.HTTPDownloadHandler" for scheme "https"
Traceback (most recent call last):                                             
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/__init__.py", line 49, in _load_handler
    dhcls = load_object(path)                                                  
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/utils/misc.py", line 62, in load_object
    mod = import_module(module)                                                
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module                                                                                 
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                               
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                                                                                                                                                                                                               [52/37052]
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                                                                                  
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                                                                           
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module                                                                                     
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                                                
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http.py", line 2, in <module>
    from scrapy.core.downloader.handlers.http11 import (                                                                                                      
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http11.py", line 16, in <module>
    from twisted.web.client import Agent, HTTPConnectionPool, ResponseDone, ResponseFailed, URI                                                               
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/twisted/web/client.py", line 2113, in <module>
    class RedirectAgent:                                                       
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/twisted/web/client.py", line 2135, in RedirectAgent
    print(http, http.TEMPORARY_REDIRECT, http.PERMANENT_REDIRECT)                                                                                             
AttributeError: module 'twisted.web.http' has no attribute 'PERMANENT_REDIRECT'                                                                               
02:49:08 scrapy.core.downloader.handlers ERROR:Loading "scrapy.core.downloader.handlers.s3.S3DownloadHandler" for scheme "s3"
Traceback (most recent call last):                                             
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/__init__.py", line 49, in _load_handler
    dhcls = load_object(path)                                                  
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/utils/misc.py", line 62, in load_object
    mod = import_module(module)                                                
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module                                                                                 
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                               
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                                                             
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                                                           
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                                                                           
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module                                                                                     
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                                                
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/s3.py", line 3, in <module>
    from scrapy.core.downloader.handlers.http import HTTPDownloadHandler                                                                                      
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http.py", line 2, in <module>
    from scrapy.core.downloader.handlers.http11 import (                                                                                                      
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http11.py", line 16, in <module>
    from twisted.web.client import Agent, HTTPConnectionPool, ResponseDone, ResponseFailed, URI                                                               
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/twisted/web/client.py", line 2113, in <module>
    class RedirectAgent:                                                       
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/twisted/web/client.py", line 2135, in RedirectAgent
    print(http, http.TEMPORARY_REDIRECT, http.PERMANENT_REDIRECT)                                                                                             
AttributeError: module 'twisted.web.http' has no attribute 'PERMANENT_REDIRECT'                                                                               
2021-03-08 14:49:08 [scrapy.core.downloader.handlers] ERROR: Loading "scrapy.core.downloader.handlers.s3.S3DownloadHandler" for scheme "s3"
Traceback (most recent call last):                                             
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/__init__.py", line 49, in _load_handler
    dhcls = load_object(path)                                                  
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/utils/misc.py", line 62, in load_object
    mod = import_module(module)                                                
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module                                                                                 
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                               
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                                                             
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                                                                                  
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                                                                           
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module                                                                                     
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                                                
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/s3.py", line 3, in <module>
    from scrapy.core.downloader.handlers.http import HTTPDownloadHandler                                                                                      
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http.py", line 2, in <module>
    from scrapy.core.downloader.handlers.http11 import (                                                                                                      
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy/core/downloader/handlers/http11.py", line 16, in <module>
    from twisted.web.client import Agent, HTTPConnectionPool, ResponseDone, ResponseFailed, URI                                                               
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/twisted/web/client.py", line 2113, in <module>
    class RedirectAgent:                                                       
  File "/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/twisted/web/client.py", line 2135, in RedirectAgent
    print(http, http.TEMPORARY_REDIRECT, http.PERMANENT_REDIRECT)                                                                                             
AttributeError: module 'twisted.web.http' has no attribute 'PERMANENT_REDIRECT'
```
And sometimes this one:

```python
INFO:scrapy.utils.log:Scrapy 2.4.1 started (bot: scrapybot)                                                                                                                                                                                                                                                                 
2021-03-08 14:29:22 [scrapy.utils.log] INFO: Scrapy 2.4.1 started (bot: scrapybot)                                                                                                                                                                                                                                          
INFO:scrapy.utils.log:Versions: lxml 4.6.2.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 21.2.0, Python 3.8.5 (default, Jan 27 2021, 15:41:15) - [GCC 9.3.0], pyOpenSSL 20.0.1 (OpenSSL 1.1.1j  16 Feb 2021), cryptography 3.4.6, Platform Linux-5.4.0-56-generic-x86_64-with-glibc2.29           
2021-03-08 14:29:22 [scrapy.utils.log] INFO: Versions: lxml 4.6.2.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 21.2.0, Python 3.8.5 (default, Jan 27 2021, 15:41:15) - [GCC 9.3.0], pyOpenSSL 20.0.1 (OpenSSL 1.1.1j  16 Feb 2021), cryptography 3.4.6, Platform Linux-5.4.0-56-generic-x86_64-wi
th-glibc2.29                                                                   
DEBUG:scrapy.utils.log:Using reactor: twisted.internet.epollreactor.EPollReactor                                                                              
2021-03-08 14:29:22 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.epollreactor.EPollReactor                                                       
INFO:scrapy.crawler:Overridden settings:                                       
{'DEPTH_LIMIT': 1,                                                             
 'DUPEFILTER_CLASS': 'scrapy_splash.SplashAwareDupeFilter',                                                                                                   
 'LOG_LEVEL': 'WARNING'}                                                       
2021-03-08 14:29:22 [scrapy.crawler] INFO: Overridden settings:                                                                                               
{'DEPTH_LIMIT': 1,                                                             
 'DUPEFILTER_CLASS': 'scrapy_splash.SplashAwareDupeFilter',                                                                                                   
 'LOG_LEVEL': 'WARNING'}                                                       
INFO:scrapy.extensions.telnet:Telnet Password: 99ade46576f9b8a4                                                                                               
INFO:scrapy.middleware:Enabled extensions:                                     
['scrapy.extensions.corestats.CoreStats',                                      
 'scrapy.extensions.telnet.TelnetConsole',                                     
 'scrapy.extensions.memusage.MemoryUsage',                                     
 'scrapy.extensions.logstats.LogStats']
WARNING:py.warnings:/home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy_splash/request.py:41: ScrapyDeprecationWarning: Call to deprecated function to_native_str. Use to_unicode instead.
  url = to_native_str(url)                                                     

2021-03-08 14:29:22 [py.warnings] WARNING: /home/raphael/.cache/pypoetry/virtualenvs/lookyloo-WHOpTNCm-py3.8/lib/python3.8/site-packages/scrapy_splash/request.py:41: ScrapyDeprecationWarning: Call to deprecated function to_native_str. Use to_unicode instead.
  url = to_native_str(url)
```

The one failing says twisted `Twisted 20.3.0`, but my virtualenv says `Twisted 21.2.0`.

**Comment by Rafiot** [comment]
Okay, I think I had a subprocess that was never killed, and kept using the old version of twisted...

Sorry for the noise.
