### ISSUE TITLE
spider_error signal is not called on an exception in DownloaderMiddlewares

### ISSUE THREAD

**Issue by adsdt** [scrapy/scrapy#5078]
### Description

The spider_error signal is not called when receiving an exception from DownloaderMiddleware. This is different from similar behavior for other scrapy components. I have not found any other way to handle the exception from DownloaderMiddleware using signal or standard methods. 
**The goal is to handle an exception after all DownloaderMiddleware.process_exception methods return None.** 

### Steps to Reproduce

1. add a spider
```
from scrapy import Request, Spider, signals


def get_import_full_name(subject):
    if hasattr(subject, "__name__"):
        return ".".join([subject.__module__, subject.__name__])
    return ".".join([subject.__module__, subject.__class__.__name__])


class ExampleDownloaderMiddleware:
    def process_request(self, request, spider):
        raise Exception('custom exception on custom middleware')

    def process_response(self, request, response, spider):
        return response

    def process_exception(self, request, exception, spider):
        return None


class ExampleSpider(Spider):
    name = 'example'
    custom_settings = {
        'DOWNLOADER_MIDDLEWARES': {
            get_import_full_name(ExampleDownloaderMiddleware): 2,
        },
    }

    @classmethod
    def from_crawler(cls, crawler, *args, **kwargs):
        spider = super().from_crawler(crawler, *args, **kwargs)
        crawler.signals.connect(spider.on_item_error, signal=signals.item_error)
        return spider

    def on_item_error(self, failure, response, spider):
        self.logger.error(f'on_item_error: {repr(failure)}')

    def start_requests(self):
        yield Request('https://api.myip.com/', callback=self.parse, dont_filter=True)

    def parse(self, response, **kwargs):
        self.logger.info('spdier.parse')

    def on_spider_error(self, failure, response, spider):
        repr(f"on_spider_error: {repr(failure)}")

```
2. run the spider
```
scrapy crawl example
```

**Expected behavior:** 
Calling the spider_error signal. Similar to the behavior when an exception is received in the following methods:
-  Spider.parse
- Spider.errback
- SpiderMiddleware.process_spider_input
- SpiderMiddleware.process_spider_output
call ```raise Exception()``` in any of these methods call a spider_error signal.

**Actual behavior:** [What actually happens]
spider_error is not called even if the error has not been handled in DownloaderMiddleware.process_exception.

**Reproduces how often:** [What percentage of the time does it reproduce?]

- 100%

### Versions

Scrapy       : 2.4.1
lxml         : 4.5.2.0
libxml2      : 2.9.5
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 20.3.0
Python       : 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1g  21 Apr 2020)
cryptography : 3.0
Platform     : Windows-10-10.0.19041-SP0

### Additional context

**Comment by elacuesta** [comment]
The provided example works as expected according to the docs, in the sense that [`spider_error`](https://docs.scrapy.org/en/2.4/topics/signals.html#spider-error) is "Sent when a spider callback generates an error (i.e. raises an exception)."

In the above example (replacing the signal being connected, from `item_error` to `spider_error` as indicated in the issue title), no response reaches the spider because the exception is raised in the request processing stage, hence the callback is not invoked. Consider instead the following (simplified) version:
```python
from scrapy import Spider, signals

class ExampleSpider(Spider):
    name = "example"
    start_urls = ["https://example.org"]

    @classmethod
    def from_crawler(cls, crawler, *args, **kwargs):
        spider = super().from_crawler(crawler, *args, **kwargs)
        crawler.signals.connect(spider.on_spider_error, signal=signals.spider_error)
        return spider

    def parse(self, response, **kwargs):
        1/0

    def on_spider_error(self, failure, response, spider):
        self.logger.error(repr(f"on_spider_error: {repr(failure)}"))
```

```
2021-04-05 01:53:54 [scrapy.core.engine] INFO: Spider opened
2021-04-05 01:53:54 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2021-04-05 01:53:54 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2021-04-05 01:53:55 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://example.org> (referer: None)
2021-04-05 01:53:55 [scrapy.core.scraper] ERROR: Spider error processing <GET https://example.org> (referer: None)
Traceback (most recent call last):
  File "/Users/eus/zyte/scrapy/venv-scrapy/lib/python3.8/site-packages/twisted/internet/defer.py", line 662, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/eus/zyte/scrapy/scrapy/spiders/__init__.py", line 90, in _parse
    return self.parse(response, **kwargs)
  File "/Users/eus/zyte/scrapy/test-spiders/signal_error.py", line 18, in parse
    1/0
ZeroDivisionError: division by zero
2021-04-05 01:53:55 [example] ERROR: 'on_spider_error: <twisted.python.failure.Failure builtins.ZeroDivisionError: division by zero>'
2021-04-05 01:53:55 [scrapy.core.engine] INFO: Closing spider (finished)
```
I think this should be considered as a feature request, the key part being "The goal is to handle an exception after all DownloaderMiddleware.process_exception methods return None". There is currently no way of doing that, AFAIK.

Regarding the second question ("When you raise an error in DownloaderMiddleware.process_response - process_exception is not called, how to handle such errors?"), these type of exceptions can be handled by the request's errback, as in the following example:
```python
from scrapy import Request, Spider, signals

class ExampleDownloaderMiddleware:
    def process_response(self, request, response, spider):
        1/0

class ExampleSpider(Spider):
    name = "example"
    custom_settings = {
        "DOWNLOADER_MIDDLEWARES": {
            ExampleDownloaderMiddleware: 2,
        },
    }

    def start_requests(self):
        yield Request("https://example.org", errback=self.errback)

    def errback(self, failure):
        self.logger.error(repr(f"errback, received {repr(failure)}"))
```

```
2021-04-05 02:10:23 [scrapy.core.engine] INFO: Spider opened
2021-04-05 02:10:23 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2021-04-05 02:10:23 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2021-04-05 02:10:23 [example] ERROR: 'errback, received <twisted.python.failure.Failure builtins.ZeroDivisionError: division by zero>'
2021-04-05 02:10:23 [scrapy.core.engine] INFO: Closing spider (finished)
```

**Comment by adsdt** [comment]
> from item_error to spider_error
typo, corrected it.

I am trying to write SpiderMiddleware for RabbitMQ broker. I believe that to do this I need to handle exceptions from all of the following components:
- SpiderMiddleware
  - spider_error, process_spider_exception
- Spider.parse, Spider.errback
  - spider_error
- ItemPipeline
  - item_error, item_dropped
- request.dont_filter
   -  request_dropped  
- DownloaderMiddleware
  - ???

For all of the above components with the exception of DownloaderMiddleware, there are signals that can be used to handle exceptions.

> I think this should be considered as a feature request, the key part being "The goal is to handle an exception after all DownloaderMiddleware.process_exception methods return None". There is currently no way of doing that, AFAIK.

Perhaps there are undocumented methods to handle this behavior? I could add the DownloaderMiddleware with the lowest priority and send a signal - but it's a terrible solution.
```
downloader_middleware_process_request_exception = object()
class Priority1DownloaderMiddleware:
    @classmethod
    def from_crawler(cls, crawler):
        m = cls(crawler)
        return m

    def __init__(self, crawler):
        self.crawler = crawler

    def process_exception(self, request, exception, spider):
        self.crawler.signals.send_catch_log(
            signal=downloader_middleware_process_request_exception,
            exception=exception,
            request=request,
            spider=spider,
        )
        return None
```

> Regarding the second question ("When you raise an error in DownloaderMiddleware.process_response - process_exception is not called, how to handle such errors?"), these type of exceptions can be handled by the request's errback, as in the following example:

But this only happens if request.errback exists. In a similar situation for SpiderMiddleware, if there is no request.errback method, we can get into SpiderMiddleware.process_spider_exception and/or handle the spider_error signal. For the DownloaderMiddleware.process_response exception, there is no such option. 

I can add request.errback if it is missing inside SpiderMiddleware methods, but this does not solve the problem. When a non-standard error occurs, a failure without a request and response object goes into the errback. Raising an exception inside the errback method allows to get to the spider_error handler, but no response is defined for it either.

It would be nice to have signals for error handling in DownloaderMiddleware.

**Comment by adsdt** [comment]
@elacuesta Is there a way to override the DownloaderMiddlewareManager class?

**Comment by Gallaecio** [comment]
@adsdt It’s not meant to be, no.

**Comment by clesauln** [comment]
on your error hook:

**def spider_error(self, failure, response, spider):**

working for me
Version: 2.10.1
