### ISSUE TITLE
FormRequest.from_response fails to parse form action url

### ISSUE THREAD

**Issue by dangra** [scrapy/scrapy#508]
Reported in #scrapy IRC channel, if parent url contains an unquoted "|" the final url is quoted including its scheme.

``` pycon
>>> from scrapy.http import FormRequest, HtmlResponse
>>> response = HtmlResponse(body='<html><body><form></form></body></html>',
...                                         url='http://foo.com/?a=|')
>>> FormRequest.from_response(response)
None
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-b87bf46cf4c1> in <module>()
----> 1 FormRequest.from_response(response)

/home/daniel/src/scrapy/scrapy/http/request/form.pyc in from_response(cls, response, formname, formnumber, formdata, clickdata, dont_click, formxpath, **kwargs)
     38         url = _get_form_url(form, kwargs.pop('url', None))
     39         method = kwargs.pop('method', form.method)
---> 40         return cls(url=url, method=method, formdata=formdata, **kwargs)
     41 
     42 def _get_form_url(form, url):

/home/daniel/src/scrapy/scrapy/http/request/form.pyc in __init__(self, *args, **kwargs)
     19             kwargs['method'] = 'POST'
     20 
---> 21         super(FormRequest, self).__init__(*args, **kwargs)
     22 
     23         if formdata:

/home/daniel/src/scrapy/scrapy/http/request/__init__.pyc in __init__(self, url, callback, method, headers, body, cookies, meta, encoding, priority, dont_filter, errback)
     24         self._encoding = encoding  # this one has to be set first
     25         self.method = str(method).upper()
---> 26         self._set_url(url)
     27         self._set_body(body)
     28         assert isinstance(priority, int), "Request priority not an integer: %r" % priority

/home/daniel/src/scrapy/scrapy/http/request/__init__.pyc in _set_url(self, url)
     55                 raise TypeError('Cannot convert unicode url - %s has no encoding' %
     56                     type(self).__name__)
---> 57             self._set_url(url.encode(self.encoding))
     58         else:
     59             raise TypeError('Request url must be str or unicode, got %s:' % type(url).__name__)

/home/daniel/src/scrapy/scrapy/http/request/__init__.pyc in _set_url(self, url)
     59             raise TypeError('Request url must be str or unicode, got %s:' % type(url).__name__)
     60         if ':' not in self._url:
---> 61             raise ValueError('Missing scheme in request url: %s' % self._url)
     62 
     63     url = property(_get_url, obsolete_setter(_set_url, 'url'))

ValueError: Missing scheme in request url: http%3A//foo.com/%3Fa=%257C
>>> 
```

**Comment by redapple** [comment]
This is still happening with libxml2 v2.9.3 and v2.9.4.

I'm not exactly sure where in libxml2 C code it fails, but using official libxml2 Python bindings, [xmlPathToURI](https://github.com/GNOME/libxml2/blob/d8083bf77955b7879c1290f0c0a24ab8cc70f7fb/uri.c#L2526) seems to be the source of these escapes (and seems to be [used when building document nodes](https://github.com/GNOME/libxml2/blob/d8083bf77955b7879c1290f0c0a24ab8cc70f7fb/tree.c#L5225)):

```
>>> import libxml2
>>> libxml2.pathToURI('http://www.example.com')
'http://www.example.com'
>>> libxml2.pathToURI('http://www.example.com?q=|')
'http%3A//www.example.com%3Fq=%257C'
```

[xmlParseURI](https://github.com/GNOME/libxml2/blob/d8083bf77955b7879c1290f0c0a24ab8cc70f7fb/uri.c#L932) does have trouble:

```
>>> libxml2.parseURI('http://www.example.com?q=|')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/libxml2.py", line 1815, in parseURI
    if ret is None:raise uriError('xmlParseURI() failed')
libxml2.uriError: xmlParseURI() failed
```

but [xmlCanonicPath](https://github.com/GNOME/libxml2/blob/d8083bf77955b7879c1290f0c0a24ab8cc70f7fb/uri.c#L2385) looks ok:

```
>>> libxml2.canonicPath(u'http://www.example.com?q=|')
'http://www.example.com?q=%7C'
```

**Comment by Nadya24** [comment]
Any progress here or a workaround?

**Comment by dangra** [comment]
@Nadya24 no, but any help is welcome.

**Comment by AdrianAtZyte** [comment]
Closing after the move to [form2request](https://form2request.readthedocs.io/en/latest/usage.html) as a [replacement for `FormRequest`](https://github.com/scrapy/scrapy/pull/6438).

If you believe this issue still impacts `form2request` and should be addressed, please open an issue [upstream](https://github.com/scrapy/form2request/issues) with a link to this issue for reference.
