### ISSUE TITLE
ModuleNotFoundError: No module named 'home'

### ISSUE THREAD

**Issue by alejandrohdo** [scrapy/scrapy#5087]
Hi Scrapy
I am working with scrapy 1.6 and python 3.6.5, now last it does not allow me to import the **settings** and it throws me an error like: **No module named 'home'**, I tried to reinstall everything from scratch but I can't solve it. Could you guide me? I detail the error it throws at me:

### Error

`Traceback (most recent call last):
  File "test/test_download_article.py", line 10, in <module>
    from url_content_download_celery import task_content_url   #url_content_download_celery
  File "/home/alejandro/projects/chamecwebscraping/chamecscrapy/chamecSpider/url_content_download_celery.py", line 22, in <module>
    from scrapy.conf import settings
  File "/home/alejandro/envs/env_web_scraping/lib/python3.6/site-packages/scrapy/conf.py", line 8, in <module>
    settings = get_project_settings()
  File "/home/alejandro/envs/env_web_scraping/lib/python3.6/site-packages/scrapy/utils/project.py", line 68, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/home/alejandro/envs/env_web_scraping/lib/python3.6/site-packages/scrapy/settings/__init__.py", line 288, in setmodule
    module = import_module(module)
  File "/home/alejandro/envs/env_web_scraping/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'home'
`
thanks for your help.

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).

The issue tracker is for issues with Scrapy itself, not for support.
