### ISSUE TITLE
[middlewares][httperror] overriding hides all exceptions

### ISSUE THREAD

**Issue by apalala** [scrapy/scrapy#5088]
A copy&paste of `scrapy.spidermiddlewares.httperror.HttpErrorMiddleware` with modifications to `process_spider_exception()` works as expected (an `Item` is yielded for each HTTP error). 

```python
 SPIDER_MIDDLEWARES = {
    'scrapy.spidermiddlewares.httperror.HttpErrorMiddleware': None,
    'mycode.spiders.middlewares.httperror.MyHttpErrorMiddleware': 50,
```

Inheriting from `HttpErrorMiddleware` and overriding the method of interest hides _all_ exceptions.

```python
class MyHttpErrorMiddleware(scrapy.spidermiddlewares.httperror.HttpErrorMiddleware):
    def process_spider_exception(self, response, exception, spider):
        if isinstance(exception, HttpError):
            super().process_spider_exception(response, exception, spider)
            return [self.create_error_item(response)]
```

**Comment by elacuesta** [comment]
Hey Juancarlo, could you elaborate? I'm getting what I think is the expected result from the following:

```python
import scrapy
from scrapy.spidermiddlewares.httperror import HttpErrorMiddleware

class MyHttpErrorMiddleware(HttpErrorMiddleware):
    def process_spider_exception(self, response, exception, spider):
        if isinstance(exception, ZeroDivisionError):
            super().process_spider_exception(response, exception, spider)
            return [{"from": "process_spider_exception"}]

class TestSpider(scrapy.Spider):
    name = "test"
    custom_settings = {
        "SPIDER_MIDDLEWARES": {
            "scrapy.spidermiddlewares.httperror.HttpErrorMiddleware": None,
            MyHttpErrorMiddleware: 50,
        },
    }

    def start_requests(self):
        yield scrapy.Request("https://example.org", callback=self.parse_org)
        yield scrapy.Request("https://example.com", callback=self.parse_com)

    def parse_org(self, response):
        raise RuntimeError("nope")

    def parse_com(self, response):
        1 / 0
```

```
2021-04-08 01:02:27 [scrapy.middleware] INFO: Enabled spider middlewares:
[<class 'spider_mware.MyHttpErrorMiddleware'>,
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
(...)
2021-04-08 01:02:27 [scrapy.core.engine] INFO: Spider opened
2021-04-08 01:02:27 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2021-04-08 01:02:27 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2021-04-08 01:02:27 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://example.com> (referer: None)
2021-04-08 01:02:27 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://example.org> (referer: None)
2021-04-08 01:02:27 [scrapy.core.scraper] DEBUG: Scraped from <200 https://example.com>
{'from': 'process_spider_exception'}
2021-04-08 01:02:27 [scrapy.core.scraper] ERROR: Spider error processing <GET https://example.org> (referer: None)
Traceback (most recent call last):
  File "/home/eugenio/zyte/scrapy/venv-scrapy/lib/python3.8/site-packages/twisted/internet/defer.py", line 662, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/eugenio/zyte/scrapy/test-spiders/spider_mware.py", line 26, in parse_org
    raise RuntimeError("nope")
RuntimeError: nope
2021-04-08 01:02:27 [scrapy.core.engine] INFO: Closing spider (finished)
```

**Comment by AntonGsv** [comment]
@apalala 
When `request.errback` is present the `SpiderMiddleware.process_spider_exception` method is not called.

**Comment by apalala** [comment]
To reproduce the issue, the guard needs to be:

```python
    if isinstance(exception, HttpError):
```

in my tests, `ZeroDivisionError` would not show on the logs. 

```python
import scrapy
from scrapy.spidermiddlewares.httperror import HttpErrorMiddleware, HttpError

class MyHttpErrorMiddleware(HttpErrorMiddleware):
    def process_spider_exception(self, response, exception, spider):
        if isinstance(exception, HttpError):
            super().process_spider_exception(response, exception, spider)  # log the error as ignored
            return [{"from": "process_spider_exception {}".format(response.status)}]   # stop the exception handling chain
        # else:  continue the `process_spider_exception()`  chain


class TestSpider(scrapy.Spider):
    name = "test"
    custom_settings = {
        "SPIDER_MIDDLEWARES": {
            "scrapy.spidermiddlewares.httperror.HttpErrorMiddleware": None,
            MyHttpErrorMiddleware: 50,
        },
    }

    def start_requests(self):
        yield scrapy.Request("https://scrapy.org/for-o-four", callback=self.parse_org)  # add a 404 here
        yield scrapy.Request("https://example.com", callback=self.parse_com)

    def parse_org(self, response):
        raise RuntimeError("nope")

    def parse_com(self, response):
        1 / 0  # exception never logged
```

**Comment by apalala** [comment]
I cannot reproduce the issue with the above code.

Closing as it is likely that the issue was due to interactions with other code in the project.

```bash
2021-04-12 08:42:29 [scrapy.core.scraper] ERROR: Spider error processing <GET https://example.com> (referer: None)
Traceback (most recent call last):
  File "/Users/apalala/.virtualenvs/looper/lib/python3.9/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/apalala/scrapinghub/looper_insights/looper/looper/spiders/sites/xbox/he.py", line 29, in parse_com
    1 / 0  # exception never logged
ZeroDivisionError: division by zero
2021-04-12 08:42:29 [scrapy.core.engine] DEBUG: Crawled (403) <GET https://scrapy.org/for-o-four> (referer: None)
2021-04-12 08:42:29 [scrapy.spidermiddlewares.httperror] INFO: Ignoring response <403 https://scrapy.org/for-o-four>: HTTP status code is not handled or not allowed
2021-04-12 08:42:29 [scrapy.core.scraper] DEBUG: Scraped from <403 https://scrapy.org/for-o-four>
{'from': 'process_spider_exception 403'}
2021-04-12 08:42:29 [scrapy.core.engine] INFO: Closing spider (finished)
```
