### ISSUE TITLE
Second and subsequent spider runs throws up "builtins.KeyError: " 

### ISSUE THREAD

**Issue by anandmg101** [scrapy/scrapy#5121]
Hi, based on the suggestions in this SO post [https://stackoverflow.com/questions/22116493/run-a-scrapy-spider-in-a-celery-task](url) I have developed my spiders. The first time I run in a new python kernel, it works well. Next time I run it, it seems it is running twice with the following error. 3rd time it is running 3 times, so on. I have tough time figuring out what exactly is happening.

During the 2nd and subsequent runs I get this error:
Unhandled Error
Traceback (most recent call last):
  File "/home/xxxxxx/.local/share/virtualenvs/yyyyy-3i5Xwd2p/lib/python3.6/site-packages/twisted/internet/base.py", line 503, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "/home/xxxxxx/.local/share/virtualenvs/yyyyy-3i5Xwd2p/lib/python3.6/site-packages/twisted/internet/defer.py", line 339, in addCallback
    return self.addCallbacks(callback, callbackArgs=args, callbackKeywords=kw)
  File "/home/xxxxxx/.local/share/virtualenvs/yyyyy-3i5Xwd2p/lib/python3.6/site-packages/twisted/internet/defer.py", line 330, in addCallbacks
    self._runCallbacks()
  File "/home/xxxxxx/.local/share/virtualenvs/yyyyy-3i5Xwd2p/lib/python3.6/site-packages/twisted/internet/defer.py", line 662, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
--- <exception caught here> ---
  File "/home/xxxxxx/.local/share/virtualenvs/yyyyy-3i5Xwd2p/lib/python3.6/site-packages/twisted/internet/base.py", line 515, in _continueFiring
    callable(*args, **kwargs)
  File "/home/xxxxxx/.local/share/virtualenvs/yyyyy-3i5Xwd2p/lib/python3.6/site-packages/twisted/internet/base.py", line 763, in disconnectAll
    selectables = self.removeAll()
  File "/home/xxxxxx/.local/share/virtualenvs/yyyyy-3i5Xwd2p/lib/python3.6/site-packages/twisted/internet/epollreactor.py", line 199, in removeAll
    [self._selectables[fd] for fd in self._reads],
  File "/home/xxxxxx/.local/share/virtualenvs/yyyyy-3i5Xwd2p/lib/python3.6/site-packages/twisted/internet/epollreactor.py", line 199, in <listcomp>
    [self._selectables[fd] for fd in self._reads],
builtins.KeyError: 9

I have no idea what is originating this issue and how to rectify it. I tried google but I couldn't find any resources for this particular problem. Not sure which one is causing this.

**Comment by Gallaecio** [comment]
Please, use [StackOverflow](https://stackoverflow.com/tags/scrapy) to ask this type of questions. See [Getting Help](https://docs.scrapy.org/en/latest/#getting-help).
