### ISSUE TITLE
AttributeError: 'int' object has no attribute 'decode'

### ISSUE THREAD

**Issue by agolebiowska** [scrapy/scrapy#5126]
### Description

[Description of the issue]

Hi, I updated python to 3.9 and for one of my projects when running `scrapy crawl` I get this error. I am not sure if this is my fault or it's a bug. 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]
No error should appear.

**Actual behavior:** [What actually happens]
```
2021-04-30 13:58:15 [scrapy.core.scraper] ERROR: Error downloading <GET https://forum.fok.nl/?allowcookies=ACCEPTEER+ALLE+COOKIES>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.9/site-packages/scrapy/core/downloader/middleware.py", line 36, in process_request
    response = yield deferred_from_coro(method(request=request, spider=spider))
  File "/usr/local/lib/python3.9/site-packages/scrapy/downloadermiddlewares/cookies.py", line 32, in process_request
    for cookie in self._get_request_cookies(jar, request):
  File "/usr/local/lib/python3.9/site-packages/scrapy/downloadermiddlewares/cookies.py", line 109, in _get_request_cookies
    response = Response(request.url, headers={"Set-Cookie": formatted})
  File "/usr/local/lib/python3.9/site-packages/scrapy/http/response/__init__.py", line 32, in __init__
    self.headers = Headers(headers or {})
  File "/usr/local/lib/python3.9/site-packages/scrapy/http/headers.py", line 11, in __init__
    super().__init__(seq)
  File "/usr/local/lib/python3.9/site-packages/scrapy/utils/datatypes.py", line 20, in __init__
    self.update(seq)
  File "/usr/local/lib/python3.9/site-packages/scrapy/utils/datatypes.py", line 56, in update
    super().update(iseq)
  File "/usr/local/lib/python3.9/site-packages/scrapy/utils/datatypes.py", line 55, in <genexpr>
    iseq = ((self.normkey(k), self.normvalue(v)) for k, v in seq)
  File "/usr/local/lib/python3.9/site-packages/scrapy/http/headers.py", line 26, in normvalue
    return [self._tobytes(x) for x in value]
  File "/usr/local/lib/python3.9/site-packages/scrapy/http/headers.py", line 26, in <listcomp>
    return [self._tobytes(x) for x in value]
  File "/usr/local/lib/python3.9/site-packages/scrapy/downloadermiddlewares/cookies.py", line 108, in <genexpr>
    formatted = filter(None, (self._format_cookie(c, request) for c in cookies))
  File "/usr/local/lib/python3.9/site-packages/scrapy/downloadermiddlewares/cookies.py", line 87, in _format_cookie
    decoded[key] = cookie[key].decode("utf8")
AttributeError: 'int' object has no attribute 'decode'
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

```
Scrapy       : 2.5.0
lxml         : 4.6.3.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 18.9.0
Python       : 3.9.4 (default, Apr 15 2021, 04:50:04) - [GCC 10.2.1 20201203]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1k  25 Mar 2021)
cryptography : 3.2
Platform     : Linux-3.10.0-1160.21.1.el7.x86_64-x86_64-with
```

**Comment by wRAR** [comment]
This looks like a problem with your code that sets cookies but if you think it's a problem in Scrapy you need to provide a minimal reproducible example of it.

**Comment by agolebiowska** [comment]
Sorry for this vague question, it is my first contact with scrapy, and thank you because I think your response actually helped... I just changed this `scrapy.Request(response.url, cookies={ 'allowallcookies': 1}, callback=self.parse_forum)` to `scrapy.Request(response.url, cookies={ 'allowallcookies': '1'}, callback=self.parse_forum)`

**Comment by wRAR** [comment]
That's what I've meant, yes.
