### ISSUE TITLE
Scrapy with proxy not working.

### ISSUE THREAD

**Issue by chronicom** [scrapy/scrapy#5149]
### Description

Scrapy request with proxy not working while Requests from standard python works.

### Steps to Reproduce
Settings.py
DOWNLOADER_MIDDLEWARES = {
   'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware': 750, 
   'test.middlewares.TestDownloaderMiddlewareProxy': 720, 
}

middlewares.py
TestDownloaderMiddlewareProxy class

def process_request(self, request, spider):
      request.meta["proxy"] = 'http://83.168.86.170:8090/'

test.py
class test(scrapy.Spider):
         start_urls = [
           "https://www.google.com",
         ]
def parse(self, response):
      print(response.text)

**Expected behavior:** [What you expect to happen]
<!doctype html><html .....................................................</body></html>

**Actual behavior:** [What actually happens]
Waiting for response forever if download time out is not set. 

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time
### Versions

Scrapy       : 2.5.0
lxml         : 4.6.3.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 21.2.0
Python       : 3.6.9 (default, Jan 26 2021, 15:33:00) - [GCC 8.4.0]
pyOpenSSL    : 20.0.1 (OpenSSL 1.1.1k  25 Mar 2021)
cryptography : 3.4.7
Platform     : Linux-5.4.0-73-generic-x86_64-with-Ubuntu-18.04-bionic

### Additional context
Using python standard Requests

proxies = {'http':'http://83.168.86.170:8090/'}
print(requests.get("https://www.google.com", proxies=proxies).text)

No problem at all.

**Comment by wRAR** [comment]
Set the USER_AGENT to some browser UA value.

Please also use https://stackoverflow.com/ for questions about your code next time.

**Comment by chronicom** [comment]
> Set the USER_AGENT to some browser UA value.
> 
> Please also use https://stackoverflow.com/ for questions about your code next time.

I did set the UA to my browser UA value. I dont think it is problem with my code.

**Comment by wRAR** [comment]
Ignoring the fact that you are comparing different things (as your requests code doesn't actually use the proxy), your Scrapy code works for me after the change I mentioned and it works for simpler websites even without that change. So no, it's not a Scrapy problem.

**Comment by chronicom** [comment]
> Ignoring the fact that you are comparing different things (as your requests code doesn't actually use the proxy), your Scrapy code works for me after the change I mentioned and it works for simpler websites even without that change. So no, it's not a Scrapy problem.

If I issue a request to whatismyipaddress.com with code below 
```
proxies = {'https':'http://65.0.185.227:80'}
print(requests.get("https://whatismyipaddress.com/", proxies=proxies).text)
```
I get 
```
<html><head><script async src='/cdn-cgi/bm/cv/669835187/api.js'></script></head><body>
<div class="cf-error-details cf-error-1020">
<h1>Access denied</h1>
<p>This website is using a security service to protect itself from online attacks.</p>
<ul class="cferror_details">
<li>Ray ID: 64ffc853396d31f3</li>
<li>Timestamp: 2021-05-15 22:25:30 UTC</li>
<li>Your IP address: 65.0.185.227</li>
<li class="XXX_no_wrap_overflow_hidden">Requested URL: whatismyipaddress.com/ </li>
```
Meaning that Requests indeed used the proxy.

With scrapy I get
```
2021-05-15 22:25:48 [scrapy.utils.log] INFO: Scrapy 2.5.0 started (bot: test)
2021-05-15 22:25:48 [scrapy.utils.log] INFO: Versions: lxml 4.6.3.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 21.2.0, Python 3.6.9 (default, Jan 26 2021, 15:33:00) - [GCC 8.4.0], pyOpenSSL 20.0.1 (OpenSSL 1.1.1k  25 Mar 2021), cryptography 3.4.7, Platform Linux-5.4.0-73-generic-x86_64-with-Ubuntu-18.04-bionic
2021-05-15 22:25:48 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.epollreactor.EPollReactor
2021-05-15 22:25:48 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'test',
 'DOWNLOAD_DELAY': 2,
 'DOWNLOAD_TIMEOUT': 10,
 'NEWSPIDER_MODULE': 'test.spiders',
 'RETRY_TIMES': 10,
 'ROBOTSTXT_OBEY': True,
 'SPIDER_MODULES': ['test.spiders']}
2021-05-15 22:25:48 [scrapy.extensions.telnet] INFO: Telnet Password: f21d880697770a10
2021-05-15 22:25:48 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2021-05-15 22:25:48 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'test.middlewares.testDownloaderMiddlewareUserAgent',
 'test.middlewares.testDownloaderMiddlewareProxy',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2021-05-15 22:25:48 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2021-05-15 22:25:48 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2021-05-15 22:25:48 [scrapy.core.engine] INFO: Spider opened
2021-05-15 22:25:48 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2021-05-15 22:25:48 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2021-05-15 22:25:48 [test] INFO: Proxy http://65.0.185.227:80 used.
2021-05-15 22:25:48 [test] INFO: Request header {b'Accept': [b'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'], b'Accept-Language': [b'en-US,en'], b'Accept-Encoding': [b'gzip, deflate, br'], b'User-Agent': [b'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.63'], b'Connection': [b'keep-alive'], b'Cache-Control': [b'max-age=0'], b'Sec-Fetch-Dest': [b'document'], b'Sec-Fetch-Mode': [b'navigate'], b'Sec-Fetch-Site': [b'cross-site'], b'Sec-Fetch-User': [b'?1'], b'Upgrade-Insecure-Requests': [b'1']}
2021-05-15 22:25:49 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://whatismyipaddress.com/robots.txt> (referer: None)
2021-05-15 22:25:49 [scrapy.robotstxt] WARNING: Failure while parsing robots.txt. File either contains garbage or is in an encoding other than UTF-8, treating it as an empty file.
Traceback (most recent call last):
  File "/home/ubuntu/venv/scrapy/lib/python3.6/site-packages/twisted/internet/defer.py", line 1445, in _inlineCallbacks
    result = current_context.run(g.send, result)
  File "/home/ubuntu/venv/scrapy/lib/python3.6/site-packages/twisted/internet/defer.py", line 47, in run
    return f(*args, **kwargs)
StopIteration: <200 https://whatismyipaddress.com/robots.txt>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/venv/scrapy/lib/python3.6/site-packages/scrapy/robotstxt.py", line 16, in decode_robotstxt
    robotstxt_body = robotstxt_body.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 7: invalid start byte
2021-05-15 22:25:49 [test] INFO: Proxy http://65.0.185.227:80 used.
2021-05-15 22:25:49 [test] INFO: Request header {b'Accept': [b'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'], b'Accept-Language': [b'en-US,en'], b'Accept-Encoding': [b'gzip, deflate, br'], b'User-Agent': [b'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.63'], b'Connection': [b'keep-alive'], b'Cache-Control': [b'max-age=0'], b'Sec-Fetch-Dest': [b'document'], b'Sec-Fetch-Mode': [b'navigate'], b'Sec-Fetch-Site': [b'cross-site'], b'Sec-Fetch-User': [b'?1'], b'Upgrade-Insecure-Requests': [b'1']}
2021-05-15 22:25:51 [scrapy.core.engine] DEBUG: Crawled (403) <GET https://whatismyipaddress.com/> (referer: None)
2021-05-15 22:25:51 [scrapy.spidermiddlewares.httperror] INFO: Ignoring response <403 https://whatismyipaddress.com/>: HTTP status code is not handled or not allowed
2021-05-15 22:25:51 [scrapy.core.engine] INFO: Closing spider (finished)
2021-05-15 22:25:51 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 1146,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 7501,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 1,
 'downloader/response_status_count/403': 1,
 'elapsed_time_seconds': 2.441141,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2021, 5, 15, 22, 25, 51, 215561),
 'httpcompression/response_bytes': 6063,
 'httpcompression/response_count': 2,
 'httperror/response_ignored_count': 1,
 'httperror/response_ignored_status_count/403': 1,
 'log_count/DEBUG': 2,
 'log_count/INFO': 15,
 'log_count/WARNING': 1,
 'memusage/max': 57962496,
 'memusage/startup': 57962496,
 'response_received_count': 2,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2021, 5, 15, 22, 25, 48, 774420)}
2021-05-15 22:25:51 [scrapy.core.engine] INFO: Spider closed (finished)
```

**Comment by chronicom** [comment]
Reason that the proxy has been changed is that I am using a rotating proxy API to fetch proxies. And these proxies normally last only a couple of hours.

**Comment by wRAR** [comment]
That first response is most likely a 403 as well. So the behavior, again, matches.

Please direct your further comments to https://stackoverflow.com/ or similar.
