### ISSUE TITLE
Doctest failure

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapy#5273]
Merging #5256 introduced a doctest failure in `docs/intro/tutorial.rst`:

```
Expected:
    Traceback (most recent call last):
    File "<console>", line 1, in <module>
    ...
    IndexError: list index out of range
Got:
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/doctest.py", line 1337, in __run
        compileflags, 1), test.globs)
      File "<doctest None[0]>", line 1, in <module>
      File "/home/runner/work/scrapy/scrapy/.tox/py/lib/python3.7/site-packages/parsel/selector.py", line 70, in __getitem__
        o = super(SelectorList, self).__getitem__(pos)
    IndexError: list index out of range
```

**Comment by Gallaecio** [comment]
I think we just need to remove the `File "<console>", line 1, in <module>` line from the documentation, as it does not (cannot) match the actual output.
