### ISSUE TITLE
Error when start Scrapy, but gone later

### ISSUE THREAD

**Issue by wilkice** [scrapy/scrapy#5311]
### Description

When start crawl by using `Scrapy crawl <spider name>`, some error happens but later it never shows again. From the error message, it seems that `request` object is not exists, so `request.dont_filter` and `request.meta` fails. But the error doesn't appear later.
> have tried serval times, the errors keeps appear first and later it's gone
```log
2021-11-05 17:48:01 [scrapy.utils.log] INFO: Scrapy 2.5.0 started (bot: match_info)
2021-11-05 17:48:01 [scrapy.utils.log] INFO: Versions: lxml 4.6.3.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 21.7.0, Python 3.7.6 (default, Jan  8 2020, 19:59:22) - [GCC 7.3.0], pyOpenSSL 19.1.0 (OpenSSL 1.1.1k  25 Mar 2021), cryptography 2.8, Platform Linux-3.10.0-1160.25.1.el7.x86_64-x86_64-with-redhat-7.4-Maipo
2021-11-05 17:48:01 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'match_info',
 'CONCURRENT_REQUESTS': 5,
 'CONCURRENT_REQUESTS_PER_IP': 16,
 'DOWNLOAD_DELAY': 0.2,
 'LOG_FILE': 'match_info.log',
 'LOG_LEVEL': 'INFO',
 'NEWSPIDER_MODULE': 'match_info.spiders',
 'SPIDER_MODULES': ['match_info.spiders']}
2021-11-05 17:48:01 [scrapy.extensions.telnet] INFO: Telnet Password: effa3e3eab8fec8e
2021-11-05 17:48:01 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats']
2021-11-05 17:48:01 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'match_info.middlewares.RandomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2021-11-05 17:48:01 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2021-11-05 17:48:01 [scrapy.middleware] INFO: Enabled item pipelines:
['match_info.pipelines.MysqlPipeline']
2021-11-05 17:48:01 [scrapy.core.engine] INFO: Spider opened
2021-11-05 17:48:01 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2021-11-05 17:48:01 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2021-11-05 17:48:01 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method RefererMiddleware.request_scheduled of <scrapy.spidermiddlewares.referer.RefererMiddleware object at 0x7ff6508a2fd0>>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/utils/signal.py", line 32, in send_catch_log
    response = robustApply(receiver, signal=signal, sender=sender, *arguments, **named)
  File "/root/miniconda3/lib/python3.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/spidermiddlewares/referer.py", line 346, in request_scheduled
    redirected_urls = request.meta.get('redirect_urls', [])
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/item.py", line 108, in __getattr__
    raise AttributeError(name)
AttributeError: meta
2021-11-05 17:48:01 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/commands/crawl.py", line 27, in run
    self.crawler_process.start()
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/crawler.py", line 327, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "/root/miniconda3/lib/python3.7/site-packages/twisted/internet/base.py", line 1318, in run
    self.mainLoop()
  File "/root/miniconda3/lib/python3.7/site-packages/twisted/internet/base.py", line 1328, in mainLoop
    reactorBaseSelf.runUntilCurrent()
--- <exception caught here> ---
  File "/root/miniconda3/lib/python3.7/site-packages/twisted/internet/base.py", line 994, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/utils/reactor.py", line 50, in __call__
    return self._func(*self._a, **self._kw)
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/core/engine.py", line 137, in _next_request
    self.crawl(request, spider)
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/core/engine.py", line 218, in crawl
    self.schedule(request, spider)
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/core/engine.py", line 223, in schedule
    if not self.slot.scheduler.enqueue_request(request):
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/core/scheduler.py", line 78, in enqueue_request
    if not request.dont_filter and self.df.request_seen(request):
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/item.py", line 108, in __getattr__
    raise AttributeError(name)
builtins.AttributeError: dont_filter

2021-11-05 17:48:06 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method RefererMiddleware.request_scheduled of <scrapy.spidermiddlewares.referer.RefererMiddleware object at 0x7ff6508a2fd0>>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/utils/signal.py", line 32, in send_catch_log
    response = robustApply(receiver, signal=signal, sender=sender, *arguments, **named)
  File "/root/miniconda3/lib/python3.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/spidermiddlewares/referer.py", line 346, in request_scheduled
    redirected_urls = request.meta.get('redirect_urls', [])
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/item.py", line 108, in __getattr__
    raise AttributeError(name)
AttributeError: meta
2021-11-05 17:48:06 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/commands/crawl.py", line 27, in run
    self.crawler_process.start()
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/crawler.py", line 327, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "/root/miniconda3/lib/python3.7/site-packages/twisted/internet/base.py", line 1318, in run
    self.mainLoop()
  File "/root/miniconda3/lib/python3.7/site-packages/twisted/internet/base.py", line 1328, in mainLoop
    reactorBaseSelf.runUntilCurrent()
--- <exception caught here> ---
  File "/root/miniconda3/lib/python3.7/site-packages/twisted/internet/base.py", line 994, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/utils/reactor.py", line 50, in __call__
    return self._func(*self._a, **self._kw)
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/core/engine.py", line 137, in _next_request
    self.crawl(request, spider)
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/core/engine.py", line 218, in crawl
    self.schedule(request, spider)
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/core/engine.py", line 223, in schedule
    if not self.slot.scheduler.enqueue_request(request):
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/core/scheduler.py", line 78, in enqueue_request
    if not request.dont_filter and self.df.request_seen(request):
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/item.py", line 108, in __getattr__
    raise AttributeError(name)
builtins.AttributeError: dont_filter

2021-11-05 17:48:06 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method RefererMiddleware.request_scheduled of <scrapy.spidermiddlewares.referer.RefererMiddleware object at 0x7ff6508a2fd0>>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/utils/signal.py", line 32, in send_catch_log
    response = robustApply(receiver, signal=signal, sender=sender, *arguments, **named)
  File "/root/miniconda3/lib/python3.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/spidermiddlewares/referer.py", line 346, in request_scheduled
    redirected_urls = request.meta.get('redirect_urls', [])
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/item.py", line 108, in __getattr__
    raise AttributeError(name)
AttributeError: meta
2021-11-05 17:48:06 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/commands/crawl.py", line 27, in run
    self.crawler_process.start()
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/crawler.py", line 327, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "/root/miniconda3/lib/python3.7/site-packages/twisted/internet/base.py", line 1318, in run
    self.mainLoop()
  File "/root/miniconda3/lib/python3.7/site-packages/twisted/internet/base.py", line 1328, in mainLoop
    reactorBaseSelf.runUntilCurrent()
--- <exception caught here> ---
  File "/root/miniconda3/lib/python3.7/site-packages/twisted/internet/base.py", line 994, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/utils/reactor.py", line 50, in __call__
    return self._func(*self._a, **self._kw)
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/core/engine.py", line 137, in _next_request
    self.crawl(request, spider)
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/core/engine.py", line 218, in crawl
    self.schedule(request, spider)
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/core/engine.py", line 223, in schedule
    if not self.slot.scheduler.enqueue_request(request):
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/core/scheduler.py", line 78, in enqueue_request
    if not request.dont_filter and self.df.request_seen(request):
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/item.py", line 108, in __getattr__
    raise AttributeError(name)
builtins.AttributeError: dont_filter

2021-11-05 17:48:06 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method RefererMiddleware.request_scheduled of <scrapy.spidermiddlewares.referer.RefererMiddleware object at 0x7ff6508a2fd0>>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/utils/signal.py", line 32, in send_catch_log
    response = robustApply(receiver, signal=signal, sender=sender, *arguments, **named)
  File "/root/miniconda3/lib/python3.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/spidermiddlewares/referer.py", line 346, in request_scheduled
    redirected_urls = request.meta.get('redirect_urls', [])
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/item.py", line 108, in __getattr__
    raise AttributeError(name)
AttributeError: meta
2021-11-05 17:48:06 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/commands/crawl.py", line 27, in run
    self.crawler_process.start()
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/crawler.py", line 327, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "/root/miniconda3/lib/python3.7/site-packages/twisted/internet/base.py", line 1318, in run
    self.mainLoop()
  File "/root/miniconda3/lib/python3.7/site-packages/twisted/internet/base.py", line 1328, in mainLoop
    reactorBaseSelf.runUntilCurrent()
--- <exception caught here> ---
  File "/root/miniconda3/lib/python3.7/site-packages/twisted/internet/base.py", line 994, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/utils/reactor.py", line 50, in __call__
    return self._func(*self._a, **self._kw)
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/core/engine.py", line 137, in _next_request
    self.crawl(request, spider)
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/core/engine.py", line 218, in crawl
    self.schedule(request, spider)
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/core/engine.py", line 223, in schedule
    if not self.slot.scheduler.enqueue_request(request):
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/core/scheduler.py", line 78, in enqueue_request
    if not request.dont_filter and self.df.request_seen(request):
  File "/root/miniconda3/lib/python3.7/site-packages/scrapy/item.py", line 108, in __getattr__
    raise AttributeError(name)
builtins.AttributeError: dont_filter

2021-11-05 17:49:01 [scrapy.extensions.logstats] INFO: Crawled 202 pages (at 202 pages/min), scraped 7348 items (at 7348 items/min)
2021-11-05 17:50:01 [scrapy.extensions.logstats] INFO: Crawled 442 pages (at 240 pages/min), scraped 21184 items (at 13836 items/min)
2021-11-05 17:51:01 [scrapy.extensions.logstats] INFO: Crawled 656 pages (at 214 pages/min), scraped 44102 items (at 22918 items/min)
2021-11-05 17:52:01 [scrapy.extensions.logstats] INFO: Crawled 883 pages (at 227 pages/min), scraped 68266 items (at 24164 items/min)
2021-11-05 17:53:01 [scrapy.extensions.logstats] INFO: Crawled 1099 pages (at 216 pages/min), scraped 92382 items (at 24116 items/min)
2021-11-05 17:54:01 [scrapy.extensions.logstats] INFO: Crawled 1316 pages (at 217 pages/min), scraped 116090 items (at 23708 items/min)
2021-11-05 17:55:01 [scrapy.extensions.logstats] INFO: Crawled 1530 pages (at 214 pages/min), scraped 138080 items (at 21990 items/min)
2021-11-05 17:56:01 [scrapy.extensions.logstats] INFO: Crawled 1744 pages (at 214 pages/min), scraped 160256 items (at 22176 items/min)
2021-11-05 17:57:01 [scrapy.extensions.logstats] INFO: Crawled 1948 pages (at 204 pages/min), scraped 185015 items (at 24759 items/min)
2021-11-05 17:58:01 [scrapy.extensions.logstats] INFO: Crawled 2164 pages (at 216 pages/min), scraped 206650 items (at 21635 items/min)
2021-11-05 17:59:01 [scrapy.extensions.logstats] INFO: Crawled 2362 pages (at 198 pages/min), scraped 231709 items (at 25059 items/min)
2021-11-05 18:00:01 [scrapy.extensions.logstats] INFO: Crawled 2579 pages (at 217 pages/min), scraped 250355 items (at 18646 items/min)
2021-11-05 18:01:01 [scrapy.extensions.logstats] INFO: Crawled 2791 pages (at 212 pages/min), scraped 273235 items (at 22880 items/min)
2021-11-05 18:02:01 [scrapy.extensions.logstats] INFO: Crawled 3004 pages (at 213 pages/min), scraped 296134 items (at 22899 items/min)
```
### Steps to Reproduce

1. `scrapy crawl <spider name>`

**Expected behavior:**
No errors

**Actual behavior:** 
Errors appears first, but later it never appears again.

**Reproduces how often:**
100% of 5 tries.
### Versions
```
Scrapy       : 2.5.0
lxml         : 4.6.3.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 21.7.0
Python       : 3.7.6 (default, Jan  8 2020, 19:59:22) - [GCC 7.3.0]
pyOpenSSL    : 19.1.0 (OpenSSL 1.1.1k  25 Mar 2021)
cryptography : 2.8
Platform     : Linux-3.10.0-1160.25.1.el7.x86_64-x86_64-with-redhat-7.4-Maipo
```

**Comment by Gallaecio** [comment]
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by wilkice** [comment]
Just now, I find this two line appears  in log after 28 min of start

```
2021-11-05 18:10:00 [scrapy.utils.log] INFO: Scrapy 2.5.0 started (bot: match_info)
2021-11-05 18:10:00 [scrapy.utils.log] INFO: Versions: lxml 4.6.3.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 21.7.0, Python 3.7.6 (default, Jan  8 2020, 19:59:22) - [GCC 7.3.0], pyOpenSSL 19.1.0 (OpenSSL 1.1.1k  25 Mar 2021), cryptography 2.8, Platform Linux-3.10.0-1160.25.1.el7.x86_64-x86_64-with-redhat-7.4-Maipo
```
Log
```
2021-11-05 17:49:01 [scrapy.extensions.logstats] INFO: Crawled 202 pages (at 202 pages/min), scraped 7348 items (at 7348 items/min)
2021-11-05 17:50:01 [scrapy.extensions.logstats] INFO: Crawled 442 pages (at 240 pages/min), scraped 21184 items (at 13836 items/min)
2021-11-05 17:51:01 [scrapy.extensions.logstats] INFO: Crawled 656 pages (at 214 pages/min), scraped 44102 items (at 22918 items/min)
2021-11-05 17:52:01 [scrapy.extensions.logstats] INFO: Crawled 883 pages (at 227 pages/min), scraped 68266 items (at 24164 items/min)
2021-11-05 17:53:01 [scrapy.extensions.logstats] INFO: Crawled 1099 pages (at 216 pages/min), scraped 92382 items (at 24116 items/min)
2021-11-05 17:54:01 [scrapy.extensions.logstats] INFO: Crawled 1316 pages (at 217 pages/min), scraped 116090 items (at 23708 items/min)
2021-11-05 17:55:01 [scrapy.extensions.logstats] INFO: Crawled 1530 pages (at 214 pages/min), scraped 138080 items (at 21990 items/min)
2021-11-05 17:56:01 [scrapy.extensions.logstats] INFO: Crawled 1744 pages (at 214 pages/min), scraped 160256 items (at 22176 items/min)
2021-11-05 17:57:01 [scrapy.extensions.logstats] INFO: Crawled 1948 pages (at 204 pages/min), scraped 185015 items (at 24759 items/min)
2021-11-05 17:58:01 [scrapy.extensions.logstats] INFO: Crawled 2164 pages (at 216 pages/min), scraped 206650 items (at 21635 items/min)
2021-11-05 17:59:01 [scrapy.extensions.logstats] INFO: Crawled 2362 pages (at 198 pages/min), scraped 231709 items (at 25059 items/min)
2021-11-05 18:00:01 [scrapy.extensions.logstats] INFO: Crawled 2579 pages (at 217 pages/min), scraped 250355 items (at 18646 items/min)
2021-11-05 18:01:01 [scrapy.extensions.logstats] INFO: Crawled 2791 pages (at 212 pages/min), scraped 273235 items (at 22880 items/min)
2021-11-05 18:02:01 [scrapy.extensions.logstats] INFO: Crawled 3004 pages (at 213 pages/min), scraped 296134 items (at 22899 items/min)
2021-11-05 18:03:01 [scrapy.extensions.logstats] INFO: Crawled 3212 pages (at 208 pages/min), scraped 318652 items (at 22518 items/min)
2021-11-05 18:04:01 [scrapy.extensions.logstats] INFO: Crawled 3426 pages (at 214 pages/min), scraped 341966 items (at 23314 items/min)
2021-11-05 18:05:01 [scrapy.extensions.logstats] INFO: Crawled 3618 pages (at 192 pages/min), scraped 370502 items (at 28536 items/min)
2021-11-05 18:06:01 [scrapy.extensions.logstats] INFO: Crawled 3844 pages (at 226 pages/min), scraped 389712 items (at 19210 items/min)
2021-11-05 18:07:01 [scrapy.extensions.logstats] INFO: Crawled 4056 pages (at 212 pages/min), scraped 417347 items (at 27635 items/min)
2021-11-05 18:08:01 [scrapy.extensions.logstats] INFO: Crawled 4280 pages (at 224 pages/min), scraped 438656 items (at 21309 items/min)
2021-11-05 18:09:01 [scrapy.extensions.logstats] INFO: Crawled 4519 pages (at 239 pages/min), scraped 451002 items (at 12346 items/min)
2021-11-05 18:10:00 [scrapy.utils.log] INFO: Scrapy 2.5.0 started (bot: match_info)
2021-11-05 18:10:00 [scrapy.utils.log] INFO: Versions: lxml 4.6.3.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 21.7.0, Python 3.7.6 (default, Jan  8 2020, 19:59:22) - [GCC 7.3.0], pyOpenSSL 19.1.0 (OpenSSL 1.1.1k  25 Mar 2021), cryptography 2.8, Platform Linux-3.10.0-1160.25.1.el7.x86_64-x86_64-with-redhat-7.4-Maipo
2021-11-05 18:10:01 [scrapy.extensions.logstats] INFO: Crawled 4758 pages (at 239 pages/min), scraped 456218 items (at 5216 items/min)
2021-11-05 18:11:01 [scrapy.extensions.logstats] INFO: Crawled 5003 pages (at 245 pages/min), scraped 458291 items (at 2073 items/min)
2021-11-05 18:12:01 [scrapy.extensions.logstats] INFO: Crawled 5249 pages (at 246 pages/min), scraped 459664 items (at 1373 items/min)
2021-11-05 18:13:01 [scrapy.extensions.logstats] INFO: Crawled 5442 pages (at 193 pages/min), scraped 483359 items (at 23695 items/min)
2021-11-05 18:14:01 [scrapy.extensions.logstats] INFO: Crawled 5587 pages (at 145 pages/min), scraped 512124 items (at 28765 items/min)
```

**Comment by wRAR** [comment]
That suggests a problem with your code.

**Comment by elacuesta** [comment]
Please include code to reproduce the issue, as Adrián [already requested](https://github.com/scrapy/scrapy/issues/5311#issuecomment-961777280).
From a quick look, I believe this looks similar to #5289, i.e. objects not being the expected type (the `AttributeError` message is not exactly the same, though).

**Comment by wilkice** [comment]
Thank you for your reply. I checked my code, it was caused by wrongly used `yield` in `start_requests` method. Exactly as #5289. After removed `yield`, it works.
