### ISSUE TITLE
scrapy.shell.inspect_response breaks with the asyncio reactor on ipython

### ISSUE THREAD

**Issue by elacuesta** [scrapy/scrapy#5447]
### Description

`scrapy.shell.inspect_response` does not work with the `asyncio` reactor when using the `ipython` shell

### Steps to Reproduce

1. Create a spider with the following contents:
```python
# test-spiders/inspect_response_asyncio.py
import scrapy

class InspectResponseSpider(scrapy.Spider):
    name = "inspect"
    custom_settings = {
        "TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
    }
    start_urls = ["https://example.org"]

    def parse(self, response):
        scrapy.shell.inspect_response(response, self)
```

3. Run the spider, explicitly indicating the `ipython` shell:
`SCRAPY_PYTHON_SHELL=ipython scrapy runspider test-spiders/inspect_response_asyncio.py`

**Expected behavior:** [What you expect to happen]

I'd expect a "regular" Scrapy shell session with `ipython`, like the following:
```bash
$ scrapy shell https://example.org
(...)
2022-03-12 12:51:43 [scrapy.core.engine] INFO: Spider opened
2022-03-12 12:51:43 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://example.org> (referer: None)
2022-03-12 12:51:44 [asyncio] DEBUG: Using selector: EpollSelector
[s] Available Scrapy objects:
[s]   scrapy     scrapy module (contains scrapy.Request, scrapy.Selector, etc)
[s]   crawler    <scrapy.crawler.Crawler object at 0x7f3867c30310>
[s]   item       {}
[s]   request    <GET https://example.org>
[s]   response   <200 https://example.org>
[s]   settings   <scrapy.settings.Settings object at 0x7f3867c30790>
[s]   spider     <DefaultSpider 'default' at 0x7f38673d8910>
[s] Useful shortcuts:
[s]   fetch(url[, redirect=True]) Fetch URL and update local objects (by default, redirects are followed)
[s]   fetch(req)                  Fetch a scrapy.Request and update local objects 
[s]   shelp()           Shell help (print this help)
[s]   view(response)    View response in a browser
In [1]:
```

**Actual behavior:** [What actually happens]

It breaks right after printing the banner (see the following collapsed section)
<details>
<summary>Click to expand</summary>
<p>

```
$ SCRAPY_PYTHON_SHELL=ipython scrapy runspider test-spiders/inspect_response_asyncio.py
2022-03-12 12:17:27 [scrapy.utils.log] INFO: Scrapy 2.6.1 started (bot: scrapybot)
2022-03-12 12:17:27 [scrapy.utils.log] INFO: Versions: lxml 4.7.1.0, libxml2 2.9.12, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 21.7.0, Python 3.9.6 (default, Sep  6 2021, 10:09:19) - [GCC 7.5.0], pyOpenSSL 21.0.0 (OpenSSL 1.1.1m  14 Dec 2021), cryptography 36.0.1, Platform Linux-4.15.0-163-generic-x86_64-with-glibc2.27
2022-03-12 12:17:27 [scrapy.crawler] INFO: Overridden settings:
{'EDITOR': 'nano',
 'SPIDER_LOADER_WARN_ONLY': True,
 'TWISTED_REACTOR': 'twisted.internet.asyncioreactor.AsyncioSelectorReactor'}
2022-03-12 12:17:27 [asyncio] DEBUG: Using selector: EpollSelector
2022-03-12 12:17:27 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.asyncioreactor.AsyncioSelectorReactor
2022-03-12 12:17:27 [scrapy.utils.log] DEBUG: Using asyncio event loop: asyncio.unix_events._UnixSelectorEventLoop
2022-03-12 12:17:27 [scrapy.extensions.telnet] INFO: Telnet Password: 8a930ae69eba944b
2022-03-12 12:17:27 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats']
2022-03-12 12:17:28 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2022-03-12 12:17:28 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2022-03-12 12:17:28 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2022-03-12 12:17:28 [scrapy.core.engine] INFO: Spider opened
2022-03-12 12:17:28 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2022-03-12 12:17:28 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2022-03-12 12:17:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://example.org> (referer: None)
2022-03-12 12:17:29 [asyncio] DEBUG: Using selector: EpollSelector
[s] Available Scrapy objects:
[s]   scrapy     scrapy module (contains scrapy.Request, scrapy.Selector, etc)
[s]   crawler    <scrapy.crawler.Crawler object at 0x7f3f5dd72ac0>
[s]   item       {}
[s]   request    <GET https://example.org>
[s]   response   <200 https://example.org>
[s]   settings   <scrapy.settings.Settings object at 0x7f3f5dd727c0>
[s]   spider     <InspectResponseSpider 'inspect' at 0x7f3f5da0c6d0>
[s] Useful shortcuts:
[s]   shelp()           Shell help (print this help)
[s]   view(response)    View response in a browser
2022-03-12 12:17:29 [scrapy.core.scraper] ERROR: Spider error processing <GET https://example.org> (referer: None)
Traceback (most recent call last):
  File "/home/eugenio/zyte/scrapy/venv-scrapy/lib/python3.9/site-packages/twisted/internet/defer.py", line 858, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/home/eugenio/zyte/scrapy/scrapy/spiders/__init__.py", line 67, in _parse
    return self.parse(response, **kwargs)
  File "/home/eugenio/zyte/scrapy/test-spiders/inspect_response_asyncio.py", line 12, in parse
    scrapy.shell.inspect_response(response, self)
  File "/home/eugenio/zyte/scrapy/scrapy/shell.py", line 161, in inspect_response
    Shell(spider.crawler).start(response=response, spider=spider)
  File "/home/eugenio/zyte/scrapy/scrapy/shell.py", line 75, in start
    start_python_console(self.vars, shells=shells,
  File "/home/eugenio/zyte/scrapy/scrapy/utils/console.py", line 102, in start_python_console
    shell(namespace=namespace, banner=banner)
  File "/home/eugenio/zyte/scrapy/scrapy/utils/console.py", line 24, in wrapper
    shell()
  File "/home/eugenio/zyte/scrapy/venv-scrapy/lib/python3.9/site-packages/IPython/terminal/embed.py", line 245, in __call__
    self.mainloop(
  File "/home/eugenio/zyte/scrapy/venv-scrapy/lib/python3.9/site-packages/IPython/terminal/embed.py", line 337, in mainloop
    self.interact()
  File "/home/eugenio/zyte/scrapy/venv-scrapy/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 638, in interact
    code = self.prompt_for_code()
  File "/home/eugenio/zyte/scrapy/venv-scrapy/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 576, in prompt_for_code
    text = self.pt_app.prompt(
  File "/home/eugenio/zyte/scrapy/venv-scrapy/lib/python3.9/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1033, in prompt
    return self.app.run(
  File "/home/eugenio/zyte/scrapy/venv-scrapy/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 937, in run
    return loop.run_until_complete(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 618, in run_until_complete
    self._check_running()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 578, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
2022-03-12 12:17:29 [py.warnings] WARNING: /home/eugenio/zyte/scrapy/venv-scrapy/lib/python3.9/site-packages/twisted/internet/defer.py:858: RuntimeWarning: coroutine 'Application.run_async' was never awaited
  current.result = callback(  # type: ignore[misc]

2022-03-12 12:17:29 [scrapy.core.engine] INFO: Closing spider (finished)
2022-03-12 12:17:29 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 211,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 1022,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 1.227345,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2022, 3, 12, 15, 17, 29, 364888),
 'httpcompression/response_bytes': 1256,
 'httpcompression/response_count': 1,
 'log_count/DEBUG': 5,
 'log_count/ERROR': 1,
 'log_count/INFO': 10,
 'log_count/WARNING': 1,
 'memusage/max': 61014016,
 'memusage/startup': 61014016,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'spider_exceptions/RuntimeError': 1,
 'start_time': datetime.datetime(2022, 3, 12, 15, 17, 28, 137543)}
2022-03-12 12:17:29 [scrapy.core.engine] INFO: Spider closed (finished)
```

</p>

</details>

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% of the time

### Versions

```
Scrapy       : 2.6.1
lxml         : 4.7.1.0
libxml2      : 2.9.12
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 21.7.0
Python       : 3.9.6 (default, Sep  6 2021, 10:09:19) - [GCC 7.5.0]
pyOpenSSL    : 21.0.0 (OpenSSL 1.1.1m  14 Dec 2021)
cryptography : 36.0.1
Platform     : Linux-4.15.0-163-generic-x86_64-with-glibc2.27
```

### Additional context

It all works correctly with:
* the `shell` command, i.e. `SCRAPY_PYTHON_SHELL=ipython scrapy shell https://example.org`
* the `python` interpreter, i.e. `SCRAPY_PYTHON_SHELL=python scrapy runspider test-spiders/inspect_response_asyncio.py`

Given the traceback and the fact that it works correctly with the `python` interpreter, there's a chance this is actually an upstream with `ipython` or `prompt_toolkit`. I'm posting here before further research in case someone can think of a solution in the Scrapy side.

**Comment by wRAR** [comment]
I did some investigation and this looks like a valid problem with embedding IPython (or other things) into an app that already runs an asyncio loop. One option seems to be https://pypi.org/project/nest-asyncio/. There may be better options though, that would allow integrating IPython into the existing loop. I had a quick look at the `prompt_toolkit` code that runs `loop.run_until_complete` but it doesn't look like it supports running inside an existing *already running* loop. Also, https://ipython.readthedocs.io/en/stable/interactive/autoawait.html suggests that the IPython asyncio integration can be turned off, I haven't checked if that helps.

**Comment by Laerte** [comment]
An workaround that we could do is do add `nest-asyncio` package as dependency and call before starting the scrapy python shell if is `ipython`:

```patch
diff --git a/scrapy/shell.py b/scrapy/shell.py
index bb3b1461..3f151460 100644
--- a/scrapy/shell.py
+++ b/scrapy/shell.py
@@ -63,6 +63,9 @@ class Shell:
             cfg = get_config()
             section, option = "settings", "shell"
             env = os.environ.get("SCRAPY_PYTHON_SHELL")
+            if env == "ipython":
+                import nest_asyncio
+                nest_asyncio.apply()
             shells = []
             if env:
                 shells += env.strip().lower().split(",")

```

With this patch i managed to sucessfully run:
```
(venv) ➜  scrapy git:(master) ✗ SCRAPY_PYTHON_SHELL=ipython scrapy runspider test-spiders/inspect_response_asyncio.py
2023-04-13 21:22:23 [scrapy.utils.log] INFO: Scrapy 2.8.0 started (bot: scrapybot)
2023-04-13 21:22:23 [scrapy.utils.log] INFO: Versions: lxml 4.9.2.0, libxml2 2.9.14, cssselect 1.2.0, parsel 1.7.0, w3lib 2.1.1, Twisted 22.10.0, Python 3.10.6 (main, Feb 25 2023, 00:35:30) [GCC 11.3.0], pyOpenSSL 23.1.1 (OpenSSL 3.1.0 14 Mar 2023), cryptography 40.0.1, Platform Linux-5.19.0-38-generic-x86_64-with-glibc2.35
2023-04-13 21:22:23 [scrapy.crawler] INFO: Overridden settings:
{'SPIDER_LOADER_WARN_ONLY': True,
 'TWISTED_REACTOR': 'twisted.internet.asyncioreactor.AsyncioSelectorReactor'}
2023-04-13 21:22:23 [py.warnings] WARNING: /home/laerte/Projetos/scrapy/scrapy/utils/request.py:232: ScrapyDeprecationWarning: '2.6' is a deprecated value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting.

It is also the default value. In other words, it is normal to get this warning if you have not defined a value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting. This is so for backward compatibility reasons, but it will change in a future version of Scrapy.

See the documentation of the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting for information on how to handle this deprecation.
  return cls(crawler)

2023-04-13 21:22:23 [asyncio] DEBUG: Using selector: EpollSelector
2023-04-13 21:22:23 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.asyncioreactor.AsyncioSelectorReactor
2023-04-13 21:22:23 [scrapy.utils.log] DEBUG: Using asyncio event loop: asyncio.unix_events._UnixSelectorEventLoop
2023-04-13 21:22:23 [scrapy.extensions.telnet] INFO: Telnet Password: 8ddc90318fe018a7
2023-04-13 21:22:23 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats']
2023-04-13 21:22:24 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2023-04-13 21:22:24 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2023-04-13 21:22:24 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2023-04-13 21:22:24 [scrapy.core.engine] INFO: Spider opened
2023-04-13 21:22:24 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2023-04-13 21:22:24 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2023-04-13 21:22:25 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://example.org> (referer: None)
2023-04-13 21:22:25 [asyncio] DEBUG: Using selector: EpollSelector
[s] Available Scrapy objects:
[s]   scrapy     scrapy module (contains scrapy.Request, scrapy.Selector, etc)
[s]   crawler    <scrapy.crawler.Crawler object at 0x7f705235b340>
[s]   item       {}
[s]   request    <GET https://example.org>
[s]   response   <200 https://example.org>
[s]   settings   <scrapy.settings.Settings object at 0x7f705235b490>
[s]   spider     <InspectResponseSpider 'inspect' at 0x7f70522a4820>
[s] Useful shortcuts:
[s]   shelp()           Shell help (print this help)
[s]   view(response)    View response in a browser
In [1]: 
```

**Comment by wRAR** [comment]
It's god news that `nest_asyncio` helps! I don't think we should add it to deps or install it from the code though, so we should add an import attempt and maybe some docs (not sure how visible would that docs be though).

**Comment by Laerte** [comment]
@wRAR Yeah, still have the `ModuleNotFoundError` exception handling and maybe emit a log about this known issue?

**Comment by wRAR** [comment]
Yeah. But I think we need to only do this if is_asyncio_reactor_installed().

**Comment by Laerte** [comment]
@wRAR Doing more tests i figure out that this handling should be on console instead of shell (since we have a fallback logic to try some shells before use the default one from python). What you think?

```patch
diff --git a/scrapy/utils/console.py b/scrapy/utils/console.py
index 100f040b..3d0c766a 100644
--- a/scrapy/utils/console.py
+++ b/scrapy/utils/console.py
@@ -1,4 +1,9 @@
 from functools import wraps
+from logging import getLogger
+
+from scrapy.utils.reactor import is_asyncio_reactor_installed
+
+logger = getLogger(__name__)
 
 
 def _embed_ipython_shell(namespace={}, banner=""):
@@ -13,6 +18,18 @@ def _embed_ipython_shell(namespace={}, banner=""):
     @wraps(_embed_ipython_shell)
     def wrapper(namespace=namespace, banner=""):
         config = load_default_config()
+        if is_asyncio_reactor_installed():
+            try:
+                import nest_asyncio
+
+                nest_asyncio.apply()
+            except ModuleNotFoundError:
+                logger.error(
+                    "nest-asyncio package is required if you want to use "
+                    "ipython as shell with asyncio reactor, this is a known "
+                    "issue: (https://github.com/scrapy/scrapy/issues/5447)"
+                )
+                return
         # Always use .instance() to ensure _instance propagation to all parents
         # this is needed for <TAB> completion works well for new imports
         # and clear the instance to always have the fresh env
```

**Comment by auxsvr** [comment]
I'm currently using the asyncio reactor with ipython as scrapy shell without `nest-asyncio`, but it's tricky. The main issue is that the shell runs in a thread other than the thread the reactor is running in, which means that one should use `threads.blockingCallFromThread` to execute code, otherwise the event loop will block or crash.
