### ISSUE TITLE
i need v1.6 and it isn't working

### ISSUE THREAD

**Issue by harold980226** [scrapy/scrapy#5456]
i run benchmark or any feature and it doesnt work.

**Comment by harold980226** [comment]
(virtual) C:\Users\Harold>scrapy bench
2022-03-21 14:51:48 [scrapy.utils.log] INFO: Scrapy 1.6.0 started (bot: scrapybot)
2022-03-21 14:51:48 [scrapy.utils.log] INFO: Versions: lxml 4.8.0.0, libxml2 2.9.12, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 22.2.0, Python 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)], pyOpenSSL 22.0.0 (OpenSSL 1.1.1l  24 Aug 2021), cryptography 36.0.2, Platform Windows-10-10.0.19041-SP0
2022-03-21 14:51:49 [scrapy.crawler] INFO: Overridden settings: {'CLOSESPIDER_TIMEOUT': 10, 'LOGSTATS_INTERVAL': 1, 'LOG_LEVEL': 'INFO'}
2022-03-21 14:51:49 [scrapy.extensions.telnet] INFO: Telnet Password: 547dded994cd4da3
2022-03-21 14:51:49 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.closespider.CloseSpider',
 'scrapy.extensions.logstats.LogStats']
2022-03-21 14:51:49 [scrapy.core.downloader.handlers] ERROR: Loading "scrapy.core.downloader.handlers.http.HTTPDownloadHandler" for scheme "http"
Traceback (most recent call last):
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\core\downloader\handlers\__init__.py", line 48, in _load_handler
    dhcls = load_object(path)
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\utils\misc.py", line 44, in load_object
    mod = import_module(module)
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\core\downloader\handlers\http.py", line 3, in <module>
    from .http11 import HTTP11DownloadHandler as HTTPDownloadHandler
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 26, in <module>
    from scrapy.core.downloader.webclient import _parse
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\core\downloader\webclient.py", line 4, in <module>
    from twisted.web.client import HTTPClientFactory
ImportError: cannot import name 'HTTPClientFactory' from 'twisted.web.client' (unknown location)
2022-03-21 14:51:49 [scrapy.core.downloader.handlers] ERROR: Loading "scrapy.core.downloader.handlers.http.HTTPDownloadHandler" for scheme "https"
Traceback (most recent call last):
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\core\downloader\handlers\__init__.py", line 48, in _load_handler
    dhcls = load_object(path)
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\utils\misc.py", line 44, in load_object
    mod = import_module(module)
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\core\downloader\handlers\http.py", line 3, in <module>
    from .http11 import HTTP11DownloadHandler as HTTPDownloadHandler
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 26, in <module>
    from scrapy.core.downloader.webclient import _parse
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\core\downloader\webclient.py", line 4, in <module>
    from twisted.web.client import HTTPClientFactory
ImportError: cannot import name 'HTTPClientFactory' from 'twisted.web.client' (unknown location)
2022-03-21 14:51:49 [scrapy.core.downloader.handlers] ERROR: Loading "scrapy.core.downloader.handlers.s3.S3DownloadHandler" for scheme "s3"
Traceback (most recent call last):
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\core\downloader\handlers\__init__.py", line 48, in _load_handler
    dhcls = load_object(path)
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\utils\misc.py", line 44, in load_object
    mod = import_module(module)
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\core\downloader\handlers\s3.py", line 6, in <module>
    from .http import HTTPDownloadHandler
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\core\downloader\handlers\http.py", line 3, in <module>
    from .http11 import HTTP11DownloadHandler as HTTPDownloadHandler
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 26, in <module>
    from scrapy.core.downloader.webclient import _parse
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\core\downloader\webclient.py", line 4, in <module>
    from twisted.web.client import HTTPClientFactory
ImportError: cannot import name 'HTTPClientFactory' from 'twisted.web.client' (unknown location)
Unhandled error in Deferred:
2022-03-21 14:51:49 [twisted] CRITICAL: Unhandled error in Deferred:

Traceback (most recent call last):
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\crawler.py", line 172, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\crawler.py", line 176, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\twisted\internet\defer.py", line 1905, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\twisted\internet\defer.py", line 1815, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status)
--- <exception caught here> ---
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\twisted\internet\defer.py", line 1660, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\core\engine.py", line 69, in __init__
    self.downloader = downloader_cls(crawler)
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\core\downloader\__init__.py", line 88, in __init__
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\middleware.py", line 53, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\middleware.py", line 34, in from_settings
    mwcls = load_object(clspath)
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\utils\misc.py", line 44, in load_object
    mod = import_module(module)
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load

  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 728, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\downloadermiddlewares\retry.py", line 24, in <module>
    from scrapy.core.downloader.handlers.http11 import TunnelError
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 26, in <module>
    from scrapy.core.downloader.webclient import _parse
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\core\downloader\webclient.py", line 4, in <module>
    from twisted.web.client import HTTPClientFactory
builtins.ImportError: cannot import name 'HTTPClientFactory' from 'twisted.web.client' (unknown location)

2022-03-21 14:51:49 [twisted] CRITICAL:
Traceback (most recent call last):
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\twisted\internet\defer.py", line 1660, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\core\engine.py", line 69, in __init__
    self.downloader = downloader_cls(crawler)
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\core\downloader\__init__.py", line 88, in __init__
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\middleware.py", line 53, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\middleware.py", line 34, in from_settings
    mwcls = load_object(clspath)
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\utils\misc.py", line 44, in load_object
    mod = import_module(module)
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\downloadermiddlewares\retry.py", line 24, in <module>
    from scrapy.core.downloader.handlers.http11 import TunnelError
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 26, in <module>
    from scrapy.core.downloader.webclient import _parse
  File "C:\Users\Harold\anaconda3\envs\virtual\lib\site-packages\scrapy\core\downloader\webclient.py", line 4, in <module>
    from twisted.web.client import HTTPClientFactory
ImportError: cannot import name 'HTTPClientFactory' from 'twisted.web.client' (unknown location)

**Comment by Gallaecio** [comment]
You are using the latest version of Twisted, which only Scrapy 2.4 and later support. Downgrade Twisted or upgrade Scrapy.

**Comment by Gallaecio** [comment]
https://docs.anaconda.com/anaconda/navigator/tutorials/manage-packages/
