### ISSUE TITLE
Why do I get "incompatible architecture" in Scrapy 

### ISSUE THREAD

**Issue by cmwells41** [scrapy/scrapy#5462]
### Description
M1 Mac Mini running Mac OS Monterey V 12.3, 8GB Memory Downloaded scrapy into PyCharm and in terminal typed 'scrapy --version' Traceback listed every module and ended with: ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

Is there a work around or fix for Apple Silicon or a different version or anything? I had read somewhere that I needed to load Rosetta 2 for M1 Macs and I did that. Otherwise I just installed from GitHub and followed installation.

I am quite new to all of this so looking through the questions that are tagged below I don't find an applicable response to the problem. I am following the tutorial and this is like the first thing to I come to. I can do a run of 'quotes_spider.py' and it finished with exit code 0. But does not produce the files expected. Also the first step in the tutorial is  $ scrapy startproject tutorial  and that does not create the folders or fill 	the data in /spiders/
### Steps to Reproduce

1. [First Step] Load scrapy into PyCharm
2. [Second Step] Load requirements
3.  follow the tutorial as far as setup and environment
4. (scrapy) ➜  scrapy git:(master) ✗ scrapy startproject tutorial

**Expected behavior:**
This was to cd tutorial and spiders

**Actual behavior:** 
(scrapy) ➜  scrapy git:(master) ✗ scrapy startproject tutorial
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/scrapy", line 5, in <module>
    from scrapy.cmdline import execute
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/scrapy/cmdline.py", line 9, in <module>
    from scrapy.crawler import CrawlerProcess
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/scrapy/crawler.py", line 18, in <module>
    from scrapy.core.engine import ExecutionEngine
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/scrapy/core/engine.py", line 17, in <module>
    from scrapy.core.scraper import Scraper
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/scrapy/core/scraper.py", line 17, in <module>
    from scrapy.utils.log import failure_to_exc_info, logformatter_adapter
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/scrapy/utils/log.py", line 12, in <module>
    from scrapy.utils.versions import scrapy_components_versions
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/scrapy/utils/versions.py", line 12, in <module>
    from scrapy.utils.ssl import get_openssl_version
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/scrapy/utils/ssl.py", line 1, in <module>
    import OpenSSL
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/OpenSSL/crypto.py", line 11, in <module>
    from OpenSSL._util import (
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/OpenSSL/_util.py", line 5, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

No files created

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions

Please paste here the output of executing `scrapy version --verbose` in the command line.
(scrapy) ➜  scrapy git:(master) ✗ scrapy version --verbose
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/scrapy", line 5, in <module>
    from scrapy.cmdline import execute
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/scrapy/cmdline.py", line 9, in <module>
    from scrapy.crawler import CrawlerProcess
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/scrapy/crawler.py", line 18, in <module>
    from scrapy.core.engine import ExecutionEngine
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/scrapy/core/engine.py", line 17, in <module>
    from scrapy.core.scraper import Scraper
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/scrapy/core/scraper.py", line 17, in <module>
    from scrapy.utils.log import failure_to_exc_info, logformatter_adapter
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/scrapy/utils/log.py", line 12, in <module>
    from scrapy.utils.versions import scrapy_components_versions
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/scrapy/utils/versions.py", line 12, in <module>
    from scrapy.utils.ssl import get_openssl_version
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/scrapy/utils/ssl.py", line 1, in <module>
    import OpenSSL
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/OpenSSL/crypto.py", line 11, in <module>
    from OpenSSL._util import (
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/OpenSSL/_util.py", line 5, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

### Additional context

Any additional information, configuration, data or output from commands that might be necessary to reproduce or understand the issue. Please try not to include screenshots of code or the command line, paste the contents as text instead. You can use [GitHub Flavored Markdown](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make the text look better.

**Comment by wRAR** [comment]
Scrapy is pure-Python so any binary-related problems are caused by other modules. Neither cryptography nor cffi-backend are parts of Scrapy.
