### ISSUE TITLE
Using spider.crawler.engine.close_spide() in a pipeline raises an exception

### ISSUE THREAD

**Issue by z719893361** [scrapy/scrapy#5465]
### Description

Using ```spider.crawler.engine.close_spide()``` in pipeline will throw an exception
### Steps to Reproduce

```
class IPVerification:
    @classmethod
    def from_settings(cls, settings):
        return cls(settings.get('REDIS_URL'))

    def __init__(self, redis_url):
        connect_pool = ConnectionPool.from_url(redis_url)
        self.redis = Redis(connection_pool=connect_pool, max_connections=128)
        self.count = 0

    def process_item(self, item, spider: Spider):
        ipv4 = item.get('ipv4')
        port = item.get('port')
        if ipv4 is None or port is None:
            return
        fingerprint = md5(ipv4.encode() + port.encode()).hexdigest()
        if self.redis.sadd('Item', fingerprint):
            return item
        if self.count > 10:
            spider.crawler.engine.close_spider(spider, 'Multiple data repetitions')
        else:
            self.count += 1
        raise DropItem('Data duplication')
```

**Reproduces how often**: 100% 

### Versions

```
Scrapy       : 2.6.1
lxml         : 4.6.4.0
libxml2      : 2.9.5
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 22.2.0
Python       : 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
pyOpenSSL    : 22.0.0 (OpenSSL 1.1.1m  14 Dec 2021)
cryptography : 36.0.1
Platform     : Windows-10-10.0.22000-SP0

```

### Error
```
 'start_time': datetime.datetime(2022, 4, 6, 1, 52, 16, 182409)}
2022-04-06 09:52:17 [scrapy.core.engine] INFO: Spider closed (Multiple data repetitions)
2022-04-06 09:52:17 [scrapy.core.engine] INFO: Error while scheduling new request
Traceback (most recent call last):
  File "D:\Program Files\Python\Python310\lib\site-packages\twisted\internet\task.py", line 526, in _oneWorkUnit
    result = next(self._iterator)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python\Python310\lib\site-packages\twisted\internet\defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "D:\Program Files\Python\Python310\lib\site-packages\scrapy\core\engine.py", line 187, in <lambda>
    d.addBoth(lambda _: self.slot.nextcall.schedule())
AttributeError: 'NoneType' object has no attribute 'nextcall'

Process finished with exit code 0
```

**Comment by wRAR** [comment]
This is #5437
