### ISSUE TITLE
`scrapy check` fails when there is more than one spider

### ISSUE THREAD

**Issue by ptorrestr** [scrapy/scrapy#5467]
### Description

Command `scrapy check` fails when there is more than one spider with contracts.

### Steps to Reproduce

1. `pip install scrapy`
2. `scrapy startproject myproject`
3. `scrapy genspider example1 example.com`
4. `scrapy genspider example2 example.com`
5. Replace the method `parse` for both spiders 

```python
 def parse(self, response):
        """
        @url https://quotes.toscrape.com/page/1/
        @returns items 1 1
        """
        return {"hello":"world"}
```
6. `scrapy check -v`

**Expected behavior:** [What you expect to happen]
Output should be
```
[example] parse (@returns post-hook) ... ok
[example2] parse (@returns post-hook) ... ok

----------------------------------------------------------------------
Ran 1 contract in 0.441s
```
**Actual behavior:** [What actually happens]
Current output
```
Traceback (most recent call last):
  File "/home/pablo/.local/share/virtualenvs/test-b4DgvrUI/bin/scrapy", line 8, in <module>
    sys.exit(execute())
  File "/home/pablo/.local/share/virtualenvs/test-b4DgvrUI/lib/python3.9/site-packages/scrapy/cmdline.py", line 145, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/home/pablo/.local/share/virtualenvs/test-b4DgvrUI/lib/python3.9/site-packages/scrapy/cmdline.py", line 100, in _run_print_help
    func(*a, **kw)
  File "/home/pablo/.local/share/virtualenvs/test-b4DgvrUI/lib/python3.9/site-packages/scrapy/cmdline.py", line 153, in _run_command
    cmd.run(args, opts)
  File "/home/pablo/.local/share/virtualenvs/test-b4DgvrUI/lib/python3.9/site-packages/scrapy/commands/check.py", line 79, in run
    self.crawler_process.crawl(spidercls)
  File "/home/pablo/.local/share/virtualenvs/test-b4DgvrUI/lib/python3.9/site-packages/scrapy/crawler.py", line 205, in crawl
    crawler = self.create_crawler(crawler_or_spidercls)
  File "/home/pablo/.local/share/virtualenvs/test-b4DgvrUI/lib/python3.9/site-packages/scrapy/crawler.py", line 238, in create_crawler
    return self._create_crawler(crawler_or_spidercls)
  File "/home/pablo/.local/share/virtualenvs/test-b4DgvrUI/lib/python3.9/site-packages/scrapy/crawler.py", line 313, in _create_crawler
    return Crawler(spidercls, self.settings, init_reactor=True)
  File "/home/pablo/.local/share/virtualenvs/test-b4DgvrUI/lib/python3.9/site-packages/scrapy/crawler.py", line 82, in __init__
    default.install()
  File "/home/pablo/.local/share/virtualenvs/test-b4DgvrUI/lib/python3.9/site-packages/twisted/internet/epollreactor.py", line 256, in install
    installReactor(p)
  File "/home/pablo/.local/share/virtualenvs/test-b4DgvrUI/lib/python3.9/site-packages/twisted/internet/main.py", line 32, in installReactor
    raise error.ReactorAlreadyInstalledError("reactor already installed")
twisted.internet.error.ReactorAlreadyInstalledError: reactor already installed
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Versions

Scrapy       : 2.6.1
lxml         : 4.8.0.0
libxml2      : 2.9.12
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 22.2.0
Python       : 3.9.9 (main, Jan  7 2022, 11:04:30) - [GCC 11.1.0]
pyOpenSSL    : 22.0.0 (OpenSSL 1.1.1n  15 Mar 2022)
cryptography : 36.0.2
Platform     : Linux-5.15.13-arch1-1-x86_64-with-glibc2.33

### Additional context

When command `check` is executed on individual spiders, there are no errors.

**Comment by Laerte** [comment]
@wRAR Tested locally #5355 fix this issue as well.

```
➜  myproject scrapy check
..
----------------------------------------------------------------------
Ran 2 contracts in 1.728s

OK
```

**Comment by alexpdev** [comment]
Okay... I'll close my pull request then

**Comment by Gallaecio** [comment]
Closing in favor of https://github.com/scrapy/scrapy/issues/5435, thanks @Laerte and @alexpdev!
