### ISSUE TITLE
ModuleNotFoundError: No module named '_lzma'

### ISSUE THREAD

**Issue by dmn001** [scrapy/scrapy#5472]
running `scrapy bench` on debian returns this error:

  File "/root/storage/venv/lib/python3.9/site-packages/scrapy/extensions/feedexport.py", line 23, in <module>
    from scrapy.extensions.postprocessing import PostProcessingManager
  File "/root/storage/venv/lib/python3.9/site-packages/scrapy/extensions/postprocessing.py", line 7, in <module>
    from lzma import LZMAFile
  File "/usr/local/lib/python3.9/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'

Python version is 3.9.6

**Comment by dmn001** [comment]
My Python was compiled without lzma, recompiled and `scrapy bench` ran okay, except for this 2nd error message:

2022-04-09 13:57:54 [scrapy.core.engine] INFO: Error while scheduling new request
Traceback (most recent call last):
  File "/root/storage/venv/lib/python3.9/site-packages/twisted/internet/task.py", line 526, in _oneWorkUnit
    result = next(self._iterator)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/storage/venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/root/storage/venv/lib/python3.9/site-packages/scrapy/core/engine.py", line 187, in <lambda>
    d.addBoth(lambda _: self.slot.nextcall.schedule())
AttributeError: 'NoneType' object has no attribute 'nextcall'

**Comment by triet-lq-holistics** [comment]
Any update on this? I got in the same problem

**Comment by geekmister** [comment]
How to fix it? I made the same mistake you did...

**Comment by geekmister** [comment]
> How to fix it? I made the same mistake you did...

Just found the issue, it is answered in Github issues on Pyenv. See under:
![image](https://github.com/scrapy/scrapy/assets/45185145/f5349ee8-4f4f-4aec-aabb-53605f70c495)

**Comment by bengabp** [comment]
Incase you didnt find a solution, [here](https://support.huawei.com/enterprise/en/doc/EDOC1100289998/db0db8f0/modulenotfounderror-no-module-named-_lzma-) is a workaround that worked for me

**Comment by Filipe-0911** [comment]
@bengabp ty soooo much, man... i was searching for this soo long.
