### ISSUE TITLE
Support per-request download handler override

### ISSUE THREAD

**Issue by Gallaecio** [scrapy/scrapy#5510]
It would be great if a plugin like https://github.com/scrapy-plugins/scrapy-playwright did not had to force you to drive all requests through its download handlers, and instead you could drive certain requests through certain download handlers.

**Comment by GeorgeA92** [comment]
I suppose it can be implemented by updating code here:
https://github.com/scrapy/scrapy/blob/23537a0f9580bfb28ac5d8b88f37df47e838f463/scrapy/core/downloader/handlers/__init__.py#L70-L75

**Comment by GeorgeA92** [comment]
@Gallaecio 
> It would be great if a plugin like https://github.com/scrapy-plugins/scrapy-playwright did not had to force you to drive all requests through its download handlers, and instead you could drive certain requests through certain download handlers.

From the other side.. theoretically it is also possible to implement this functionality by updating source code of custom downloader handler (instead of making changes to core parts of scrapy).
Updated handler expected to work as regular scrapy twisted-based handler and as playwright-based handler depending on.. request parameters (value of specific meta key for example).

**Comment by Gallaecio** [comment]
That is true.

However, the key question to me is whether we should keep the restriction of 1 download handler per URL scheme, or open it up to any URL feature.

It may be as “simple” as allowing users to override the `DownloadHandlers` class through a setting, instead of hardcoding it in https://github.com/scrapy/scrapy/blob/0e579182319504ba7bfd0c09333fe92f70c6d312/scrapy/core/downloader/__init__.py#L78

Exposing that as a setting, and refactoring (and renaming?) `DownloadHandlers` to make it easy to subclass it, could make it trivial to provide an alternative component that allows more flexible download handler selection, e.g. based on request meta, domain, etc.

**Comment by kmike** [comment]
Some random, unrelated thoughts, with no concrete suggestions :) 

1. Another aproach could be to allow multiple download handlers for each schema, and make handlers themselves decide if they want to handle a request. Not sure though. It fits scrapy-playwright use case, but may not fit others - flexibility is in the hands of handler writers in this case. 
2. I wonder if this problem is related in any way to http2, protocol negotiation, etc, as we currently have separate download handlers for those. Even if we don't go into negotiation, how can we say "use http2 for website A, use http 1.1 for website B"?
3. That's probably obvious, but with any of the approaches, we should make sure not to give up on lazy loading.

**Comment by PsykotropyK** [comment]
Hello. I was actually looking for this functionality following this [enhancement request](https://github.com/scrapy/scrapy/issues/5618) as I wanted duplicate the normal downloader and reference my fork in the `DOWNLOAD_HANDLERS`. But as I am using playwright in the mean time....

I'll see if I can help on this, though it would be of great use I think

**Comment by Gallaecio** [comment]
I wonder what the downsides would be to follow a custom-schema approach similar to the one I have seen in the Git world: `schema+schema://`.

So, rather than replacing the native Scrapy download handlers, maybe you could register download handlers with a separate schema (e.g. `playwright+http`, `playwright+https`, `zyte+http`, `zyte+https`), and have the request schema by set by an early download middleware based on request parameters (e.g. metadata).

If there were no significant downsides to such an approach, we would need no changes in Scrapy itself.

**Comment by payala** [comment]
This is super interesting, as I'm facing this need now to switch some requests through Playwright and some through Zite API. Has there been any activity on this? Any thoughts on what would be the recommended approach if I wanted to implement this myself?

**Comment by elacuesta** [comment]
While there is no built-in support, a possible workaround could be to define a custom download handler (see #4944) implementing a `download_request` method that routes the request to your desired handler.

A naive and heavily simplified example:
```python
class MyDownloadHandler:
    def __init__(self) -> None:
        self.handlers = {
            "one": FirstHandler(),
            "two": SecondHandler(),
        }

    def download_request(self, request, spider):
        handler = self.handlers[request.meta["handler"]]
        return handler.download_request(request, spider)
```

**Comment by payala** [comment]
I was thinking about it yesterday, and for my particular use case, that's exactly what I was thinking about, something like this:

```python
# mux_download_handler.py
from scrapy.downloadermiddlewares.downloadhandler import DownloadHandler
from scrapy_playwright.handler import ScrapyPlaywrightDownloadHandler
from scrapy.core.downloader.handlers.http11 import HTTP11DownloadHandler

class MuxDownloadHandler(DownloadHandler):
    def __init__(self, settings):
        super().__init__(settings)
        self.playwright_handler = ScrapyPlaywrightDownloadHandler(settings)
        self.http_handler = HTTP11DownloadHandler(settings)

    @classmethod
    def from_crawler(cls, crawler):
        return cls(crawler.settings)

    def download_request(self, request, spider):
        if request.meta.get('playwright'):
            return self.playwright_handler.download_request(request, spider)
        elif request.meta.get('zyte_smartproxy'):
            return self.http_handler.download_request(request, spider)
        else:
            return self.http_handler.download_request(request, spider)

```

While it's very specific, it can be a possible custom solution.

**Comment by payala** [comment]
@elacuesta that's exactly what I was thinking about yesterday, this is my implementation, which seems to be working fine:

```python
from scrapy_playwright.handler import ScrapyPlaywrightDownloadHandler
from scrapy_zyte_api import ScrapyZyteAPIDownloadHandler


class MuxDownloadHandler:
    lazy = False
    
    def __init__(self, crawler):
        self.playwright_handler = ScrapyPlaywrightDownloadHandler.from_crawler(crawler)
        self.zyte_handler = ScrapyZyteAPIDownloadHandler.from_crawler(crawler)

    @classmethod
    def from_crawler(cls, crawler):
        return cls(crawler)

    def download_request(self, request, spider):
        if request.meta.get('playwright'):
            return self.playwright_handler.download_request(request, spider)
        elif request.meta.get('zyte'):
            # Zyte handler processing logic
            # Assuming Zyte is configured via middleware or custom handling here
            # We delegate to the default HTTP handler for Zyte requests
            return self.zyte_handler.download_request(request, spider)
        else:
            # Default to Playwright handler because without 'playwright' meta
            # tag, it behaves like a normal HTTP request
            return self.playwright_handler.download_request(request, spider)
```

**Comment by Ehsan-U** [comment]
---
`spider.py`
```python
class OpenSecrets(scrapy.Spider):
    name = "opensecrets"
    source = "https://www.opensecrets.org/"
    custom_settings = {
        "USER_AGENT": None,
        "PLAYWRIGHT_LAUNCH_OPTIONS": {"headless": False}
    }


    def start_requests(self) -> Iterable[Request]:
        url = "https://www.opensecrets.org/news/feed"
        yield scrapy.Request(url, callback=self.parse, meta={"playwright": True})

```
`settings.py`
```python
DOWNLOAD_HANDLERS = {
      "http": "MuxDownloadHandler",
      "https": "MuxDownloadHandler",
  }
```


It cause this error when using `PLAYWRIGHT_LAUNCH_OPTIONS`

```python
Traceback (most recent call last):
  File "/home/ehsan/projects/upwork/karim/politics-policy-cable-news/.venv/lib/python3.12/site-packages/twisted/internet/defer.py", line 2013, in _inlineCallbacks
    result = context.run(
             ^^^^^^^^^^^^
  File "/home/ehsan/projects/upwork/karim/politics-policy-cable-news/.venv/lib/python3.12/site-packages/twisted/python/failure.py", line 467, in throwExceptionIntoGenerator
    return g.throw(self.value.with_traceback(self.tb))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ehsan/projects/upwork/karim/politics-policy-cable-news/.venv/lib/python3.12/site-packages/scrapy/core/downloader/middleware.py", line 68, in process_request
    return (yield download_func(request, spider))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ehsan/projects/upwork/karim/politics-policy-cable-news/.venv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1253, in adapt
    extracted: _SelfResultT | Failure = result.result()
                                        ^^^^^^^^^^^^^^^
  File "/home/ehsan/projects/upwork/karim/politics-policy-cable-news/.venv/lib/python3.12/site-packages/scrapy_playwright/handler.py", line 379, in _download_request
    return await self._download_request_with_retry(request=request, spider=spider)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ehsan/projects/upwork/karim/politics-policy-cable-news/.venv/lib/python3.12/site-packages/scrapy_playwright/handler.py", line 398, in _download_request_with_retry
    page = await self._create_page(request=request, spider=spider)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ehsan/projects/upwork/karim/politics-policy-cable-news/.venv/lib/python3.12/site-packages/scrapy_playwright/handler.py", line 297, in _create_page
    ctx_wrapper = await self._create_browser_context(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ehsan/projects/upwork/karim/politics-policy-cable-news/.venv/lib/python3.12/site-packages/scrapy_playwright/handler.py", line 258, in _create_browser_context
    await self._maybe_launch_browser()
  File "/home/ehsan/projects/upwork/karim/politics-policy-cable-news/.venv/lib/python3.12/site-packages/scrapy_playwright/handler.py", line 205, in _maybe_launch_browser
    logger.info("Launching browser %s", self.browser_type.name)
                                        ^^^^^^^^^^^^^^^^^
AttributeError: 'ScrapyPlaywrightDownloadHandler' object has no attribute 'browser_type'

```
