### ISSUE TITLE
twisted.internet.error.CannotListenError

### ISSUE THREAD

**Issue by dw1573** [scrapy/scrapy#5549]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\scrapy\utils\defer.py", line 169, in maybeDeferred_coro
  File "site-packages\pydispatch\robustapply.py", line 55, in robustApply
  File "site-packages\scrapy\extensions\telnet.py", line 65, in start_listening
  File "site-packages\scrapy\utils\reactor.py", line 23, in listen_tcp
  File "site-packages\twisted\internet\posixbase.py", line 565, in listenTCP
  File "site-packages\twisted\internet\tcp.py", line 1336, in startListening
twisted.internet.error.CannotListenError: Couldn't listen on 127.0.0.1:6073: [WinError 10048] 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。.
RandomUserAgentMiddleware init
2022-07-04 09:05:51 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method TelnetConsole.start_listening of <scrapy.extensions.telnet.TelnetConsole object at 0x000001E4E7D2DD08>>
Traceback (most recent call last):
  File "site-packages\twisted\internet\tcp.py", line 1334, in startListening
OSError: [WinError 10048] 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。

**Comment by wRAR** [comment]
I guess all your `TELNETCONSOLE_PORT` values are taken by other Scrapy processes.

**Comment by bblanchon** [comment]
Setting `TELNETCONSOLE_ENABLED` to `False` solved this issue for me.
