### ISSUE TITLE
scrapy.utils.log.logformatter_adapter - returns fixed tuple

### ISSUE THREAD

**Issue by jedmonson** [scrapy/scrapy#5570]
### Description

[This adapter function](https://github.com/scrapy/scrapy/blob/f60c7ae768fa2f238ea6d7646098fe99ef8ad461/scrapy/utils/log.py#L222) returns a tuple with three elements - however, the args argument can never be None.

Because it returns three items in the tuple, the [inputs to logging.log](https://github.com/scrapy/scrapy/blob/f60c7ae768fa2f238ea6d7646098fe99ef8ad461/scrapy/core/scraper.py#L275) are:
```
  level: item[0],
  msg: item[1],
  args: tuple( item[2] ) - args can never be an empty tuple or None.
```

The python logging library tries to format args onto a message (when there are no items in args). This is problematic because the msg variable is never supposed to be formatted in `logging.LogRecord.getMessage()`, which breaks when the msg contains `%` characters.

### Steps to Reproduce

1. Make a main.py file:
```
import scrapy
import logging
from scrapy.logformatter import LogFormatter
from twisted.python.failure import Failure


class CustomLogFormatter(LogFormatter):
  def scraped(self, item, response, spider):
    return {
      'level': logging.INFO,
      'args': None,
      'msg': {
        'scrapy_message': 'Item scraped.',
        'this_breaks_things': '90% is not a format string',
        'item': item,
        'src': (str(response.getErrorMessage()
                if isinstance(response, Failure) else response))
      }
    }


class Main(scrapy.Spider):
  name = 'test_scrapy'
  start_urls = ['https://github.com/scrapy/scrapy']
  custom_settings = {
    'LOG_FORMATTER': CustomLogFormatter,
  }

  def parse(self, response, *args, **kwargs):
   logging.info({"message": "got response", "content_len": len(response.text)})
   yield {"nice": "data"}

```

2. Run `scrapy runspider main.py -o data.json`
3. Review error message.

**Expected behavior:** I expect this code to run without errors, logging a message when the item is scraped.
```
2022-07-21 15:01:43 [root] INFO: {'message': 'got response', 'content_len': 254494}
2022-07-21 15:01:43 [scrapy.core.scraper] INFO: {'scrapy_message': 'Item scraped.', 'this_breaks_things': '90% is not a format string', 'item': {'nice': 'data'}, 'src': '<200 https://github.com/scrapy/scrapy>'}
2022-07-21 15:01:43 [scrapy.core.engine] INFO: Closing spider (finished)
```

**Actual behavior:** I get the following error:
```
[...successful initialization...]
2022-07-21 14:52:00 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2022-07-21 14:52:01 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://github.com/scrapy/scrapy> (referer: None)
2022-07-21 14:52:01 [root] INFO: {'message': 'got response', 'content_len': 253356}
--- Logging error ---
Traceback (most recent call last):
  File "/home/cusp/.pyenv/versions/3.8.2/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/home/cusp/.pyenv/versions/3.8.2/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/home/cusp/.pyenv/versions/3.8.2/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/home/cusp/.pyenv/versions/3.8.2/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: %i format: a number is required, not dict
Call stack:
  File "/home/cusp/.pyenv/versions/3.8.2/bin/scrapy", line 8, in <module>
    sys.exit(execute())
  File "/home/cusp/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/cmdline.py", line 145, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/home/cusp/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/cmdline.py", line 100, in _run_print_help
    func(*a, **kw)
  File "/home/cusp/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/cmdline.py", line 153, in _run_command
    cmd.run(args, opts)
  File "/home/cusp/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/commands/runspider.py", line 56, in run
    self.crawler_process.start()
  File "/home/cusp/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/crawler.py", line 327, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "/home/cusp/.pyenv/versions/3.8.2/lib/python3.8/site-packages/twisted/internet/base.py", line 1318, in run
    self.mainLoop()
  File "/home/cusp/.pyenv/versions/3.8.2/lib/python3.8/site-packages/twisted/internet/base.py", line 1328, in mainLoop
    reactorBaseSelf.runUntilCurrent()
  File "/home/cusp/.pyenv/versions/3.8.2/lib/python3.8/site-packages/twisted/internet/base.py", line 994, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/cusp/.pyenv/versions/3.8.2/lib/python3.8/site-packages/twisted/internet/task.py", line 682, in _tick
    taskObj._oneWorkUnit()
  File "/home/cusp/.pyenv/versions/3.8.2/lib/python3.8/site-packages/twisted/internet/task.py", line 528, in _oneWorkUnit
    result = next(self._iterator)
  File "/home/cusp/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/utils/defer.py", line 74, in <genexpr>
    work = (callable(elem, *args, **named) for elem in iterable)
  File "/home/cusp/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/core/scraper.py", line 197, in _process_spidermw_output
    dfd.addBoth(self._itemproc_finished, output, response, spider)
  File "/home/cusp/.pyenv/versions/3.8.2/lib/python3.8/site-packages/twisted/internet/defer.py", line 539, in addBoth
    return self.addCallbacks(
  File "/home/cusp/.pyenv/versions/3.8.2/lib/python3.8/site-packages/twisted/internet/defer.py", line 478, in addCallbacks
    self._runCallbacks()
  File "/home/cusp/.pyenv/versions/3.8.2/lib/python3.8/site-packages/twisted/internet/defer.py", line 858, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/home/cusp/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scrapy/core/scraper.py", line 257, in _itemproc_finished
    logger.log(*logformatter_adapter(logkws), extra={'spider': spider})
Message: {'scrapy_message': 'Item scraped.', 'this_breaks_things': '90% is not a format string', 'item': {'nice': 'data'}, 'src': '<200 https://github.com/scrapy/scrapy>'}
Arguments: {'level': 20, 'args': None, 'msg': {'scrapy_message': 'Item scraped.', 'this_breaks_things': '90% is not a format string', 'item': {'nice': 'data'}, 'src': '<200 https://github.com/scrapy/scrapy>'}}
2022-07-21 14:52:01 [scrapy.core.engine] INFO: Closing spider (finished)
2022-07-21 14:52:01 [scrapy.extensions.feedexport] INFO: Stored json feed (1 items) in: some.json
2022-07-21 14:52:01 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 223,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 43888,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 0.841262,
 'feedexport/success_count/FileFeedStorage': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2022, 7, 21, 18, 52, 1, 680924),
 'httpcompression/response_bytes': 253382,
 'httpcompression/response_count': 1,
 'item_scraped_count': 1,
 'log_count/DEBUG': 1,
 'log_count/INFO': 13,
 'memusage/max': 59277312,
 'memusage/startup': 59277312,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2022, 7, 21, 18, 52, 0, 839662)}
2022-07-21 14:52:01 [scrapy.core.engine] INFO: Spider closed (finished)

```

**Reproduces how often:** This is reproduced 100% of the time.

### Versions

```
Scrapy       : 2.5.1
lxml         : 4.6.5.0
libxml2      : 2.9.10
cssselect    : 1.1.0
parsel       : 1.6.0
w3lib        : 1.22.0
Twisted      : 21.7.0
Python       : 3.8.2 (default, Feb 16 2021, 11:46:05) - [GCC 9.3.0]
pyOpenSSL    : 21.0.0 (OpenSSL 1.1.1m  14 Dec 2021)
cryptography : 36.0.1
Platform     : Linux-5.15.0-41-generic-x86_64-with-glibc2.29

```

### Additional context
Would be interested in f anyone has a different way to log dictionaries as the messages - passing no `args` to logging.log.

**Comment by Gallaecio** [comment]
Are you aware that you can escape `%` with an additional `%`: `%%`?

**Comment by Gallaecio** [comment]
There is no error with `'90%% is not a format string'`.

**Comment by jedmonson** [comment]
@Gallaecio - Yes I'm aware of this, it seems odd (and like a bug) that I would need to escape `%` characters in the message when I do not have to do this with `logging.log`.

When I pass None as the `args` in the CustomLogFormatter - I am expected logging.log to receive no `args` - but this is not the case.

**Comment by jedmonson** [comment]
It would be helpful for me to understand why args should default to logkws here::
https://github.com/scrapy/scrapy/blob/60c8838554a79e70c22a7c6a57baedfcaf521444/scrapy/utils/log.py#L218-L222

Because this function `always` returns a third positional argument (which is expanded into the input of logging.log) - logging.log may experience issues like the one described above.

**Comment by Gallaecio** [comment]
So I take it this is no so much about the impossibility of passing a `%`, but about the wish to not have to use `%%` when no arguments are passed. I guess it is a valid request, although I wonder if it is worth handling, specially since it would be a backward-incompatible change (strings currently using `%%` would start displaying `%%` instead of `%` if we change this).
