### ISSUE TITLE
DropItem should not log error

### ISSUE THREAD

**Issue by marcpawl-arista** [scrapy/scrapy#5575]
### Description

In signal handler raising DropItem should not log an ERROR, but could log a DEBUG.

### Steps to Reproduce

1.
    def headers_received(self, headers, body_length, request, spider) :
        if b'Content-Type' in headers:
            if headers[b'Content-Type'] == [b'text/html']:
                return
        # Skip this file
        raise scrapy.exceptions.DropItem()

2. Scrape a website3. 

**Expected behavior:** [What you expect to happen]

DEBUG message which can be filtered out by setting logging level, and still getting errors.

**Actual behavior:** [What actually happens]
[2022-07-22T17:39:27.234Z] 2022-07-22 17:39:22 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method ToScrapeSpiderXX.headers_received of <ToScrapeSpiderXX 'toscrape-xpath' at 0x7ff862ba8df0>>
[2022-07-22T17:39:27.234Z] Traceback (most recent call last):
[2022-07-22T17:39:27.234Z]   File "/usr/local/lib/python3.8/dist-packages/scrapy/utils/signal.py", line 30, in send_catch_log
[2022-07-22T17:39:27.234Z]     response = robustApply(receiver, signal=signal, sender=sender, *arguments, **named)
[2022-07-22T17:39:27.234Z]   File "/usr/local/lib/python3.8/dist-packages/pydispatch/robustapply.py", line 55, in robustApply
[2022-07-22T17:39:27.234Z]     return receiver(*arguments, **named)
[2022-07-22T17:39:27.234Z]   File "/xx/xx/spiders/toscrape-pypi.py", line 36, in headers_received
[2022-07-22T17:39:27.234Z]     raise scrapy.exceptions.DropItem()
[2022-07-22T17:39:27.234Z] scrapy.exceptions.DropItem

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Please paste here the output of executing `scrapy version --verbose` in the command line.

### Additional context

Any additional information, configuration, data or output from commands that might be necessary to reproduce or understand the issue. Please try not to include screenshots of code or the command line, paste the contents as text instead. You can use [GitHub Flavored Markdown](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make the text look better.

**Comment by Gallaecio** [comment]
https://docs.scrapy.org/en/latest/topics/signals.html#scrapy.signals.headers_received
