### ISSUE TITLE
"cannot identify image file"

### ISSUE THREAD

**Issue by KonstantinKlepikov** [scrapy/scrapy#5585]
There is no changes with basic construction of scrapy. I use Scrapy = "^2.5.1" 

When image pipelene is used for downloading an specific image, i get error.

Example:

```sh
2022-07-28 23:52:46 [scrapy.pipelines.files] ERROR: File (unknown-error): Error processing file from <GET https://content.uvi.ru/upload/product_photos/cardboard_box1.jpg> referred in <None>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
    result = current_context.run(gen.send, result)
StopIteration: <200 https://content.uvi.ru/upload/product_photos/cardboard_box1.jpg>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/scrapy/pipelines/files.py", line 465, in media_downloaded
    checksum = self.file_downloaded(response, request, info, item=item)
  File "/usr/local/lib/python3.8/site-packages/scrapy/pipelines/media.py", line 140, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/scrapy/pipelines/images.py", line 115, in file_downloaded
    return self.image_downloaded(response, request, info, item=item)
  File "/usr/local/lib/python3.8/site-packages/scrapy/pipelines/media.py", line 140, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/scrapy/pipelines/images.py", line 119, in image_downloaded
    for path, image, buf in self.get_images(response, request, info, item=item):
  File "/usr/local/lib/python3.8/site-packages/scrapy/pipelines/images.py", line 132, in get_images
    orig_image = self._Image.open(BytesIO(response.body))
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f42d16ae220>
```

What i know about this problem. Actually the source of this is [image processing](https://docs.scrapy.org/en/latest/_modules/scrapy/pipelines/images.html#ImagesPipeline), where we see this function for decoding encoding data

```python
def to_bytes(text, encoding=None, errors='strict'):
    """Return the binary representation of ``text``. If ``text``
    is already a bytes object, return it as-is."""
    if isinstance(text, bytes):
        return text
    if not isinstance(text, str):
        raise TypeError('to_bytes must receive a str or bytes '
                        f'object, got {type(text).__name__}')
    if encoding is None:
        encoding = 'utf-8'
    return text.encode(encoding, errors)
```

Is not clear for me - how request data is transfer to pillow. For example, when i use [requests.content](https://requests.readthedocs.io/en/latest/user/quickstart/#binary-response-content) - the problem not reproduces. Thats ok:

```python
img = requests.get('https://content.uvi.ru/upload/product_photos/cardboard_box1.jpg')
with BytesIO(img.content) as bimg:
    pil_im = Image.open(bimg)
    display(pil_im)
```

**Comment by wRAR** [comment]
```
In [1]: fetch('https://content.uvi.ru/upload/product_photos/cardboard_box1.jpg')
2022-07-30 13:05:22 [scrapy.core.engine] INFO: Spider opened
2022-07-30 13:05:23 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://content.uvi.ru/upload/product_photos/cardboard_box1.jpg> (referer: None)

In [2]: from PIL import Image

In [3]: from io import BytesIO

In [4]: orig_image = Image.open(BytesIO(response.body))

In [5]:
```

Please provide a minimnal reproducible example of this problem.

**Comment by Gallaecio** [comment]
Chances are sometimes the server gives a bad response instead of sending the expected file.

**Comment by wRAR** [comment]
That part of the code doesn't look Twisted-related though.

**Comment by wRAR** [comment]
Do you have a minimal reproducible example for this?

**Comment by lfqtm** [comment]
hi, I'm getting the same error too, can this help you?
---
\>>> fetch('https://r.ttyingqiu.com/upload/sportdata/leagueLogo/19bc08fd59288a5811c21c814dfd9c2a.png')
2023-06-26 21:22:34 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://127.0.0.1:5377/session {"desiredCapabilities": {"browserName": "chrome", "version": "", "platform": "ANY", "javascriptEnabled": true, "chromeOptions": {"excludeSwi
tches": ["enable-automation"], "extensions": [], "args": ["--headless", "--disable-gpu", "no-sandbox", "disable-blink-features=AutomationControlled"]}}, "requiredCapabilities": {}}

DevTools listening on ws://127.0.0.1:5383/devtools/browser/986cf6b2-7190-4b72-a560-756fcac434e5
2023-06-26 21:22:35 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2023-06-26 21:22:35 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://127.0.0.1:5377/session/9e58df5d1811003452c8215e951a61e5/url {"url": "https://r.ttyingqiu.com/upload/sportdata/leagueLogo/19bc08fd59288a5811c21c814dfd9c2a.png", "se
ssionId": "9e58df5d1811003452c8215e951a61e5"}
2023-06-26 21:22:46 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2023-06-26 21:22:46 [selenium.webdriver.remote.remote_connection] DEBUG: POST http://127.0.0.1:5377/session/9e58df5d1811003452c8215e951a61e5/timeouts/implicit_wait {"ms": 5000.0, "sessionId": "9e58df5d1811003452c8215e951a61e5"}
2023-06-26 21:22:46 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2023-06-26 21:22:46 [selenium.webdriver.remote.remote_connection] DEBUG: GET http://127.0.0.1:5377/session/9e58df5d1811003452c8215e951a61e5/source {"sessionId": "9e58df5d1811003452c8215e951a61e5"}
2023-06-26 21:22:46 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2023-06-26 21:22:46 [selenium.webdriver.remote.remote_connection] DEBUG: DELETE http://127.0.0.1:5377/session/9e58df5d1811003452c8215e951a61e5 {"sessionId": "9e58df5d1811003452c8215e951a61e5"}
2023-06-26 21:22:46 [selenium.webdriver.remote.remote_connection] DEBUG: Finished Request
2023-06-26 21:22:48 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://r.ttyingqiu.com/upload/sportdata/leagueLogo/19bc08fd59288a5811c21c814dfd9c2a.png> (referer: None)
\>>> from PIL import Image
\>>> from io import BytesIO
\>>> orig_image = Image.open(BytesIO(response.body))
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing BlpImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing BmpImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing BufrStubImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing CurImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing DcxImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing DdsImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing EpsImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing FitsImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing FitsStubImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing FliImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing FpxImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Image: failed to import FpxImagePlugin: No module named 'olefile'
2023-06-26 21:24:05 [PIL.Image] DEBUG: Image: failed to import MicImagePlugin: No module named 'olefile'
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing MpegImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing MpoImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing MspImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing PalmImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing PcdImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing PcxImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing PdfImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing PixarImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing PngImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing PpmImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing PsdImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing QoiImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing SgiImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing SpiderImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing SunImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing TgaImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing TiffImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing WebPImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing WmfImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing XbmImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing XpmImagePlugin
2023-06-26 21:24:05 [PIL.Image] DEBUG: Importing XVThumbImagePlugin
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "D:\Program Files\anaconda3\envs\py39\lib\site-packages\PIL\Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x00000252856D3A40>
