### ISSUE TITLE
S3 backend can't handle uploads larger than 5GB 

### ISSUE THREAD

**Issue by ogabrielsantos** [scrapy/scrapy#5735]
### Description

When feeds larger than 5GB are sent using AWS S3 backend, I'm receiving the follow error:

```bash
2022-11-24 18:45:31 [scrapy.extensions.feedexport] ERROR: Error storing csv feed (55 items) in: s3://scrapy-test/large_export.csv
Traceback (most recent call last):
  File "/Users/ogabrielsantos/crawler-scrapy/venv/lib/python3.10/site-packages/twisted/python/threadpool.py", line 244, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
  File "/Users/ogabrielsantos/crawler-scrapy/venv/lib/python3.10/site-packages/twisted/python/threadpool.py", line 260, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
  File "/Users/ogabrielsantos/crawler-scrapy/venv/lib/python3.10/site-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/ogabrielsantos/crawler-scrapy/venv/lib/python3.10/site-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
  File "/Users/ogabrielsantos/crawler-scrapy/venv/lib/python3.10/site-packages/scrapy/extensions/feedexport.py", line 196, in _store_in_thread
    self.s3_client.put_object(
  File "/Users/ogabrielsantos/crawler-scrapy/venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/ogabrielsantos/crawler-scrapy/venv/lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (EntityTooLarge) when calling the PutObject operation: Your proposed upload exceeds the maximum allowed size
```

### Steps to Reproduce

I've write a minimum exemple code to simulate this issue:

```python
from scrapy.spiders import Spider


class LargeExportSpider(Spider):
    name = "large_export"
    start_urls = ["http://news.ycombinator.com/"]
    custom_settings = {
        "FEEDS": {
            "s3://scrapy-test/large_export.csv": {
                "format": "csv",
            },
        },
    }

    def parse(self, response, **kwargs):
        text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque iaculis odio efficitur, ultricies"

        for _ in range(0, 55):  # creates a 5.3GB csv file
            yield {"name": "John Doe", "text": text * 1000000}

```

### Versions
`scrapy version --verbose`:
```bash
Scrapy       : 2.7.1
lxml         : 4.9.1.0
libxml2      : 2.9.13
cssselect    : 1.2.0
parsel       : 1.7.0
w3lib        : 2.0.1
Twisted      : 22.10.0
Python       : 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)]
pyOpenSSL    : 22.1.0 (OpenSSL 3.0.5 5 Jul 2022)
cryptography : 38.0.1
Platform     : macOS-13.0.1-arm64-arm-64bit
```

`requirements.txt`:
```
botocore==1.29.16
Scrapy==2.7.1
```

### Additional context

Doing some investigation, I've seen that `S3FeedStorage` uses `put_object` which, as [per documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/upload-objects.html), has a limit of 5GB per uploaded object:

https://github.com/scrapy/scrapy/blob/6ded3cf4cd134b615239babe28bb28c3ff524b05/scrapy/extensions/feedexport.py#L196

Looks like `boto3` [already have an upload method](https://boto3.amazonaws.com/v1/documentation/api/1.16.53/guide/s3-uploading-files.html) which handles multipart files, but scrapy relies on `botocore`.

**Comment by Gallaecio** [comment]
Sounds related to https://github.com/scrapy/scrapy/issues/960 (at the very least, the solution seems to be the same)

**Comment by ogabrielsantos** [comment]
I'm workarounding it until an official fix, this way:

`requirements.txt`:
```
boto3==1.26.16
```

`crawlers/feed.py`:
```python
class LargeS3FeedStorage(S3FeedStorage):
    def __init__(
        self,
        uri,
        access_key=None,
        secret_key=None,
        acl=None,
        endpoint_url=None,
        *,
        feed_options=None,
        session_token=None,
    ):
        super().__init__(
            uri, access_key, secret_key, acl, endpoint_url, feed_options=feed_options, session_token=session_token
        )

        self.s3_client = boto3.client(
            "s3",
            aws_access_key_id=self.access_key,
            aws_secret_access_key=self.secret_key,
            aws_session_token=self.session_token,
            endpoint_url=self.endpoint_url,
        )

    def _store_in_thread(self, file):
        file.seek(0)
        self.s3_client.upload_file(Filename=file.name, Bucket=self.bucketname, Key=self.keyname)
        file.close()
```

`settings.py`:
```python
FEED_STORAGES = {
    "s3": "crawlers.feed.LargeS3FeedStorage",
}
```

**Comment by ogabrielsantos** [comment]
OOPS. Accidentally closed by private repository merge. Reopening.

**Comment by VMRuiz** [comment]
This issue is still present on last Scrapy versions: 

`botocore.exceptions.ClientError: An error occurred (EntityTooLarge) when calling the PutObject operation: Your proposed upload exceeds the maximum allowed size` 

This happens because there is a limitation on the [put_object](https://github.com/scrapy/scrapy/blob/master/scrapy/extensions/feedexport.py#L212) method  used by `S3FeedStorage`. 

The users could implement workarounds by enabling feeds batching or using compressing, but these are not proper solutions. S3FeedStorage should be changed to use `upload_file` instead, which automatically allows for  multipart uploading.

Source: https://www.learnaws.org/2022/08/22/boto3-s3-upload_file-vs-put-object/
