### ISSUE TITLE
ModuleNotFoundError: No module named 'twisted._threads](url)

### ISSUE THREAD

**Issue by thekingisherenow** [scrapy/scrapy#5741]
[ Scrapy startproject yess
Traceback (most recent call last):
  File "/mnt/c/Users/Administrator/Desktop/Nextjs/scraper/env/bin/Scrapy", line 5, in <module>
    from scrapy.cmdline import execute
  File "/mnt/c/Users/Administrator/Desktop/Nextjs/scraper/env/lib/python3.8/site-packages/scrapy/__init__.py", line 12, in <module>
    from scrapy.spiders import Spider
  File "/mnt/c/Users/Administrator/Desktop/Nextjs/scraper/env/lib/python3.8/site-packages/scrapy/spiders/__init__.py", line 10, in <module>
    from scrapy.http import Request
  File "/mnt/c/Users/Administrator/Desktop/Nextjs/scraper/env/lib/python3.8/site-packages/scrapy/http/__init__.py", line 11, in <module>
    from scrapy.http.request.form import FormRequest
  File "/mnt/c/Users/Administrator/Desktop/Nextjs/scraper/env/lib/python3.8/site-packages/scrapy/http/request/form.py", line 16, in <module>
    from scrapy.http.response.text import TextResponse
  File "/mnt/c/Users/Administrator/Desktop/Nextjs/scraper/env/lib/python3.8/site-packages/scrapy/http/response/text.py", line 26, in <module>
    from scrapy.utils.response import get_base_url
  File "/mnt/c/Users/Administrator/Desktop/Nextjs/scraper/env/lib/python3.8/site-packages/scrapy/utils/response.py", line 15, in <module>
    from twisted.web import http
  File "/mnt/c/Users/Administrator/Desktop/Nextjs/scraper/env/lib/python3.8/site-packages/twisted/web/http.py", line 123, in <module>
    from twisted.internet._producer_helpers import _PullToPush
  File "/mnt/c/Users/Administrator/Desktop/Nextjs/scraper/env/lib/python3.8/site-packages/twisted/internet/_producer_helpers.py", line 14, in <module>
    from twisted.internet.task import cooperate
  File "/mnt/c/Users/Administrator/Desktop/Nextjs/scraper/env/lib/python3.8/site-packages/twisted/internet/task.py", line 31, in <module>
    from twisted.internet.base import DelayedCall
  File "/mnt/c/Users/Administrator/Desktop/Nextjs/scraper/env/lib/python3.8/site-packages/twisted/internet/base.py", line 70, in <module>
    from twisted.python.threadpool import ThreadPool
  File "/mnt/c/Users/Administrator/Desktop/Nextjs/scraper/env/lib/python3.8/site-packages/twisted/python/threadpool.py", line 15, in <module>
    from twisted._threads import pool as _pool
ModuleNotFoundError: No module named 'twisted._threads](url)

**Comment by wRAR** [comment]
This looks like a problem with your Twisted installation, not specific to Scrapy.
