### ISSUE TITLE
Missing traceback for exceptions occurred in `open_spider` method of an item pipeline

### ISSUE THREAD

**Issue by Prometheus3375** [scrapy/scrapy#5817]
### Description

Traceback shown for an exception raised in a pipeline while opening a spider contains not enough information regarding the pipeline which has thrown this exception.

### Steps to Reproduce

1. Create any simple spider.
2. Create pipeline in file `pipelines.py` with next code:
    ```python
    from typing import Any
    
    from scrapy import Spider
    from scrapy.crawler import Crawler
    
    
    class MyPipeline:
        @classmethod
        def from_crawler(cls, crawler: Crawler, /):
            return cls()
    
        def open_spider(self, spider: Spider, /):
            self.value = {}['']
    
        def close_spider(self, spider: Spider, /): pass
    
        def process_item(self, item: Any, spider: Spider, /) -> Any:
            return item

    ```
5. Add pipeline to the settings:
    ```python
    ITEM_PIPELINES = {
        'pipelines.MyPipeline': 600,
    }
    ```
6. Start crawling with spider.
7. Observe logs.

**Expected behavior:**
Comprehensive traceback with exact position which caused the exception.

**Actual behavior:**

Here is an example of logs I received. Project directory was redacted.

```
2023-01-31 05:04:05 [scrapy.core.engine] INFO: Spider opened
2023-01-31 05:04:06 [scrapy.core.engine] INFO: Closing spider (shutdown)
2023-01-31 05:04:06 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method SpiderState.spider_closed of <scrapy.extensions.spiderstate.SpiderState object at 0x000001A66705EE30>>
Traceback (most recent call last):
  File "<redacted>\.venv\lib\site-packages\scrapy\crawler.py", line 118, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<redacted>\.venv\lib\site-packages\scrapy\utils\defer.py", line 292, in maybeDeferred_coro
    result = f(*args, **kw)
  File "<redacted>\.venv\lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "<redacted>\.venv\lib\site-packages\scrapy\extensions\spiderstate.py", line 29, in spider_closed
    pickle.dump(spider.state, f, protocol=4)
AttributeError: 'MySpider' object has no attribute 'state'
2023-01-31 05:04:06 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method WunderStats.spider_closed of <wunder_scrapy.extensions.stats.WunderStats object at 0x000001A667098040>>
Traceback (most recent call last):
  File "<redacted>\.venv\lib\site-packages\scrapy\crawler.py", line 118, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<redacted>\.venv\lib\site-packages\scrapy\utils\defer.py", line 292, in maybeDeferred_coro
    result = f(*args, **kw)
  File "<redacted>\.venv\lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "<redacted>\wunder_scrapy\extensions\stats.py", line 61, in spider_closed
    self.update_elapsed_time()
  File "<redacted>\wunder_scrapy\extensions\stats.py", line 103, in update_elapsed_time
    elapsed_time = datetime.utcnow() - self.start_time
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
2023-01-31 05:04:06 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'log_count/ERROR': 2, 'log_count/INFO': 10, 'log_count/WARNING': 1}
2023-01-31 05:04:06 [scrapy.core.engine] INFO: Spider closed (shutdown)
Unhandled error in Deferred:
2023-01-31 05:04:06 [twisted] CRITICAL: Unhandled error in Deferred:

Traceback (most recent call last):
  File "<redacted>\.venv\lib\site-packages\scrapy\crawler.py", line 220, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "<redacted>\.venv\lib\site-packages\scrapy\crawler.py", line 224, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "<redacted>\.venv\lib\site-packages\twisted\internet\defer.py", line 1947, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "<redacted>\.venv\lib\site-packages\twisted\internet\defer.py", line 1857, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
--- <exception caught here> ---
  File "<redacted>\.venv\lib\site-packages\twisted\internet\defer.py", line 1697, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "<redacted>\.venv\lib\site-packages\scrapy\crawler.py", line 118, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
builtins.KeyError: ''

2023-01-31 05:04:06 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "<redacted>\.venv\lib\site-packages\twisted\internet\defer.py", line 1697, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "<redacted>\.venv\lib\site-packages\scrapy\crawler.py", line 118, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
KeyError: ''
```

**Reproduces how often:** 100%

### Versions

Scrapy       : 2.7.1
lxml         : 4.9.2.0
libxml2      : 2.9.12
cssselect    : 1.2.0
parsel       : 1.7.0
w3lib        : 2.1.1
Twisted      : 22.10.0
Python       : 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
pyOpenSSL    : 23.0.0 (OpenSSL 3.0.7 1 Nov 2022)
cryptography : 39.0.0
Platform     : Windows-10-10.0.19044-SP0

### Additional context

As you may notice, the last line of traceback `yield self.engine.open_spider(self.spider, start_requests)` is not helpful. In addition, the lack of proper handling of errors produced by item pipelines leads to other error, like missing state of spider or subtraction between `datetime` object and `None`. In my case I spent nearly 4 hours to locate the cause of error, it was `KeyError` as in the example which are always contain no context except for the missing key.

### Current workaround
Wrap code of `open_spider` method of your own item pipelines with `try-except` block and re-reaise error with any necessary context (for example, pipeline name).

**Comment by Gallaecio** [comment]
For background: https://github.com/scrapy/scrapy/issues/2362

**Comment by AdrianAtZyte** [comment]
#7179
