### ISSUE TITLE
ModuleNotFoundError: No module named '_lzma'

### ISSUE THREAD

**Issue by bytejunkie** [scrapy/scrapy#5921]
### Description

Scrapy fails to run, giving an error where the module _lzma isnt found.

### Steps to Reproduce

1. Fresh install of Ubuntu 23.04
2. Virtualenv for scrapy and python 3.9.16 (because this is likely to end in a Lambda on AWS) 
3. following the tutorial, i run 

```
scrapy crawl example 
```

**Expected behavior:** [What you expect to happen]
it should scrape the example.com site, as per the example code. 

**Actual behavior:** [What actually happens]

```
Traceback (most recent call last):
  File "/home/matt/.pyenv/versions/scrapy/bin/scrapy", line 8, in <module>
    sys.exit(execute())
  File "/home/matt/.pyenv/versions/3.9.16/envs/scrapy/lib/python3.9/site-packages/scrapy/cmdline.py", line 158, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/home/matt/.pyenv/versions/3.9.16/envs/scrapy/lib/python3.9/site-packages/scrapy/cmdline.py", line 111, in _run_print_help
    func(*a, **kw)
  File "/home/matt/.pyenv/versions/3.9.16/envs/scrapy/lib/python3.9/site-packages/scrapy/cmdline.py", line 166, in _run_command
    cmd.run(args, opts)
  File "/home/matt/.pyenv/versions/3.9.16/envs/scrapy/lib/python3.9/site-packages/scrapy/commands/crawl.py", line 24, in run
    crawl_defer = self.crawler_process.crawl(spname, **opts.spargs)
  File "/home/matt/.pyenv/versions/3.9.16/envs/scrapy/lib/python3.9/site-packages/scrapy/crawler.py", line 232, in crawl
    crawler = self.create_crawler(crawler_or_spidercls)
  File "/home/matt/.pyenv/versions/3.9.16/envs/scrapy/lib/python3.9/site-packages/scrapy/crawler.py", line 266, in create_crawler
    return self._create_crawler(crawler_or_spidercls)
  File "/home/matt/.pyenv/versions/3.9.16/envs/scrapy/lib/python3.9/site-packages/scrapy/crawler.py", line 349, in _create_crawler
    return Crawler(spidercls, self.settings, init_reactor=init_reactor)
  File "/home/matt/.pyenv/versions/3.9.16/envs/scrapy/lib/python3.9/site-packages/scrapy/crawler.py", line 107, in __init__
    self.extensions = ExtensionManager.from_crawler(self)
  File "/home/matt/.pyenv/versions/3.9.16/envs/scrapy/lib/python3.9/site-packages/scrapy/middleware.py", line 68, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/home/matt/.pyenv/versions/3.9.16/envs/scrapy/lib/python3.9/site-packages/scrapy/middleware.py", line 43, in from_settings
    mwcls = load_object(clspath)
  File "/home/matt/.pyenv/versions/3.9.16/envs/scrapy/lib/python3.9/site-packages/scrapy/utils/misc.py", line 60, in load_object
    mod = import_module(module)
  File "/home/matt/.pyenv/versions/3.9.16/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/matt/.pyenv/versions/3.9.16/envs/scrapy/lib/python3.9/site-packages/scrapy/extensions/feedexport.py", line 23, in <module>
    from scrapy.extensions.postprocessing import PostProcessingManager
  File "/home/matt/.pyenv/versions/3.9.16/envs/scrapy/lib/python3.9/site-packages/scrapy/extensions/postprocessing.py", line 7, in <module>
    from lzma import LZMAFile
  File "/home/matt/.pyenv/versions/3.9.16/lib/python3.9/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

every time. 

### Versions
Scrapy       : 2.8.0
lxml         : 4.9.2.0
libxml2      : 2.9.14
cssselect    : 1.2.0
parsel       : 1.8.1
w3lib        : 2.1.1
Twisted      : 22.10.0
Python       : 3.9.16 (main, May  3 2023, 20:53:01) - [GCC 12.2.0]
pyOpenSSL    : 23.1.1 (OpenSSL 3.1.0 14 Mar 2023)
cryptography : 40.0.2
Platform     : Linux-6.2.0-20-generic-x86_64-with-glibc2.37

### Additional context
I'm aware 23.04 is new, I'm open to this being because its too new, the modules aren't compatible etc. 
I've tried to install the modules as per many suggestions on the web, but they dont appear to exist. 
I think this is down to needing the modules installed on global python rather than in the virtual env, but if thats wrong, pls put me straight.

**Comment by wRAR** [comment]
Unless `import lzma` in the plain Python interpreter works, this is a problem with your Python. Either way it's not related to Scrapy.

**Comment by bytejunkie** [comment]
i dont understand how can it not be related? it must be a dependancy or it wouldnt be being called?

**Comment by bytejunkie** [comment]
fixed after i found this [github](https://github.com/pandas-dev/pandas/issues/27532#issuecomment-514044754) which reminded me that if i install python modules globally, they wont be in the pyenv version. uninstalled that and reinstalled and the modules appeared.

**Comment by wRAR** [comment]
> it must be a dependancy

It's an stdlib module. 

> reminded me that if i install python modules globally, they wont be in the pyenv version

(that link is unrelated to this)

**Comment by geekmister** [comment]
How to fix it? I made the same mistake you did...

**Comment by bytejunkie** [comment]
install the python modules globally. 
then destroy your pyenv and recreate. they will now be in the core modules the env is created with.

**Comment by geekmister** [comment]
Just found the issue, it is answered in Github issues on Pyenv. See under:
![image](https://github.com/scrapy/scrapy/assets/45185145/adf6c511-4d3f-4dfa-a212-2e9b575108bb)
1. brew install xz
2. reinstall pyenv python version
3. make new python env

**Comment by wRAR** [comment]
> How to fix it? I made the same mistake you did...

You need to have liblzma development files available when building your Python, just like the link in https://github.com/scrapy/scrapy/issues/5921#issuecomment-1535433143 says.

**Comment by NeonEvergreen** [comment]
<img width="976" alt="Screenshot 2024-12-24 at 1 46 20 AM" src="https://github.com/user-attachments/assets/a5301033-0200-4ca1-9ae3-025ad1cf71c9" />

Issue has been resolved.  [link](https://github.com/pyenv/pyenv/issues/1800)
It seems pyenv's installation of python version didn't unpackage some of the core stdlib files properly.
