### ISSUE TITLE
python-docx import in spider fails

### ISSUE THREAD

**Issue by tosilswc** [scrapy/scrapy#5955]
Scrapy 2.8.0 on Python 3.10.6 on Ubuntu 22.04.2

my spider.py has these imports
`import scrapy
from scrapy.spiders import XMLFeedSpider
import re
import unicodedata
from docx import Document
`

but when I run the spider from the cmd via 
`scrapy crawl spider -O spider.json`

I get this error
`Traceback (most recent call last):                                                                                             
  File "/home/lorenzotosi/.local/bin/scrapy", line 8, in <module>                                                                                             
    sys.exit(execute())                                                                                                        
  File "/home/lorenzotosi/.local/lib/python3.10/site-packages/scrapy/cmdline.py", line 153, in execute                         
    cmd.crawler_process = CrawlerProcess(settings)                                                                             
  File "/home/lorenzotosi/.local/lib/python3.10/site-packages/scrapy/crawler.py", line 289, in __init__                        
    super().__init__(settings)                                                                                                 
  File "/home/lorenzotosi/.local/lib/python3.10/site-packages/scrapy/crawler.py", line 166, in __init__                        
    self.spider_loader = self._get_spider_loader(settings)                                                                                                      File "/home/lorenzotosi/.local/lib/python3.10/site-packages/scrapy/crawler.py", line 160, in _get_spider_loader              
    return loader_cls.from_settings(settings.frozencopy())                                                                     
  File "/home/lorenzotosi/.local/lib/python3.10/site-packages/scrapy/spiderloader.py", line 67, in from_settings              
    return cls(settings)                                                                                                       
  File "/home/lorenzotosi/.local/lib/python3.10/site-packages/scrapy/spiderloader.py", line 24, in __init__
    self._load_all_spiders()                                                                                                   
  File "/home/lorenzotosi/.local/lib/python3.10/site-packages/scrapy/spiderloader.py", line 51, in _load_all_spiders                                          
    for module in walk_modules(name):                                                                                          
  File "/home/lorenzotosi/.local/lib/python3.10/site-packages/scrapy/utils/misc.py", line 88, in walk_modules                                                 
    submod = import_module(fullpath)                                           
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module                                                                                
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                               
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import                                                                                             
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load                                                                                          
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked                                                                                 
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked                                                                                           
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module                                                                                     
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed                                                                                
  File "[REMOVED FOR PRIVACY]/spider.py", line 6, in <module>
    from docx import Document          
ModuleNotFoundError: No module named 'docx' `

The package python-docx is correctly installed and it is in path, what could go wrong here?

**Comment by wRAR** [comment]
This is definitely not a Scrapy-related problem.
