### ISSUE TITLE
Unable to install requirements.txt missing

### ISSUE THREAD

**Issue by stccorp** [scrapy/scrapy#6012]
### Description

Unable to install on windows 10

### Steps to Reproduce

pip install Scrappy

**Expected behavior:** [What you expect to happen]
No Errores

**Actual behavior:** [What actually happens]
Collecting Scrappy
  Using cached Scrappy-0.3.0.alpha.4.tar.gz (17 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting guessit (from Scrappy)
  Using cached guessit-3.7.1-py3-none-any.whl (170 kB)
Collecting tvdb-api (from Scrappy)
  Using cached tvdb_api-3.1.0.tar.gz (23 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
INFO: pip is looking at multiple versions of scrappy to determine which version is compatible with other requirements. This could take a while.
Collecting Scrappy
  Using cached Scrappy-0.3.0.alpha.3.tar.gz (16 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached Scrappy-0.3.0.alpha.2.tar.gz (16 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached Scrappy-0.3.0.alpha.tar.gz (16 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached Scrappy-0.2.10.beta.14.tar.gz (16 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached Scrappy-0.2.10.beta.13.tar.gz (15 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached Scrappy-0.2.10.beta.12.tar.gz (15 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached Scrappy-0.2.10.beta.11.tar.gz (15 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "C:\Users\test\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\test\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\test\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\test\AppData\Local\Temp\pip-build-env-8hm_g8ev\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\test\AppData\Local\Temp\pip-build-env-8hm_g8ev\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\test\AppData\Local\Temp\pip-build-env-8hm_g8ev\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\test\AppData\Local\Temp\pip-build-env-8hm_g8ev\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by stccorp** [comment]
Same problem in a new installation using virtualBox with ubuntu 22.04

 × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-55rxxijn/scrappy_6001ac920b1a41e8a7c0c27277eaf4a3/setup.py", line 4, in <module>
          with open('requirements.txt') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

**Comment by Laerte** [comment]
You are trying to install other package instead of Scrapy, The package name is Scrapy not Scrap**p**y. If you want to install Scrapy you should run:
```
pip install Scrapy
```
