### ISSUE TITLE
Import scrapy showing error

### ISSUE THREAD

**Issue by ahammed-nibras** [scrapy/scrapy#6217]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scrapy/__init__.py", line 48, in <module>
    from scrapy.spiders import Spider
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scrapy/spiders/__init__.py", line 10, in <module>
    from scrapy.http import Request
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scrapy/http/__init__.py", line 12, in <module>
    from scrapy.http.request.rpc import XmlRpcRequest
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scrapy/http/request/rpc.py", line 13, in <module>
    DUMPS_ARGS = get_func_args(xmlrpclib.dumps)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scrapy/utils/python.py", line 144, in get_func_args
    func_args, _, _, _ = inspect.getargspec(func)
                         ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

**Comment by Laerte** [comment]
What version of Scrapy are you trying to install?

**Comment by ahammed-nibras** [comment]
1.6.2

**Comment by Laerte** [comment]
You are using a outdated version of Scrapy that is not compatible with Python 3.12, you should update your Scrapy version.
