### ISSUE TITLE
Decompressor' object has no attribute 'process'

### ISSUE THREAD

**Issue by Icefloji** [scrapy/scrapy#6294]
when i follow tutorial in the document, run 'scrapy crawl quotes', but AttributeError appears.

2024-03-18 23:01:30 [scrapy.core.scraper] ERROR: Error downloading <GET https://quotes.toscrape.com/page/2/>
Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\twisted\internet\defer.py", line 2003, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "D:\anaconda3\lib\site-packages\scrapy\core\downloader\middleware.py", line 68, in process_response
    method(request=request, response=response, spider=spider)
  File "D:\anaconda3\lib\site-packages\scrapy\downloadermiddlewares\httpcompression.py", line 90, in process_response
    decoded_body = self._decode(
  File "D:\anaconda3\lib\site-packages\scrapy\downloadermiddlewares\httpcompression.py", line 134, in _decode
    return _unbrotli(body, max_size=max_size)
  File "D:\anaconda3\lib\site-packages\scrapy\utils\_compression.py", line 64, in _unbrotli
    output_chunk = decompressor.process(input_chunk)
AttributeError: 'Decompressor' object has no attribute 'process'

**Comment by Gallaecio** [comment]
https://github.com/scrapy/scrapy/issues/6252
