### ISSUE TITLE
Error while installing Scrappy using pip.

### ISSUE THREAD

**Issue by Gaming-YT-Offcial** [scrapy/scrapy#6412]
### Description

Can't install Scrappy using `pip install Scrappy` in a Windows WSL Kali Linux.

### Steps to Reproduce

1. Run `pip install scrappy`

**Expected behavior:** Start the installation of Scrappy.

**Actual behavior:** Throws an error stating **subprocess-exited-with-error**

**Reproduces how often:** 100%

### Versions

I was unable to get the versions as I was unable to install Scrappy.

### Additional context

**Python Version:** 3.11.9

### Output Log
```
Collecting scrappy
  Using cached Scrappy-0.3.0.alpha.4.tar.gz (17 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-etr3fsgy/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-etr3fsgy/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-etr3fsgy/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-etr3fsgy/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
        File "/tmp/pip-build-env-etr3fsgy/overlay/local/lib/python3.11/dist-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-etr3fsgy/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/core.py", line 146, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "/tmp/pip-build-env-etr3fsgy/overlay/local/lib/python3.11/dist-packages/setuptools/dist.py", line 320, in __init__
          self.metadata.version = self._normalize_version(self.metadata.version)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-etr3fsgy/overlay/local/lib/python3.11/dist-packages/setuptools/dist.py", line 356, in _normalize_version
          normalized = str(Version(version))
                           ^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-etr3fsgy/overlay/local/lib/python3.11/dist-packages/setuptools/_vendor/packaging/version.py", line 200, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: '0.3.0 alpha 4'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by Gaming-YT-Offcial** [comment]
I realized I made a spelling mistake on **Scrapy**. Instead I typed **Scrappy**.
