### ISSUE TITLE
Exception in FeedExporter when Using Path Objects with Storage URI Parameters 

### ISSUE THREAD

**Issue by kkmarv** [scrapy/scrapy#6425]
### Description

According to the [documentation](https://docs.scrapy.org/en/latest/topics/feed-exports.html#feeds), the `FEEDS` dict accepts `Path` objects as keys:

> [...] dictionary in which every key is a feed URI (_or a [pathlib.Path](https://docs.python.org/3/library/pathlib.html#pathlib.Path) object_) [...]

However, when using a `Path` object with Storage URI parameters, the `FeedExporter` runs into the following exception:

```
[scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method FeedExporter.open_spider of <scrapy.extensions.feedexport.FeedExporter object at 0x00000240E9F21F00>>
Traceback (most recent call last):
  File "...\.venv\lib\site-packages\scrapy\utils\defer.py", line 348, in maybeDeferred_coro
    result = f(*args, **kw)
  File "...\.venv\lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "...\.venv\lib\site-packages\scrapy\extensions\feedexport.py", line 467, in open_spider
    uri=uri % uri_params,
```

This is because the `__init__` method of the `FeedExporter` uses `as_uri()` on `Path` objects, which yields an URL-encoded URI, loosing the format characters.

### Steps to Reproduce

1. Set any key of the `FEEDS` dict to a `Path` object containing a %-formatted path:
```python
FEEDS = {
  pathlib.Path("./%(time)s.csv"): {
    "format": "csv",
    "store_empty": True,
  }
}
```
2. Run any spider `scrapy crawl <spider_name>`.

**Expected behavior:** No exception in logs and the feed file being created.

**Reproduces how often:** 100%

### Versions

```
Scrapy       : 2.11.2
lxml         : 5.2.2.0
libxml2      : 2.11.7
cssselect    : 1.2.0
parsel       : 1.9.1
w3lib        : 2.2.1
Twisted      : 24.3.0
Python       : 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
pyOpenSSL    : 24.1.0 (OpenSSL 3.2.2 4 Jun 2024)
cryptography : 42.0.8
Platform     : Windows-10-10.0.22631-SP0
```

**Comment by wRAR** [comment]
Yeah, passing a special templated string to `Path()` instead of a real path doesn't make sense to me. So I don't think I want this to be supported (but I guess it's much easier to make it supported).

**Comment by wRAR** [comment]
After some more more thinking: on one hand, it may be a normal practice to use globs or templates in Path objects, and in  simple cases the library will be fine with that, on the other hand it's a wrong idea in general (see e.g. https://discuss.python.org/t/add-support-for-pathlib-path-format/23441) and I don't see why would a user use Path objects in this way here instead of just strings.

**Comment by kkmarv** [comment]
I agree that Scrapy should not support the Path Interface. It's a wrong approach in this case. I think default strings suffice for that. Or Scrapy could even a implement custom TemplatedPath object? Either way, supporting pathlib's Path doesn't make much sense.

**Comment by nitintecg** [comment]
Hi @wRAR ,
I want to contribute to Scrapy and this is my First Contribution.
I'm able to reproduce this error, is expected here is to modify Feed exports documentation ?

**Comment by wRAR** [comment]
> is expectation here is to modify existing Feed exports documentation ?

Yeah, I think so.

**Comment by vcrab1312** [comment]
I ran into this issue as well.

First I figured that indeed I should just use plain strings instead of pathlib.Path objects. However since the docs say these strings are URIs the core issue remains: the percent character is  
used _both_ to encode characters like spaces in URIs and as part of the printf-style string formatting syntax.

So I suspect **any** properly formatted URI which needs escaped characters will fail because scrapy tries to format it as a template string.

In my specific case the path had a space in it which becomes `%20` when uri-encoded. That means that even when I construct the templated URI string manually by doing `Path("some/path with/spaces").as_uri()` for the first portion and then concatenating it with a template string for the filename, it still fails on the`uri % params` call.
