### ISSUE TITLE
process_spider_exception not executed for errback_httpbin

### ISSUE THREAD

**Issue by mohmad-null** [scrapy/scrapy#6437]
Extension of https://github.com/scrapy/scrapy/issues/1015 - spider exceptions don't trigger process_spider_exception if they;'re called from the errback function.

```

import logging

from scrapy import Request, Spider
from scrapy.crawler import CrawlerProcess


class ExceptionHandlerMiddleware:
	def __init__(self):
		print("init")

	def process_spider_output(self, response, result, spider):
		logging.info('[process_spider_output] Shows that middleware is installed')
		return result

	def process_spider_exception(self, response, exception, spider):
		logging.warning('[process_spider_exception] Exception caught: %s' % str(exception))
		return []

	# def process_spider_input(self, response, spider):
	# 	raise Exception(' from process_spider_input')


class TestingSpider(Spider):
	name = 'exception_spider'
	start_urls = ['http://this-is-an-invalid_url']
	custom_settings = {
		'SPIDER_MIDDLEWARES': {
			__name__ + '.ExceptionHandlerMiddleware': 700,
		}
	}

	def start_requests(self):
		for url in self.start_urls:
			yield Request(
				url,
				callback=self.parse,
				errback=self.errback_httpbin,
			)

	def parse(self, response, **kwargs):
		logging.info('[parse] Now in exceptional parse')
		raise Exception('from parse')

	def errback_httpbin(self, failure):
		logging.info('[parse] Now in exceptional errback_httpbin')
		raise Exception('from errback_httpbin')

process = CrawlerProcess()
process.crawl(TestingSpider)
process.start()

```

Results in:

> 2024-07-14 11:38:37 [root] INFO: [parse] Now in exceptional errback_httpbin

>2024-07-14 11:38:37 [scrapy.core.scraper] ERROR: Error downloading <GET http://this-is-an-invalid_url>
Traceback (most recent call last):
  File "E:\X_Dev\geoseer__scraper\venv\lib\site-packages\scrapy\core\downloader\middleware.py", line 54, in process_request
    return (yield download_func(request=request, spider=spider))
ValueError: invalid hostname: this-is-an-invalid_url

>2024-07-14 11:38:37 [scrapy.core.scraper] ERROR: Spider error processing <GET http://this-is-an-invalid_url> (referer: None)
Traceback (most recent call last):
  File "E:\X_Dev\geoseer__scraper\venv\lib\site-packages\twisted\internet\defer.py", line 1078, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "E:\X_Dev\geoseer__scraper\src\spiders\testing_spider.py", line 47, in errback_httpbin
    raise Exception('from errback_httpbin')
Exception: from errback_httpbin

>2024-07-14 11:38:37 [scrapy.core.engine] INFO: Closing spider (finished)

**Comment by wRAR** [comment]
Should it?

**Comment by mohmad-null** [comment]
a) Why would it not? I believe errback is for catching download errors, not spider errors.
b) If it's not meant to, it needs to be documented; I've lost hours to this.

**Comment by wRAR** [comment]
> Why would it not?

On one hand, nothing says it should. On other hand, errbacks are not the same as callbacks and nothing suggests that something that works with callbacks should work with errbacks in the same way.

> I believe errback is for catching download errors, not spider errors.

Not sure what do you mean by this. If by spider errors you mean exceptions in callbacks then it doesn't seem relevant to an exception in an errback?

> If it's not meant to, it needs to be documented

With an explicit "this also doesn't work with errbacks"?

**Comment by mohmad-null** [comment]
I fear you're presuming far too much knowledge on the part of the end user as to the architecture of Scrapy. I've been using is for 6 years and I have no clue why there would be any difference between "errbacks" and "callbacks" for this. At the risk of being arrogant, it therefore seems reasonable to expect that many/most other users won't either.

Or in comic form: https://www.xkcd.com/2501/

> With an explicit "this also doesn't work with errbacks"?

The use of the word "also" there is confusing. That suggests it doesn't work for other things, yet I see no documentation for that either.
The documentation simply says (my bold): "**This method is called when a spider ** or process_spider_output() method (from a previous spider middleware) **raises an exception.**".

Consider the following:

```
class MySpider(Spider):
	def start_requests(self):
		for url in self.start_requests:
			yield Request(
				url,
				callback=self.parse,
				errback=self.errback_httpbin
			)
	...
	def parse(self):
		...
	def errback_httpbin(self):
		...
```

Both `parse` and `errback_httpbin` are declared in the same place (inside a Spider), and both are called from the same place (inside a Spider). The documentation has therefore implicitly stated that both of these should call `process_spider_exception()` if an exception is raised, as should any other method of this Spider.

**Comment by Gallaecio** [comment]
I’m pretty sure this is only meant to work with callbacks, errbacks are the last point for downloader middleware exception handling, and nothing is meant to capture their exceptions as far as I recall.

So I would either take this as a documentation improvement request (change “spider” to “spider callback”, maybe “spider callback or start_request method” but we should verify it works with `start_requests` first, and if not, whether or not it should), or as an improvement request.

**Comment by wRAR** [comment]
> I fear you're presuming far too much knowledge on the part of the end user as to the architecture of Scrapy. I've been using it for 6 years and I have no clue why there would be any difference between "errbacks" and "callbacks" for this or anything like it. At the risk of being arrogant, it therefore seems reasonable to expect that many/most other users won't either.

TBH I would expect users to not use errbacks at all. And if they do, do they also expect that returning items from it also works? [The only docs we have on errbacks](https://docs.scrapy.org/en/latest/topics/request-response.html#using-errbacks-to-catch-exceptions-in-request-processing) suggest they are just for exception logging and other handling, and if an exception is raised in the errback I would expect it to be unhandled, like in most other places. I'm really surprised that someone could know about errbacks and at the same time think they are in any way similar to callbacks.

> The use of the word "also" there is confusing. That suggests it doesn't work for other things, yet I see no documentation for that either.

Agreed, I meant something like adding "this doesn't treat errbacks in the same way as callbacks" to the text. (To be clear, I don't think it makes much sense to do this.)

> Both parse and errback_httpbin are declared in the same place (inside a Spider), and both are called from the same place (inside a Spider). 

:-/

>  The documentation has therefore implicitly stated that both of these should call process_spider_exception() if an exception is raised, as should any other method of this Spider.

:-/

Is this just because `process_spider_exception()` docs say "when a spider [...] raises an exception"? That should be easy to fix.

**Comment by mohmad-null** [comment]
> errbacks are the last point for downloader middleware exception handling, and nothing is meant to capture their exceptions as far as I recall.

But what if a user *wants* to capture any exceptions that are raised by the errback?

> change “spider” to “spider callback”, maybe “spider callback or start_request method”

I'd suggest: "This method is called when a spider's `callback` method, or `start_methods` raise an exception. For avoidance of doubt, it is not called when the `errback` method raises an exception. It is also called when `process_spider_output()` method (from a previous spider middleware (with a higher/lower* order)) raises an exception.". * delete higher/lower as appropriate. "Previous" is unclear which applies.

> we should verify it works with start_requests first, and if not, whether or not it should), or as an improvement request.

Just tested it: it doesn't. You can test easily using the sample code in the OP. I'd consider this a bug in either the docs or the function depending on expectations.

Don't have time to address @wRAR's comments right now, sorry.

**Comment by Gallaecio** [comment]
> > errbacks are the last point for downloader middleware exception handling, and nothing is meant to capture their exceptions as far as I recall.
> 
> But what if a user _wants_ to capture any exceptions that are raised by the errback?

If this user is a developer of a Scrapy plugin, they would usually catch the exceptions reaching errbacks in a downloader middleware.

If this user is the spider developer, errbacks are designed to catch exceptions, not raise them. They can do `try except` in their errback implementation if they so wish, but I would expect them to write an implementation that does not raise unexpected errors instead. Scrapy already logs the exception, and users should see that and realize they need to change their errback implementation to handle that exception.

If this user is a developer of a Scrapy plugin that wants to do something if a user made a mistake in the implementation of an errback, I don’t think that’s something we need to support.

If this is about developing a Scrapy plugin that allows some special handling of specific exceptions raised from an errback, like allowing raising a `Retry` exception and scheduling a retry request for it, it sounds a bit complicated to me, but if you have a good use case in mind, feel free to share it, maybe we can treat this as a feature request.

> > change “spider” to “spider callback”, maybe “spider callback or start_request method”
> 
> I'd suggest: "This method is called when a spider's `callback` method, or `start_methods` raise an exception. For avoidance of doubt, it is not called when the `errback` method raises an exception. It is also called when `process_spider_output()` method (from a previous spider middleware (with a higher/lower* order)) raises an exception.". * delete higher/lower as appropriate. "Previous" is unclear which applies.

I see some issues on this specific wording, but I agree that we can clarify that `errback` exceptions are not caught.

> > we should verify it works with start_requests first, and if not, whether or not it should), or as an improvement request.
> 
> Just tested it: it doesn't. You can test easily using the sample code in the OP. I'd consider this a bug in either the docs or the function depending on expectations.

Not a bug. This simply means the docs should change from "spider" to "spider callbacks", and clarify that `start_requests ` exceptions are not caught either. If anyone comes up with a good use case for that, we can consider if a feature request, but I would not change anything there until we implement the upcoming async def support for `start_requests`.

**Comment by mohmad-null** [comment]
> I would expect them to write an implementation that does not raise unexpected errors instead. Scrapy already logs the exception, and users should see that and realize they need to change their errback implementation to handle that exception.

...

> ... and clarify that start_requests exceptions are not caught either. If anyone comes up with a good use case for that ...

Rather obviously it's unreasonable to expect software developers to create software without bugs or "unexpected errors". I put it to you that it's excessively prescriptive to only allow errors to be handled one way as seems to be done here (they go to logs and the application continues along).
The problem with the current mechanism is that it may be many hours or days before the user realises there was an exception in some base class that rendered all of the crawl null and void. Also likely is that they'll never notice because they're part of a different group/team that runs a tool someone else made for them and no-one ever told them they had to parse log files for fatal bugs (assuming of course logs are even kept!).
Unfortunately this current design will make it likely that many critical bugs will be undiscovered.

To me, a more reasonable approach (as in, what happens in pretty much every other application) is that the exception should continue until it is caught by the user's code. If the user doesn't catch it, it's clearly a severe bug of some sort and the application should crash ASAP, rather than risk poisoning the database with bad/corrupted data, wasting bandwidth, CPU, etc.

I point you to the zen of Python:
```
...
Errors should never pass silently.
Unless explicitly silenced.
...
```
Going into one of innumerable log files that contains hundreds of thousands of lines  is very much a silent error. The user will need to know to manually search them, or write a tool to parse them, and they'll need to remember to do this after every single crawl, or manually during a crawl repeatedly.


>  The only docs we have on errbacks suggest they are just for exception logging and other handling

To be blunt, this would suggest to me that Scrapy has insufficient documentation on errbacks.

> TBH I would expect users to not use errbacks at all.

Why not? Genuine question. How do you catch all the twisted errors and connection failures otherwise? 
The primary answer on SO with a healthy 40 votes makes clear that it's `errbacks`: https://stackoverflow.com/questions/31146046/how-do-i-catch-errors-with-scrapy-so-i-can-do-something-when-i-get-user-timeout and this one too - https://stackoverflow.com/questions/25840049/how-to-scrapy-handle-dns-lookup-failed
I suspect you'd suggestion DOWNLOADER middleware and `process_exception` maybe? But it seems the community is using errbacks.
Also: https://github.com/scrapy/scrapy/issues/3510. The AI written stuff also goes for errbacks: https://webscraping.ai/faq/scrapy/how-do-i-handle-http-errors-in-scrapy (note: My google was for: "handle dns timeout scrapy" - I wasn't explicitly looking for "errbacks")


> I'm really surprised that someone could know about errbacks and at the same time think they are in any way similar to callbacks.

I created these spiders ~7 years ago so I have no idea as to what the details were back then, and I'm re-discovering them now as I augment and amend them and update them to new Python which in turn requires new Scrapy version (the perpetual tech treadmill 🙄). This doesn't seem an unreasonable situation: Most people who did stuff years ago won't remember the details now. And that's before we get into cases where a person has inherited code from someone else: daily life in the commercial world.

> Is this just because process_spider_exception() docs say "when a spider [...] raises an exception"? That should be easy to fix.

Yes, though I'd prefer that exceptions not just silently disappear, as above.

**Comment by Gallaecio** [comment]
Spiders deal with uncontrolled input, websites.

If you start a crawl for 100 000 pages from a website, leave it running and go to sleep, and a change in 1 of those pages triggers an unexpected exception because your code did not anticipate it, currently in Scrapy you would have 99 999 properly parsed pages, and logs telling you of an issue in 1 page, that you can fix in the morning, and re-run your spider for that 1 page.

If Scrapy were to stop on that 1 page, which could be at any point in that 100 000 page crawl, you would wake up to anywhere between 0 and 99 999 pages scraped, and not knowing if that 1 error was present in any page that your spider did not crawl because it stopped as soon as it found the error.

I honestly think the current approach from Scrapy if correct in this regard.

**Comment by wRAR** [comment]
> Unfortunately this current design will make it likely that many critical bugs will be undiscovered.

> Going into one of innumerable log files that contains hundreds of thousands of lines is very much a silent error. The user will need to know to manually search them, or write a tool to parse them, and they'll need to remember to do this after every single crawl, or manually during a crawl repeatedly.

Please consider using tools that tell you that you have errors and/or unhandled exceptions in your spider logs even when you don't grep the logs yourself after every single crawl. E.g. spidermon. Or at least a dashboard that shows error counts.

> To be blunt, this would suggest to me that Scrapy has insufficient documentation on errbacks.

Can you elaborate? Even your SO links only talk about logging and other similar handling.

>  How do you catch all the twisted errors and connection failures otherwise?

For what reason? To retry them? A downloader middleware, certainly. And never an errback in any case, even just for logging, because errbacks need to be defined explicitly in all places that create requests.

**Comment by mohmad-null** [comment]
In my case I'm doing probably a million requests across my crawls, and yes, if there's an uncaught exception, I most assuredly do want it to except because that means there's a bug in my code.

> I honestly think the current approach from Scrapy is the best default behavior in this regard.

I'm not suggesting changing the default behaviour. If someone has taken the trouble to create an `errback` method **and** middleware with `process_spider_exception` in it then they probably **do** want exactly this behaviour. Again, the point of `process_spider_exception` is to catch exceptions; why would you only want caught exceptions from `parse` and not `errback` too?

> If you don’t like it, you can use a try except and trigger a spider close. This is possible, even if not very well documented. But I would not like to have that as the default behavior.

`CloseSpider` isn't appropriate, it only closes the spider. I've had to implement a method to kill the entire crawl, so I do have a workaround for now thanks.

> Please consider using tools that tell you that you have errors and/or unhandled exceptions in your spider logs even when you don't grep the logs yourself after every single crawl. E.g. spidermon. Or at least a dashboard that shows error counts.

Thanks, but that's a lot of extra work (an entire separate stack to maintain, more code to write and maintain, another thing to execute) for no gain in my case. If it `except`s on unknown exceptions, it makes noise and I instantly find out and can fix it.

> For what reason [do you catch twisted/connection failures]? ... 

So I can log in the database the response details.

> And never an errback in any case, even just for logging, because errbacks need to be defined explicitly in all places that create requests.

Works for me... :-)
