### ISSUE TITLE
Twisted 24.7.0rc1 deprecation: "twisted.web.http.HTTPClient was deprecated in Twisted 24.7.0rc1: Use twisted.web.client.Agent instead"

### ISSUE THREAD

**Issue by jpmckinney** [scrapy/scrapy#6450]
## Summary

Twisted 24.7.0rc1 deprecates twisted.web.http.HTTPClient. Use twisted.web.client.Agent instead.

## Motivation

To avoid deprecation warnings.

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by Gallaecio** [comment]
Which version of Scrapy are you using? [I thought we addressed this in 2.4](https://github.com/scrapy/scrapy/pull/4165).

**Comment by jpmckinney** [comment]
The deprecated import is here:

https://github.com/scrapy/scrapy/blob/03a15ced4f0a4284c75a917fdfb07c44b21f9ff2/scrapy/core/downloader/webclient.py#L10

**Comment by wRAR** [comment]
All of this is very old HTTP/1.0 code, which is not used by default for quite some years (you need to change the `DOWNLOAD_HANDLERS` setting for "http" from `scrapy.core.downloader.handlers.http.HTTPDownloadHandler` to `scrapy.core.downloader.handlers.http.HTTP10DownloadHandler` to use it, losing HTTP/1.1 support). I don't think it's possible to actually port it, so we can either merge the non-overridden parts of `twisted.web.http.HTTPClient` into `scrapy.core.downloader.webclient.ScrapyHTTPPageGetter` like we did with `twisted.web.client.HTTPClientFactory` in #4165, or deprecate and drop the code.

If we want to drop the code, we could extract it into a separate project but that one won't be maintained. Or we could simply drop it and maybe suggest something to use instead (a custom download handler based on... something? or, more likely, just an older Scrapy version).

**Comment by Gallaecio** [comment]
I think we can just deprecate it and eventually drop it. No need to research into potential recommendations now. We can always try to guide anyone that shows an interest in implementing or maintaining a Scrapy plugin for this in the future.

**Comment by wRAR** [comment]
AFAICS it shouldn't be possible to get the warning without using the HTTP/1.0 code that we just deprecated. If someone uses Scrapy that still imports this with Twisted that no longer has this class, they will need to upgrade Scrapy or, easier, downgrade Twisted.

**Comment by andersk** [comment]
@wRAR That is not true, it’s pulled in via `scrapy.core.downloader.handlers.http11` (not `http10`). This affects a totally default Scrapy project, and can be reproduced just by following the [tutorial](https://docs.scrapy.org/en/latest/intro/tutorial.html) with the `PYTHONDEVMODE=1` environment variable set.

Here’s a traceback with `PYTHONWARNINGS=error`:

```pytb
2025-02-05 15:02:55 [scrapy.core.downloader.handlers] ERROR: Loading "scrapy.core.downloader.handlers.http.HTTPDownloadHandler" for scheme "http"
Traceback (most recent call last):
  File "/tmp/v/lib/python3.12/site-packages/scrapy/core/downloader/handlers/__init__.py", line 76, in _load_handler
    dhcls: type[DownloadHandlerProtocol] = load_object(path)
                                           ^^^^^^^^^^^^^^^^^
  File "/tmp/v/lib/python3.12/site-packages/scrapy/utils/misc.py", line 71, in load_object
    mod = import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qrc496n6fsqp4p5m5h8wmw5d5jwyw5mr-python3-3.12.8/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/tmp/v/lib/python3.12/site-packages/scrapy/core/downloader/handlers/http.py", line 2, in <module>
    from scrapy.core.downloader.handlers.http11 import (
  File "/tmp/v/lib/python3.12/site-packages/scrapy/core/downloader/handlers/http11.py", line 30, in <module>
    from scrapy.core.downloader.webclient import _parse
  File "/tmp/v/lib/python3.12/site-packages/scrapy/core/downloader/webclient.py", line 10, in <module>
    from twisted.web.http import HTTPClient
  File "/tmp/v/lib/python3.12/site-packages/twisted/python/deprecate.py", line 483, in __getattribute__
    value = deprecatedAttribute.get()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/v/lib/python3.12/site-packages/twisted/python/deprecate.py", line 538, in get
    warn(message, DeprecationWarning, stacklevel=3)
DeprecationWarning: twisted.web.http.HTTPClient was deprecated in Twisted 24.7.0: Use twisted.web.client.Agent instead.
```

Please reopen this.

**Comment by wRAR** [comment]
@andersk you are testing 2.12.0, not master.

**Comment by andersk** [comment]
My apologies, I assumed from the “quite some years” claim that 2.12.0 was thought to be new enough. I now see that this was fixed in the `http11` and `http2` handlers by #6635.

**Comment by wRAR** [comment]
Well, both things are true, `_parse()` didn't use the deprecated code, it was just defined in the module that imports `twisted.web.http.HTTPClient`.
