### ISSUE TITLE
UnicodeDecodeError from response.json()

### ISSUE THREAD

**Issue by mohmad-null** [scrapy/scrapy#6456]
```
Traceback (most recent call last):
  File "c:\scraper\venv\lib\site-packages\scrapy\core\spidermw.py", line 106, in process_sync
    for r in iterable:
  File "c:\scraper\src\funcs.py", line 184, in get_error_and_response_codes
    elif response.json().get('error') is None:
  File "c:\scraper\venv\lib\site-packages\scrapy\http\response\text.py", line 85, in json
    self._cached_decoded_json = json.loads(self.body)
  File "c:\python3.8\lib\json\__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 148: invalid start byte
```

For this response: 
```
{
   "message":"Error handling service request :Service introuvable. Il est possible que le service soit arrêté ou qu�il ne soit pas configuré.",
}
```
 - the bad character being a https://unicodeplus.com/U+FFFD

when called via `response.json()`

https://docs.scrapy.org/en/latest/_modules/scrapy/http/response/text.html#TextResponse.json

**Comment by Gallaecio** [comment]
The JSON spec requires UTF-8 encoding. It seems your target website does not properly follow that. You will have to read response.body, decode it with whatever encoding they are using into text, and then JSON-decode the result.

**Comment by mohmad-null** [comment]
Thanks, yes, I can get around it myself easily enough, but that obviates the entire point of having `response.json()` exist.

As you yourself said in https://github.com/scrapy/scrapy/issues/6437: "Spiders deal with uncontrolled input, websites.". I consider this a bug because Scrapy can't handle bad Unicode input, something that's remarkably common.

**Comment by Gallaecio** [comment]
Scrapy can handle any response body. Response.json() cannot handle invalid JSON, which I think is OK. I don’t think there is a safe way to handle unsupported encoding. But I guess we could work out a chardet-based implementation.

Still, it may slow down parsing for correctly-formatted JSON, we need to be careful.

**Comment by Gallaecio** [comment]
Any chance you can share an actual URL with the issue? I wonder how web browser deal with that.
