### ISSUE TITLE
Scrapy getting error when tying to click submit button after get success response from anticaptcha

### ISSUE THREAD

**Issue by MDFARHYN** [scrapy/scrapy#6493]
I am using anticaptcha api for solve captcha.I am getting success response from api see below

`Solved CAPTCHA: 03AFcWeA6MMcUMSkRKvTNeuenNTD8riCIwZ9UoQfciYaLV5BFxQIMnH8cFS6xElR-DGcYTedEVBjQbG9oRAHOmZOs-QHAfXAYK4HOk2ioH3GsQgKjlFGLPQMeYYqguEmaMcu5kjLIRWPzbuffxybkLiFd0c2L87I1IF43-gFfk5y4HPRdmy_QFTyqHHhNDKumo_fUI6khzWFFlKnC0Wt1SQMn-hytfgCJn52WCe8E7TU1HhKhZLl7_GIaMezN_hOTEjXxW3GVqryUTIEPFwwhojK92GgzDh_6PH3kTwR8_dsY7flujaPdno3Kc-HLanh5X7iJLH3pvG2yyZIWauhkwYOnVie1jSgqSj0909J1sTk-rFyiX6cajcgRRYRXkugfwNRSJbSXjj6PwvPVzzw8bBRsG-bDOqMcy3alF0EYwmt8o8RUjbwW-jVWOBnZMWdApJNzdy6OfNc07JPuNuhLM4bCnabaH6MY5RIDUxoUVK8-5Bs7N-Uv69L7U4oUJJ6O5FmbMgB_zgTgwtakRCM4BgQ-rXF3koW90kfZTxmRkyfg-wzJUQkgh_zW`
I can't clicking submit button on reCAPTCHA demo page after get success response. getting this error

```
Solved CAPTCHA: 03AFcWeA6MMcUMSkRKvTNeuenNTD8riCIwZ9UoQfciYaLV5BFxQIMnH8cFS6xElR-DGcYTedEVBjQbG9oRAHOmZOs-QHAfXAYK4HOk2ioH3GsQgKjlFGLPQMeYYqguEmaMcu5kjLIRWPzbuffxybkLiFd0c2L87I1IF43-gFfk5y4HPRdmy_QFTyqHHhNDKumo_fUI6khzWFFlKnC0Wt1SQMn-hytfgCJn52WCe8E7TU1HhKhZLl7_GIaMezN_hOTEjXxW3GVqryUTIEPFwwhojK92GgzDh_6PH3kTwR8_dsY7flujaPdno3Kc-HLanh5X7iJLH3pvG2yyZIWauhkwYOnVie1jSgqSj0909J1sTk-rFyiX6cajcgRRYRXkugfwNRSJbSXjj6PwvPVzzw8bBRsG-bDOqMcy3alF0EYwmt8o8RUjbwW-jVWOBnZMWdApJNzdy6OfNc07JPuNuhLM4bCnabaH6MY5RIDUxoUVK8-5Bs7N-Uv69L7U4oUJJ6O5FmbMgB_zgTgwtakRCM4BgQ-rXF3koW90kfZTxmRkyfg-wzJUQkgh_zW
2024-10-10 20:44:17 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.google.com/recaptcha/api2/demo> (referer: None)
Traceback (most recent call last):
  File "F:\ryobute_scraping\documens_source_code\venv\lib\site-packages\scrapy\utils\defer.py", line 295, in aiter_errback
    yield await it.__anext__()
  File "F:\ryobute_scraping\documens_source_code\venv\lib\site-packages\scrapy\utils\python.py", line 374, in __anext__
    return await self.data.__anext__()
  File "F:\ryobute_scraping\documens_source_code\venv\lib\site-packages\scrapy\utils\python.py", line 355, in _async_chain
    async for o in as_async_generator(it):
  File "F:\ryobute_scraping\documens_source_code\venv\lib\site-packages\scrapy\utils\asyncgen.py", line 14, in as_async_generator
    async for r in it:
  File "F:\ryobute_scraping\documens_source_code\venv\lib\site-packages\scrapy\utils\python.py", line 374, in __anext__
    return await self.data.__anext__()
  File "F:\ryobute_scraping\documens_source_code\venv\lib\site-packages\scrapy\utils\python.py", line 355, in _async_chain
    async for o in as_async_generator(it):
  File "F:\ryobute_scraping\documens_source_code\venv\lib\site-packages\scrapy\utils\asyncgen.py", line 14, in as_async_generator
    async for r in it:
  File "F:\ryobute_scraping\documens_source_code\venv\lib\site-packages\scrapy\core\spidermw.py", line 118, in process_async
    async for r in iterable:
  File "F:\ryobute_scraping\documens_source_code\venv\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 355, in process_spider_output_async
    async for r in result or ():
  File "F:\ryobute_scraping\documens_source_code\venv\lib\site-packages\scrapy\core\spidermw.py", line 118, in process_async
    async for r in iterable:
  File "F:\ryobute_scraping\documens_source_code\venv\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 30, in process_spider_output_async
    async for r in result or ():
  File "F:\ryobute_scraping\documens_source_code\venv\lib\site-packages\scrapy\core\spidermw.py", line 118, in process_async
    async for r in iterable:
  File "F:\ryobute_scraping\documens_source_code\venv\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 35, in process_spider_output_async  
    async for r in result or ():
  File "F:\ryobute_scraping\documens_source_code\venv\lib\site-packages\scrapy\core\spidermw.py", line 118, in process_async
    async for r in iterable:
  File "F:\ryobute_scraping\documens_source_code\Advanced_Scrapy_Features\advance_scrapy\advance_scrapy\spiders\SolveCaptcha.py", line 47, in parse  
    await page.evaluate("response => { document.getElementById('g-recaptcha-response').innerHTML = response; }", captcha_solution)
  File "F:\ryobute_scraping\documens_source_code\venv\lib\site-packages\playwright\async_api\_generated.py", line 8332, in evaluate
    await self._impl_obj.evaluate(
  File "F:\ryobute_scraping\documens_source_code\venv\lib\site-packages\playwright\_impl\_page.py", line 440, in evaluate
    return await self._main_frame.evaluate(expression, arg)
  File "F:\ryobute_scraping\documens_source_code\venv\lib\site-packages\playwright\_impl\_frame.py", line 278, in evaluate
    await self._channel.send(
  File "F:\ryobute_scraping\documens_source_code\venv\lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "F:\ryobute_scraping\documens_source_code\venv\lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
ValueError: Page.evaluate: The future belongs to a different loop than the one specified as the loop argument
```
here is my full code. How to avoid this error and why getting this error ? also how to click on submit button after get respose?

```
import scrapy
from anticaptchaofficial.recaptchav2proxyless import recaptchaV2Proxyless

class RecaptchaSpider(scrapy.Spider):
    name = "recaptcha_spider"
    start_urls = ["https://www.google.com/recaptcha/api2/demo"]

    custom_settings = {
        'DOWNLOADER_MIDDLEWARES': {
            'advance_scrapy.middlewares.RotatingProxyMiddleware': None,
            'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware': None,
        },
        "PLAYWRIGHT_BROWSER_TYPE": "chromium",
        "PLAYWRIGHT_LAUNCH_OPTIONS": {"headless": False},
        "PLAYWRIGHT_DEFAULT_NAVIGATION_TIMEOUT": 60000,
    }

    def start_requests(self):
        for url in self.start_urls:
            yield scrapy.Request(
                url,
                meta={
                    "playwright": True,
                    "playwright_include_page": True,
                },
                callback=self.parse,
            )

    async def parse(self, response):
        page = response.meta.get("playwright_page")
        if not page:
            self.logger.error("Playwright page not found in response meta.")
            return

        api_key = "my api key"
        page_url = response.url
        solver = recaptchaV2Proxyless()
        solver.set_key(api_key)
        solver.set_website_url(page_url)
        solver.set_website_key("6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-")

        captcha_solution = solver.solve_and_return_solution()
        if captcha_solution:
            print(f"Solved CAPTCHA: {captcha_solution}")

            # Insert the CAPTCHA response into the page
            await page.evaluate("response => { document.getElementById('g-recaptcha-response').innerHTML = response; }", captcha_solution)
            
            # Click the submit button
            await page.click("#recaptcha-demo-submit")
            
            # Wait to ensure the form submission completes
            await page.wait_for_timeout(5000)

            content = await page.content()
            print("Page content after submission:", content)

            yield {"content": content}
        else:
            self.logger.error("Failed to solve CAPTCHA.")

        # Close the page after completing all actions
        await page.close()
```

**Comment by wRAR** [comment]
Unfortunately you haven't followed https://github.com/scrapy/scrapy/issues/6490#issuecomment-2406621269

Please also don't try creating issues in scrapy-playwright that don't follow that.
