### ISSUE TITLE
Something wrong with the service_identity.

### ISSUE THREAD

**Issue by xmduhan** [scrapy/scrapy#783]
When I start scrapy(0.24.1) in ubuntu(12.04) shell,I found that is a warning,it suggest to install a service_identity module. I follow it.But when  service_identity installation  is finished,the scrapy do not work again.It complain the following:
----------------------------------- Error Stack----------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 4, in <module>
    execute()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 122, in execute
    cmds = _get_commands_dict(settings, inproject)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 46, in _get_commands_dict
    cmds = _get_commands_from_module('scrapy.commands', inproject)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 29, in _get_commands_from_module
    for cmd in _iter_command_classes(module):
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 20, in _iter_command_classes
    for module in walk_modules(module_name):
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 68, in walk_modules
    submod = import_module(fullpath)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    **import**(name)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/commands/bench.py", line 3, in <module>
    from scrapy.tests.mockserver import MockServer
  File "/usr/local/lib/python2.7/dist-packages/scrapy/tests/mockserver.py", line 6, in <module>
    from twisted.internet import reactor, defer, ssl
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/ssl.py", line 223, in <module>
    from twisted.internet._sslverify import (
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 184, in <module>
    verifyHostname, VerificationError = _selectVerifyImplementation()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 159, in _selectVerifyImplementation
    from service_identity import VerificationError
  File "/usr/local/lib/python2.7/dist-packages/service_identity/__init__.py", line 11, in <module>
    from . import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/service_identity/pyopenssl.py", line 12, in <module>
    from pyasn1_modules.rfc2459 import GeneralNames
  File "/usr/local/lib/python2.7/dist-packages/pyasn1_modules/rfc2459.py", line 72, in <module>
    class AttributeValue(univ.Any): pass
AttributeError: 'module' object has no attribute 'Any'
----------------------------------- End Error Stack----------------------------------------------

**Comment by yenumulasudhirkumar** [comment]
It worked like a charm!
U saved my day!

Thank you !! :)

**Comment by VAlexander** [comment]
It is useful to check if there is any dependency corrupted using command below:
    pip check
This is truly awesome!!! I spent 2 minutes to solve this issue. 

In my case I found that attrs and pyasn1-modules have not been installed.
So, I installed attrs in the virtualenv:
   pip install attrs

and pyasn1-modules has been installed in two steps:
1.out of the virtualenv execute command below:
    sudo apt-get install python-pyasn1-modules
2.in the virtualenv execute next command:
   pip install pyasn1-modules
