### ISSUE TITLE
ImportError: Error loading object 'scrapy.contrib.memusage.MemoryUsage': No module named mail.smtp

### ISSUE THREAD

**Issue by addbook** [scrapy/scrapy#958]
2014-11-25 09:19:19+0800 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'prj.spiders', 'SPIDER_MODULES': ['prj.spiders'], 'RETRY_HTTP_CODES': [500, 503, 504, 400, 403, 404, 408], 'BOT_NAME': 'prj', 'DOWNLOAD_TIMEOUT': 1000, 'COOKIES_ENABLED': False, 'USER_AGENT': 'Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.43 Safari/537.31', 'DOWNLOAD_DELAY': 10}
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 4, in <module>
    execute()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 143, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 89, in _run_print_help
    func(_a, *_kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 150, in _run_command
    cmd.run(args, opts)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/commands/crawl.py", line 60, in run
    self.crawler_process.start()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 92, in start
    if self.start_crawling():
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 124, in start_crawling
    return self._start_crawler() is not None
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 139, in _start_crawler
    crawler.configure()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 46, in configure
    self.extensions = ExtensionManager.from_crawler(self)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 50, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 29, in from_settings
    mwcls = load_object(clspath)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 42, in load_object
    raise ImportError("Error loading object '%s': %s" % (path, e))
ImportError: Error loading object 'scrapy.contrib.memusage.MemoryUsage': No module named mail.smtp

**Comment by oleksandr-sumtsov** [comment]
Had the same problems Ubuntu 14.04
Solution:
sudo apt-get install python-twisted

**Comment by kmike** [comment]
@oleksandr-sumtsov how did you install Scrapy? This error is strange because Twisted should be installed automatically when Scrapy is installed.

**Comment by oleksandr-sumtsov** [comment]
@kmike 
<code>
sudo pip install Scrapy
</code>

**Comment by Jackroyal** [comment]
@oleksandr-sumtsov 
3q   it solves my problem too

**Comment by shizi2980** [comment]
@oleksandr-sumtsov
Thank you, it works

**Comment by swathir** [comment]
@oleksandr-sumtsov
Worked ! Thanks :)

**Comment by wakeid** [comment]
Do u know how to solve this problem in centos ?
'yum install python-twisted' not works.

**Comment by kmike** [comment]
@wakeid Scrapy doesn't work in Python 3 yet.

**Comment by wakeid** [comment]
@kmike many thanks, mike ^_^
scrapy is awesome,Thank you for your effort!
